### ISSUE TITLE
persistor object documentation

### ISSUE THREAD

**Issue by Moharu** [rt2zz/redux-persist#100]
Today I had to develop a functionality that required a manual persistor rehydrate() call. After a while, I got it to work just fine, but I think it would be appreciated if the docs were improved to explain the rehydrate method and parameters (such as that it need a serialized input and can receive a callback). I don't know if this is kind of implicit, as I'm just developing my first project with redux, but I think it would help a lot.

Anyways, props for the awesome project :smile:

**Comment by Moharu** [comment]
I also ended up using the "getStoredState" method that is available in the API. It was really easy to understand and use, but a mention in the docs would be useful

**Comment by rt2zz** [comment]
👍 thanks!
