### ISSUE TITLE
Preventing nested propery persist doesn't work

### ISSUE THREAD

**Issue by aries92** [rt2zz/redux-persist#1021]
```javascript
//reducer
export const initialState = {
  step: 1,
 ...other values
};

export default function myReducer(state = initialState, action) {
...
}

//reducers/index
const rootPersistConfig = {
  key: 'root',
  storage: storage,
  blacklist: [],
};

const myReducerConfig = {
  key: 'cp',
  storage: storage,
  blacklist: ['step',],
  debug: true,
};

const rootReducer = combineReducers({
  myReducer: persistReducer(myReducerConfig, myReducer),
});

export default persistReducer(rootPersistConfig, rootReducer);

//store.js
export const store = createStore(reducer, {}, composeWithDevTools(applyMiddleware(thunk)));
export const persistor = persistStore(store)
```

//debug returns 
redux-persist/stateReconciler: rehydrated keys 'l_persist'
and all other values except 'step'

but 'step' still hydrate

if I set blacklist for root reducer and set name of reducer (myReducer) to it
full reducer is blacklisted as expected

but how to blacklist only property 'step' in myReducer

version: 5:10:0

**Comment by TomPradat** [comment]
I think this is the expected behavior, if you don't blacklist the nested reducer the rootReducer is expected to handle the persist configuration.

Please use markdown code snippets for better readability ;)

**Comment by aries92** [comment]
@TomPradat 
updated question
I mean how to prevent persist to storage only one property of myReducer
example above still save to storage

**Comment by TomPradat** [comment]
Here is an example with only the property step blacklisted : https://codesandbox.io/s/8ylzw72658

![2019-04-15 (2)](https://user-images.githubusercontent.com/16164512/56161420-c0d8a700-5fc9-11e9-90d4-a8a5b6eb6aa2.png)

**Comment by aries92** [comment]
@TomPradat 
works, thanks
but if needed to blacklist further deep
like if
```javascript
step: {
 type: 'smt',
 number: 0
}
```
and need to blacklist only 'number'

**Comment by TomPradat** [comment]
For this I think you should have a child reducer for your step object.

You can also look at https://github.com/rt2zz/redux-persist#transforms. I didn't try it but this might work for your use case
