### ISSUE TITLE
changing the storage key??

### ISSUE THREAD

**Issue by karanpratapsingh** [rt2zz/redux-persist#1023]
I've used this package to make an app of mine, I've used the storage key as '1.0.0-xyz' for instance and the app is released.
But I want to change that key to '2.0.0' or something else now, as I am aware this will cause users to lose their persisted data.

Is their a safe way to do this??

**Comment by karanpratapsingh** [comment]
@rt2zz 
 can you help me please?

**Comment by TomPradat** [comment]
I'm not sure why you need to change the storage key. I don't think you should add the version inside the key name, a version key already exists in the config object.

That said you might be able to change your key and add a migration at the parent/root level to duplicate the existing key. You might need two migrations. I'll try it and let you know

**Comment by TomPradat** [comment]
@karanpratapsingh Did you succeed doing what you wanted ? If so how ?

**Comment by karanpratapsingh** [comment]
Yes I succeeded, tho I didn't find any solution anywhere. So in my app's main screen I added a simple listener which checked the redux key and logs out the user if the key is the old one and repopulated the store with the new one on the next login. as my app had few active users then hence it wasn't a big deal.

**Comment by TomPradat** [comment]
Alright, good to know. To prevent further issues i think you should not change the storage key with your versionning :)
