### ISSUE TITLE
Unable to resolve module `redux-persist/integration/react`

### ISSUE THREAD

**Issue by johnveloper** [rt2zz/redux-persist#1024]
also tried `redux-persist/es/integration/react`

**Comment by johnveloper** [comment]
ok i found the fix:
```
npm install redux-persist
npm install redux-persist
```
for some reason npm won't instal the integration first time (persistReducer and persistStore worked)

**Comment by TomPradat** [comment]
Indeed the npm package is `redux-persist`.

`redux-persist/integration/react` is just the path where to find the React component inside the package.

**Comment by Metourni** [comment]
I fixed this issue by changing the import statement
In the documentation its

`import { PersistGate } from 'redux-persist/integration/react'`

I imported the library like this 

`import { PersistGate } from 'redux-persist/es/integration/react';`

**Comment by hrutik7** [comment]
npm install redux-persist

This is working for me :)

**Comment by Rcd503** [comment]
I resolved this error with typescript 
Follow below:

"include": ["./node_modules/redux-persist/types"]

this line add at project root file tsconfig.json

**Comment by yashP45** [comment]
I resolved this by just installing "react-persist" twice & then restarting the server

**Comment by xuniorss** [comment]
I had this problem when importing `import { PersistGate } from 'redux-persist/integration/react'` 
I solved it by adding the following reference statement at the beginning of the file:
 `/// <reference types="redux-persist/types" /> `

**Comment by louiebasalo** [comment]
reinstalling redux-persist and restarting the server works.

**Comment by jessiemblack** [comment]
I ran `yarn add redux-persist`, closed out of metro, ran `yarn run cache` and it worked for me
