### ISSUE TITLE
createTransform() Parses Classes back to Objects

### ISSUE THREAD

**Issue by ludescher** [rt2zz/redux-persist#1054]
I’m using Classes to create and store Data and as it turns out Transform’s are not working with classes.

I know that createTransform() only saves Objects, so I wrote a function to parse the Class to an Object with additional mapping (inboundState).
And in the “rehydrate” of the Transform (outboundState), the Objects is being parsed to a Class again.

It all works so far, the Class is saved properly and the parsing works as expected (outboundState returns a Class), but if I call the Class from redux, it returns an Object.

Is this a known issue?

**Comment by moaxaca** [comment]
@ludescher  I've encountered the same.

**Comment by ludescher** [comment]
It’s been a while, but I guess there is still no official solution to this problem.
Lucky us, @moaxaca 😉

My Solution:
Ditch Redux & Redux-Persist and write your own custom Storage-Solution.
Performs and works even better.

**Comment by moaxaca** [comment]
I will end up using apollo but for this app solution was rollback version X)

**Comment by ludescher** [comment]
@moaxaca sounds like a plan.
good luck.
