### ISSUE TITLE
`createPersistor` accesses state.getState() - assuming it returns an object

### ISSUE THREAD

**Issue by richtier** [rt2zz/redux-persist#106]
https://github.com/rt2zz/redux-persist/blob/master/src/createPersistor.js#L35

if `store.getState()` returns a ImmutableJS map then this will fail.

Is there a built-in way to work around this?

**Comment by rt2zz** [comment]
Long story short: currently we do not support top level immutable state, only [immutable sub-reducers](https://github.com/rt2zz/redux-persist-transform-immutable).

There is an [open issue](https://github.com/rt2zz/redux-persist/issues/64) to support top level immutable state. It is possible, the biggest hold up is how to design a simple elegant API. e.g. we could allow a configurable "state iterator" and "state setter", but that api feels clunky. Open to suggestions

**Comment by richtier** [comment]
perhaps `createPersistor` could first check if a function called something like `getStateForReduxPersist`, and it that does not exist fall back to `getState`.

This will allow devs to add `getStateForReduxPersist` function to the store and return the state in the way Redux Persist can interact with.

**Comment by rt2zz** [comment]
Ok tentative immutable support now available at https://github.com/rt2zz/redux-persist-immutable

**note** I have not actually run this in an app, but the tests pass ;)

Feedback welcome!
