### ISSUE TITLE
If the storage data changes, will those changes be loaded?

### ISSUE THREAD

**Issue by timhuff** [rt2zz/redux-persist#1066]
I'm using this with react-native. I have a background task that loads up the store and runs some data fetching. My question is: will the updated data be loaded automatically by redux-persist when the app comes back into the foreground? If the app was killed, the data will be loaded by nature of initializing the store. My concern is for when the app is open in the background and execution of JS is paused. I'm concerned that when the app is pulled into the foreground, the state stored in the foreground will overwrite the changes that occurred in the background. I'm thinking I might need to do `persistor.pause()` when the app goes into the background and `persistor.persist()` when the app comes into the foreground. Does `persistor.persist()` re-load the state from storage?

**Comment by timhuff** [comment]
After some investigation, it appears that this isn't a concern and that `redux-persist` handles this use-case great out of the box.

**Comment by Li357** [comment]
I'm dealing with this exact use-case with `react-native-background-task`. Did you just call `createStore` and `persistStore` then dispatch?

**Comment by timhuff** [comment]
You mean on the background task? I'm using `react-native-background-fetch`. My code looks like this:

```ts
const headlessTask = async () => {
  try {
    await Bluebird.resolve(syncData()).timeout(25000)
  } catch (e) {
    console.error(e)
  } finally {
    await persistor.flush()
    store.dispatch(stopRequestQueue())
    BackgroundFetch.finish(BackgroundFetch.FETCH_RESULT_NEW_DATA);
  }
}

async function syncData() {
  await persistRehydrationPromise
  let state: AppState = store.getState()
  await Promise.all([
    store.dispatch(startRequestQueue()),
    store.dispatch(syncCache()),
  ])
  state = store.getState()
}

export function setupBackgroundTasks() {
  BackgroundFetch.configure({
    minimumFetchInterval: 15, // <-- minutes (15 is minimum allowed)
    // Android options
    enableHeadless: true,
    stopOnTerminate: false,
    startOnBoot: true,
    requiredNetworkType: BackgroundFetch.NETWORK_TYPE_ANY,
  }, headlessTask, (error) => {
    console.log("[js] RNBackgroundFetch failed to start");
    console.log(error)
  });
}

BackgroundFetch.registerHeadlessTask(headlessTask);
```

(note: I think `BackgroundFetch.finish(BackgroundFetch.FETCH_RESULT_NEW_DATA);` is a bit of an abuse. I just don't want it to retry if it fails. Also, "failure" (an exeception being thrown) is kind of expected if I have a lot of data to push. That bluebird `.timeout` function will throw an error if the function takes longer than 25 seconds)

You might want to be aware of the information here: https://dontkillmyapp.com/

It imports store from the same place that my react native app imports it. It's a file that does all the redux-y things (and, yea, at the bottom of the file is `createStore` and `persistStore`, amongst other things). The key here is to have this file be shared between the background task and the react native app and to ensure that it doesn't import any file which uses react native. This is redux-land - it should be completely unaware of background-task-land and react-native-land.

Hope I've saved you some time here.

**Comment by Li357** [comment]
@timhuff  The snippet's really helpful - `react-native-background-task` is just a wrapper around `react-native-background-fetch`. I didn't think just using the created store from the foreground could be possible in the background. Thanks!

**Comment by timhuff** [comment]
I started by using `react-native-background-task` but bailed on it after I noticed this:

![image](https://user-images.githubusercontent.com/609217/62500936-2a193b80-b7ae-11e9-9a1c-a107b185a709.png)

I've used TransistorSoft's work before. It's quality. I would recommend using `react-native-background-fetch` directly.
