### ISSUE TITLE
Object containing arrays not persisting

### ISSUE THREAD

**Issue by bockc** [rt2zz/redux-persist#1067]
I have in my reducer an object following this structure : 
```
const object = {
  JID1: [
    { 
      string: "stringifiedDraft",
      data: {
        data1: {}, 
        data2: {},
        data3: {},
      },
      anotherString: "JID",
    },
    {...},
  ],
  JID2: [...],
  JID3: [...],
}
```

My reducer seems to be correctly updated during runtime without any issue whatsoever.
However, when I restart my app, `redux-persist` only returns me an empty object for this entry while all the other data is returned correctly.

I tried several things like persisting a dummy object like `const object = { test: "test" }` and this one persists without any issue. I noticed that as soon as I have something like `const object = { thing: [{ test: "test"}] }` in my reducer, only an empty object is returned.

I tried to stringify the new state before applying it to the reducer to check if there was an issue when `redux-persist` stringifies my reducers states but everything went fine and my data is still here perfectly stringified so the problem does not seem to be there.

My reducers tree works this way: `rootReducer -> moduleReducer -> problemReducer`

Any idea ?

**Comment by gejimayu** [comment]
Please check in the localStorage (or whatever you use), is the data stored correctly ?

I've tried to save object with array as an attribute value in my environment and it works just fine.

**Comment by bockc** [comment]
I'm using react-native, I forgot to mention that, so I had to check my local storage a different way.

Anyway, I logged my local storage completely and from what I see, it does not seem to be saved at all. That's strange because if I stringify my data, it is correctly saved in the local storage and everything works fine. That's a workaround at most for now, I'd like to find a real solution.

Maybe has it something to do with the fact that I did a nested persist configuration for this precise reducer ?
The thing is: I want to save my whole reducer except for a specific key which otherwise makes redux-persist crash my app, this specific key is an object containing a reference, thus cannot be stringified and completely corrupts my stored data forcing users to reinstall the application to use it.

This is my config for blacklisting this single key:
```
import { combineReducers } from 'redux';
import storage from 'redux-persist/lib/storage';
import { persistReducer } from 'redux-persist';
import { device } from 'utils';
import chatConversationReducer from './chatConversationReducer';
import chatListReducer from './chatListReducer';

const chatModulePersistConfig = {
  version: device.getVersion(),
  key: 'chatModuleReducer',
  storage,
  blacklist: ['chatListReducer', 'chatConversationReducer'],
};

const chatListPersistConfig = {
  version: device.getVersion(),
  key: 'chatListReducer',
  storage,
  blacklist: ['client'],
};

const chatModuleReducer = combineReducers({
  chatConversationReducer,
  chatListReducer: persistReducer(chatListPersistConfig, chatListReducer),
});

export default persistReducer(chatModulePersistConfig, chatModuleReducer);
```

And here is the config of my redux store:
```
import { createStore, compose, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';
import { persistStore, persistReducer } from 'redux-persist';
import storage from 'redux-persist/lib/storage';
import createSagaMiddleware from 'redux-saga';
import { device } from 'utils';
import Reducers from './reducers';
import rootSaga from './sagas/sagas';

const rootPersistConfig = {
  version: device.getVersion(),
  key: 'root',
  storage,
  blacklist: [
    'appInfosReducer',
    'chatModuleReducer',
    'groupsModuleReducer',
    'loggerReducer',
    'mediaManagerReducer',
    'rightsReducer',
    'searchReducer',
    'socialModuleReducer',
    'userAppsReducer',
    'videoPlayerReducer',
    'widgetsReducer',
  ],
};

const persistedReducer = persistReducer(rootPersistConfig, Reducers);
const sagaMiddleware = createSagaMiddleware();
const middlewares = [sagaMiddleware, thunk];
// eslint-disable-next-line no-underscore-dangle
const composeEnhancer = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const store = createStore(persistedReducer, composeEnhancer(applyMiddleware(...middlewares)));
const persistor = persistStore(store);

sagaMiddleware.run(rootSaga);

export { persistor, store };
```

Do you see anything fishy that could explain this behavior ?

**Comment by GuillaumeMunsch** [comment]
I'm working with @bockc. We solved the issue.
No problem with the package, the error was on our side. We kind of forgot that the redux state was immutable 🤷‍♂

We'll mark this as resolved :)

**Comment by margrudniak** [comment]
i have faced that problem recently, what was the solution?

**Comment by margrudniak** [comment]
I found solution for my problem. My initial state presents like: 
` const initialState: AuthState = {
   ...,
  user: {
    ...,
    entries: [],
  },
};`
And at this case, during REHYDRATE redux persist delete array.
My root reducer looks like:
`const rootReducer = persistReducer(persistConfig, combineReducers({
     authSlice
});`
but when i persist reducer to the slice it works perfectly
`const rootReducer = combineReducers({
  authSlice: persistReducer(persistConfig, authSlice),
});`
so you have to remove persistReducer from top, and wrap the slice
I think this is due to nested arrays / objects

**Comment by comp-phys-marc** [comment]
Hello @bockc and @GuillaumeMunsch ,

I am currently facing this same issue on React Native with the following config and initial state. 

```
import { createStore } from "redux";
import reducer from './reducers';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { persistStore, persistReducer } from 'redux-persist';
import storage from 'redux-persist/lib/storage' ;

const persistConfig = {
    key: 'root',
    storage: AsyncStorage,
};

const persistedReducer = persistReducer(persistConfig, reducer);

export const store = createStore(persistedReducer);
export const persistor = persistStore(store);
```

```

const INITIAL_TOKEN_STATE = "";

...

const INITIAL_RECORD_STATE: Array<Record> = [];

const recordReducer = (state = INITIAL_RECORD_STATE, action: { type: string; payload: Record | Array<Record>; }) => {

...

}

export default combineReducers({
    ...
    records: recordReducer,
});
```

I am able to persist all other (string) state except for the array shown.

What was your solution if you don't mind sharing a bit more? How did you know your state was immutable and what did you need to do once you realized?

**Comment by comp-phys-marc** [comment]
I was able to figure out the issue. Whereas before I had the following in my reducer:

```
        case 'ADD_RECORD':
            state.push(action.payload[0]);
            return state;
```

I had to replace the state (rather than mutate it) in order for redux persist to trigger:

```
        case 'ADD_RECORD':
            state = state.concat(action.payload);
            return state;
```

With the help of a custom transform I was able to then see Redux Persist doing its job.

```
import { createTransform } from 'redux-persist';
import { Record } from "../utils/types";

const ArrayTransform = createTransform(
    // transform state on its way to being serialized and persisted.
    (inboundState: Array<Record>, key) => {
        alert("inbound " + JSON.stringify(inboundState));
        return JSON.stringify(inboundState);
    },
    // transform state being rehydrated
    (outboundState: string, key) => {
        alert("outbound " + JSON.stringify(outboundState));
        return JSON.parse(outboundState);
    },
    { whitelist: ['records'] }
);

const persistConfig = {
    key: 'root',
    storage: AsyncStorage,
    transforms: [ArrayTransform]
};
```
