### ISSUE TITLE
Blacklist keys

### ISSUE THREAD

**Issue by Crphang** [rt2zz/redux-persist#107]
Hey guys, I was using this great framework to persist my redux state to localStorage and it worked well other than with [React-Router-Redux.](https://github.com/reactjs/react-router-redux) In my case, my reducers looks like:

```
const reducer = combineReducers({
  ...allOtherReducers,
  routing: routerReducer
})
```

Because of autoRehydrate(), whenever I access a route directly by typing http://myappurl/someroute, it will rehydrate my state and redirect back to the original persisted route. Blacklisting seems to be the correct option since the user don't need to persist their routes.

Following the example, I should do: 

`persistStore(store, {blacklist: ['routing']})`

However, it continued to persist my routes and rehydrate. After some investigation, I realised that the key that should be blacklisted should be `reduxPersist:routing` because the reduxPersist prepended `reduxPersist:` at the start of the keys.

Would like to know whether others face this issue and it'll be great if the getting started guide can reflect this!

**Comment by rt2zz** [comment]
On cursory inspection, I suspect what is happening is that you started without the blacklist, state was saved, and then after adding it to the blacklist the old saved value continues to be rehydrated even though no new state is being written over it.

The short fix would be to call `persistor.purgeAll()` to clear your state and then it should begin to function as expected.

The more sustainable solution is for us to think about having getStoredState respect the whitelist & blacklist. Right now it just restores everything it can find.

**Comment by Crphang** [comment]
Oh blur me. That worked haha!

Haha yes, possibly it can read the config everytime and purge whatever keys that are necessary as the application doesn't really function probably when the persistorObject runs purgeAll each time.

**Comment by rt2zz** [comment]
K just implemented blacklist in getStoredState: https://github.com/rt2zz/redux-persist/blob/master/src/getStoredState.js#L22

This should help avoid confusion in the future. Thanks! Will cut a release soon.

**Comment by irvingv8** [comment]
Hello there! I'm facing this problem too, currently my persistor looks like this:
`persistStore(store, {blacklist: ['routing']})`

My reducer looks like :

```
const rootReducer = combineReducers({
	routing: routerReducer,
	auth: AuthenticationReducer,
	competition: CompetitionReducer,
	form: formReducer,
	status: StatusReducer,
	user: UserReducer
});
```

I tried using persistor.purge() and clearing localStorage, but it is still coming back (the routing key).

**Comment by rt2zz** [comment]
what version of redux-persist are you using?

**Comment by irvingv8** [comment]
@rt2zz Ty for your assistance!

I'm using "redux-persist": "^4.0.0-beta1"

**Comment by irvingv8** [comment]
I'm not really sure what went wrong but, im using session storage now, so my persistor looks like:

const persistor = persistStore(store, {storage: asyncSessionStorage, blacklist: ['routing']});

and my sessionStorage is actually working, but it is still also saving to my localStorage (where it doesn't read my blacklist), also it is rehydrating from the localStorage

**Comment by rt2zz** [comment]
are you setting up two persistors, one with session storage and one with local storage?

If you do this you will need to blacklist routing in both. seeing the full configureStore setup might help me understand.

**Comment by irvingv8** [comment]
@rt2zz No, I'm just using 1 persistor, however im using redux devtools, dunno if it could be something with it...

this is how I'm setting it up ATM:

```
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

const enhancer = composeEnhancers(
	applyMiddleware(promise,ReduxThunk),
	autoRehydrate()
);

export const store = createStore(reducers, enhancer);

const persistor = persistStore(store, {storage: asyncSessionStorage, blacklist: ['routing']});
```

**Comment by irvingv8** [comment]
@rt2zz I found the problem! It was just me being dumb, I started trying this out using the "Simplest Usage", then I started using the "Delay Render Until Rehydration Complete" approach and well, I ended up with 2 persistors... so my bad, sorry for the troubles, Great work! TY for this tool, it's awesome, keep it up!

**Comment by rt2zz** [comment]
@irvingv8 nice! glad to hear its sorted

**Comment by karna41317** [comment]
@irvingv8 Thanks man, had same issue, solved

**Comment by irvingv8** [comment]
@karna41317 Glad to hear this was useful for someone else! 

#KeepOnHacking!

**Comment by biboukat** [comment]
const clearTokenActivation = createTransform(
  (inboundState) => {
    console.log('inboundState', inboundState);
    return {
      ...inboundState,
      activatedToken: undefined,
    };
  },
);

**Comment by biboukat** [comment]
**don't remaining token of activation**
`const clearTokenActivation = createTransform(
  (inboundState) => {
    console.log('inboundState', inboundState);
    return {
      ...inboundState,
      activatedToken: undefined,
    };
  },
);

persistStore(store,
  { storage: AsyncStorage,
    blacklist: ['auth{activatedToken}'],
    transforms: [
      clearTokenActivation,
    ],
  },
  () => {`
