### ISSUE TITLE
import storage from 'redux-persist/lib/storage' not working

### ISSUE THREAD

**Issue by hendrikrodriguezguillen** [rt2zz/redux-persist#1080]
I am using the following: 
{
    "native-base": "^2.13.5",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
}
, but when importing:
import storage from 'redux-persist/lib/storage'
 I get the error "redux-persist failed to create sync storage. falling back to noop storage."

inquire a bit into your code and observe the following in the file "redux-persist/lib/storage/getStorage.js" in

`function hasStorage(storageType) {`
`  if ((typeof self === "undefined" ? "undefined" : _typeof(self)) !== 'object' || !(storageType in self)) {`
`    return false;`
`  }`
`...`
`}`
apparently this is true: !(storageType in self), that is storageType is not in self

**Comment by whispyy** [comment]
I'm experiencing the same issues, everythings worked well on react-native : 0.59.10, when i migrated into 0.60.5, I've encoutered same error.
 
My dependencies :

```
"dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-reanimated": "^1.2.0",
    "react-native-safe-area-view": "^0.14.7",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-navigation": "^4.0.0",
    "react-navigation-drawer": "^2.0.1",
    "react-navigation-stack": "^1.5.1",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-persist": "^6.0.0"
  },
```
my configureStore

```
import { createStore } from 'redux'
import { persistStore, persistReducer } from 'redux-persist'
import storage from 'redux-persist/lib/storage' // defaults to localStorage for web

import rootReducer from './reducers'

const persistConfig = {
  key: 'root',
  storage,
}

const persistedReducer = persistReducer(persistConfig, rootReducer)

export default () => {
  let store = createStore(persistedReducer)
  let persistor = persistStore(store)
  return { store, persistor }
}
```
iOS error :

![image](https://user-images.githubusercontent.com/6684065/64130301-7d6fb100-cd8f-11e9-992e-75e0013f7372.png)

**Comment by hungtn2812** [comment]
In redux-persist v6, you try changing as follow:
import storage from 'redux-persist/lib/storage';
 => import AsyncStorage from '@react-native-community/async-storage';

const persistConfig = {
  //...
  storage,
}
=>
const persistConfig = {
  //...
  storage: AsyncStorage
}

**Comment by hungtn2812** [comment]
In redux-persist v6, you try changing as follows:
import storage from 'redux-persist/lib/storage';
=> import AsyncStorage from '@react-native-community/async-storage';

const persistConfig = {
//...
storage,
}
=>
const persistConfig = {
//...
storage: AsyncStorage
}

**Comment by hungtn2812** [comment]
In redux-persist v6, you try changing as follow:
import storage from 'redux-persist/lib/storage';
=> import AsyncStorage from '@react-native-community/async-storage';

const persistConfig = {
//...
storage,
}
=>
const persistConfig = {
//...
storage: AsyncStorage,
}

**Comment by hungtn2812** [comment]
In redux-persist v6, you try changing as follows:
import storage from 'redux-persist/lib/storage';
=> import AsyncStorage from '@react-native-community/async-storage';

const persistConfig = {
//...
storage,
}
=>
const persistConfig = {
//...
storage: AsyncStorage,
}

**Comment by hungtn2812** [comment]
In redux-persist v6, you try changing as follows:
import storage from 'redux-persist/lib/storage';
=> _import AsyncStorage from '@react-native-community/async-storage';_

const persistConfig = {
//...
storage,
}
=>
_const persistConfig = {
//...
storage: AsyncStorage,
}_

**Comment by whispyy** [comment]
Your fix works, thanks!

**Comment by rt2zz** [comment]
thanks @hungtn2812 	thats exactly right.

for those who missed the change, react-native deprecated AsyncStorage, now users must import from `@react-native-community/async-storage`. Consequently redux-persist dropped the default storage engine on react-native and all users upgrading to v6 / rn 59+ will need to explicitly pass in storage
```
import AsyncStorage from '@react-native-community/async-storage';

const persistConfig = {
	//...
	storage: AsyncStorage,
}
```

**Comment by hendrikrodriguezguillen** [comment]
In my case, this is not the problem since I investigated and took into account what rt2zz says. My problem is that the error occurs immediately after doing `import storage from 'redux-persist/lib/storage'`

**Comment by hendrikrodriguezguillen** [comment]
this is my code:

`import { applyMiddleware, compose, createStore } from 'redux'
import reducers from './reducers'
import { createLogger } from 'redux-logger'
import { persistStore, persistReducer } from 'redux-persist'
import thunk from 'redux-thunk';
import { Constants } from '../assets'
import AsyncStorage from '@react-native-community/async-storage';
import storage from 'redux-persist/lib/storage'

const loggerMiddleware = createLogger({ predicate: () => false })
const persistedReducer = persistReducer({ key: 'primary', storage, whitelist: Constants.PERSISTED_REDUCERS }, reducers)

function configureStore(initialState) {
	const enhancer = compose(
		applyMiddleware(thunk, loggerMiddleware)
	)	
	let store = createStore(persistedReducer, initialState, enhancer)	
	return store;
}

const initialState = {}
export const store = configureStore(initialState);
export const persistor = persistStore(store, {storage: AsyncStorage});`

**Comment by ckOfor** [comment]
use version `"redux-persist": "^5.10.0"`

**Comment by NathanNovak** [comment]
> In redux-persist v6, you try changing as follows:
> import storage from 'redux-persist/lib/storage';
> => _import AsyncStorage from '@react-native-community/async-storage';_
> 
> const persistConfig = {
> //...
> storage,
> }
> =>
> _const persistConfig = { //... storage: AsyncStorage, }_

That still is pulling up the same error message.

**Comment by todorone** [comment]
I also experience the same error with `storage: AsyncStorage` configuration on redux-persist v6 and RN 0.61.4.
@rt2zz What could be the reason?

**Comment by todorone** [comment]
Spent an hour trying to figure out why the error is being thrown while `AsyncStorage` is still working, but no luck. The code is too entangled and not obvious for me - why `createWebStorage` is still being invoked if we explicitly passed `AsyncStorage` into `config`? @rt2zz Any hint?

**Comment by ckOfor** [comment]
Downgrade redux-persist to 5.10.0

**Comment by EdSancha** [comment]
For future reference, if you are using expo, instead of:
`import AsyncStorage from '@react-native-community/async-storage';`

you need to do:
`import { AsyncStorage } from 'react-native';`

[Reference](https://docs.expo.io/versions/latest/react-native/asyncstorage/)

**Comment by vokecodes** [comment]
I found this helpful

[(https://stackoverflow.com/a/58592803/8793423)]

**Comment by vokecodes** [comment]
I found this helpful

https://stackoverflow.com/a/58592803/8793423
