### ISSUE TITLE
Why is rehydration not working for me?

### ISSUE THREAD

**Issue by r1cebank** [rt2zz/redux-persist#110]
Hi, thank you for the awesome library. I am having some issue using this for react native 0.26, the rehydration did not really modify my state. Here is the log for the rehydrate action

![screenshot at jun 06 14-22-37](https://cloud.githubusercontent.com/assets/261671/15838431/d39128c6-2bf2-11e6-8b8e-b20b3f60120c.png)

and this is how I implement this into my app:

![screenshot at jun 06 14-23-07](https://cloud.githubusercontent.com/assets/261671/15838439/e03933f2-2bf2-11e6-8463-e395687fa82d.png)

Its probably caused by something I did, any help is appreciated. 

Thank You

**Comment by rt2zz** [comment]
Most likely you are modifying state in your reducers, so autoRehydrate is skipping your reducers.

In order for autoRehydrate to work, you need dataReducer to by default return state unmodified.
```js
switch action.type:
// ...
default: return state
```

Your other option is to not use autoRehydrate and instead handle the rehydrate manually:
```js
switch action.type:
  case REHYDRATE: 
    return {...state, ...action.payload.dataReducer}
// ...
```

I wrote this on my phone so let me know if anything is broken or confusing

**Comment by r1cebank** [comment]
Thanks for the quick reply, I do have dataReducer and return state unmodified by default. Could it be caused by something else?

**Comment by rt2zz** [comment]
actually upon further inspection I think your createStore call is wrong, It only takes 3 arguments so it should look more like:
```js
let enhancer = autoRehydrate()(devtools())
createStoreWithMiddleware(rootReducer, initialState, enhancer)
```

**Comment by r1cebank** [comment]
Man, I am so careless. Thanks for all the help.

**Comment by rt2zz** [comment]
👍

**Comment by sattaman** [comment]
This just helped me. My issue was I had autoRehydrate last in the enhancer chain, after devTools. 

```
const configureStore = (initialState) => {
  const enhancer = compose(
    applyMiddleware(thunk, createLogger()),
    devTools(),    
    autoRehydrate(),
  );
  return createStore(rootReducer, initialState, enhancer);
};

```
Swapping to 

```
const configureStore = (initialState) => {
  const enhancer = compose(
    applyMiddleware(thunk, createLogger()),
    autoRehydrate(),
    devTools(),
  );
  return createStore(rootReducer, initialState, enhancer);
};
```

Fixed for me.

**Comment by ivanhoe-dev** [comment]
> Most likely you are modifying state in your reducers, so autoRehydrate is skipping your reducers.
> 
> In order for autoRehydrate to work, you need dataReducer to by default return state unmodified.
> 
> ```js
> switch action.type:
> // ...
> default: return state
> ```
> 
> Your other option is to not use autoRehydrate and instead handle the rehydrate manually:
> 
> ```js
> switch action.type:
>   case REHYDRATE: 
>     return {...state, ...action.payload.dataReducer}
> // ...
> ```
> 
> I wrote this on my phone so let me know if anything is broken or confusing

You've saved my life. Just realized the default case of the reducer must be `state`

**Comment by daveckw** [comment]
I had the same issue and realised that in my reducer I did this:

defaut:
return{...state}

instead of

default:
return state

**Comment by shameekagarwal** [comment]
for me, it was because i was passing `rootReducer` instead of `persistedReducer` inside `createStore`

```
export const store = createStore(
  persistedReducer,
  applyMiddleware(...middleware)
);
```
