### ISSUE TITLE
Migration is called every time on app start or reload

### ISSUE THREAD

**Issue by b3hz4d** [rt2zz/redux-persist#1111]
I have problem with version of migration
Migration from version to new version works perfect but it's version is not updating and on next app reload or start migration will apply it again
What's wrong??

**Comment by b3hz4d** [comment]
Update: I checked and see that Nested Persists have this problem that version (_persists.versoin) is not updating after migration, only root reducer (combinedReducer) version get updated if I update its version
Need help

**Comment by rmilesson** [comment]
I'm facing the same problem. Is there are way to fix this? My version is not updating in a nested persist scenario which makes the migration run every time.

**Comment by b3hz4d** [comment]
> I'm facing the same problem. Is there are way to fix this? My version is not updating in a nested persist scenario which makes the migration run every time.

What are you returning for default value in reducer?
