### ISSUE TITLE
redux-persist not persisting

### ISSUE THREAD

**Issue by Ovi** [rt2zz/redux-persist#1114]
I first used it in my on-going app and it did not work.
Then created a new react app and configured redux and redux-persist but still, it's not working.

It stores the store in localstorage, but when I refresh my app, all the data is reset.

#
##### store.js
```js
import { createStore } from 'redux';
import { persistStore, persistReducer } from 'redux-persist';
import storage from 'redux-persist/lib/storage';
import rootReducer from './reducers';

const persistConfig = {
  key: 'root',
  storage,
};

const persistedReducer = persistReducer(persistConfig, rootReducer);
const store = createStore(persistedReducer);
const persistor = persistStore(store);

export { store, persistor };
```

#
##### reducers.js
```js
import { combineReducers } from 'redux';

const INIT_STATE = {
  quote: null,
};

const quote = (state = INIT_STATE, action) => {
  switch (action.type) {
    case 'SET_QUOTE':
      return { ...state, quote: action.payload };

    default:
      return { ...state };
  }
};

export default combineReducers({ quote });
```

#

##### src/index.js
```jsx
import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';
import { store, persistor } from './redux/store';
import App from './App';

const MainApp = () => (
  <Provider store={store}>
    <PersistGate loading={null} persistor={persistor}>
      <Router>
        <Switch>
          <Route path="/" component={App} />
        </Switch>
      </Router>
    </PersistGate>
  </Provider>
);

export default render(<MainApp />, document.querySelector('#root'));
```
#

Tried the latest versions of redux-persist, redux and react-redux, and with few older versions too but no luck!

**Comment by NomanGul** [comment]
@Ovi You did the same mistake I did several times before :smiley: 

Instead of returning this in `reducers.js`:

```javascript
default:
  return { ...state };
```

return this:

```javascript
default:
  return state;
```

I hope It'll help you and please close this issue after it works :+1:

**Comment by ROGAL12321** [comment]
@NomanGul Thanks for sharing that! It resolves my problem I had for 2 months 🙄

**Comment by harryrein3** [comment]
Can anyone explain why the { ...state } doesn't work but state does? It worked for me! But just curious why.

**Comment by DarKayserLeo** [comment]
> @Ovi You did the same mistake I did several times before 😃
> 
> Instead of returning this in `reducers.js`:
> 
> ```js
> default:
>   return { ...state };
> ```
> 
> return this:
> 
> ```js
> default:
>   return state;
> ```
> 
> I hope It'll help you and please close this issue after it works 👍

Wow this is the answerI made the same MISTAKE, I wasted like 2 hours trying to figure out the issue.  damn man I feel bad xD

**Comment by AbdelkhalekESI** [comment]
@NomanGul It works !! can you explain why please ?

**Comment by toastsgithub** [comment]
I also encountered this problem, but my mistake is returning original `state` object instead of new object `{ ...state, changeToState }` in `case` clause.

**returning `{ ...state, changeToState }` will work fine.**

Hopefully this will help those who might have same problem with me.

**Comment by sumukhah** [comment]
Well in my case, i stopped the remote debugging. Then it fixed automatically :)

**Comment by robinvw1** [comment]
The solution of @NomanGul works. Still looking for a reason (just like the others) why it has to be like that.

If anyone have the time to write it down, we can all leave this behind us. :joy:

**Comment by samwizzy** [comment]
Thank you for this solutions, I feel like all my problems in the past 24hours has come to a stop. This will certainly save lot of lives out there 

How can a very little glitch like this cause anyone sleepless nights

All I had to do was🤦🏽‍♂️
`
default
    return state
`

**Comment by recursive-reshy** [comment]
Does anyone know why spreading the state object doesn't allow the state to rehydrate?

**Comment by NomanGul** [comment]
> The solution of @NomanGul works. Still looking for a reason (just like the others) why it has to be like that.
> 
> If anyone has the time to write it down, we can all leave this behind us. 😂



copied from https://stackoverflow.com/questions/67747646/using-state-instead-of-state-in-persistreducer-in-redux#comment122501873_69305171

> How much I understood it is when I spread the state, as it creates a new object, on app reload, the redux checks for the default and as that is a new object, it updates the state but the state which we spreaded is not the persisted state but the initialState. But when we don't spread the state and simply return the state, it doesn't mutate the state and simply returns it which is actually the persisted state. Still a little hard to understand.

**Comment by rajat-simform** [comment]
> @Ovi You did the same mistake I did several times before 😃
> 
> Instead of returning this in `reducers.js`:
> 
> ```js
> default:
>   return { ...state };
> ```
> 
> return this:
> 
> ```js
> default:
>   return state;
> ```
> 
> I hope It'll help you and please close this issue after it works 👍

This is a very perfect solution.
Thanks for the help!
