### ISSUE TITLE
execute sequence problem

### ISSUE THREAD

**Issue by tigerohuang** [rt2zz/redux-persist#114]
1. initialize 

     case REHYDRATE:
      let incoming = action.payload.user;
      if(!isNil(incoming.token))
         globals.token = incoming.token;
      console.log('i am loadding user');

2. use the initialize

      componentDidMount() {
        this.props.dispatch(loadHome());
    }

   and in loadHome，it needs the globals.token ,but I found loadHome execute before console.log('i am loadding user');  so it can't get the token.

**Comment by tigerohuang** [comment]
I think REHYDRATE should execute before any business logic

**Comment by tigerohuang** [comment]
export default function configureStore(onComplete: ?() => void) {
  const store = autoRehydrate()(createStoreWithMiddleware)(reducers);
  persistor = persistStore(store, {storage: AsyncStorage}, onComplete);
  // persistor = persistStore(store, {blacklist: ['reducers'],storage: AsyncStorage}, onComplete);
  // persistor = persistStore(store, {skipRestore: true,storage: AsyncStorage}, onComplete);
  if (isDebuggingInChrome) {
    window.store = store;
  }
  return store;
}

**Comment by rt2zz** [comment]
@tigerohuang it looks like you got it solved?

One option is to use https://github.com/rt2zz/redux-action-buffer to buffer all actions until rehydrate is complete. Another option is to run your business logic in the onComplete handler which it looks like you may have ended up doing.
