### ISSUE TITLE
Doesn't persist

### ISSUE THREAD

**Issue by burakcan** [rt2zz/redux-persist#116]
Hello and thank you for this library,
I was using redux-persist to persist to localstorage and rehydrate a part of my app. But somehow, it suddenly stopped persisting. Rehydrate action is still fired with and empty payload but nothing is written to the localstorage.

i'm using it with persistStore:
```persistStore(store);```

Also i couldn't figure out how to whitelist only a deeply nested branch. I need to do this because the branch that i want to persist is a part of another branch which is often really really big.

**Comment by rt2zz** [comment]
did you possibly leave `.purgeAll()` in your code? 

Redux persist is generally designed to persist whole sub-reducers, you may want to consider restructuring your reducers to put that deeply nested state near the top. Another option is you can write a [transform](https://github.com/rt2zz/redux-persist#transforms) to filter out only the state you care about:
