### ISSUE TITLE
lib/autoRehydrate.js still requiring ./bufferActions

### ISSUE THREAD

**Issue by dudeinthemirror** [rt2zz/redux-persist#117]
Hi, I just upgraded to version 3.2.2.
I'm getting this error:

![screen shot 2016-06-12 at 8 11 34 am](https://cloud.githubusercontent.com/assets/981638/15991933/7be5c1f4-3075-11e6-9141-9b60c2dbf838.png)

When I look at `node_modules/redux-persist/lib/autoRehydrate.js` line 11, I see this require which still refers to inexistent file `./bufferActions.js`:

![screen shot 2016-06-12 at 7 54 43 am](https://cloud.githubusercontent.com/assets/981638/15991941/a212fc70-3075-11e6-9fc0-96a8f8316956.png)

What am I missing here ?
(tried the usual cleanup several times: watchman watch-del-all, rm -rf ./node_modules, rm -rf ${TMPDIR}/react-*)
Thanks in advance for your time.

**Comment by dudeinthemirror** [comment]
It looks like it was a weird caching issue on my side. 
Fixed now, will close the issue.
Thanks again for a great library.

**Comment by rt2zz** [comment]
👍  glad you got it sorted. Did it requires a fresh npm install?
