### ISSUE TITLE
[RFC] Moving to a single rehydrate action 

### ISSUE THREAD

**Issue by rt2zz** [rt2zz/redux-persist#12]
Redux Persist currently emits several rehydration actions: one for every reducer. It was designed this way because it directly reflects the way redux persist works under the hood, on a per reducer basis. However we could just as easily merge every persisted value into one single 'initial state' object and fire a single `REHYDRATE` action.

Pros:
- less noise in action log
- makes writing custom auto-rehydration functions easier
- can potentially remove `REHYDRATE_COMPLETE` action

Cons:
- Dealing with nested data can be error prone in custom rehydration handlers

Thoughts?

**Comment by zalmoxisus** [comment]
Does it mean that the rehydration key will not match the reducer key anymore? It is not a big problem I guess, we may just catch them by payload parameters. I'd opt for less noise.

**Comment by rt2zz** [comment]
@zalmoxisus yes, there would no longer be a reducer key on the action. 

By less noise, do you mean you would prefer it was consolidated to one action?

**Comment by zalmoxisus** [comment]
Yes, having a lot of reducers could generate a lot of rehydate actions in the devtool, making it difficult for debuging.

Also REHYDRATE_COMPLETE is a bit ambiguous as it is invoked only after the initial rehydratations. If we use something like persist-crosstab, one would expect to have REHYDRATE_COMPLETE when new rehydratations occur  as well.

Though I agree that dealing with nested data can be error prone in custom rehydration handlers.

**Comment by rt2zz** [comment]
Will most likely make the switch in 2.0. This creates better symmetry with the `getStoredState` api and reduces log noise.

Will deal with the "debugability" question with a debug option.
