### ISSUE TITLE
Manual Persist

### ISSUE THREAD

**Issue by KarlPurk** [rt2zz/redux-persist#120]
Is it possible to manually persist state rather than having state automatically persisted on each change?

**Comment by rt2zz** [comment]
not currently, but I would be open to ideas for what this would look like

**Comment by rt2zz** [comment]
@KarlPurk can you elaborate on why you want to manual trigger persist? If performance is an issue you can set a debounce on the persist, or also blacklist expensive reducers.

**Comment by KarlPurk** [comment]
For development purposes.  Manually persisting state is useful when debugging issues where the application has to be in a particular state in order to reproduce the bug.  You can setup the application in the desired state and manually persist the state to storage - you're then in a position where you can make code changes and refresh the application to return to the same state quickly, allowing for easier debugging.

**Comment by simonacca** [comment]
@KarlPurk Maybe you can try solving this problem with hot reloading.

A possible production use case for this feature is the following: I have set a rather long `debounce` for performance reasons and would like to be sure that the state is persisted when the user exits my app.

The ideal interface, I think, would be something like this:

```javascript
const persistor = persistStore(store, { debounce: 5000 });

window.onbeforeunload = function(){
  persistor.persist();
};
```

**Comment by rt2zz** [comment]
@simonacca clever. The api is not exposed for this currently, but I am open to suggestions. `persistor.persist()` seems ambiguous (ie. it is *already* persisting). Some ideas:
`persistor.flush()`
`persistor.persistImmediate()`

This method would probably need to return a promise as persistence is typically (depending on storage engine) not sync.

**Comment by simonacca** [comment]
Agreed, `.flush()` or `.persistImmediate()` is a much better API.

I am trying to implement this in #217 , let me know what you think.

**Comment by fresk-nc** [comment]
it would be cool if I could persist the state even though it has not changed

**Comment by wwwdata** [comment]
Another use case that we are currently having:

We have a native app which also has a react native app. So certain parts of the app are implemented with react native and are using redux-persist. Before shutting down the react native part of the app, we want to make sure all the redux state got persisted and we don't kill of the react native (in terms of Android) activity too early before the state could be persisted.

**Comment by rt2zz** [comment]
`flush` is now part of the api, `persistor.flush()` which returns a promise that resolves when the flush is complete.

**Comment by carlgieringer** [comment]
One use-case is an app that is being very careful not to persist anything for privacy reasons. (I am not an expert on privacy, so this comment should not be taken as a reflection of what should be done to comply with privacy regulations.) Prior to obtaining consent from the user, the app would not persist anything at all. After obtaining consent, the app would like to trigger persisting the state that previously should have been persisted.

Below is an approach I am considering. It has the downside of creating an empty `persist:root` entry in local storage prior to consent, but I think that's an acceptable technical limitation.

```
  const serialize = (data) => {
    return cookieConsent.isAccepted(BASIC_FUNCTIONALITY) ? JSON.stringify(data) : ''
  }
  const persistedReducer = persistReducer({
    key: 'root',
    storage,
    serialize,
    whitelist: config.reduxPersistWhitelist,
  }, createRootReducer(history))

  const store = createStore(...)

  const persistor = persistStore(store)
  cookieConsent.on('update', (cookies) => {
    // store.dispatch({type: PERSIST})
    // persistor.flush().catch((err) => logger.exception(err, "error flushing persistor after cookie consent update"))
    persistor.persist()
  })
```
