### ISSUE TITLE
Add comparison table for redux-localstorage in the readme

### ISSUE THREAD

**Issue by mattkrick** [rt2zz/redux-persist#123]
I'm pretty new to persisted state in redux & I'd love to see a comparison table between this & the other popular packages (eg redux-localstorage, redux-storage, etc) so I can quickly pick which one to start learning, or learn that one has a deal breaker before diving in.

Not to self-promote, but it's the quickest example I could come up with: https://github.com/mattkrick/redux-optimistic-ui#hows-it-different-from-redux-optimist

**Comment by rt2zz** [comment]
I do not have a comprehensive comparison, but I would recommend either redux-persist or redux-storage. Persist works per reducer and I think is generally more performant while redux-storage works on the entire state.
