### ISSUE TITLE
Performance issues caused by automatic persisting for each change?

### ISSUE THREAD

**Issue by fzyzcjy** [rt2zz/redux-persist#1234]
HI thanks for the library! IMHO, this library persists onto disk for each change of the state tree. Therefore, IMHO that will cause a lot of computations and will be slow. I wonder how do you solve this problem in real apps? Or do I make something wrong? Thanks!

**Comment by vovkasm** [comment]
Did you seen `throttle` option in [api.md](https://github.com/rt2zz/redux-persist/blob/master/docs/api.md#type-persistconfig)?
