### ISSUE TITLE
[Racial equality] Change blacklist and whitelist 

### ISSUE THREAD

**Issue by deebov** [rt2zz/redux-persist#1241]
Hi everyone 👋

I want to suggest to omit the blacklist and whitelist keywords [in redux-persist]. While these terms are used widely in the tech community they raise concerns in racial equality meaning that black=bad, white=good. 

Here's what I would recommend using instead: blocklist/ignorelist, allowlist

**Comment by pro-nasa** [comment]
https://github.com/rt2zz/redux-persist/pull/1213#issuecomment-681130564

**Comment by BeKnowDo** [comment]
You know...the Sun is white more or less. Night is black. Are they racist?

You hear how ridiculous it sounds?
