### ISSUE TITLE
Removing a value in an array is not persisted after refresh.

### ISSUE THREAD

**Issue by donutsahoy** [rt2zz/redux-persist#1251]
I am having an issue deleting values from an array of objects that is being persisted. Like this issue https://github.com/rt2zz/redux-persist/issues/811

However I am still encountering this issue and it appears that the resulting PR from that issue was accepted and pulled in so maybe I'm doing something wrong? If I do a delete and then had something no issue there it works fine but just deleting does not work.

The deletion shows up in console logs of the state before and after and the array shows the element is gone. Until I refresh the app and then it shows back up.

This is how I am doing the delete.

`        case 'DELETE':
            newState = state;
            newState.splice(newState.findIndex(el => el.uuid === action.payload.uuid), 1);
            return (newState);`

I've even tried flushing the persistor after the delete dispatch has been called and that doesn't fix the issue either.

NB: I am running version 6.

**Comment by papb** [comment]
Looks like you are modifying the array instead of providing a new one. Things should be immutable in redux, so try `return newState.slice()` instead. It should work.

**Comment by donutsahoy** [comment]
Looks like the classic mistake of assuming that array1 = array creates a copy when it actually doesn't. Thanks for the heads up, fixed the issue and it works like a charm. Thank you!

**Comment by papb** [comment]
@donutsahoy Happy to help :)
