### ISSUE TITLE
Static purgeAll

### ISSUE THREAD

**Issue by nevir** [rt2zz/redux-persist#127]
It'd be handy to have a static `purge` and `purgeAll` that can be called before constructing a persistor.

I'm looking to be able to do this after fatal errors that have likely landed the user in a bad state (and it's safer to just wipe the store, have them log in again, and rebuild their state)

**Comment by rt2zz** [comment]
this is available in the 4.0.0-alpha1 release 🎈

**Comment by nevir** [comment]
Sweet, thanks!

**Comment by rt2zz** [comment]
note: it is exported as `purgeStoredState`

`purgeStoredState(config)` is the equivalent to "purgeAll"
