### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by RyanWarner** [rt2zz/redux-persist#1275]
If not, does anyone have any alternatives they would suggest?

perhaps the maintainer could also do one final commit to update the readme letting people know it's no longer being actively developed.

**Comment by wmonecke** [comment]
No, it isn't and I haven't found a reliable alternative.

**Comment by allandiego** [comment]
Alternative:
https://recoiljs.org
With recoil persist

**Comment by marstall** [comment]
Redux Offline seems similar? 
https://github.com/redux-offline/redux-offline

**Comment by Marvedog** [comment]
@marstall Seems like `redux-offline` depends on `redux-persist` though.

**Comment by Rebsos** [comment]
Maybe this lib does not need to be highly maintained. I'm STILL on v4 (2017) with RN 63. Works great.

**Comment by wmonecke** [comment]
> Maybe this lib does not need to be highly maintained. I'm STILL on v4 (2017) with RN 63. Works great.

We are experiencing a pretty big bug where the store gets completely wiped when doing a migration. 
It makes users lose all their data.

**Comment by Marvedog** [comment]
@Rebsos It may not be high maintenance, but some maintenance we need.
@wmonecke Do you know how to get hold of the maintainers?

**Comment by RyanWarner** [comment]
@Rebsos That's definitely not true for everyone.

I'm having issues with this library during server side rendering. It's swallowing up my SEO data in a NextJS app. Even if it doesn't need much maintenance, it is useful for developers to know if this library is maintained or not, especially if they are evaluating options in a new project.

**Comment by rueiwoqp** [comment]
> > Maybe this lib does not need to be highly maintained. I'm STILL on v4 (2017) with RN 63. Works great.
> 
> We are experiencing a pretty big bug where the store gets completely wiped when doing a migration.
> It makes users lose all their data.

I have the same issue and it makes this completely unusable. Tracking down the issue is nearly impossible. I've set the timeout to 0, which supposedly prevents the store from getting wiped but it happens randomly after weeks of working fine.

**Comment by Philip-Nunoo** [comment]
@RyanWarner 

I wish people pay for opening issues for open source projects.

But all the same, So the assumption that the last commit being done a year ago invalidates a project, is not true. Maybe there is nothing to fix. 

But all the same, I see no reason why people report issues on an open-source(it's open source for crying out loud) project and refuse to submit a PR if they found an issue. But the issue shouldn’t be a reason to not use it.

I actually went through the issues that were raised, and I noticed that individuals could have created a PR for those and submitted it or used it in their own project. And if there exists a PR that resolves your issue, why don't you go ahead and use that. 

That is my personal opinion, we don’t pay the maintainers so why would you be asking “Is this library still maintained?”

**Comment by RyanWarner** [comment]
> @RyanWarner
> 
> I wish people pay for opening issues for open source projects.
> 
> But all the same, So the assumption that the last commit being done a year ago invalidates a project, is not true. Maybe there is nothing to fix.
> 
> But all the same, I see no reason why people report issues on an open-source(it's open source for crying out loud) project and refuse to submit a PR if they found an issue. But the issue shouldn’t be a reason to not use it.
> 
> I actually went through the issues that were raised, and I noticed that individuals could have created a PR for those and submitted it or used it in their own project. And if there exists a PR that resolves your issue, why don't you go ahead and use that.
> 
> That is my personal opinion, we don’t pay the maintainers so why would you be asking “Is this library still maintained?”

@Philip-Nunoo 

There is no problem with the maintainer deciding to stop working on this project. I just want to know if they've abandoned the project so that I can decide how I want to move forward.

I don't refuse to submit a PR, I refuse to submit a PR if that PR will never get reviewed and merged because there is no maintainer. I see PRs from _years_ ago sitting stale. Why should I put in work to fix a bug that will never get released?

Further, I also don't mind paying maintainers. I have sponsored open source maintainers in the past, am currently paying an open source maintainer (see my "Sponsors" section), and would gladly contribute money if the maintainer of this library were to communicate with me about my issues.

I don't understand why you're trying to take some sort of moral stance on my simple "yes or no" question. I have nothing against the maintainer of this library, wether they continue to support the library or not. They do not owe me anything, and I am thankful for all the free work they have done thus far.

**Comment by cristianoccazinsp** [comment]
What's the status on this? Any new fork/maintainers?

**Comment by wmonecke** [comment]
@Philip-Nunoo Welcome to the open-source world. Before going after someone I would recommend you to understand what open-source means. You are allowed to open issues, even if you don't submit PRs. Also, much of the software you use is build on top of OS code. It is reasonable to ask if a library is still maintained, especially in one that will persist states and might be key to an app's success! Happy coding!

**Comment by wmonecke** [comment]
@jayarjo I would love to help maintain this repo and review PRs. I have messaged @rt2zz via Twitter.

**Comment by marstall** [comment]
well done @wmonecke ! Really appreciate this.

**Comment by ckalika** [comment]
@RyanWarner It is (as of last week).

I took over maintenance last week, so definitely want to engage with you guys to make it better. Hopefully this restores a bit of confidence, as the library still works very well (though we need to upgrade the docs).

**Comment by Philip-Nunoo** [comment]
Great. 👍

**Comment by marstall** [comment]
@ckalika hey! great to hear. this library is really a key part of the puzzle. and quite core to two apps I work on (shelf.fm & SiteWorx listing control app)

**Comment by adamsythe** [comment]
@ckalika 

I see that there are still no releases in the last 2 years and lots of outstanding PR's.  I know that taking over the project is a big ask and i dont mean to come across pushy but I am just checking that you are still actively mantaining it and ask if you have a plan for another release?  

This library is cornerstone to a lot of big projects so it is just a little scary looking at that date on the last release :)

**Comment by marstall** [comment]
@adamsythe I see a big release a year ago? looks juicy, plan to give it a shake on my next SiteWorx release, thanks @ckalika

**Comment by Rebsos** [comment]
There are some code changes 10 months ago, but I also don't see any release since 2019:

# npm view redux-persist --json

    "6.0.0-pre1": "2019-05-07T21:10:45.875Z",
    "6.0.0-pre2": "2019-06-04T19:24:11.039Z",
    "6.0.0-pre2.0": "2019-07-05T16:09:34.879Z",
    "6.0.0-pre2.1": "2019-07-05T16:16:16.204Z",
    "6.0.0": "2019-09-02T00:39:26.341Z"

# https://github.com/rt2zz/redux-persist
    Releases 12
    v6.0.0 Latest
    on 2 Sep 2019

**Comment by adamsythe** [comment]
@marstall  the last release was 2nd of septemer 2021, 18 months ago and 3 weeks before @ckalika took over.  Am I missing something?

**Comment by marstall** [comment]
ok it's late, maybe I'm misunderstanding here - but it's Aug of 2022 now - so September 2021 would be 11 months ago ...

**Comment by marstall** [comment]
oh I see you guys are talking about a release, I get it now, I was just looking at the last commit.

**Comment by adamsythe** [comment]
sorry i meant septemer 2019.  Not sure where i got that 18 months from but yeh over 2 years and before new maintainer took over
