### ISSUE TITLE
Blacklist nested reducer.

### ISSUE THREAD

**Issue by ayoola-solomon** [rt2zz/redux-persist#128]
How do I blacklist nested reducers from 
`{
  default: {
  leads: { message: 'Welcome to EURO 2016' },
  locale: { translation: 'de' }
 }
}`

Have got this 
`export default combineReducers({ leads, locale })`

and this 
`const reducer = combineReducers(reducers);`
`const store   
     = applyMiddleware(promiseMiddleware)(createStore)(reducer, initialState, autoRehydrate());`
`persistStore(store);`

**Comment by rt2zz** [comment]
what do you want to blacklist exactly? Blacklist only applies to the first tier of reducer, so in your example you can blacklist `leads` or `locale`. If you need more fine grained blacklisting you could implement a custom transform.

**Comment by ayoola-solomon** [comment]
I want to blacklist `leads`. Can you show me examples of the customs transform you are talking about.

**Comment by rt2zz** [comment]
I believe this transform will work for you: https://github.com/edy/redux-persist-transform-filter
