### ISSUE TITLE
What is key in config?

### ISSUE THREAD

**Issue by amsterdamharu** [rt2zz/redux-persist#1290]
The readme shows the following code a couple of times:

```
const persistConfig = {
  key: 'root',
  storage: storage,
  blacklist: ['navigation'] // navigation will not be persisted
};
```

But other than stating it's mandatory it is not explained what this key means.

Fill api documents clears it up in no way by stating `the key for the persist`

**Comment by amsterdamharu** [comment]
....

**Comment by gmadez** [comment]
I've used it as the "name" of the file in conjunction with prefix (defaulted to "persist" as per constants.js)
So, an input like this one:
![image](https://user-images.githubusercontent.com/1152197/115476189-f773d880-a206-11eb-97ef-8910cf5d40c5.png)

generates the following file: 
![image](https://user-images.githubusercontent.com/1152197/115476282-36099300-a207-11eb-929c-6355941432b2.png)

**Comment by olsonpm** [comment]
Got here with the same question.  A mandatory config property with no explanation on what it is/does feels weird.
