### ISSUE TITLE
Do i need to ask for permission for that?

### ISSUE THREAD

**Issue by Ginso** [rt2zz/redux-persist#1295]
Hello,
i'm relatively new to using stuff like cookies and sessionStorage and so on.
Where exactly does this package store the data (if i use like in the example on the readme)?
Do i need to ask the user for permission to store data like that?(According to GDPR)

**Comment by ckalika** [comment]
@Ginso Hey there. This depends on whether you're using it on web or on react-native. If you're using it on the web, then it stores to local storage. If you're using it on react-native, then you can pass in a storage engine (the most common of which is https://github.com/react-native-async-storage/async-storage).

As for the GDPR implications... Yes you'll probably need to ask for permission, the same as you would for cookies. I'm UK-based, so here's the documentation that might point you in the right direction. Keep in mind, it may differ a bit now that we've gone through Brexit: https://ico.org.uk/for-organisations/guide-to-pecr/cookies-and-similar-technologies/
