### ISSUE TITLE
actionCreator never called

### ISSUE THREAD

**Issue by zalmoxisus** [rt2zz/redux-persist#13]
Trying to add a custom action creator to take action during rehydration according to the [recipes](https://github.com/rt2zz/redux-persist/blob/master/docs/recipes.md), but it is not called. Is this parameter still in use? I guess no according to https://github.com/rt2zz/redux-persist/issues/4.

**Comment by rt2zz** [comment]
Woops, I forgot to update the recipes: I renamed it to `rehydrateAction`
```js
persistStore(store, { rehydrateAction: rehydrateAction })
```

Note: your rehydrateAction must use the `import { REHYDRATE } from 'redux-persist/constants'` action type if you want autoRehydrate to pick it up.

I also removed it from the docs because I am not yet sure if this is the best api for taking action during rehydration. Are you making server calls within your custom rehydrate action? Let me know if it works well for you.

**Comment by zalmoxisus** [comment]
It works now. Thanks a lot!

Just testing so far. Trying to replace browser extension [messaging](https://developer.chrome.com/extensions/messaging) with just rehydratations. As the result we get a crossbrowser (only the Storage Backend will be different) extension with just redux actions. It seems to be pretty suitable for Chrome, but still have to implement some hacks for Firefox and check how stable it will be. Maybe it is a crazy idea, but worth to try :)

**Comment by rt2zz** [comment]
awesome, let me know how it goes, or if you need any additional integration points into redux-persist to make it work.

**Comment by rt2zz** [comment]
not sure I fully understand your architechture, but you might consider calling persistor.rehydrate to keep things in sync between tabs

```js
const persistor = persistStore(store)
//...
persistor.rehydrate(someReducerKey, newState, () => {})
```

**Comment by zalmoxisus** [comment]
Sure, If it is stable. Yes, as in redux-persist-crosstabs. Thanks for your help!

**Comment by zalmoxisus** [comment]
@rt2zz, as I promised, here are the results of this "experiment": https://github.com/zalmoxisus/browser-redux

It [uses chrome.store](https://github.com/zalmoxisus/browser-redux/tree/master/src/app/store) as described in your documentation. Synchronisation is [made as in persist-croostab](https://github.com/zalmoxisus/browser-redux-sync/blob/master/index.js).

It seems to work pretty well. The only differences from using redux-persist on web apps are:
1. Unlike window.addEventListener('storage'), chrome.storage.onChanged is triggered on local changes as well, which is reported as a [bug](https://code.google.com/p/chromium/issues/detail?id=361113). But it can be [managed trivially](https://github.com/zalmoxisus/browser-redux/commit/34bb4c0acf4db5a795d4c45d24a28816d7a15d94).
2. chrome.storage.local can store objects, so we don't need to serialize the data (in order to boost the performance), but we still need it to fix 1.

**Comment by rt2zz** [comment]
that looks awesome.

Regarding serialization, redux-persist serializes the data before calling the storage api. I did add an undocumented escape hatch where you can specify a serialize and deserialize function in the config:
```js
persistStore(store, { serialize: (data) => data, deserialize: (data) => data })
```

**Comment by zalmoxisus** [comment]
That's exactly what I need. Thanks a lot!
