### ISSUE TITLE
Error: redux-persist: persist timed out for persist key "root"

### ISSUE THREAD

**Issue by djschilling** [rt2zz/redux-persist#1308]
After upgrading react-native from `0.63.3` to `0.64.1` i get the error `Error: redux-persist: persist timed out for persist key "root"`.

I am using redux-persist version `6.0.0`.

I also read this issue but could not find a solution there: https://github.com/rt2zz/redux-persist/issues/717

This is my persist config:

```
const persistConfig = {
    key: 'root',
    storage: AsyncStorage,
    blacklist: ['fetching'],
    timeout: 20000
};
```

**Comment by DracotMolver** [comment]
I'm facing the same. But I don't use `AsyncStorage`. Anyways, try adding the `timeout:null`:

```js
const persistConfig = {
  key: 'root',
  storage: FilesystemStorage,
  // There is an issue in the source code of redux-persist (default setTimeout does not cleaning)
  timeout: null,
}
```

**Comment by kanoosharma** [comment]
> I'm facing the same. But I don't use `AsyncStorage`. Anyways, try adding the `timeout:null`:
> 
> ```js
> const persistConfig = {
>   key: 'root',
>   storage: FilesystemStorage,
>   // There is an issue in the source code of redux-persist (default setTimeout does not cleaning)
>   timeout: null,
> }
> ```

this works for me.. thanks a lot man

**Comment by djschilling** [comment]
in my case it was an old version of core-js that caused the issue.
