### ISSUE TITLE
Delaying App render till Rehydration results in Invalid react checksum.

### ISSUE THREAD

**Issue by amrit92** [rt2zz/redux-persist#131]
I am trying to use the given delaying strategy. However since i am rendering server side, this  results in React throwing a checksum error. I am using redux-persist so that the following can be achieved.
Server renders -> Redux-persist loads the state ->other redux actions are carried out and UI renders. 
I know this is perhaps not an issue for Redux-persist to resolve However I am sure this is a common usecase.

**Comment by rt2zz** [comment]
I am unfamiliar with this problem and have not done server side rendering myself. One possible fix would be to instead of delaying rendering entirely you render immediately with initial state but put a loader up until persist completes.

**Comment by teameh** [comment]
> I am unfamiliar with this problem and have not done server side rendering myself. One possible fix would be to instead of delaying rendering entirely you render immediately with initial state but put a loader up until persist completes.

Which apart from fixing the checksum error will also give you an quicker 'time to first paint' :)

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
