### ISSUE TITLE
Need a new maintainer

### ISSUE THREAD

**Issue by cristianoccazinsp** [rt2zz/redux-persist#1325]
@rt2zz are you still maintaining this library? There are many PRs waiting and this is still an extremely useful library.

If not, would you please allow for a new maintainer?

Thanks,

**Comment by joemewes** [comment]
+1

**Comment by smellman** [comment]
I just working this issue, so please comment to my PR.

**Comment by ckalika** [comment]
Hey there.

I spoke with @rt2zz last week about taking over as maintainer of the project and he seemed keen. I'll be spending some time over the next couple of weeks trying to get a handle on the state of things so I can triage issues and pull requests. I know there are some major ones outstanding and there are some that will have to be flushed, but I hope that won't stop people from contributing in future.

@smellman Can we go through your PR at some point soon?

Cheers.

- Christopher

**Comment by smellman** [comment]
@ckalika Please check my PR. I rewrite all code to TypeScript.

**Comment by dancixx** [comment]
@ckalika Is there any information about a new version maybe?

**Comment by Dr-Horv** [comment]
@ckalika any update on current state of things?
