### ISSUE TITLE
Why persistence works without <PersistGate>

### ISSUE THREAD

**Issue by ablaszkiewicz** [rt2zz/redux-persist#1333]
Hello. I am integrating **redux-persist** with **next-js** and following a simple, straight forward tutorial which I did in previous project and before finishing last step (which was to wrap everything with **PersistGate**) just out of curiosity I checked what would happen without it.

And guess what. Everything works fine. Data is persisted between reloads.
![abc](https://user-images.githubusercontent.com/54682207/129491789-a32816c6-7c4f-42a3-b1ae-ac41d7271421.jpg)

(Works without underlined code fragments)
Can someone explain it to me? Why does it work?

**Comment by greg-wb-ap** [comment]
It is to stop a flash of "initial state" between the server load of the page and the retrieval of state from the storage layer.

**Comment by ablaszkiewicz** [comment]
Oh thank you. Makes sense now.
