### ISSUE TITLE
How does redux-persist listen for localstorage changes

### ISSUE THREAD

**Issue by lalLAL95828** [rt2zz/redux-persist#1337]
When two pages are opened, one page changes the value of localstorage. How does the other page listen for changes

**Comment by ckalika** [comment]
@lalLAL95828 Check out the example of the storage event here: https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event

This isn't a project-specific question, but I've added it as a TODO to add as a code sample relating to redux-persist, as it's likely useful.
