### ISSUE TITLE
Blacklist nested attributes

### ISSUE THREAD

**Issue by 39otrebla** [rt2zz/redux-persist#134]
Assuming my store objects looks like this 
`{ data: {search: {data: [....]}, history:{search: [...], product: [...]}, favourites: {search: [...], product: [...]}}, navigation: {....}, user: {....}}`

How can I blacklist `data.search`, while keeping `data.history` and `data.favourites` ?
I've tried with` ['data.search']`, but no luck. 

Thank you.

**Comment by rt2zz** [comment]
This is not available out of the box but it should be trivial to write a transform that does that. It would look something like
```js
let blacklistTransform = createTransform(
  (inboundState, key) => {
      if (key !== 'data') return inboundState
      else return {
        ...inboundState,
        data: undefined,
       }
  }
)
```

**Comment by rt2zz** [comment]
while I have not personally used it, this project aims to solve this problem: https://github.com/edy/redux-persist-transform-filter

**Comment by brunolemos** [comment]
@rt2zz that could be implemented using lodash to easily accept nested paths. Probably [pick](https://lodash.com/docs/4.17.2#pick) for whitelist and [omit](https://lodash.com/docs/4.17.2#omit) for blacklist.

**Comment by ankit90anand** [comment]
There is one more way. Store a getter function in place of nested key which needs to be blacklisted. 

let nestedKey = "blacklisted";
let getNestedKey = ()=>nestedKey;
...
{
     case REHYDRATE : return  {...state,
           nestedKey:getNestedKey
      };
}

In storage getter function will always be null.

When passing as props call the getter function to get the actual value.

**Comment by gyosifov** [comment]
As @brunolemos  and @rt2zz have suggested the code looks something like this:

import omit from 'lodash/omit'

let blacklistTransform = createTransform(
    (inboundState, key) => {
        if (key === 'data') {
            return omit(inboundState, ['search']);
        } else {
            return inboundState;
        }
    }
)
...
const persistConfig = {
    key: 'root',
    storage,
    transforms: [blacklistTransform],
}

**Comment by Venryx** [comment]
Here's a slightly more modular version of @gyosifov's solution above:
```
import omit from 'lodash/omit';

const blacklistPaths = ['prop1', 'prop2', 'prop3.nestedProp'];
const persistConfig = {
	[...]
	transforms: [
		// use a custom blacklist transform, so that we can blacklist nested paths
		createTransform((inboundState, key) => {
			if (blacklistPaths.indexOf(key) != -1) return undefined;
			const blacklistPaths_forKey = blacklistPaths.filter(path => path.startsWith(`${key}.`)).map(path => path.substr(key.length + 1));
			return blacklistPaths_forKey.length ? omit(inboundState, ...blacklistPaths_forKey) : inboundState;
		}, null),
	],
};
```

**Comment by nandorojo** [comment]
Has anyone come up with a better solution so far?

**Comment by icy-meteor** [comment]
@Venryx Works well, thank you :)

**Comment by elie-chaaban** [comment]
@Venryx how can we make like the code you did but with double .
i meant: [global.auth.loading] instead of [auth.loading]


please thanks!

**Comment by elie-chaaban** [comment]
i tried this

createTransform((inboundState, key) => {
      const blacklistPaths_forKey = blacklistPaths
        .filter((path) => path.startsWith(`${key}.`))
        .map((path) => `${key}.` + path.substr(key.length + 1));
      console.log(...blacklistPaths_forKey);
      return omit(inboundState, ...blacklistPaths_forKey);

added the `${key}.` after mapping but it s still saving the attribute
