### ISSUE TITLE
use in angular2 - 

### ISSUE THREAD

**Issue by 1STi** [rt2zz/redux-persist#135]
Hi!

When importing from angular2 application, i'm getting:
Module build failed: (5,43): error TS2307: Cannot find module 'redux-persist'.

The lib is in node_modules as the others.

Have some idea how to fix it? I can code and submit a PR. I think this is because index.js on src folder.

**Comment by rt2zz** [comment]
are you installing via npm? index.js is in src, but in the package delivered by npm you should see index.js in lib. If you install directly from github then you will need to build the project to get the built lib dir.

**Comment by 1STi** [comment]
Hi,

Yes, installed via npm. I think the issue is the absence of typescript bindings for angular2...

Some thoughts?

**Comment by rt2zz** [comment]
I am not familiar with typescript but I am open to adding support. I believe redux now ships with typescript annotations.

**Comment by murraybauer** [comment]
I've got the same issue.  Never had a problem with using other npm modules with angular 2.

Not sure how to fix it.

This article talks about how to build an angular 2 library.  It seems the tsconfig.json file is key to get the correct commonJS module export.  But that is for typescript which this project doesn't use.

https://medium.com/@OCombe/how-to-publish-a-library-for-angular-2-on-npm-5f48cdabf435#.me99m3i2p

**Comment by murraybauer** [comment]
Figured it out.

Use require instead of import:

const persistStore = require('redux-persist').persistStore;
const autoRehydrate = require('redux-persist').autoRehydrate;

**Comment by rt2zz** [comment]
glad you got it solved! Not sure why import syntax would not work, but let me know if any changes to the lib would help.

**Comment by xcssum** [comment]
I think the reason is needing a .d.ts file to help typescript compile this

**Comment by dannymy** [comment]
As import works with the provided solution, I can not properly configure store in the Angular2:

```
// 1.
const store = createStore(
  rootReducer,
  applyMiddleware(autoRehydrate, thunk, logger)
);

// 2.
const store = applyMiddleware(
   autoRehydrate,
   thunk,
   logger
)(createStore)(rootReducer, {});

this.ngRedux.provideStore(store);
```
Both throw an exception (without autoRehydrate configuration is ok and everything works). Am I doing something completely wrong?

**Comment by murraybauer** [comment]
@dannymy what was the exception?

It should work.

**Comment by dannymy** [comment]
@murraybauer `reducer is not a function`, where rootReducer is a combined reducer function.

**Comment by murraybauer** [comment]
@dannymy hrmm not sure exactly.

I would first make sure the `autoRehydrate` function is defined and imported correctly by going `console.log(autoRehydrate)`

Short of that no idea.

**Comment by dannymy** [comment]
@murraybauer looks like it's correctly imported, as it's the right function that returns
 `function (next) { ...`
Could you tell, if you are configuring store the same way? Anyway, thanks for looking into. Will solve somehow.

**Comment by rt2zz** [comment]
@dannymy autoRehydrate is a store enhancer, not a middlware. try like this:

```js
const store = createStore(
  rootReducer,
  compose(
    autoRehydrate()
    applyMiddleware(thunk, logger)
  )
);
```

where compose is imported from redux
