### ISSUE TITLE
After upgrading React native 0.66 Redux persist stop working on android

### ISSUE THREAD

**Issue by Shubhamd-Sankey** [rt2zz/redux-persist#1358]
it works when my react native version is 0.64
```import {createStore, applyMiddleware} from 'redux';
import thunk from 'redux-thunk';
import {persistStore, persistReducer} from 'redux-persist';
import AsyncStorage from '@react-native-community/async-storage';
import {rootReducer} from '../reducer/RootReducers';

let middleWare = [thunk];

const persistConfig = {
  key: 'root',
  storage: AsyncStorage,
  whitelist: ['mainReducer'],
};

// const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

const persistStoreReducer = persistReducer(persistConfig, rootReducer);

export const configStore = createStore(
  persistStoreReducer,
  applyMiddleware(...middleWare),
);

export let persistor = persistStore(configStore);```

**Comment by anwarhamr** [comment]
I'm having this issue w/ a new project using RN 67, any luck?

**Comment by dhumal436** [comment]
i solved using **redux-persist-filesystem-storage** instead of async storage

**Comment by Aurelienlajoinie** [comment]
Hello, switching to the new recommended library works for  us :)
Cf. Async Storage has moved to new organization: https://github.com/react-native-async-storage/async-storage

**Comment by minsoo-web** [comment]
> i solved using **redux-persist-filesystem-storage** instead of async storage

You saved my life, Thanks @dhumal436 

My version is below
RN: 0.66.3
redux-persist: 6.0.0

my code is below

```ts
const persistConfig = {
  key: 'persist',
  storage: FilesystemStorage, // it was AsyncStorage from '@react-native-async-storage/async-storage'
  timeout: undefined,
  keyPrefix: '',
};
```

When use AsnycStorage,
It was fine all ios version and device,
and Android also

but, some old Android version is not working properly

I changed AsyncStorage to redux-persist-filesystem-storage 
It is all fine 

Thanks
