### ISSUE TITLE
Uncaught TypeError: genericSetImmediate is not a function

### ISSUE THREAD

**Issue by stoplion** [rt2zz/redux-persist#136]
Adding in..
```
import {persistStore, autoRehydrate} from 'redux-persist'
const store = createStore(reducer, undefined, autoRehydrate())
persistStore(store)
```
and getting..
`Uncaught TypeError: genericSetImmediate is not a function`

**Comment by rt2zz** [comment]
did you resolve the issue?

**Comment by xeno** [comment]
I'm getting this same error on a fresh install, using the react-slingshot boilerplate. I'm also using reduxThunk, so I have to pass autoRehydrate into compose() on the third param of createStore, and persistStore(store) is in a separate file.

**Comment by xeno** [comment]
I've tracked it down to line 18 of persistStore.js

I'm using Chrome 52.0.2743.82 m on windows.

**Comment by rt2zz** [comment]
We might consider using setTimeout 0 instead of setImmediate.

**Comment by xeno** [comment]
I ran the code used in the definition at the top of the file, and I'm getting a function returned. Seems like it may be a scope issue.

**Comment by scriperdj** [comment]
same issue..can u pls post the working code

**Comment by murraybauer** [comment]
To get it working I simply changed the two references to the function genericSetImmediate with setTimeout in persistStore.js
