### ISSUE TITLE
Localstorage + safari incognito mode

### ISSUE THREAD

**Issue by azimgd** [rt2zz/redux-persist#142]
![image](https://cloud.githubusercontent.com/assets/4882133/17360733/4641c20c-596d-11e6-8d58-2fc7244b86f4.png)

What would be the best way (or maybe using alternative persistor) to handle this scenario ?

**Comment by rt2zz** [comment]
there is no way to persist data in incognito mode. In this case I think we need to detect this and not log these warnings. PR's greatly appreciated!
