### ISSUE TITLE
Question: Is this module Offline first?

### ISSUE THREAD

**Issue by ichagas** [rt2zz/redux-persist#144]
That is a great module, congratulations! 

I am new in React-Native + Redux scenario and I am curious if this module has similar offline capabilities as [PouchDB](http://pouchdb.com), for instance. In my understanding the `REHYDRATE` process means only downstream (Server -> App), is that right?

Is it capable to handle user inputs during the offline period and them sync later to a Parse Server, for instance? `REHYDRATE` logic can be implemented in both direction?

**Comment by rt2zz** [comment]
redux-persist actually deals entirely with the front-end and has no concept of the network or offline/online.

If you wanted to write a custom storage engine that syncs to your backend when available that would be possible with redux-persist, but is not handled out of the box.

**Comment by jasan-s** [comment]
@ichagas  did you ever find a solution or implement one yourself? I am in the same boat while developing a PWA app

**Comment by ichagas** [comment]
No, I am using PouchDB for offline first but it is too much for my requirements. I don’t need to actually have a DB + Indexes in the client side.

I would prefer a much simpler scenario using Parse Server + react-persist for basic offline sync (ie.: user insert/update/delete during offline). In my project, Server is always right and if device change something during offline I would like to just dispatch the action as soon as it get back online, only that.

Anyway, I’ve never tested the react-redux solution to figure out how “rehydration” concept work if it is only Server to Device direction OR both way.

**Comment by cseelus** [comment]
http://rationalappdev.com/offline-first-apps-with-react-native-and-redux

Based on that article we created an app that fetches some Objects via JSON after login and stores them locally, so the User can create new Objects based on the stored ones and sync them when a network connection is available again.
