### ISSUE TITLE
A non-serializable value was detected in the state 😥

### ISSUE THREAD

**Issue by m3nur** [rt2zz/redux-persist#1445]
![image](https://github.com/rt2zz/redux-persist/assets/45517204/bbd59251-ada5-4f82-862f-554f3c1245b0)

**Comment by joshkel** [comment]
I don't believe these errors have anything to do with redux-persist. `history/fetchHistorySuccess` isn't one of redux-persist's internal actions, and messages about "A non-serializable value was detected in an action" are logged by redux-toolkit (specifically, its serializable check middleware), not by redux-persist. For more information, see the URLs from those messages (e.g., https://redux-toolkit.js.org/usage/usage-guide.html#working-with-non-serializable-data).
