### ISSUE TITLE
`purge` & `purgeAll` should provide a callback

### ISSUE THREAD

**Issue by nevir** [rt2zz/redux-persist#145]
It would be helpful to know when the purge has succeeded.  The case I have in mind is clearing the store when logging a user out; and I want to be sure that it's been completely flushed before moving on

Probably: 

```js
persistor.purge(keys, callback);
persistor.purgeAll(callback);
```

**Comment by rt2zz** [comment]
agreed. Here is a PR towards that affect https://github.com/rt2zz/redux-persist/pull/119 but I believe the purgeAll implementation needs work. If we go this route I would like to support both callback and promises.

If you have a chance to implement this please open a PR (or add to #119) and I will gladly merge!

**Comment by rt2zz** [comment]
This is done on master, will cut a new release in the next week or so
