### ISSUE TITLE
`npm outdated` shows incorrect latest version

### ISSUE THREAD

**Issue by ryanhomer** [rt2zz/redux-persist#147]
`npm outdated` shows me this:

![redux-persist_incorrect_latest](https://cloud.githubusercontent.com/assets/600471/17534897/6d7fbc16-5e40-11e6-8e39-da8f83d72f0e.png)

Note that the latest version displayed is 3.2.2 but I have 3.3.0 installed. Is this a job for `npm dist-tag`?

**Comment by rt2zz** [comment]
ya I had that version hidden behind a tag for testing. just released 3.3.2, should resolve this issue 👍
