### ISSUE TITLE
Node.js support? 

### ISSUE THREAD

**Issue by pellejacobs** [rt2zz/redux-persist#148]
I'm using redux to manage my state in a node app and I was looking into an easy and fast way to persist my state. Unfortunately, it seems like none of the available adaptors actually support node as an environment. What would you recommend to use as an adaptor? 

Currently, I'm using [node-localstorage](https://github.com/lmaccherone/node-localstorage) as a custom adaptor, implementing it the same way as defaults/asyncLocalStorage. However, it might make sense to support this, so you can pass a localStorage object from the node-localstorage library as an adaptor. On the other hand, this might really be a fringe case. 🤔

**Comment by rt2zz** [comment]
I think this is a good idea. I would recommend releasing a new module called `redux-persist-node-storage` which could look roughly like:
```js
var storage = require('node-localstorage')

module.exports = {
    getItem: function (key, cb) {
      try {
        var s = storage.getItem(key)
        nextTick(() => {
          cb(null, s)
        })
      } catch (e) {
        cb(e)
      }
    },
    setItem: function (key, string, cb) {
      try {
        storage.setItem(key, string)
        nextTick(() => {
          cb(null)
        })
      } catch (e) {
        cb(e)
      }
    },
    removeItem: function (key, cb) {
      try {
        storage.removeItem(key)
        nextTick(() => {
          cb(null)
        })
      } catch (e) {
        cb(e)
      }
    },
    getAllKeys: function (cb) {
      try {
        var keys = []
        for (var i = 0; i < storage.length; i++) {
          keys.push(storage.key(i))
        }
        nextTick(() => {
          cb(null, keys)
        })
      } catch (e) {
        cb(e)
      }
    }
  }
```

and could then be plugged directly into redux-persist as a storage backend. `persistStore(store, {storage: reduxPersistNodeStorage})`

**Comment by pellejacobs** [comment]
Not a bad idea. My only conservation is that we are duplicating code: what you just wrote is almost exactly the same as https://github.com/rt2zz/redux-persist/blob/master/src/defaults/asyncLocalStorage.js#L35-L82. What do you think?

**Comment by rt2zz** [comment]
while the code is duplicate it is also trivial and unlikely to change. IMO this is cleaner and easier to reason about from the outside.

If you do publish said module let me know, and I will add a link to the readme to try and get some extra eyes on it :)

**Comment by pellejacobs** [comment]
@rt2zz Here is the repo: https://github.com/pellejacobs/redux-persist-node-storage.

**Comment by rt2zz** [comment]
👍
