### ISSUE TITLE
Reducer changes triggering update of other reducers

### ISSUE THREAD

**Issue by laurmurclar** [rt2zz/redux-persist#151]
In our application, we have a pretty specific case where if one particular whitelisted reducer changes, we want to add another whitelisted reducer to `storesToProcess`. 

For more context, we have two states that look a bit like 

```
A: { id: 123 }
B: { items: {123: {name: 'Lucy', etc... }, 124: { name:.. }}, otherItems: ...}
```

B gets populated before A, but we only want to store the part of B identified by A. We have a custom serialiser that has some code like:

```
...
if ( key === 'B') {
  const object = { items: {} }
  object.items[store.A.id] = store.B.items[store.A.id];
  return JSON.stringify(object);
}
...
```

However, since B updates before A, `store.A.id` is undefined at the point when B updates. When A updates, the state of B has not changed (`lastState[key] === state[key]`) and so B isn't added to `storesToProcess`, ie. the transform isn't called for state B. 

We will be overwriting the `createPersistor` function to make sure the two reducers get updated.  Do you think it would be useful to include this option for everyone? My plan is to pass in a list of linked reducers to `createPersistor` in the config. Then when checking if a key should be added to `storesToProcess`, if the key is in that list also check if any of the states of the other keys in the list have changed. I'd be happy to create a PR for this if other people find it useful.

**Comment by rt2zz** [comment]
@laurmurclar this is a unique case I have not heard of before. I am not super keen on adding complexity to the core lib, but I wonder if there are clever ways we can accomplish this without modification.

e.g.
```js
import { createTransform, persistStore } from 'redux-persist'

let store = createStore(...)

let customTransform= createTransform((subState, key) => {
  // no-op if not reducer B 
  if (key !== 'B') return subState

  // get latest state
  const state = store.getState()

  // build modified state for reducer B
  const newSubState = { items: {} }
  newSubState.items[state.A.id] = state.B.items[state.A.id];
  return newSubState
})

persistStore(store, {transforms: [customTransform]})
```

**Comment by laurmurclar** [comment]
@rt2zz Thanks for getting back to me so quickly. The solution you mentioned above is pretty much the solution I came up with initially. However, we need more than just a custom transform in this case. It doesn't work (with the code above) because the steps are as follows:

Initial state: 
```
A: {}
B: {items: {}}
```

B updates *first* (but since A.id is undefined, our persisted state is still `B: {items: {}}`)
```
Redux state: 
-------------
A: {}
B: {items: { 123: {etc..}, 124: {etc...}}
- - - - - - - - - - - - - - - - - - - -
Persisted:
--------------
A: {}
B: {items: {}}
```

Then A updates (but since the state of B has *not* changed, B is not added to `storesToProcess` and therefore `key !== 'B'`)
```
Redux state: 
-------------
A: {id: 123}
B: {items: { 123: {etc..}, 124: {etc...}}
- - - - - - - - - - - - - - - - - - - -
Persisted:
--------------
A: {id: 123}
B: {items: {}}
```


The desired behaviour is that the update of A will also trigger an update of the persisted state for B, resulting in:

```
Persisted:
--------------
A: {id: 123}
B: {items: { 123: {etc..}}
```

**Comment by laurmurclar** [comment]
I can show you the working solution tomorrow, I just need to tidy it up a little first
