### ISSUE TITLE
How to hydrate redux store for all actions or a given set of actions?

### ISSUE THREAD

**Issue by FarhadG** [rt2zz/redux-persist#154]
I'm working in an app where there are two tabs open looking at different sections of the same app. I'd like for the data to be in sync across these browser tabs and I was curious what you'd recommend for hydrating the redux store every time localStorage has updated (for all or a given set of actions) .

Thank you for your suggestion.

**Comment by rt2zz** [comment]
I think https://github.com/rt2zz/redux-persist-crosstab is what you are looking for. I know a handful of people have used it successfully in the past, but we could definitely use more eyes and feedback. Let me know how that goes.

**Comment by FarhadG** [comment]
Works like a charm! Thank you!
