### ISSUE TITLE
Using lodash-webpack-plugin breaks redux-persist functionality

### ISSUE THREAD

**Issue by creage** [rt2zz/redux-persist#155]
Using lodash-webpack-plugin to minimize build affects react-persist functionality.

Adding
`new LodashModuleReplacementPlugin`
to webpack plugins, causes redux-persist stopping write it's data to localStorage.

**Comment by rt2zz** [comment]
any idea why? we use babel-plugin-lodash during out build step, but I dont think that would be related...

**Comment by creage** [comment]
Please, see comment of John-David Dalton [here](https://github.com/lodash/lodash-webpack-plugin/issues/54#issuecomment-242085558). Could it somehow cause some of lodash modules you use in your plugin, are not properly included?

**Comment by rt2zz** [comment]
his comment is suggesting that the issue is unlikely to be related to LodashModuleReplacementPlugin. 

Are you getting any exceptions thrown?

**Comment by creage** [comment]
No, no errors at all. State is not written to localStorage, otherwise everything is fine.

**Comment by gilbarbara** [comment]
Same problem here.
the `forEach` method in `createPersistor` doesn't iterate at all..

**Comment by rt2zz** [comment]
@gilbarbara I am not sure what is going on here. If you can take some time to dig in and debug that would be greatly appreciated.

FWIW in the next release we will be switching the way we import lodash and removing babel-lodash plugin.

**Comment by rt2zz** [comment]
wow this was a weird bug, the lodash import was being convered to an array iterator and would not work on the collection (read: object) we have for state.

As a work around I converted code from lodash forEach to es6 keys -> foreach, working now in 4.0.0-alpha7

**Comment by marvinhagemeister** [comment]
@rt2zz awesome debugging!

**Comment by rt2zz** [comment]
the lodash author weighed in, and basically are only two options a) do not use lodash functions on collections or b) bundle our code. I am inclined towards **a** for now.

**Comment by marvinhagemeister** [comment]
My vote goes for `a)` too. The more we can use native JavaScript functions, the better.
