### ISSUE TITLE
Keys with array values are transformed to objects

### ISSUE THREAD

**Issue by pianohacker** [rt2zz/redux-persist#16]
Because typeof [] == 'object' in our favorite language, the reducer in autoRehydrate will activate the shallow merge behavior for arrays and turn them into objects. I'm currently working around this with a custom autoRehydrate, but it would be nice if this were handled better.

Open question: should arrays be shallow-merged, or slurped in without modification? I'd say the latter, both because it makes more sense for my application and because I don't think arrays can be sanely merged.

**Comment by rt2zz** [comment]
Good catch. I agree, if the sub state is an array lets just take it as is. 

I think this can be easily done with a bit of conditional Array.isArray around https://github.com/rt2zz/redux-persist/blob/master/src/autoRehydrate.js#L45

Let me know if you get it working. I have been meaning to do a bit of cleanup and code beautification in autoRehydrate anyway..

**Comment by rt2zz** [comment]
I just pushed an update that fixes this issue. Will release a new version soon.

**Comment by rt2zz** [comment]
thanks for pointing this out!

**Comment by pianohacker** [comment]
Wow. Fantastic! I already loved this module except for this niggling edge case (as it exactly matched what I was doing but was much cleaner), and this was a super fast response. Thanks!
