### ISSUE TITLE
persisting firebase database for offline use. (Question) 

### ISSUE THREAD

**Issue by jasan-s** [rt2zz/redux-persist#162]
This may be a naive question, by I'll ask anyways: I'm building a Progressive webapp which is designed to be offline first. I have already used service worker to cache the static app shell but for database data retrieved from firebase database , I can't seem to figure out how to cache it for offline use that persists on hard reset. There is this [polymer element ](https://github.com/PolymerElements/app-storage )that does is but I need a solution that I can use with React. I'm using Redux, so would Redux-persist achieve the same goal?

**Comment by jasan-s** [comment]
I believe this is the lib for me :)

**Comment by rt2zz** [comment]
👍

**Comment by mayankrungta** [comment]
Sorry which is the lib for this? I need to do the same for an Ionic 3 app. The data is not persisting across a hard reset.

**Comment by rt2zz** [comment]
@mayankrungta are you using redux-persist? if its not persisting you might not have autoRehydrate configured correctly. Please post you configureStore code.
