### ISSUE TITLE
using Action Buffer leads to issue when using react router onEnter option

### ISSUE THREAD

**Issue by jasan-s** [rt2zz/redux-persist#164]
so i'm rendering AuthenticateContainer at auth path and with onEnter checking if user is already authed or not using checkAuth function                                                                                                                 `<Route path='auth' component = {AuthenticateContainer} onEnter = {checkAuth}/>`

My checkAuth function: 
```
export function checkAuth (nextState, replace) {
  if (store.getState().users.isFetching === true) {
    return
  }
  const isAuthed = store.getState().users.isAuthed
  const nextPathName = nextState.location.pathname
  if (nextPathName === '/' || nextPathName === '/auth') {
    if (isAuthed === true) {
      replace('/feed')
    }
  } else {
    if (isAuthed !== true) {
      replace('/auth')
    }
  }
}

```

The problem is that with Action buffer the checkAuth function fires before the rehydration completes. Thus the isAuthed value is the initial value of false.   If I remove the actionbuffer the isauthed is set to true before the checkAuth is called but of course with that the rehydration writes over actions.

**Comment by rt2zz** [comment]
In most cases I recommend delaying rendering your entire app until state is rehydrated. This can be done a few different ways, the easiest of which is described [here](https://github.com/rt2zz/redux-persist/blob/master/docs/recipes.md#delay-render-until-rehydration-complete).

Rehydration only takes a few ms (depending of course on some details like how large your state is), so usually this will cause an imperceptible change to app start time, but buys you a lot of certainty around how state is loaded and prevents accidental tricky race conditions.

**Comment by jasan-s** [comment]
@rt2zz  that was definitely helpful . I got it fully functional. One last thing i want to integrate is the Redux persist migrate. I looked at its Readme and still unclear how to implement it.  I'm using webpack to generate an app.[chunkhash].js & vendor.[chunkhash]. How would i detect this change in chunkhash and rebuild the local indexeddb database?

**Comment by rt2zz** [comment]
@jasan-s we need help figuring out how best to use redux-persist in conjunction with code splitting. When a new chunk is resolved should we rehydrate any newly added reducers? 

The safest default implementation is to blacklist any reducers that are view / chunk specific, and simply persist your core reducers (e.g. auth, dictionaries, etc.). Going to close this out, but if you want to chat more about integrating redux-persist-migrate and also code splitting I am happy to continue in a new issue.
