### ISSUE TITLE
[3.6.0-alpha1] autoRehydrate not working with immutable

### ISSUE THREAD

**Issue by ntucker** [rt2zz/redux-persist#165]
The problem is the reducer from createRehydrationReducer is only run once from the @@INIT action.

stateReconciler only matters INSIDE that reducer, but it doesn't even get the chance to run.

Maybe this is because I'm not using Action Buffers?

```javascript
import { persistStore, autoRehydrate } from 'redux-persist'
import immutableTransform from 'redux-persist-transform-immutable'
import { stateIterator, stateGetter, stateSetter,
         stateReconciler, lastStateInit } from 'redux-persist-immutable-state'

  let enhancer = compose(
    autoRehydrate({ stateReconciler }),
    applyMiddleware(
      ...middleware,
    ),
  )

  const store = createStore(rootReducer, Map(), enhancer)
  persistStore(store, {
    whitelist: ['counter'],
    debounce: 500,
    storage: localforage,
    transforms: [immutableTransform({})],
    stateIterator,
    stateGetter, stateSetter,
    lastStateInit,
  })
```

As mentioned: https://github.com/rt2zz/redux-persist/pull/113#issuecomment-243931005

**Comment by rt2zz** [comment]
Afaik redux-persist-immutable-state is not yet compatible with redux-persist. You can use redux-persist2 in the meantime or wait until we launch support, hopefully next week

**Comment by ntucker** [comment]
But it was merged.... https://github.com/rt2zz/redux-persist/pull/158

https://github.com/rt2zz/redux-persist/pull/113#issuecomment-243931005

With that merged, what is the diff from redux-persist-2?

**Comment by rt2zz** [comment]
Ok tentative immutable support now available at https://github.com/rt2zz/redux-persist-immutable

**note** I have not actually run this in an app, but the tests pass ;)

**Comment by rt2zz** [comment]
to answer your question, it was merged with amendments. The main difference is that redux-persist-immutable wraps redux-persist rather than requiring you set the config options explicitly.

**Comment by rt2zz** [comment]
closing as alpha version of redux-persist-immutable is now released 🎉

**Comment by ntucker** [comment]
Still not working for me...
