### ISSUE TITLE
autoRehydrate no longer working after upgrading 0.30 to 0.31

### ISSUE THREAD

**Issue by tijs** [rt2zz/redux-persist#166]
I just upgraded my app from 0.30 to 0.31 and noticed the autoRehydrate feature is no longer working. I have set up my store like so:

    const store = createStore(rootReducer, middleware, autoRehydrate());

And i was 'logging' the REHYDRATE action like so:

```
export default function persist(state = initialState, action) {
  switch (action.type) {
    case REHYDRATE:
      return {
        ...state,
        storageLoaded: true,
      };
    default:
      return state;
  }
}
```

But since upgrading the REHYDRATE action stopped 'firing' and no data is persisted between reloads of the app. I'm using the asyncStorage storage engine.

Is this a known issue? Should i reconfigure anything after upgrading?

**Comment by rt2zz** [comment]
The second arg to createStore should be initialState not middleware. 

As far as run 0.31, this lib was working for me and others. Might be something specific to your implementation. What version of redux-persist are you using?

**Comment by tijs** [comment]
redux-persist@3.5.0

Good catch on the middleware argument btw. i have no idea how that has been working correctly but it was. Just changed it to the correct setup, which also works fine on 0.30. 

```
const middleware = applyMiddleware(generatorMiddleware, thunk, promiseMiddleware, logger);
const store = createStore(
  rootReducer,
  {},
  compose(autoRehydrate(), middleware)
);
persistStore(store, { storage: AsyncStorage });
```
I'll also check if that by any chance fixes the issue in 0.31

**Comment by tijs** [comment]
@rt2zz awesome that was also causing my issue in 0.31. no idea why 0.30 and lower even worked but thanks for spotting it!

**Comment by tijs** [comment]
@rt2zz strangely enough i still see the issue on android but only with remote debugging turned on; when i turn remote debugging off REHYDRATE works fine and the app loads. When i have remote debugging on REHYDRATE never fires. I assume this is also something in my configuration then since you said people are running 0.31 without issues but i just wanted to double check if that rings any bells for you..

**Comment by rt2zz** [comment]
Haha ya 31 has a bug where android promises do not resolve when debugger is on. Might be worth upgrading to run 32 if you can

**Comment by tijs** [comment]
ha! ok thats very helpful. thanks for saving me some hours this weekend most likely 💯

**Comment by pablopi** [comment]
Did this update work?
