### ISSUE TITLE
How to disable keyPrefix?

### ISSUE THREAD

**Issue by ivadenis** [rt2zz/redux-persist#168]
Hi, I'm working with legacy architecture and I need to integrate with a particular key in a local storage. Can you suggest a workaround?

**Comment by rt2zz** [comment]
You can set keyPrefix in configure object. Eg {keyPrefix: ''}

**Comment by ivadenis** [comment]
@rt2zz if keyPrefix is falsey, then it defaults to ```'reduxPersist:'```, and ```!'' === true```. So, this won't work unfortunately.

**Comment by rt2zz** [comment]
Ah sounds like bad programming ;)

Mind submitting a PR to specifically check if keyPrefix is undefined?

**Comment by rt2zz** [comment]
fix in 4.0.0-alpha4
