### ISSUE TITLE
Not working with Hot reloading in Development Env

### ISSUE THREAD

**Issue by jasan-s** [rt2zz/redux-persist#169]
something to do with the use stateful component assume. 
```
const App = () => (
    <MuiThemeProvider>
      <Provider store = {store}>
        {getRoutes(checkAuth)}
      </Provider>
    </MuiThemeProvider>
    )
injectTapEventPlugin()

**// class AppProvider extends Component {

//   constructor () {
//     super()
//     this.state = { rehydrated: false }
//   }

//   // componentWillMount () {
//   //   persistStore(store, {}, () => {
//   //     this.setState({ rehydrated: true })
//   //   })
//   // }

//   render () {
//     // if (!this.state.rehydrated) {
//     //   return <div>Loading...</div>
//     // }
//     return (
//       <Provider store={store}>
//       <App />
//       </Provider>
//     )
//   }
// }**

ReactDOM.render(
    <App/>,
  document.getElementById('app')
)
```
  
Problem was the code in bold. But without this I can't delay the render. What to do?

**Comment by jasan-s** [comment]
I'm wondering if i can use process.env.NODE_ENV in my main index.js file to detect build environment and do a conditional If based on that?

**Comment by rt2zz** [comment]
I think this may be due to us not "lifting" the replaceReducer method in autoRehydrate.  I believe the solution is to re-apply autoRehydrate inside of replaceReducer.

**Comment by jasan-s** [comment]
can you eloborate how to do that?

**Comment by rt2zz** [comment]
@jasan-s more details here: https://github.com/rt2zz/redux-persist/issues/130

I am not using this in a hot reloading env and had not had time to implement it yet. But I think the fix would need to change the way we enhance the store here: https://github.com/rt2zz/redux-persist/blob/master/src/autoRehydrate.js#L8

Something like:
```js
let store =  next(createRehydrationReducer(reducer), initialState, enhancer)
return {
  ...store
  replaceReducer: (reducer) => {
    return store.replaceReducer(createRehydrationReducer(reducer))
  }
}
```

If you can give that a try and make it work please let me know! I know many in the community would be greatly benefitted.

**Comment by rt2zz** [comment]
@jasan-s I released a tentative version of this in 4.0.0-alpha3, if you have a chance please give it a try and let me know how that goes.

**Comment by jasan-s** [comment]
I will give it a shot :) and let you know. what changes did you make?

**Comment by rt2zz** [comment]
https://github.com/rt2zz/redux-persist/blob/master/src/autoRehydrate.js#L11-L13

**Comment by jasan-s** [comment]
Yes Sir, that fixed the issue :+1:
