### ISSUE TITLE
API Enhancement: rehydrateReducers

### ISSUE THREAD

**Issue by jsdevel** [rt2zz/redux-persist#176]
I found myself writing a lot of boilerplate.  It's possible there's an existing solution for this, in which case I'll use it.  If not, I've created the following function that may be of use to others:

``` js
import { REHYDRATE } from 'redux-persist/constants';

function createRehydrateReducer(reducer, name) {
  return function(state = {}, action) {
    switch (action.type) {
      case REHYDRATE:
        return { ...state, ...action.payload[name] };
      default:
        return reducer(state, action);
    }
  };
};

export default function(reducers = {}) {
  Object.keys(reducers).forEach((key) => {
    reducers[key] = createRehydrateReducer(reducers[key], key);
  });
  return reducers;
}
```

It assumes you want to blindly use what was in storage.  The main use case is restoring app state from localStorage or AsyncStorage when the app first loads.

Here's how I use it:

``` js
const rootReducer = combineReducers(rehydrateReducers({
  todos,
  profile,
  tokens,
  user,
}));
```

**Comment by rt2zz** [comment]
Did you try `autoRehydrate`? Did it not suit your use case for some reason? It does something very similar except in the form of a store enhancer instead of reducer enhancers.
