### ISSUE TITLE
Persist, not rehydrate

### ISSUE THREAD

**Issue by NeXTs** [rt2zz/redux-persist#181]
Hey

Is it possible to configure it to persist state and NOT rehydrate?

I need to keep state in localstorage. So that page builds instantly on next visits.

Also I need to sync localstorage state between tabs to avoid issues with authentication.

redux-persist-crosstab did its part great, state actually syncs between tabs.
But redux-persist does rehydration on page load and everything on the page flashes. I don't need this feature.
And I didn't find the way to disable this rehydration in docs.

How to make state persistant and not rehydrate?

**Comment by rt2zz** [comment]
@NeXTs I am not with good internet at the moment, but I can hopefully point you in the right direction:

[createPersistor](https://github.com/rt2zz/redux-persist/blob/master/docs/api.md#createpersistorstore-config) will create a persistor, but not fire off any rehydrate action. You can then pass this persistor into redux-persist-crosstab to start receiving crosstab rehydration, without ever receiving the initial rehydration action.

I have never used this flow before, so there may be some nuances that need exploring, but I suspect this general approach could work for you. Let me know.

**Comment by NeXTs** [comment]
Hi,

just tried `createPersistor` instead of `persistStore` but it doesn't work for me
It doesn't restore state from localstorage
Moreover it broke syncing across tabs :(

I am suprised that I am only one who needs such behaviour.
Probably I am creating issue in project which in idea isn't fully related to my needs, but it's closer to it than any other module on the market
