### ISSUE TITLE
redux-persist:cannot process cyclical state

### ISSUE THREAD

**Issue by vickysongang** [rt2zz/redux-persist#182]
Hey,I encounter a problem like this:

```
      redux-persist:cannot process cyclical state.
      Consider changing your state structure to have no cycles.
      Alternatively blacklist the corresponding reducer key.
      Cycle encounted at key "context" with value "[object Object]"
```

And my state structure is:

``` js
    {
          "activeConversation": "223sssse234234",
          "client": IMClient, // object
          "convById": Map()   // Map, store the conversation object
          "msgById": Map()    // Map, store the message object
          convListSortedByUpdatedTimeList(), // store the message ids
    }
```

so how can I resolve the problem? I need your help,thank you!

**Comment by marvinhagemeister** [comment]
Your state tree needs to be serializeable. That's basically the whole idea behind redux, that you can easily swap out the state tree because it is serializable. In your case it seems like you have a function inside your store.

**Comment by rt2zz** [comment]
Agree with @marvinhagemeister 

Also to elaborate on the error, it means [json-stringify-safe](https://github.com/isaacs/json-stringify-safe) failed to serialize the state. I would check out convListSortedByUpdatedTimeList() and IMClient to make sure these do not have any circuclar data.

**Comment by rt2zz** [comment]
if you want to serialize cyclic state (and somehow have a parser that know how to do that) you can implement it via a custom transform (`createTransform`)

**Comment by raphaelrk** [comment]
I was storing my react-navigation current navigation state in the redux store and that was somehow causing a cycle. Changed it to only store the current route name

**Comment by leticiacostadias** [comment]
I've been having basically the same issue, I'm having the log that follows:

```
redux-persist: cannot process cyclical state.
      Consider changing your state structure to have no cycles.
      Alternatively blacklist the corresponding reducer key.
      Cycle encounted at key "0" with value "5978ab989c24c60015f1a81c".
```

Where `0` is the first position of an array and `5978ab989c24c60015f1a81c` is a id from my mongodb. This is being stored like this:

```
"data": {
     ...,
      "wallets": [
        {
          "label": String,
          "operational_settings": {
            "automatic_balance": Boolean
          },
          "user_id": userId,
          "accounts": [
            "5978ab989c24c60015f1a81c"
          ],
          "created_at": ISODate
        }
      ]
}
```

Any of what I may be doing wrong?

**Comment by atyenoria** [comment]
@leticiacostadias 

In my case,  using blacklist solved this problem.
The possible cyclic redux variable shouldn't be stored in redux-persist

https://github.com/rt2zz/redux-persist#blacklist--whitelist

**Comment by OsamaOso2026** [comment]
any thing new with this issue @leticiacostadias
