### ISSUE TITLE
'webkitStorageInfo' & 'webkitIndexedDB' are deprecated in Safari

### ISSUE THREAD

**Issue by zerostyle** [rt2zz/redux-persist#191]
Getting a couple errors in the latest Safari on Mac:

`'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.`

`'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.`

**Comment by marvinhagemeister** [comment]
That is curious. Are you sure that the problem is caused by `redux-persist`? We only use either `localStorage` or `SessionStorage` with the default persistor that's shipped with redux-persist. Do you use a custom persistor? At work I noticed similar errors and they were caused by tracking scripts.

**Comment by zerostyle** [comment]
I'm using SessionStorage, but the issue has gone away. I'm going to close for now and keep an eye on it.

**Comment by marvinhagemeister** [comment]
Right, feel free to reopen it once the issue comes up again.
