### ISSUE TITLE
Using store in react routers onEnter 

### ISSUE THREAD

**Issue by Knaackee** [rt2zz/redux-persist#193]
I try to implement routes that require authentication. 

My problem is that the store is not rehydrated in my router onEnter function.
How to rehydrate before this onEnter gets called or what are my alternatives.
How to retrieve the state from redux-persist manually?

Great work and thanks in advance!

**Comment by rt2zz** [comment]
generally the simplest/best solution to this problem is to delay rendering your App until rehydrate completes. Typically this is only a few ms.
