### ISSUE TITLE
Unhandled promise rejection TypeError: action is undefined 

### ISSUE THREAD

**Issue by jasan-s** [rt2zz/redux-persist#194]
Oddly, I 'm only receiving this error on Desktop Firefox Browser, mobile firefox works fine. and every other browser chrome, safari on mobile and desktop work fine. 
error:
![typeerror](https://cloud.githubusercontent.com/assets/13863953/19409276/718e15a4-9285-11e6-8504-7daf009ab1f8.png)
The error seems to be because  of Line 71209(marked):
```

	  var versionKeys = Object.keys(manifest).map(processKey).sort();
	  var currentVersion = versionKeys[versionKeys.length - 1];

	  var migrationDispatch = function migrationDispatch(next) {
	    return function (action) {
	      

if (action.type === _constants.REHYDRATE) { // THIS IS LINE 71209

	        var incomingState = action.payload;
	        var incomingVersion = versionSelector(incomingState);
	        if (incomingVersion !== currentVersion) {
	          var migratedState = migrate(incomingState, incomingVersion);
	          action.payload = migratedState;
	        }
	      }
	      return next(action);
	    };
	  };
```

**Comment by marvinhagemeister** [comment]
It's hard to tell what is wrong because the error happens somewhere higher on the stack tree. The marked comparison fails because `action` is undefined. Could it be that somewhere in your code your dispatching `undefined` inserted of an action object?

**Comment by jasan-s** [comment]
**Update:**    I think it was an error because my redux store change(maybe). the indexDb in firefox was showing a store 10+ version old.  I mainly use chrome for development.  I coudn't find a a way to delete the indexdb in firefox. thus i reinstalled firefox and everything works.

**Comment by marvinhagemeister** [comment]
@jasan-s I'm happy to hear that you found a solution. 👍 

For reference: You can delete the contents of `IndexedDB` right from the firefox devtools: https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector
