### ISSUE TITLE
Default filenames include %3A

### ISSUE THREAD

**Issue by CharlieHess** [rt2zz/redux-persist#201]
Looks a bit silly; macOS doesn't like `reduxPersist:reducer`.

![](https://d3vv6lp55qjaqc.cloudfront.net/items/3x220n2i1I2x2t2G0W2S/Image%202016-10-26%20at%2012.31.16%20PM.png?X-CloudApp-Visitor-Id=1741631&v=5866834d)

**Comment by rt2zz** [comment]
how do you get this view? are you using localStorage or a custom storage?

Open to suggestions. we could switch to `-` but that would be a breaking change.

**Comment by CharlieHess** [comment]
@rt2zz I'm using `AsyncNodeStorage`.

**Comment by CharlieHess** [comment]
@rt2zz one easy workaround would be a config option so we can override the format.

**Comment by rt2zz** [comment]
`persistStore(store, { keyPrefix: 'anyString' })`

defaults to `redux-persist:` 👍

**Comment by CharlieHess** [comment]
Aha--didn't even see that one. Thanks!
