### ISSUE TITLE
Request to join cdnjs

### ISSUE THREAD

**Issue by ian4hu** [rt2zz/redux-persist#202]
this is a great lib for redux, and I'm using it with public cdn service, and I can not found it in the cdnjs, would you mind to send redux-persist to cdnjs?

here is the [cdnjs/cdnjs](https://github.com/cdnjs/cdnjs)

**Comment by rt2zz** [comment]
not sure what it takes to be a part of cdnjs, fwiw we already support unpkg (https://unpkg.com/redux-persist@4.0.0-alpha7/dist/redux-persist.js).

**Comment by ian4hu** [comment]
I'll try to import it to the cdnjs, and sometimes I prefer use a prebuilt version from cdn in my app.
