### ISSUE TITLE
Question: How to avoid JSON serialization?

### ISSUE THREAD

**Issue by njlg** [rt2zz/redux-persist#206]
I'm using `redux-persist` with `localforage` and just want `localforage` to handle serialization of the data if required. It seems like `redux-persist` is forcing the data to a JSON stringifier.

**Comment by rt2zz** [comment]
I would like to support this case better, but for now there is an escape hatch by passing `{ serialize: (data) => data, deserialize: (data) => data }` as config.

**Comment by njlg** [comment]
Awesome! Thanks for the tidbit.
