### ISSUE TITLE
Webkit warnings

### ISSUE THREAD

**Issue by Darkbladecr** [rt2zz/redux-persist#208]
When using redux-persist with localForage I receive several warnings in the console log:

> 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
> 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

![screen shot 2016-11-12 at 12 52 03](https://cloud.githubusercontent.com/assets/4283896/20237905/f135c01a-a8d6-11e6-841a-f6208205f0e8.png)

**Comment by marvinhagemeister** [comment]
I can't thing of any place where we use `indexedDB` in redux-persist. This is very likely an issue with localForage.

**Comment by rt2zz** [comment]
Agreed, we do nothing with the storage other than call the provided methods.
