### ISSUE TITLE
Missing session storage engine

### ISSUE THREAD

**Issue by jonathanfoster** [rt2zz/redux-persist#209]
I was trying to use session storage and I noticed the import of `redux-persist/storages` can't resolve the file. I'm following the instructions on how to configure the storage engine in the [README](https://github.com/rt2zz/redux-persist#storage-engines)

I can import `redux-persist/constants` with no issue. It looks like [storages.js](https://github.com/rt2zz/redux-persist/blob/master/storages.js) is in master, but I can't find that file after npm installing. I have v3.5.0 installed.

How can I import `asyncSessionStorage`?

**Comment by jonathanfoster** [comment]
I found the solution in a closed issue https://github.com/rt2zz/redux-persist/issues/92. The closed issue has a PR https://github.com/rt2zz/redux-persist/pull/138 that updated the README, but it looks like it may have been overwritten at some point.

**Comment by jonathanfoster** [comment]
Submitted PR https://github.com/rt2zz/redux-persist/pull/210 to update README.

**Comment by rt2zz** [comment]
ah sorry, the readme is for v4, changing the import is one of the breaking changes we made to help with dead code elimination. 

Your syntax is correct for v3 👍
