### ISSUE TITLE
npm install tries to download inexistent beta version

### ISSUE THREAD

**Issue by ales004** [rt2zz/redux-persist#213]
If you write:
npm install --save redux-persist

npm tries to download the version: 
https://registry.npmjs.org/redux-persist/-/redux-persist-4.0.0-beta1.tgz

that does not exist.

We had to set the version to 4.0.0-alpha7 for it to run.

**Comment by hugohow** [comment]
+1

**Comment by po-jo** [comment]
This is a duplicate of : https://github.com/rt2zz/redux-persist/issues/212, isn't it ?

**Comment by marvinhagemeister** [comment]
Agreed, I'm closing this in favor of #212
