### ISSUE TITLE
support persisting to pouchdb?

### ISSUE THREAD

**Issue by simpzan** [rt2zz/redux-persist#222]
Hi there, would you consider to support persisting to pouchdb. 
pouchdb supports sync wonderfully.  
It will be great to combine pouchdb's sync and redux-persist's local persist.

**Comment by rt2zz** [comment]
This is be a great storage engine. A cursory look at the docs https://pouchdb.com/api.html#fetch_document makes me think this will not be hard to implement, just need to conform to the expected storage api a la https://github.com/pellejacobs/redux-persist-node-storage/blob/master/src/index.ts

**Comment by rt2zz** [comment]
This could make for some really awesome features with syncing user session to a remote db or coordinating session across two remote peers 👍

**Comment by alburdette619** [comment]
Has any work been done on this?  There is a library called redux-pouchdb but it seems to be unmaintained and not currently even working.

**Comment by brandonmp** [comment]
Just looking into this myself & figured I'd share this relatively new project: https://github.com/medihack/redux-pouchdb-plus

Haven't used it but seems to take advantage of some of the synergies b/t pouch and redux

**Comment by selipso** [comment]
The most developed PouchDB library for RN seems to be https://github.com/stockulus/pouchdb-react-native but it doesn't use redux. It already handles syncing, though, with work being done on enabling attachments. Could be a good package to collaborate as it seems to have an easier API to work with.

**Comment by rt2zz** [comment]
redux-persist@5 no longer relies on `getAllKeys` which leads me to believe writing an adapter for pouchdb would be trivial, just need `getItem, setItem, and removeItem`.

**Comment by yanick** [comment]
There might be only hard thing involved in a pouchdb adapter. When a document is saved, pouchDb returns back a new copy of the doc with a new `_rev` (so that it'll detect if one tries to update the docs from an outdated version). But `setItem` has no direct way to add something to the main state...

**Comment by MuraraAllan** [comment]
Any upgrade on that? I'm starting a project that involves pouchDB + Redux and I'm highly interested in contribute with this awesome library! 
The scope is to deploy a custom module to deal with Network Quality, Type of Sync|Replication With CouchDB and propagation to redux.
That can definitely be implemented with some work. Also would be great to get in touch with a bit of flux. 
That being said, If you guys are interested in move this forward, you can count on me.

**Comment by MuraraAllan** [comment]
@rt2zz up to some help here? :) 

Rehydrate -
whenever a state is being rehydrated, a set item in Storage is being dispatched, it leads to a revision bug on PouchDB, as in : 

![screenshot from 2019-01-01 22-32-59](https://user-images.githubusercontent.com/8569238/50577712-41a5d580-0e15-11e9-92dd-45091e85c1df.png)


Toughts?


delete localValue._persist;
._persist is invalid for PouchDB i got to delete it each time. That is a neast workaround but not trustable right? 

Taking that pouchDB is intended to store documents classified by indexes , there is an abstraction decision to be taken related to Key and PrefixKey;


What is the expected Storage Behaviour?

--------------------------------------------------------------------------------------
1 - Abstracting PouchDB and putting it as a dependency for redux-persist-pouchdb;
const persistCompanyConfig = {
  key: 'usersSession',
  storage: pouchDbPlugin,
  debug : true,
  prefixKey : 'https://couchDBserver.com.br',
  stateReconciler : autoMergeLevel2,
  sync : () => {
    pouchDbSyncFunctionNormallyDeclared()
  }
};

constructor() {
  storage.dbs[key] = new PouchDB(`${keyPrefix}${key}`);
  storage.dbs[key].sync(config.sync); 
}
--------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------
2 - Not abstracting PouchDB, actually receiving a generated PouchDB from config;
const db = new pouchDB('anyNameUserDefined');
db.sync(() => {});
const persistAppStateConfig = {
  key: 'appState',
  storage: storageConstructor(db),
  debug : true,
};
storage.db = parm;
--------------------------------------------------------------------------------------

**Comment by MuraraAllan** [comment]
I need some help.

Rehydrate -
whenever a state is being rehydrated, a set item in Storage is being dispatched, it leads to a revision bug on PouchDB, as in : 

![screenshot from 2019-01-01 22-32-59](https://user-images.githubusercontent.com/8569238/50577712-41a5d580-0e15-11e9-92dd-45091e85c1df.png)


Toughts?


delete localValue._persist;
._persist is invalid for PouchDB i got to delete it each time. That is a neast workaround but not trustable right? 

Taking that pouchDB is intended to store documents classified by indexes , there is an abstraction decision to be taken related to Key and PrefixKey;


What is the expected Storage Behaviour?


```
1 - Abstracting PouchDB and putting it as a dependency for redux-persist-pouchdb;
const persistCompanyConfig = {
  key: 'usersSession',
  storage: pouchDbPlugin,
  debug : true,
  prefixKey : 'https://couchDBserver.com.br',
  stateReconciler : autoMergeLevel2,
  sync : () => {
    pouchDbSyncFunctionNormallyDeclared()
  }
};
constructor() {
  storage.dbs[key] = new PouchDB(`${keyPrefix}${key}`);
  storage.dbs[key].sync(config.sync); 
}
 ```

```
2 - Not abstracting PouchDB, actually receiving a generated PouchDB from config;
const db = new pouchDB('anyNameUserDefined');
db.sync(() => {});
const persistAppStateConfig = {
  key: 'appState',
  storage: storageConstructor(db),
  debug : true,
};
storage.db = parm;
```

**Comment by yanick** [comment]
AH! I think I got it:

https://github.com/yanick/redux-persist-pouchdb
