### ISSUE TITLE
ES6 Set and Map

### ISSUE THREAD

**Issue by adrienjt** [rt2zz/redux-persist#223]
Hi, I use ES6 Sets and Maps in nested reducers of my app's state. Persistence doesn't work for them. They are persisted as {}. I'm thinking I might need a transform such as [redux-persist-transform-immutable](https://github.com/rt2zz/redux-persist-transform-immutable). Am I on the right track?

If at all important, I use React Native's AsyncStorage.

**Comment by rt2zz** [comment]
yes redux-persist-transform-immutable uses transitjs under the hood. You will have to double check that transit supports Map and Set. If it does, I would recommend making a new module `redux-persist-transform-transit` which skips the immutable part and simply applies transit.

**Comment by rt2zz** [comment]
closing, if you decide to make sure a module let me know! otherwise redux-persist-transform-immutable should work just as well.

**Comment by chrise86** [comment]
@adrienjt did you come up with a solution? I'm facing the same issue; I need to transform some `Map` objects within various reducers, but it seems to be trying to transform everything, which is causing issues.

I'm using `redux-offline`, and this is the transform that is passed to the persist options:

```
import transit from 'transit-js'
import { createTransform } from 'redux-persist'

createTransform((state, key) => {
      const writer = transit.writer('json')
      return writer.write(state)
    }, (raw, key) => {
      const reader = transit.reader('json')
      return reader.read(raw)
    })
```

**Comment by adrienjt** [comment]
No, but I didn't try hard. Instead I switched to plain JavaScript objects, which are more idiomatic in Redux. But because I still like to think in terms of sets and maps, I wrote [redux-data-structures](https://redux-data-structures.js.org), a library of reducer factory functions for common data structures like sets and maps, among others.
