### ISSUE TITLE
Customising the behaviour when there has been a persist error

### ISSUE THREAD

**Issue by martinfilliau** [rt2zz/redux-persist#225]
The current behaviour is to do a `console.warn` (if not running in "production") : https://github.com/rt2zz/redux-persist/blob/master/src/createPersistor.js#L58

I'd like to prepare a pull request to be able to personalise this behaviour by being able to pass a function to `persistStore` and then `createPersistor` to override the default behaviour. (In our case, we need to be able to friendly warn the user there is a risk its data might be lost.)

Have I missed an existing option? Does it seem reasonable?

**Comment by rt2zz** [comment]
@martinfilliau the REHYDRATE action fires with an error property. Could you consider implementing the error handling in either a middleware or reducer?

Actually thinking about it a bit, I suspect we might want to add an explicit error handler to autoRehydrate which already handles the rehydrate action, and seems like an intuitive place to handler custom fallback functionality.

**Comment by rt2zz** [comment]
If this is not sufficient I am certainly open to ideas for better error handling.

**Comment by martinfilliau** [comment]
@rt2zz `REHYDRATE` is an intesting option however we would need to catch errors earlier, as soon as it happens ideally. In our use case, we'd like to be able to warn users of a potential loss of data as soon as possible. Gonna propose a PR.

**Comment by TanninOne** [comment]
getStoredState will also silently fail if data can't be deserialized.
Suppressing such a fundamental error is pretty horrible to be honest.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.

@TanninOne @martinfilliau I'd really appreciate if you could submit a PR to help the project out. A similar error handling PR was recently submitted and merged: https://github.com/rt2zz/redux-persist/pull/949
