### ISSUE TITLE
Changelogs and NPM Beta version

### ISSUE THREAD

**Issue by dijonkitchen** [rt2zz/redux-persist#228]
It looks like 3.0.0 is the latest stable version in the releases: https://github.com/rt2zz/redux-persist/releases

The latest version on releases is 3.5.0, but on NPM, when you install it, it automatically pulls 4.0.0-beta1: https://www.npmjs.com/package/redux-persist

What are the differences between these major versions; I assume some are breaking changes? Is there a changelog for them? Additionally, what versions are the docs good for?

**Comment by rt2zz** [comment]
docs are for v4. v4 beta was published as it is the only "supported" version, and had no breaking changes to *documented* features.

I plan to release v4 this week along with a change log for said undocumented features.

**Comment by dijonkitchen** [comment]
#237

**Comment by dijonkitchen** [comment]
It's downloading stable now! I'm looking forward to the doc updates!

**Comment by IanVS** [comment]
It seems that https://github.com/rt2zz/redux-persist/releases is still pointing to `3.0.0` as the latest release, and I cannot find any changelog for `4.0.0`, although the npm badge indicates that latest is `4.0.1`. 

#237 is helpful, but is there a formal changelog anywhere as well?

**Comment by rt2zz** [comment]
There are actually 7 newer tags, they are just collapsed by default. Nevertheless, I just added release notes. Thanks!
