### ISSUE TITLE
Going Back to Previous Route State when opens in new tab or page reloads

### ISSUE THREAD

**Issue by fullyfaltu** [rt2zz/redux-persist#232]
I'm trying to `redux-persist` to persist my data on client side. But problem is when I try to refresh/reload page, it goes back to previous page (last route state). Here is how I'm trying to persist data:

_Before using redux-persist:_
```
const reducer = require('./modules/reducer');
const store = finalCreateStore(reducer, data);
```

It works smoothly. But when I used redux-persist, react router behaviour differs.

_Using redux-persist:_

```
const store = finalCreateStore(reducer, data, autoRehydrate());
  if (typeof window !== 'undefined') {
    persistStore(store);
  }

```

I tried to use blacklist `routing` from persistance but it also didn't work. 

P.s. I'm using [react-redux-universal-hot-example](https://github.com/erikras/react-redux-universal-hot-example) boilerplate.

**Comment by rt2zz** [comment]
are you using react-redux-router? blacklisting routing should work, is it possible you have the wrong key?

One way you can check is see if the REHYDRATE payload has routing data in it, and also verify the the transition happens after rehydration or not.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
