### ISSUE TITLE
[QUESTION] Initializing Redux state with AsyncStorage

### ISSUE THREAD

**Issue by StephenMayeux** [rt2zz/redux-persist#233]
I am building a React Native app, and I want to initialize my redux state so that my login/register component only renders if a user's device does not have a token stored in AsyncStorage.

I have several reducers and have combined them in a file called `/reducers/index.js` with the redux method `combineReducers`. My `auth` reducer has a key called **loggedIn** which is either true or false. I am using this particular key from my auth reducer to display my login/registration component.

I have read the examples, but I am having a hard time getting this to work. This is what I have so far in my top level component.

```javascript
import React, { Component } from 'react';
import { Provider } from 'react-redux';
import { createStore, applyMiddleware } from 'redux';
import ReduxThunk from 'redux-thunk';
import Logger from 'redux-logger';
import { AsyncStorage } from 'react-native';
import reducers from './reducers';
import Router from './Router';

const store = createStore(reducers, {}, applyMiddleware(ReduxThunk, Logger()));

class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <Router />
      </Provider>
    );
  }
}

export default App;
```

Essentially what I would like to do is call `AsyncStorage.getItem('uniqueUserToken')` and if it returns a string, then initialize `auth.loggedIn` to true. But if it returns `null` then initialize loggedIn to false, or even just an empty object. 

I have found it quite easy to do on the web with localStorage, which is synchronous, but I cannot wrap my head around this particular challenge. How could I achieve this using redux-persist? Thank you for creating a great package, and I look forward to getting it to work in my project.

**Comment by rt2zz** [comment]
as you have observed the async nature of AsyncStorage (and localForage on web) make this something of a challenge, however I think this is a good thing, as async access is the only sane way to read from disk for large quantities of data.

In this case you are going to want to defer loading Router until after state has persisted. The simplest way to do this is as follows:
```js
class App extends Component {
  componentWillMount(){
    persistStore(store, config, () => {
      this.setState({ rehydrated: true })
    })
  }
  render() {
    if (!this.state.rehydrate) return <Text>Loading...</Text>
    return (
      <Provider store={store}>
        <Router />
      </Provider>
    );
  }
}

export default App;

**Comment by StephenMayeux** [comment]
thanks @rt2zz for the suggestion. I understand your example at a high level, but I am unsure how I should construct my config object. I suppose I should whitelist my `auth` reducer and set storage to AsyncStorage, but where do I actually use `AsyncStorage.getItem('getUserProfile')` so that I can initialize the state?

**Comment by rt2zz** [comment]
persistStore + autoRehydrate will handle all of that for you. In your case config should probably be `{ storage: AsyncStorage }`
```js
// @NOTE make sure autoRehydrate needs to be set up in configureStore

class App extends Component {
  componentWillMount(){
    persistStore(store, { storage: AsyncStorage }, () => {
      this.setState({ rehydrated: true })
    })
  }
  render() {
    if (!this.state.rehydrate) return <Text>Loading...</Text>
    return (
      <Provider store={store}>
        <Router />
      </Provider>
    );
  }
}

export default App;
```

**Comment by StephenMayeux** [comment]
Thanks for the follow up @rt2zz. I worked it through with a friend, and we discovered that we had to also call in the `REHYDRATE` action.type constant in our auth reducer, and then return a new state with its payload. Works like a charm now, and I am really happy that this straightforward package solved my particular issue!

**Comment by rt2zz** [comment]
@StephenMayeux great! fwiw I think your approach works great, but you can also use autoRehydrate to automatically achieve the same thing for all reducers 👍

**Comment by nativedone** [comment]
@rt2zz Works perfectly with autoRehydrate() option.

Thanks for addressing that key point :1st_place_medal:

**Comment by oskaryil** [comment]
@nativedone Where are you placing the autoRehydrate()?

**Comment by zainozzaini** [comment]
Thanks for the issue.. Before,I only get this reference -  https://medium.com/@sumitkushwaha/syncing-redux-store-with-asyncstorage-in-react-native-2b8b890b9ca1 to get an idea how to get initialize value from redux store (AsyncStorage) but this thread is exactly clear up me everything.
