### ISSUE TITLE
lodash adds too much weight to your library

### ISSUE THREAD

**Issue by unindented** [rt2zz/redux-persist#235]
Couldn't you do without it? Would you accept a PR?

**Comment by rt2zz** [comment]
we follow the redux pattern, with the assumption the end user will implement `https://www.npmjs.com/package/babel-plugin-lodash` or es6 tree shaking.

If you think there is a better way I am all ears.

**Comment by unindented** [comment]
Yeah, the pattern somehow works well for `redux` but not well for `redux-persist`. If I look at `source-map-explorer`, `redux-persist` is adding ~130KB to my build.

Before:

<img width="1119" alt="screen shot 2016-12-15 at 08 32 59" src="https://cloud.githubusercontent.com/assets/69485/21216893/35623898-c2a1-11e6-9f03-8a6d176489c3.png">

After:

<img width="1119" alt="screen shot 2016-12-15 at 08 30 10" src="https://cloud.githubusercontent.com/assets/69485/21216896/3a410858-c2a1-11e6-9a8d-92c419d90f26.png">

I'm guessing we're bringing in `clone` or something that depends on it, and those are huge functions. If I had to bet, I'd put my money on `omit`: https://github.com/rt2zz/redux-persist/blob/4849ea2cba554203658fba2eb855e0bdd07492f7/src/persistStore.js#L4

If I write a PR with a lighter-weight alternative, would you be open to reviewing and accepting it? People are getting super aggressive about library sizes, and I love this library, so I want to be able to use it.

**Comment by unindented** [comment]
I am not running tree-shaking on my side though (I use TypeScript instead of Babel, and I'm still waiting for webpack 2 stable), so I should look into that before doing anything else.

**Comment by unindented** [comment]
Weird, using webpack 2.2.0-rc.0 didn't shake out any lodash bits:

![screen shot 2016-12-15 at 12 45 04](https://cloud.githubusercontent.com/assets/69485/21224537/8ce14bf4-c2c4-11e6-8243-2eae34e0361f.png)

**Comment by rt2zz** [comment]
@unindented wow thanks for digging in. Yes as a starting point I agree omit can be removed, in this particular case we are reassigning the output to the original variable, so I think it is safe to do this mutatively and save some perf from not having to object copy.

**Comment by rt2zz** [comment]
while suprising, you may be correct about omit causing havoc. I see the compiled source does include directly out of lodash modules `lodash/forEach` etc.

@unindented what tool are you using to create those visualizations?

**Comment by rt2zz** [comment]
I have not run analysis yet, but I removed two lodash methods omit and forEach: https://github.com/rt2zz/redux-persist/pull/236

**Comment by unindented** [comment]
Awesome, thanks @rt2zz! The tool I'm using is [`source-map-explorer`](https://www.npmjs.com/package/source-map-explorer):

```
$ source-map-explorer dist/index.js dist/index.js.map
```

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
