### ISSUE TITLE
v4: release

### ISSUE THREAD

**Issue by rt2zz** [rt2zz/redux-persist#237]
Hi All, as we are preparing to release v4, I wanted discuss the breaking changes and new features.

Fortunately we have made no breaking changes to documented api's, and all v3 -> v4 breaking changes for undocumented features are listed below. Most users are already on v4 beta1 so this should be pretty painless.

Known breaking changes since v3
- https://github.com/rt2zz/redux-persist/commit/25f2f0648ba34c85283d2e5051232c83f996d056]liftReducer with autorehydrate (fix bug with hmr, non-hmr users should be unaffected)
- https://github.com/rt2zz/redux-persist/commit/5aef897bcb11cb8cfef7b2178bc8678aad1f4105 remove `purgeAll()`, purge all now default behavior of `purge()`
- https://github.com/rt2zz/redux-persist/commit/178689972f432c225329bbc180be44b52fa86292 config.serialize is now a boolean option instead of a function. custom serialize function can still be achieved via transform.

New features since v3
- https://github.com/rt2zz/redux-persist/commit/8a65894ad9c18c290e073e67d7c5f3c6bd170f97 umd & es builds! @marvinhagemeister 
- https://github.com/rt2zz/redux-persist/commit/3e1b0d4f91832af3abcdcc09fa2b0f22600640aa better localForage support! @willmcclellan 
- https://github.com/rt2zz/redux-persist/commit/89ee3291717140858c4fdde70a248c27ce0bca95 more comprehensive localStorage checks! @IanVS 
- https://github.com/rt2zz/redux-persist/commit/349a0b08cf7e4a235b17cd50cf3ffd62ed3fb7dc typescript defs! @morlay 
- https://github.com/rt2zz/redux-persist/commit/e9503e39315118587268589f62a4d979ba9c81fe flowtype defs! @gnoff 

Huge thanks to everyone who has put effort into this project, and @marvinhagemeister for being the chillest co-maintainer!

The effort is paying off with 268,000 lifetime downloads, 1400+ stars, and [quickly growing adoption numbers](https://npm-stat.com/charts.html?package=redux-persist)

⚔ 🛡 🔥 
 -- Zack

<img width="930" alt="screen shot 2016-12-15 at 10 31 21 pm" src="https://cloud.githubusercontent.com/assets/2302315/21253860/7ea35184-c316-11e6-89ef-b116a48ff3c5.png">

**Comment by dijonkitchen** [comment]
Think this can be closed with the updates to the releases? https://github.com/rt2zz/redux-persist/releases

**Comment by rt2zz** [comment]
👍
