### ISSUE TITLE
Typings to typescript are incomplete

### ISSUE THREAD

**Issue by LKay** [rt2zz/redux-persist#240]
Typings are missing `keyPrefix` property in config. Also some types in case of transform are not really necessary. There is no `interfaces` module in original library so this shouldn't appear only in typings. 

@morlay You created typings in "old" style. Without knowing you were working on these I also created typing for this library and it has been already merged into `@types` in npm. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13389
Maybe we should merge yours with mine for better support? Who should take care of this?

**Comment by morlay** [comment]
Thanks, we could added the `keyPrefix`. sorry for my mistake.

And the types of transform, may not really necessary, but want to keep it same as flow types.

the `interfaces` will be useful to create plugin, it will not be transformed to Javascript.
and multiple files use same interfaces, so i put them in an interface file.

The "old" style just want to keep all definitions in one file, and make it could be partial imported.

BTW, I don't like publishing to `@types`,  which will make maintain hard. when some changes, it will take too much time to upgrade the definitions. 
Could we merge yours back to this repo?

**Comment by LKay** [comment]
I'm not really big fan of `@types` either but since the definitions are already in the project's repo I'll make some changes and raise a PR soon. Then I'll also remove typings form DefinitelyTyped.

**Comment by morlay** [comment]
Cool. we may wait a minute.
the `keyPrefix` is missing in type version.
https://github.com/rt2zz/redux-persist/blob/master/type-definitions/index.js.flow#L18
Should we need to added it both? @rt2zz

**Comment by LKay** [comment]
@morlay The PR is up.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.

Also, the PR was closed by the author.
