### ISSUE TITLE
Do I have to write transform every time I add a field in my whitelisted reducers?

### ISSUE THREAD

**Issue by jonwu** [rt2zz/redux-persist#243]
Example: 

1. I start with a simple reducer: `user: { name: Jonathan }`
2. Then I whitelist this reducer: `{ whitelist: ['user'] }`
3. Later, I refactored my reducer to `user: { name: Jonathan, age: 21 }` and refresh app.
4. Unfortunately, my initial state returns `user: { name: Jonathan }` without `age`.

This seems to be the normal use case, but I was wondering what is the **best way** to refactor my whitelisted reducers? Currently, I'm transforming every new field I add and purging the ones I remove: 

```
let counterTransform = createTransform(
    (state) => (Object.assign({}, state, { age: state.age ? stage.age : 21 })),
    (state) => (state),
    { whitelist: 'user'}
)
```

This seems like a lot of code to write, especially when refactoring nested objects in my reducer. Thus, I feel like i'm doing something wrong. Is this the correct way to update my reducers?

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
