### ISSUE TITLE
Store with AsyncStorage storage not rehydrating

### ISSUE THREAD

**Issue by JulianKingman** [rt2zz/redux-persist#244]
I have a store that I'm persisting with AsyncStorage, but it doesn't seem to be rehydrating. The callback fires, but getState comes up empty. If I get the values of AsyncStorage, however, I can see that it is being persisted, just not rehydrated. Thoughts?

````javascript
Store = createStore(reducers, undefined, autoRehydrate());
persistStore(Store, {storage: AsyncStorage}, () => {
  // rehydrated
  console.log(Store.getState());
});
````

**Comment by rt2zz** [comment]
can you add log: true to autoRehydrate:
`Store = createStore(reducers, undefined, autoRehydrate({ log: true }));`

autoRehydrate will skip rehydration if you handle the action in your reducer. Double check that you are not modifying state in your default action handler in your reducers. The log on autoRehydrate may give us some hints here.

**Comment by JulianKingman** [comment]
Good call, here's what I get from the log, what should I be looking for?
````bash

      redux-persist/autoRehydrate: 1 actions were fired before rehydration completed. This can be a symptom of a race
      condition where the rehydrate action may overwrite the previously affected state. Consider running these actions
      after rehydration:
````

**Comment by JulianKingman** [comment]
Re: modifying state, does something like a lodash `_.update` function qualify?

**Comment by JulianKingman** [comment]
BTW, no actions are listed after the above message from redux-persist.

**Comment by JulianKingman** [comment]
I 'fixed' this by adding my own reducer. Still unsure why it didn't work. Should I close this? The issue still exists...
````javascript
  case 'persist/REHYDRATE':
      // only do this if offline
      if(typeof Meteor.ddp === undefined || Meteor.ddp.status === "disconnected"){
        return action.payload;
      }
````

**Comment by rt2zz** [comment]
@JulianKingman sorry for the delay in getting back to you. The log warning you mentioned here: https://github.com/rt2zz/redux-persist/issues/244#issuecomment-270191582 was actually a false alarm in the debug logic, that has now been fixed.

Yes _.update would result in state being modified and hence autoRehydrate skipping. In this case I think your solution is reasonable.

I am working on a way to make this immutability implementation detail more apparent to consumers, but for now I think things have to be dealt with on a case by case basis.
