### ISSUE TITLE
README should show usage with `compose` and `applyMiddleware`

### ISSUE THREAD

**Issue by ucarion** [rt2zz/redux-persist#246]
For many people, redux-persist is the first library they use which exposes an enhancer, rather than a middleware. This seems to cause a lot of confusion for people who don't read much past the README. Currently the opening example is:

```js
import {persistStore, autoRehydrate} from 'redux-persist'
const store = createStore(reducer, undefined, autoRehydrate())
persistStore(store)
```

Maybe it'd be friendlier to show a more realistic example, since everyone uses `applyMiddleware` in real life:

```js
import {compose} from 'redux'
import {persistStore, autoRehydrate} from 'redux-persist'
const store = createStore(reducer, undefined, compose(applyMiddleware({}), autoRehydrate())
persistStore(store)
```

I'd happily open a PR to do so, but I thought I should ask first.

**Comment by tiemevanveen** [comment]
Thanks for the example 😁. Would indeed be a nice addition to the readme!

**Comment by ypyang237** [comment]
In case anybody was wondering, I got my isomorphic react app working with an enhancer this way ` `import { createStore, applyMiddleware, compose } from 'redux'
import thunkMiddleware from 'redux-thunk'
import reducers from './reducers'

import {persistStore, autoRehydrate} from 'redux-persist'

const enhancer = compose(
  autoRehydrate(),
  applyMiddleware(thunkMiddleware)
)

// initStore
export default (reducers, initialState, isServer) => {
  if (isServer && typeof window === 'undefined') {
    return createStore(reducers, initialState || {}, applyMiddleware(thunkMiddleware));
  } else {
    if (!window.store) {
      window.store = createStore(reducers, initialState || {}, enhancer)
    }
    persistStore(store)
    return window.store
  }
}
`

Hope this helps someone!

**Comment by purnawirman** [comment]
@ypyang237 you helped me, i love you!

**Comment by ddaaggeett** [comment]
@ypyang237 - awesome putting `autoRehydrate()` inside `compose()`!
@ucarion - nice issue - and should this be closed now?
