### ISSUE TITLE
getStoredState relies on deprecated deserialize config option

### ISSUE THREAD

**Issue by jesenko** [rt2zz/redux-persist#247]
I encountered issue when migrating from v3 to v4, changing persistor option `serialize: (..) => ...` to,`serialize: false`.

I guess that in https://github.com/rt2zz/redux-persist/blob/master/src/getStoredState.js#L6 deprecated `deserialize` option is still used? It should probably rely on `serialize: bool` option instead?

**Comment by rt2zz** [comment]
wow good catch, sorry I did not see this sooner. Just released v4.2.0 with fix https://github.com/rt2zz/redux-persist/commit/5c20ec5f17e006d4a2e21af8144ff96811b22013
