### ISSUE TITLE
Persist and rehydrate from multiple storages

### ISSUE THREAD

**Issue by actra-gschuster** [rt2zz/redux-persist#248]
Hey there.

Situation is that I need to store and load portions of my app state to localStorage (e.g. theme, locale settings) and others to sessionStorage (backend session id, form data etc.).
For rehydration I'd need 2 persistStore() calls which causes problem with redux-action-buffer as it listens on REHYDRATE action, which is fired after the first rehydration.

I'm currently handling it by buffering further REHYDRATE actions and unshift()ing them to the action chain so they are handled after the first REHYDRATE but before the first "real" action.
The solution doesn't seem to be the best, thus I'd like to ask if there's any advice on how to implement my scenario best.

TIA!

**Comment by rt2zz** [comment]
I dont think there is consensus yet on how best to handle this. If you use something like redux-saga or redux-observable it is easy to wait for 2 REHYDRATE actions and then fire a BOOTSTRAP_COMPLETE action which starts everything else.

If you are using plain thunks you might consider keeping the logic close to configureStore, and implement BOOTSTRAP_COMPLETE after both persistStore callbacks are completed.

I am actually not sure what yo mean by `buffering further REHYDRATE actions and unshift()ing`, how does that work?
