### ISSUE TITLE
Why isn't Promise interface used with storage?

### ISSUE THREAD

**Issue by benmvp** [rt2zz/redux-persist#261]
Hi there!

Thanks so much for this library! It's proven to be insanely useful!

I'm building a combo React AND React Native app that's sharing both the Redux code as well as components (via [`react-native-web`](https://github.com/necolas/react-native-web)).

I noticed when I used `react-native-web`'s web implementation of [`AsyncStorage`](https://github.com/necolas/react-native-web/blob/master/docs/apis/AsyncStorage.md), nothing was persisting. Turns out that it's [strictly Promised-based](https://github.com/necolas/react-native-web/blob/master/src/apis/AsyncStorage/index.js) whereas `redux-persist` expects the callback style. This basically makes the two libraries incompatible w/ each other.

On the one hand, `react-native-web` _could_ implement the callbacks to be 100% compatible with React Native's [`AsyncStorage`](https://github.com/facebook/react-native/blob/master/Libraries/Storage/AsyncStorage.js), but then I looked at even the [`asyncLocalStroage`](https://github.com/rt2zz/redux-persist/blob/master/src/defaults/asyncLocalStorage.js) here and it also is Promised-based (while also supporting callbacks).

So with all that said, I was curious why the code uses the callback style instead of handling Promises?

I have a [workaround](https://github.com/benmvp/bart-salmon/blob/5bb1448bafbbd46e78f519b884cfeb0acf296099/app/store/configureStore.prod.js#L23-L25) to only use the "real" `AsyncStorage` from React Native and when I'm rendering for the web just let `redux-persist` default to `asyncLocalStorage`, but it would be awesome to not have to do that.

**Comment by marvinhagemeister** [comment]
At the time the main bulk of code for redux-persist was written `Promises` weren't that widely used in client-side code. A promise-based API is a great idea! Would you love to make a first draft?

**Comment by rt2zz** [comment]
personally I think callbacks are the core async primitive of js, and react-native-web should definitely support it. I would be open to switching to promise based consumption in redux-persist, but only if it coincided with PR's to get the ecosystem switched over as well (e.g. https://github.com/abersager/redux-persist-cookie-storage/blob/master/src/redux-persist-cookie-storage.js).

Let me know what you think, or if perhaps there is a clever way we can support both without any performance overhead.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
