### ISSUE TITLE
Cant find variable: Reflect, appears after upgrading RN 0.40

### ISSUE THREAD

**Issue by wachunei** [rt2zz/redux-persist#263]
After upgrading to RN 0.40 I keep getting this error when purging some keys at rehydration.
It happens only on device and not in simulator, which is strange.

redux-persist@4.1.0
react-native@0.40.0

Any ideas?

**Comment by rt2zz** [comment]
I have not seen this, and have been running redux-persist 4.x against rn 0.40 for some time now.

If this continues to be an issue I am open to removing the use of reflect here: https://github.com/rt2zz/redux-persist/blob/1cd5d29ab49b96be1026e8bab67aaeae1699e9d9/src/persistStore.js#L27

**Comment by wachunei** [comment]
@rt2zz It has still been happening. I'm guessing that API may be not available in every production environment and we can't rely on expecting that to be true, maybe can we use a polyfill as a dependency?

**Comment by rt2zz** [comment]
@wachunei perhaps, but I doubt the benefits of Reflect.delete are worth the costs of polyfilling. `delete` should work just as well in this case.

**Comment by marcinkornek** [comment]
The same happen for me with `react-native 0.42.0`. When I tried to remove all keys with `purge()` it did nothing (it didn't delete items) but when I tried to purge array of keys it showed me `Cant find variable: Reflect` error.

**Comment by wachunei** [comment]
closed by #291
