### ISSUE TITLE
Typescript type definition error with localForage

### ISSUE THREAD

**Issue by Dante-101** [rt2zz/redux-persist#273]
I am unable to use localForage with redux-persist in a typescript project

My import statements:
```
import { persistStore, autoRehydrate } from 'redux-persist'
import * as localForage from 'localforage'
```

Calling persistStore as:
`persistStore(store, { storage: localForage })`

Results in the following compilation error:
> Argument of type '{ storage: LocalForage; }' is not assignable to parameter of type 'PersistorConfig | undefined'.
>   Type '{ storage: LocalForage; }' is not assignable to type 'PersistorConfig'.
>     Types of property 'storage' are incompatible.
>       Type 'LocalForage' is not assignable to type 'Storage | undefined'.
>         Type 'LocalForage' is not assignable to type 'Storage'.
>           Property 'getAllKeys' is missing in type 'LocalForage'.

**Comment by rt2zz** [comment]
@Dante-101 I do not use typescript, but my guess is this should be solved by making sure localForage is typed correctly. Open to suggestions

**Comment by Dante-101** [comment]
Do you know the person who is responsible for typescript definitions of redux-persist? 

To explain the error, the typescript definition of PersistorConfig requires that any storage that is used by redux-persist implement getAllKeys() function. LocalForage's definition doesn't have getAllKeys() which causes this error. I believe it should not be a necessity because even localStorage doesn't have getAllKeys().

**Comment by rt2zz** [comment]
ah ok so the actual type for Storage should be has *either* `getAllKeys` or `keys`. If it possible to model that in typescript?

**Comment by marvinhagemeister** [comment]
Sorry for taking so long! Our code checks for both `getAllKeys` and `keys`, with the latter being `localforage`. The `Storage` interface needs to treat both as optional parameters to support both use cases:

```ts
interface Storage {
    setItem: Function;
    getItem: Function;
    removeItem: Function;
    getAllKeys?: Function;
    keys?: Function;
  }
```

@Dante-101 This PR should fix this https://github.com/rt2zz/redux-persist/pull/276 Could you give it a quick look if it works for you? If it does I'll hit the green merge button 💯

**Comment by Dante-101** [comment]
Good to go. Thank you!

**Comment by marvinhagemeister** [comment]
Awesome, thanks for having a quick look at it! I just merged the PR and the next release will contain the updated typings 👍

**Comment by rt2zz** [comment]
Just released v4.3.1 (this appears to be a backwards compatible bugfix to typings, correct me if I am wrong)

**Comment by marvinhagemeister** [comment]
yep, completely backwards compatible :)

**Comment by marklawlor** [comment]
This bug was reintroduced again in v4.4.0

https://github.com/rt2zz/redux-persist/commit/dbbb132d0dfca96d3a114b7bae05bf4bc0be7da2#diff-c627ce0fe5832d82e77118c76c47f8f2R8

Also I don't think `Noop` is the correct type definition for `keys`. But I'm very new to redux-persist and unsure what it should be.

**Comment by rt2zz** [comment]
@marklawlor indeed, will resolve asap

**Comment by rt2zz** [comment]
@marklawlor can you confirm this is the correct fix: https://github.com/rt2zz/redux-persist/pull/285/files

I am not a TS user

**Comment by rt2zz** [comment]
@marklawlor v4.4.1 out now with fix for Noop and getAllKeys optional. Let me know if that works 👍

**Comment by rt2zz** [comment]
@marklawlor I believe this has now been resolved: https://github.com/rt2zz/redux-persist/blob/master/type-definitions/index.d.ts#L8

v4.4.2 is out, as before let me know if any issues
