### ISSUE TITLE
New keys in reducers are skipped

### ISSUE THREAD

**Issue by bulby97** [rt2zz/redux-persist#280]
Anytime I create a new key in a reducer, I need to purge the store, otherwise the key is ignored during the rehydratation.  Is there any solution ?

FYI here is my code :
```
componentWillMount() {
    persistedStore = persistStore(store, {
      storage: AsyncStorage,
      transforms: [immutableTransform()],
    }, () => {
      this.setState({ rehydrated: true })
    })
  }
```

This is a problem because I'm using codepush to update my code OTF. 
Because the new key doesn't exists, the app crash

To resume, here are the steps: 
 - Use app, persist store
 - Create new functionality,  new key and new actions in reducer
 - Codepush the code
 - Open App, persisted store gets loaded  => App crash

**Comment by rt2zz** [comment]
@bulby97 is your top level reducer immutable? autoRehydrate does a shallow merge specifically to avoid this issue. That said it is still possible to have a situation where shallow merge is not sufficient and you will receive a crash (e.g. value was previously null, now expected to be object).

You probably have two decent options to fix this:
- write a custom REHYDRATE action handler in your reducer. In this you can ensure whatever keys need to exist do exists, and do any other data manipulation required
- use https://github.com/rt2zz/redux-persist-state-manager which supports migrations. then write a migration to default values appropriately for whatever keys are added.

**Comment by bulby97** [comment]
@rt2zz Awesome ! 

My top level reducer was not immutable at all. I did it and now everything works, thank you !

**Comment by MaxiSantos** [comment]
@bulby97 how did you fix the issue? I didn't understand.
