### ISSUE TITLE
function autoRehydrate do not execute before any actions

### ISSUE THREAD

**Issue by zuzuviewer** [rt2zz/redux-persist#287]
my English is not very well ,so show codes to guys:
`export const store = createStore(
    reducer,undefined,compose(
        applyMiddleware(thunk,logger),autoRehydrate()
    )
);`;
but my custom action execute before REHYDRATE

**Comment by pjb3** [comment]
I'm running into the same problem that I believe @zuzuviewer is trying to describe, which is that I'd like to find a way make sure authRehydrate complete before my app is first rendered. Is that possible?

**Comment by zuzuviewer** [comment]
yeah,it's what I want to say.Thank you very much.And I found a way to solve it,[https://github.com/rt2zz/redux-action-buffer/blob/master/README.md#redux-persist-example].But I don't use it .Import a start page without any custom action which is my way

**Comment by wZi** [comment]
Thank you, friend. This solve my problem.

**Comment by rt2zz** [comment]
👍 

there are two solutions 
1) is action buffer as mentioned above.
2) is to delay your app from rendering until rehydration is complete: https://github.com/rt2zz/redux-persist/blob/master/docs/recipes.md#delay-render-until-rehydration-complete
