### ISSUE TITLE
Excluding some part of the store from Rehydration

### ISSUE THREAD

**Issue by nicolabortignon** [rt2zz/redux-persist#288]
I just started digging into this repo, it's a stellar work! well done.

There are few details that I'm still struggling with.
Specifically:

1- It seems that the Store is always completely Rehydrated.
Why do we need to include in the reducer something like: 
```
case REHYDRATE:
      console.log('RECEIVED REHYDRATE FROM user')
      var incoming = action.payload.myReducer
       console.log(incoming)
      if (incoming) return {...state, ...incoming, specialKey: processSpecial(incoming.specialKey)}

      return state


```
2- let's assume there is a subpart of a store that I don't want to persist.
let's say, state.user.isAuthenticated.   The idea is that this is a boolean that tells me if the user is authenticated or not. I want the user to go through authentication every time it opens the app (i'm on react native). the rest of the store should be normally rehydrated and persisted.
How can I achieve this?

**Comment by nicolabortignon** [comment]
Ok, let me see if I got this, 
with **autoRehydrate()** the store is always rehydrated,
to handle exclusion you can intercept the action 'REHYDRATE' on the reducer.

**if my reducer is called authentication, and the field i want to exclude is isAuthed, I should do something like**
```
    case REHYDRATE:
      var incoming = action.payload.authentication
      if (incoming) return {
        ...state, 
        ...incoming, 
        isAuthed : state.isAuthed  // this is the important line.
      }
      return state

```

nothing that I do 

` isAuthed : state.isAuthed`

instead of 

` isAuthed : false`

because I have no control on the sequence of other actions (and an authentication may have started before the rehydration is finished)

**Comment by rmevans9** [comment]
I think you could achieve this with this library: https://github.com/edy/redux-persist-transform-filter

**Comment by rt2zz** [comment]
@nicolabortignon yes that is one strategy, redux-persist-transform-filter would help you do something similar also.

Separately though, I generally recommend waiting for rehydrate to complete before starting any side effects, otherwise you run the risk of race conditions and hard to debug scenarios.

**Comment by raarts** [comment]
The reducer should actually wait for 'persist/REHYDRATE'.

**Comment by aguynamedben** [comment]
Related issues:
* https://github.com/rt2zz/redux-persist/issues/330
* https://github.com/rt2zz/redux-persist/issues/318, specifically note this comment: https://github.com/rt2zz/redux-persist/issues/318#issuecomment-291008227

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
