### ISSUE TITLE
Persists `Infinity` as `null`

### ISSUE THREAD

**Issue by hyperh** [rt2zz/redux-persist#290]
I have a value in my redux store that is set to `Infinity`, however, when I rehydrate the store, the value has become `null`. I'm guessing it's due to this? http://stackoverflow.com/questions/16644597/json-stringify-converting-infinity-to-null

**Comment by marvinhagemeister** [comment]
Yep, that's exactly the case. `Infinity` is unfortunately not part of the `JSON` spec.

**Comment by rt2zz** [comment]
fwiw transitjs might have infinity support and would be trivial to implement as a custom transform a la https://github.com/rt2zz/redux-persist-transform-immutable/blob/master/index.js
