### ISSUE TITLE
Constant imports don't work in Jest

### ISSUE THREAD

**Issue by designbyadrian** [rt2zz/redux-persist#292]
I'm using the bespoke rehydrate action in my reducer, so in the begining of my reducer I import the contant like so:

```javascript
import { REHYDRATE } from 'redux-persist/constants';
```

When I run my tests (jest) `npm test`, the program stops as soon as it tries to run the reducer, with no errors.

I wonder if it's related to Jest itself not supporting Node require functions properly, as mention in https://github.com/facebook/jest/issues/2017.

**Comment by designbyadrian** [comment]
What the heck, it seems I needed to troubleshoot for more than 30 minutes. This might be an invalid ticket. I'll get back to you when I'm sure. Sorry.

**Comment by designbyadrian** [comment]
Stupid dev is stupid. Entirely my fault creating an infinite loop. It's very difficult detecting in tests, let alone output console logs from Jest's web workers!

**Comment by rt2zz** [comment]
👍 glad it worked out

**Comment by Jose24San** [comment]
I ran into a similar issue by using webstorms auto import feature when I imported REHYDRATE constant, turns out I was importing it from redux-persist/es/constants and jest did not like that. However when I imported it from 'redux-persist/constants' the jest error went away.
