### ISSUE TITLE
Possible bug: Obscure logic

### ISSUE THREAD

**Issue by vjancik** [rt2zz/redux-persist#293]
https://github.com/rt2zz/redux-persist/blob/master/src/autoRehydrate.js#L49

On this line you assign the `reducedState` to `newState`.

Which however, makes the line 64 (https://github.com/rt2zz/redux-persist/blob/master/src/autoRehydrate.js#L64) obsolete, wouldn't you say?

**Comment by rt2zz** [comment]
good catch, that is definitely a redundant line. PR welcome!

**Comment by vjancik** [comment]
That (https://github.com/rt2zz/redux-persist/pull/300) makes it correct I believe.

The difference in behavior now is, that if there isn't a `key` in the *inbound state* for which the corresponding reducer mutated the state, that mutation will be discarded and instead the *initial state* will be used.

Which could happen e.g. if you added a new reducer to your store, along with a `REHYDRATE` action handler, but that reducer hasn't been persisted before.

**Comment by rt2zz** [comment]
for your example, I would still expect the return value of the reducer REHYDRATE handler to be valid. I think the more conservative approach is to always accept the reducedState and then simply remove line 64: https://github.com/rt2zz/redux-persist/blob/master/src/autoRehydrate.js#L64

**Comment by vjancik** [comment]
The `REHYDRATE` reducer is supposed to implement a custom transform for the incoming serialized data.
However, the way this reconciler is written, first come the conditions which "skip" rehydration for some reducers.
The first `if`, if true, skips rehydration.
If the `REHYDRATE` reducer took the incoming serialized state, and modified it, and inserted into the state, and we'd merge that into the new state by default, there would be no way to "skip" rehydration, and the first `if` would be rendered useless.
