### ISSUE TITLE
Store not persisted after removing the data manually from local storage

### ISSUE THREAD

**Issue by Suresh-R-S** [rt2zz/redux-persist#296]
My store.js is as follows : 

```
import { applyMiddleware , createStore } from 'redux';
import rootReducer from './reducers/rootReducer';
import thunk from 'redux-thunk';
import logger from 'redux-logger';
import {persistStore} from 'redux-persist';

const middleware = applyMiddleware(thunk,logger());
const store = createStore(rootReducer,middleware);

persistStore(store);

export default store;
```
When the app is loaded and when I check the logs,an action persist/REHYDRATE is dispatched successfully and the store is persisted.

But after I remove the data from localStorage manually from the chrome inspect and refresh the app, the store is no longer persisted. i.e. the action is dispatched but the payload is null.

![screen shot 2017-03-14 at 12 27 48 pm](https://cloud.githubusercontent.com/assets/13781322/23889186/be1998e2-08b1-11e7-93bd-c07b1bc856b3.png)

I understand the data in my store is immutable data, but as a 1st step I'am trying to persist the data, but currently I'am not being able to do it.

**Comment by rt2zz** [comment]
the rehydrate payload is null probably because after you deleted localStorage, it was never re-persisted. if you reload the app again do you see the payload?

**Comment by Suresh-R-S** [comment]
@rt2zz  No even after reloading the app the status is same :(

**Comment by rt2zz** [comment]
ah, it looks like you are missing autoRehydrate, see the example usage here: https://github.com/rt2zz/redux-persist#basic-usage

**Comment by Suresh-R-S** [comment]
@rt2zz I have tried with autoRehydrate too..
autoRehydrate is to rehydrate the persisted store back right??
When I include autoRehydrate the store seems to be persisted. But again, when I delete the localStorage values manually & the app reloads, the store seems to be not persisted. Not sure what is going wrong.

**Comment by rt2zz** [comment]
If you delete localstorage, then the store will not persist on the next load because localstorage is where redux-persist keeps state between reloads. If you need better sandboxing of the storage values you can use localForage instead of localStorage.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
