### ISSUE TITLE
process is not defined in asyncLocalStorage using AoT (Angular)

### ISSUE THREAD

**Issue by zerefel** [rt2zz/redux-persist#297]
Hey there, I have just started using redux-persist. So far everything is awesome, thanks for the cool project!

The project I'm working on is currently using Angular v4.0.0-rc.3.

My configuration is the following:
```
const persistConfig = {storage: localForage, whitelist: ['user']};

getStoredState(persistConfig, (err, state) => {
    const store = createStore(
        rootReducer,
        state,
        compose(
            applyMiddleware(...middlewares),
            autoRehydrate()
        )
    );

    persistStore(store, persistConfig);
    this.redux.provideStore(store);
});
```

This compiles and works perfectly in dev mode, which is using JIT compilation. However, when I compile the project using AoT compilation and afterward try loading the app in the browser, I get the following error:

`Uncaught ReferenceError: process is not defined
    at Object.<anonymous> (asyncLocalStorage.js:6)
    at Object.<anonymous> (main.136593f….bundle.js:49989)
    at n (bootstrap de3c07e…:52)
    at Object.<anonymous> (main.136593f….bundle.js:49704)
    at n (bootstrap de3c07e…:52)
    at Object.<anonymous> (main.136593f….bundle.js:77532)
    at n (bootstrap de3c07e…:52)
    at Object.<anonymous> (main.136593f….bundle.js:48073)
    at n (bootstrap de3c07e…:52)
    at Object.<anonymous> (main.136593f….bundle.js:59429)
    at n (bootstrap de3c07e…:52)
    at Object.<anonymous> (main.136593f….bundle.js:54560)
    at n (bootstrap de3c07e…:52)
    at Object.<anonymous> (main.136593f….bundle.js:90915)
    at n (bootstrap de3c07e…:52)`

I tried looking up the issue, but no one else seems to have it. Let me know if you need me to provide any additional code.

Cheers.

**Comment by rt2zz** [comment]
Interesting, I have not heard of others having this issue. We do access process.nextTick, but only conditional on process existing https://github.com/rt2zz/redux-persist/blob/master/src/defaults/asyncLocalStorage.js#L4

I could entertain an argument that we should simply use setImmediate, and skip the whole process.nextTick business which is mainly a node.js construct.

**Comment by scic** [comment]
I have the same error on a webpack production build. Minifying will rewrite that code as follows

`c=process`

which leads to a reference error (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined).

This access needs to be rewritten as:

`typeof process !== 'undefined'`

**Comment by rt2zz** [comment]
@scic @zerefel we made a few changes to simply the process usage, now the only reference to process is for `process.env.NODE_ENV`, which with a typical envify solution will compile down to a string literal.

Please let me know if the changes cause any issues for your builds.
