### ISSUE TITLE
prevent action trigger if redux persisted state exists

### ISSUE THREAD

**Issue by simran-k** [rt2zz/redux-persist#298]
1. Where am I really supposed to put this line of code to rehydrate my state from persisted state?

```
case 'persist/REHYDRATE':
      console.log("getting persisted state for you may like items")
       let persistedState = action.payload['youMayLikeItems']
       return {...state, ...persistedState};


```
I have some reducer files and an index.js which imports state from all those reducers and creates the final application state, it looks somewhat like this:
Am I supposed to use persisted state here?If yes, how?

```
const rootReducer = combineReducers({
  reduxAsyncConnect,
  categories,   //add comma seprated list of reducers
  cookies : sessionId,
  quoteIdAndCustomerId,
  wishListItems,
  cartData,
  loadingBar: loadingBarReducer,
  addToCartItems
});
```

3. Do I create a separate reducer that listens to persist/REHYDRATE ? 

4. How do I prevent trigger of actions in case the persisted state in redux exists i.e If I have value in persisted state, do not call the api on page reload. I believe this is the most imp. piece of info I need to optimize my redux app. I see my actions are getting triggered even though the state persists

5. How to use it properly with server side rendering?

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
