### ISSUE TITLE
sorry!Has a problem

### ISSUE THREAD

**Issue by phpsmarter** [rt2zz/redux-persist#299]
when I add redux-persist to one of  redux-doc's examples: todos-with-undo with below code
```
import React from 'react'
import { render } from 'react-dom'
import { compose,applyMiddleware,createStore } from 'redux'
import {persistStore, autoRehydrate} from 'redux-persist'
import { Provider } from 'react-redux'
import createLogger from 'redux-logger';
import App from './components/App'
import reducer from './reducers'

const logger = createLogger();//add logger middleware
// const store = createStore(
//   reducer,
//   applyMiddleware( logger)
// );
const store = createStore(
  reducer,
  undefined,
  compose(
    applyMiddleware(logger),
    autoRehydrate()
  )
);

// begin periodically persisting the store
persistStore(store)

render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('root')
)

```
Seems  persist can work! But when I close&reopen browser ,then add some items 

will get some  warning code 
![](https://ww3.sinaimg.cn/large/006tNc79ly1fdpi42t5i8j30um03et8x.jpg)

How to solve this problem? Thanks!

**Comment by rt2zz** [comment]
that looks like an issue with your code, you need to assign keys to any components that are rendered in an array

**Comment by phpsmarter** [comment]
Thank you , I found the problem,in Action ,nextTodoId isn't storage,whe I reopen the browser, nextTodoId  always is 0 ,there must have  two todos with same id.Can I solve this problem  with redux-persist?
```
let nextTodoId = 0 //how to restore this variable  when I reopen brower;
export const addTodo = (text) => ({
  type: 'ADD_TODO',
  id: nextTodoId++,
  text
})
```

**Comment by phpsmarter** [comment]
And I change  method of  get ids.Seems solved problem?
```
export const addTodo = (text) => ({
  type: 'ADD_TODO',
  id: new Date().getTime().toString(),
  text
})
```

**Comment by rt2zz** [comment]
yes you can persist todos and `nextTodoId` no problem, I would recommend setting up with the vanilla instructions in the readme.
