### ISSUE TITLE
[Question] How does redux-persist handle non-string values?

### ISSUE THREAD

**Issue by dubert** [rt2zz/redux-persist#3]
Let's say I wanted to store booleans, or objects.

AsyncStorage gives an error if it isn't a string. Is there a conversion? Or is it just not allowed?

**Comment by rt2zz** [comment]
it `JSON.stringify`s the state before calling `storage.setItem`, so it should be able to store any variable.

Can you paste in the error you are seeing?

**Comment by rt2zz** [comment]
Looking at it, I realize I need to wrap that JSON.stringify in a try catch. It is possible some things cannot be stringifies. Still seeing your error would help, as most cases should work as is.

**Comment by dubert** [comment]
@rt2zz, I'm not getting an error with persistStore, but I did get errors before I switched to it, and I was curious how to do it. The answer was much simpler than I thought! Thanks!
