### ISSUE TITLE
Batched writes

### ISSUE THREAD

**Issue by chadwilken** [rt2zz/redux-persist#301]
To start off I would like to say I love your library and it has made my life easier. We are using version 4.4.2 and it seems that if we dispatch actions in rapid success (which is common in a few places of our app) it seems to drop intermediate dispatches before the first and last dispatch. Do you have a way to batch or queue these writes?

**Comment by rt2zz** [comment]
can you clarify what you mean by "drop intermediate dispatches"

redux-persist will not affect the action dispatch at all, what it will do is queue any chunks of changed state to be written to disk.

Are you noticing performance issues? I would recommend setting a small debounce like 16ms `{debounce: 16}`. This will trigger the writing of each chunk of changed state every 16ms and avoid unnecessary work.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
