### ISSUE TITLE
RN Conflict With Event Listener

### ISSUE THREAD

**Issue by edo1493** [rt2zz/redux-persist#306]
Hi guys, 
I am using redux-persist along with OneSignal in react native. This is generating a conflict in the sense that some OneSignal events that should be fired on start are never fired. These are events triggered on the native sdk. 

This is the One Signal issue: https://github.com/geektimecoil/react-native-onesignal/issues/200

I was wondering if you had experienced something like this (with also other libraries) before.

Thanks.

**Comment by rt2zz** [comment]
I am not familiar with onesignal, but it sounds like delaying rendering is causing the events to be lost until REHYDRATE is complete. You can work around this in a few ways. One suggestion is to put your one signal listeners outside of the rehydrate listener, and then buffer any received actions. e.g.

```js
  <OneSignalController>
    <App />
  </OneSignalController>
```

If your onesignal data does not need to be persisted, you can simply add the corresponding reducer to the redux persist blacklist and then no need to buffer the events at all!
