### ISSUE TITLE
[flow] types

### ISSUE THREAD

**Issue by juanolon** [rt2zz/redux-persist#312]
hey ppl.
are the files on type-definitions to be consume by thirds? i have include them to my .flowconfig file like this:
```
[libs]
node_modules/redux-persist/lib/index.js.flow
```

But still, it throws some erros.
```
Library type error:
node_modules/redux-persist/lib/index.js.flow:38
 38:   declare type CreateTransform = (in: TransformIn, out: TransformOut, config: TransformConfig) => Transform
                                           ^^^^^^^^^^^ identifier `TransformIn`. Could not resolve name

Library type error:
node_modules/redux-persist/lib/index.js.flow:38
 38:   declare type CreateTransform = (in: TransformIn, out: TransformOut, config: TransformConfig) => Transform
                                                             ^^^^^^^^^^^^ identifier `TransformOut`. Could not resolve name

Library type error:
node_modules/redux-persist/lib/index.js.flow:38
 38:   declare type CreateTransform = (in: TransformIn, out: TransformOut, config: TransformConfig) => Transform
                                                                                   ^^^^^^^^^^^^^^^ identifier `TransformConfig`. Could not resolve name

Library type error:
node_modules/redux-persist/lib/index.js.flow:38
 38:   declare type CreateTransform = (in: TransformIn, out: TransformOut, config: TransformConfig) => Transform
                                                                                                       ^^^^^^^^^ identifier `Transform`. Could not resolve name

```

This definitions are defined on the TypeScript definition file. That's why it wonders me.

**Comment by rt2zz** [comment]
It looks like the flow definitions need work. TransformIn, TransformOut, TransformConfig and Transform all appear missing, and the type for `Store` seems to be causing issues as well. PR welcome!

**Comment by rt2zz** [comment]
https://github.com/rt2zz/redux-persist/pull/319

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.

Also related, Flow issues still need work: https://github.com/rt2zz/redux-persist/issues/953#issuecomment-449545453 @juanolon if you're still using redux-persist, could you help out the project and try to sort out some of these Flow issues? See the comment linked above for what the current issues are.
