### ISSUE TITLE
Current redux state is not written to disk properly

### ISSUE THREAD

**Issue by Diwei-Chen** [rt2zz/redux-persist#313]
Thanks for putting on this amazing library.

We recently meet a problem that current redux state cannot properly/correctly be written disk which leads to a wrong rehydration.. The process can be seen as follows:

1. We have one resource to show which is stored in resources collection.
![screen shot 2017-03-30 at 6 25 11 pm](https://cloud.githubusercontent.com/assets/26317142/24492482/69d8ceba-1577-11e7-80c4-805509204e79.png)
![screen shot 2017-03-30 at 6 11 28 pm](https://cloud.githubusercontent.com/assets/26317142/24492489/6d6ea234-1577-11e7-92da-f39dbb39cf69.png)

2. After we add one more resource to database and delete it, everything works correctly.
![screen shot 2017-03-30 at 6 13 48 pm](https://cloud.githubusercontent.com/assets/26317142/24492516/7e7506ae-1577-11e7-8a00-f8e6829c8a03.png)
![screen shot 2017-03-30 at 6 14 27 pm](https://cloud.githubusercontent.com/assets/26317142/24492526/854f7fd6-1577-11e7-916b-0a5a0324df40.png)

3. But after we refresh the app, current redux state is rehydrated to the state after we added the second resource.
![screen shot 2017-03-30 at 6 18 36 pm](https://cloud.githubusercontent.com/assets/26317142/24492540/9091400a-1577-11e7-94aa-3bed08457e71.png)
![screen shot 2017-03-30 at 6 19 04 pm](https://cloud.githubusercontent.com/assets/26317142/24492546/983aadf0-1577-11e7-96b9-7de6a2e3b558.png)

Is this because redux-persist doesn't write the current redux state to disk properly or we hit command + R which is hot reload and just happen in simulator? Any suggestions, please?

My persistStore configuration is:
`const persistor = persistStore(MeteorStore, {
  storage: AsyncStorage,
  keyPrefix: 'react-native-meteor-redux',
  debounce: 1000
}, () => {
  MeteorStore.loaded();
});`

Regards,

**Comment by LuisRizo** [comment]
Same issue here. After logging in to my app, if I log out and refresh the app, I am still logged in. Maybe the persistStore doesn't update when we delete data?

**Comment by xiongxiong** [comment]
Same issue here. Only result of the first action is persisted, others not. Both in simulator and iPhone.

**Comment by Diwei-Chen** [comment]
https://github.com/DesignmanIO/react-native-meteor-offline/issues/29
