### ISSUE TITLE
Missing changelog/release notes

### ISSUE THREAD

**Issue by martin-svk** [rt2zz/redux-persist#317]
Hi,

first of all thanks for this great library. But I don't see any `CHANGELOG.md` or similar file.
And there are not even release notes in the `releases` tab.

Is going through the merged commits the only way to find out what it's new when upgrading to newer version? Thanks.

**Comment by rt2zz** [comment]
Just added notes for v4.6

Will try to be better about this in the future 🎈

**Comment by smmoosavi** [comment]
please be better about this :D
