### ISSUE TITLE
Whitelisting Specific Parts of State

### ISSUE THREAD

**Issue by nickcharles** [rt2zz/redux-persist#318]
My Redux state is a multi-level tree. Is there a way for me to whitelist just key A.X instead of the entirety of A?

**Comment by enahum** [comment]
Yes I also have a multi-level tree like

```js
entities: {
   users: {},
   posts: {},
   typing:{},
   ...
},
requests: {...}
```

How can I just blacklist entities.typing?

**Comment by haukurk** [comment]
+1

**Comment by rt2zz** [comment]
Currently there are three ways to achieve this:
- implement a custom REHYDRATE handler in your reducer which skips the keys you dont want to persist
- use https://github.com/edy/redux-persist-transform-filter to achieve the same effect ^
- refactor your reducer to store non-persisted state in different reducer than persisted state

Best solution I think depends on the specifics of your app.

**Comment by enahum** [comment]
Yeah I think im going to go with the filter. Thanks

**Comment by FilipMessa** [comment]
is there some example of custom REHYDRATE hadnler?

**Comment by Andarist** [comment]
@FilipMessa It's as simple as just handling `REHYDRATE` action in ur reducer which you can import from `'redux-persist/constants'`

**Comment by aguynamedben** [comment]
Related https://github.com/rt2zz/redux-persist/issues/330

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
