### ISSUE TITLE
Open to improvements around setimmediate?

### ISSUE THREAD

**Issue by toranb** [rt2zz/redux-persist#329]
I'm new to the project so please forgive me if some history has shown why we use `global.setImmediate` to pull in what I would otherwise assume comes from `npm install setimmediate`

https://github.com/rt2zz/redux-persist/blob/master/src/defaults/asyncLocalStorage.js#L1

Is it possible we could use an ES6 import here or will this always be a global lookup (when undefined)?

A little background: I'm currently working to add `redux-offline` and thus `redux-persist` support for emberJS developers and the very last blocker is this line so I'm curious what I can do to learn more about it /and possibly unblock it by using an ES6 import of some kind (if possible).

Thank you in advance!

**Comment by rt2zz** [comment]
What is the problem with calling `global.setImmediate`?

IIRC this was the safest way to retrieve setImmediate from non-browser environments like react-native. It is also found in other places like this polyfill: https://github.com/davidmarkclements/setImmediate-min/blob/master/index.js

I am open to resolving this, but do not fully understand the issue. Let me know! I would prefer to not introduce a new dep.

**Comment by toranb** [comment]
Fair question :) 

I'd like to improve this for browser only dev (like I'm facing today w/ emberJS). I've worked around it by doing a simple patch but wanted to see if we could ES6-ify this import to improve the experience for non react devs (assuming that is an option?). 

```js
var global = {
    setImmediate: window.setTimeout
  }
```

I'm open to be educated here - just curious how I can go about using this w/out hacks like you see above ^^

**Comment by rt2zz** [comment]
I do not know - if anyone else can weight in that would be great.

It occurs to me however, there may be a much simpler solution, we can remove setImmediate calls from all of the default localStorage implementation and we can replaced the use in `persistStore` as folllows
`const genericSetImmediate = typeof setImmediate === 'undefined' ? global.setImmediate || function (fn) { return setTimeout(fn, 0) } : setImmediate`
->
`const genericSetImmediate = typeof setImmediate === 'undefined' ? (fn) => setTimeout(fn, 0) : setImmediate`

**Comment by toranb** [comment]
@rt2zz I've been able to work around this (to avoid the global hack mentioned above). So for now I'd say "ignore me" and I'll do my best to learn more about react native/ other (non ember) envs that the community is using this great library :)

If you still want to hash out the change above I'm all ears - curious if others would find that useful

**Comment by rt2zz** [comment]
great, I will still mull over these potential changes but maybe with a little less urgency :D

**Comment by toranb** [comment]
@rt2zz absolutely (no rush) - I hope the big take away here was "someone not in the react/node ecosystem found a global that we assumed everyone already had by way of webpack".

Thanks again! I'm really looking forward to using this library more as I learn "how to offline"

**Comment by rt2zz** [comment]
@toranb in order to reduce the bundle size (and avoid setImmediate polyfill for babel users) we ended up going in a different direction: https://github.com/rt2zz/redux-persist/pull/334

I am not sure how to make this compatible for people without global polyfilled (although that is a tiny polyfill). I think this needs more discussion.

**Comment by rt2zz** [comment]
could it make sense to do a tiny local scoping:

```js
let global = typeof global !== 'undefined' ? global : {}
```

**Comment by Andarist** [comment]
hm, no harm in such a check i think - for `babel` users it will still trigger polyfill (i think), but its tiny, so it is a minor issue and at the same time it should allow usage without custom setups for non-babel users
