### ISSUE TITLE
Polyfills included in builds

### ISSUE THREAD

**Issue by Andarist** [rt2zz/redux-persist#333]
I've noticed that i.e. [this](https://github.com/rt2zz/redux-persist/blob/c3a9332c5218f663047d78e0206ca78b6c316c55/src/defaults/asyncLocalStorage.js#L1) and [this](https://github.com/rt2zz/redux-persist/blob/c3a9332c5218f663047d78e0206ca78b6c316c55/src/persistStore.js#L6) still requires some polyfills to be included automatically when bundled.

Both `global` (which is not a problem I think, it's really small) is required and `setImmediate` too.

Maybe we could change both to something like:
```javascript
const genericSetImmediate = typeof setImmediate !== 'undefined' ? global.setImmediate : fn => setTimeout(fn, 0)
```
This should produce a smaller bundle (I think, but needs to be tested) due to lack of requiring `setImmediate` which has also a dependency on `process`, so it requires it too.

WDYT?

**Comment by rt2zz** [comment]
nice, we came to pretty much the same conclusion here: https://github.com/rt2zz/redux-persist/issues/329

Seems clear then, that we should make the update.

**Comment by Andarist** [comment]
Oh, didnt notice the other issue. Sorry about that.

Problem with `babel` (I think) that it implicitly polyfill some stuff (like `process`, `global`, `setImmediate`) and include `core-js` shims. Have no idea if this is somehow configurable, would like to explore this, but dont have time right now. 

Gonna provide a PR for this.
