### ISSUE TITLE
How to advance  the steps  of the REHYDRATE to avoid return initialState?

### ISSUE THREAD

**Issue by guoliang1206** [rt2zz/redux-persist#338]
Hi, guys
There has a  problem that stuck me . I have used redux to manage the user login operation. 

1. this is the initialState of the navigator.
```
const initialNavState = {
    index:0,
    routes: [
        { key: 'InitA', routeName: 'Login' },
        { key: 'InitB', routeName: 'Home' },
    ],
};
```
2. and this is the reducer:

```
function nav(state = initialNavState, action) {
    switch (action.type) {
        case LOGIN:{
            return  AppNavigator.router.getStateForAction(NavigationActions.navigate({routeName:'Home}), state);
        }
```

3. and final I created the  store:
```
    store = createStore(AppReducer, undefined, autoRehydrate());
    
    componentDidMount() {
        persistStore(this.store, { storage: AsyncStorage });
    }

```
the problem is: if I reload the code,  because the store created by reducer, so my reducer get the initialState, and then do the `persist/REHYDRATE` action.  Andd my app will show the Login screen and go to the Home screen quickly, 

![pr1](https://cloud.githubusercontent.com/assets/12846676/25426154/d2ce5974-2aa0-11e7-8592-4bbf2eccd025.gif)

**Comment by rt2zz** [comment]
@guoliang1206 did you resolve the issue? the recommended approach is to show a loading indicator on your app until REHYDRATE is complete, and then render your navigator.

**Comment by guoliang1206** [comment]
@rt2zz yes, I did. I have catch the action "REHYDRATE", and then I re-render the screen, show the home screen.
