### ISSUE TITLE
Latest NPM version 4.7.0 removes the storage

### ISSUE THREAD

**Issue by shaunrfield** [rt2zz/redux-persist#339]
We have our CI using the latest package in our build.  The latest version released appears to have moved or removed the storage module.  These are the errors we are getting in our webpack compilation.
```
Module not found Can't resolve 'redux-persist/storages' in 'C:\BuildAgent\work\23d3470f8eb46308\PromappMvc\Scripts\app\store'
Module not found Can't resolve 'redux-persist/constants' in 'C:\BuildAgent\work\23d3470f8eb46308\PromappMvc\Scripts\app\reducers'
```

We couldn't find any release notes on these changes.  Could someone please advise what has changed.

**Comment by rt2zz** [comment]
Sorry will fix asap, I think some files need to be whitelisted

**Comment by rt2zz** [comment]
In the meantime I would recommend 4.6

**Comment by shaunrfield** [comment]
Cheers.  We have changed out package.json to specifically target 4.6.0 for now.

**Comment by rt2zz** [comment]
can you give `4.7.1` a shot 👍

**Comment by Andarist** [comment]
Also if u are using webpack2beta, please upgrade. It had bug regarding this

**Comment by bruno-barbosa** [comment]
@rt2zz 4.7.1 has solved the issue, thank you!
