### ISSUE TITLE
No-op sub state change prevents auto rehydration

### ISSUE THREAD

**Issue by doxxx** [rt2zz/redux-persist#34]
If a reducer for a sub state returns a new but identical state object, autoRehydrate detects this as a change and skips rehydrating that sub state.

**Comment by rt2zz** [comment]
This is by design, autorehydrate checks for object equality.

Do you have a reducer that makes this behaivor problematic?

**Comment by doxxx** [comment]
I was able to fix my reducers that were causing the problem, but I filed
this in case it was unintended. Since it's by design, feel free to close it.

**Comment by rt2zz** [comment]
I will leave this open for a bit to see if anyone else wants to weigh in. 

The rationalization is, if the reducer handles the the `REHYDRATE` action, it implies custom rehydration and based on this assumption autoRehydrate will skip that reducer. This also is nice because it prevents conflicts where autoRehydrate might overwrite something the reducer wanted.

**Comment by doxxx** [comment]
Sounds reasonable to me.

**Comment by IanVS** [comment]
If a nested reducer handles the `REHYDRATE` action, is that entire reducer skipped?  For example:

```js
function subReducer1(state = initialState, action) {
  switch (action.type) {
  case 'ITEMS_UPDATED':
    return {...state, items: actions.payload};  
  default:
    return state;
}

function subReducer2(state = initialState, action) {
  switch (action.type) {
  case REHYDRATE:
    return {...state};  // presumably something more complicated here
  default:
    return state;
}

const topReducer = combineReducers({
    subReducer1,
    subReducer2,
});
```

In the above example, will `subReducer1` still be auto-rehydrated?  In my testing so far, it does not seem to be.

**Comment by IanVS** [comment]
Actually, in my case I have one more level of `combineReducers`, so it's more like:

```js
const topReducer = combineReducers({
    anotherReducer,
    midReducer: combineReducers({
        subReducer1,
        subReducer2,
    });
});
```

Not sure if that makes any difference.

**Comment by rt2zz** [comment]
@IanVS yes that matters, autoRehydrate only looks at the first level of state. So in this case you have a few options:
1) dont use autoRehydrate and have all of your reducers implement REHYDRATE
2) have none of your sub reducer handle REHYDRATE (then autorehydrate will work as expected)
3) write a custom version of autoRehydrate that does exactly what you need.
