### ISSUE TITLE
Doesn't persist state.

### ISSUE THREAD

**Issue by bogomazov** [rt2zz/redux-persist#345]
If I understand how redux-persist works correctly, after 
```
export const Store = createStore(
  rootReducer,
  {},
  compose(
    applyMiddleware(thunk.withExtraArgument(getAPI), createLogger()),
    autoRehydrate()
  ))

persistStore(Store, { storage: AsyncStorage })
```

it will save my state automatically after each `dispatch` occurs that results in a state change.
However, after I change state and restart the app, it "rehydrates" (loads values from local storage and merges with current state) on a startup with my initial state - so no changes were saved. 

I also don't see any logs regarding redux-persist after I change a state.

if Redux-persist is not meant to persist the whole state, how do I do so?

Thanks.

**Comment by bogomazov** [comment]
It started working after I restarted the emulator...

**Comment by Kliton** [comment]
Up.
