### ISSUE TITLE
Why isn't stateReconciler run in createTransform?

### ISSUE THREAD

**Issue by braco** [rt2zz/redux-persist#346]
Let's say you have a common state tree like so:
```
{
   reducerName1: {}
   reducerName2: {}
   reducerName3: {}
}
```
It seems that the default stateReconciler does a one level, shallow merge of the tree. This means if your initial state has keys:
```
initial state = {
   reducerName1: { foo: "value" }
}
```
that the thawed state does not:
```
thawed state = {
   reducerName1: { bar: "value" }
}
```
they will get wiped out by default (`foo` in this case will be removed)

Wouldn't this be easily solved by allowing a per-object stateReconciler in createTransform()?:

```
const transform = createTransform(
  ...,
  ...,
  { stateReconciler: () => ({ merge this reducer into itself }) }
);
```
And why isn't this default behavior, or at least an optional behavior, out of curiosity? Seems like a lot of issues revolve around some form of this problem.

**Comment by rt2zz** [comment]
@braco  its a hard problem, if we reconcile deeper, you can easily end up with incorrect state (unless you always write migrations). If we dont reconcile at all then, similarly you end up writing more migrations to make sure initial state is preserved. 

The choice was to go with the solution that would work out of the box for the most people, in this case that is to shallow merge 1 level deep. I agree we can do more here to enable customizing the behavior. IMO the default should now be to do a hard set (make no assumptions) but there should be easy opt-in for shallow, and custom merge strategies.

This would not I think be done at the transform level however, and instead in the higher order reducer. I have some ideas for how to do this, although I suspect will not be ready for at least a couple of weeks.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
