### ISSUE TITLE
Some components not receiving the rehydrated state

### ISSUE THREAD

**Issue by natashache** [rt2zz/redux-persist#348]
I'm building a progressive web app with react, redux, and using redux-persist to store the app state in localforage for offline use. The problem is when the app is offline, some of the app components are able to receive the persisted state as props, while other components don't receive anything at all. 

I added
```
  componentWillReceiveProps(nextProps) {
      console.log('updated props: ', nextProps)
  }
```
in all the relevant components. And the console.log is completely missing on some components when offline. I assume this means the component is not receiving prop updates from the state rehydration at all. In contrast, when the app is online, the console.log shows in every component.

Here is a problematic page on my deployed app https://mysoundwise.com/courses/115. The page has three high-level components: the navbar, the page body, and the footer. The navbar component receives rehydrated state with no problem, but the page body does not receive anything.

Would really appreciate any insights on this.

**Comment by LuckyMona** [comment]
Do you find the solution? it occurred to me also

**Comment by natashache** [comment]
@LuckyMona Yes mine is working now. The problem seems to be that some components get rendered before the state is rehydrated. So they are not receiving the props. I followed the solution in #126 and moved all local state updating to `componentWillReceiveProps` function and it worked.

**Comment by LuckyMona** [comment]
Can you please make it clearer about this part：moving all local state updating to `componentWillReceiveProps ` function？I add the code below in my `reducer.js` as what rt2zz says in #126，but it doesn't work

```
import { REHYDRATE } from 'redux-persist/constants'

function myReducer(state, action){
//...
case REHYDRATE:
   return {...state, ...action.payload.myReducer, rehydrated: true}
//...
```

**Comment by natashache** [comment]
@LuckyMona Here's my root component. It shows "loading" on page until rehydration is complete. That's what did the trick for me.
```
export default class App extends Component {
  constructor() {
    super()
    this.state = {
      rehydrated: false
    }
  }

  componentWillMount(){
    const persistor = persistStore(store, {storage: localForage}, () => {
      this.setState({ rehydrated: true })
    })
  }

  render() {
    if(!this.state.rehydrated) {
      return <div>Loading...</div>
    }
    return (
      <Provider store = { store }>
        <Routes />
      </Provider>
    )
  }
}
```

**Comment by LuckyMona** [comment]
Thanks very much for your detailed guidance！ By the way, Could your web app work normal if you refreshed the page with ”F5“ ? Mine would get the initial state rather than the updated state，which rather confuse me.
