### ISSUE TITLE
Post build issue with webpack 2.4+

### ISSUE THREAD

**Issue by deldreth** [rt2zz/redux-persist#352]
Debugging an issue related to seeing this error on any action dispatches that eventually alter state.
`Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_3_json_stringify_safe___default(...) is not a function`

I've only tried to receive this error in webpack 2.4+ but it appears to be related to the following webpack issue: https://github.com/webpack/webpack/issues/4742

Considering the age and lack of traction on json-stringify-safe it may be ideal to fork the dependency and update its exports or build it for specific platforms. It may be possible to specifically reference the `.default` export from json-stringify-safe, but I've not attempted.

I'm assuming that this may be an issue with all versions of webpack 2+ but I've not confirmed this.

**Comment by deldreth** [comment]
I can confirm that this affects all of webpack 2+

**Comment by rt2zz** [comment]
@deldreth did you resolve this issue? I have used it sucessfully with webpack 2+, wondering why the difference. I wonder if https://github.com/debitoor/safe-json-stringify could be a better alternative?
