### ISSUE TITLE
Add method for manually updating the persistor?

### ISSUE THREAD

**Issue by zacacollier** [rt2zz/redux-persist#355]
Maybe there's already a simple way to do this and I'm just not seeing it here, but it'd be nice if there was a way to manually call redux-persist and save the current store to local storage, either in the form of an action, or a method on the API (or both). I've experienced cases where the store is only partially persisted, it'd be nice if there were a simple way to ensure that it is persisted by manually updating the persistor.

This would be handy in async (thunk) actions, something like:
```javascript
import store from '../store';
...
function updateUserProfile(user, profile) {
  return (dispatch, user, profile) =>
      post(`http://localhost:8080/${user.id}/profile_endpoint`, profile)
          .then(res => dispatch('USER_PROFILE_UPDATE', res.data)
          .then(() => dispatch(persist/SAVE, store)
}
```

Or via an API method:
```javascript
import { saveStore } from 'redux-persist';

// stuff happening
saveStore();
```

Thoughts? Sorry if this is a redundant question - if there's already a good solution to this problem, I'm all ears.

Otherwise, if you'd like to see an enhancement similar to what I've described here, I'd be happy to try working on it.

**Comment by iamwebdesigner** [comment]
I also need this. I think it would be nice to add it to persistor as a `save()` method

**Comment by drhorse** [comment]
After user changes the language option, I'd like to wait till the language option is saved to store before I restart the app. So yes, I need it too.

**Comment by iamwebdesigner** [comment]
@drhorse please request for merge [this PR](https://github.com/rt2zz/redux-persist/pull/321)

**Comment by aguynamedben** [comment]
The PR was merged: https://github.com/rt2zz/redux-persist/pull/321

The API is `.flush()` and is documented in the README [here](https://github.com/rt2zz/redux-persist#persistor-object). It's available in redux-persist v5.
