### ISSUE TITLE
How state change is monitored?

### ISSUE THREAD

**Issue by Diwei-Chen** [rt2zz/redux-persist#356]
Hi @rt2zz , thanks for your efforts on this awesome library.

I am wondering how redux-persist monitors redux-state changes? i.e., is it the same way as Redux does(http://redux.js.org/docs/faq/ImmutableData.html#shallow-and-deep-equality-checking) or implementing a deep equality checking?

regards,

https://github.com/DesignmanIO/react-native-meteor-offline/issues/35

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
