### ISSUE TITLE
Chained Reducers

### ISSUE THREAD

**Issue by oandreazza** [rt2zz/redux-persist#358]
Hi!

In my app I have chained reducers like that:
`appReducers: Object auth
:
Object
jobs
:
Object
user
:
Object`

I just wanna persist the _jobs_ reducers, but in persistStore when I set the whitelist, I can't set nested reducers, only the appReducer. Is there a way to persist nested reducers?

Thanks!

**Comment by fsarachu** [comment]
Same issue here! By now I solve this handling the REHYDRATE action type in the nested reducers that I wanna blacklist. In the action handler I just return the received state, ignoring the rehydration.

**Comment by aguynamedben** [comment]
See this comment: https://github.com/rt2zz/redux-persist/issues/318#issuecomment-291008227

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
