### ISSUE TITLE
autoRehydrate not working after production minifcation

### ISSUE THREAD

**Issue by redgenie** [rt2zz/redux-persist#362]
There's an odd behavior happening with my app now, if I build the package using `NODE_ENV=development`, everything works as it's supposed to be, once I change to `production`, rehydration doesn't work anymore. After checking the dev tools IndexDB and local storage, I find the states persisted there, but rehydration doesn't work.

Middleware looks something like this:
```javascript
  const middlewares = [
    sagaMiddleware,
    routerMiddleware(history),
    createActionBuffer(REHYDRATE),
  ];
  const enhancers = [
    autoRehydrate(),
    applyMiddleware(...middlewares),
  ];
  const store = createStore(
    createReducer(),
    initialState,
    compose(...enhancers),
  );
// ...

```
Redux version 3.6.0. redux-persist: 4.8.0

Any clues?

**Comment by RemeJuan** [comment]
@redgenie I was having that same issue now myself, and fortunately my application is quite simple. I managed to resolve it using the more manual approach of using the 'per reducer' method to rehydrate.

**Comment by rt2zz** [comment]
@redgenie that is very concerning. I have not observed this and am not sure what could cause it. We are currently close to shipping redux-persist v5, which takes a different approach to autoRehydrate. 

hopefully you can debug and figure out what is going on, but short of that I think updating to v5 might be a reasonable altenrative https://github.com/rt2zz/redux-persist/tree/v5

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.

@redgenie Did you end up trying v5 out?
