### ISSUE TITLE
State is not persisted when action is dispatched in componentDidMount

### ISSUE THREAD

**Issue by ghostec** [rt2zz/redux-persist#364]
I had a container like this:

```
...
constructor(props) {
super(props);
}

componentDidMount() {
this.dispatch({ type: "PURGE" });
}

render() {
return <div />
}
...

export default connect(state => state)(Container);
```

However, after a long time debugging, the state generated by my rootReducer was not persisted.
Even without refreshing the page, just typing localStorage and examining it showed the incorrect state, same as before PURGE action.

When I dispatch the same action with an onClick trigger:

```
<div onClick={event => handleClick({ dispatch: props.dispatch }))>CLICK</div>
```

Then my PURGE action is persisted in localStorage and reflected upon page refresh.

Is there any reason for this to happen? Should I not dispatch actions on componentDidMount if I want them to be persisted?

Thanks!

**Comment by glowind** [comment]
I guess it's because the asynchro nature of the Rehydration. The component render before the Rehydration is complete.

https://github.com/rt2zz/redux-persist/blob/master/docs/recipes.md

**Comment by ghostec** [comment]
@glowind Sorry, I forgot to mention. I'm handling rehydration issues. My main component is some sort of a router where I postpone any rendering if props.storage.rehydration is false (a reducer as you might guess). So, when my componentDidMount calls a dispatch, I know for sure that my store was rehydrated. (Or for some reason a race condition might happen??)

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.

@ghostec You may want to take a look at the PersistGate features in the project's README to prevent React component rendering until redux-persist rehydration has completed. I'm not sure, but that feature may have been added after you posted this issue.
