### ISSUE TITLE
confused about opt-in vs. opt-out

### ISSUE THREAD

**Issue by raould** [rt2zz/redux-persist#365]
hi, Thanks for making the library!

I wonder if the docs might explain more about when persist will/not over-write state.

I have several reducers (call them A, B, and C), put together with redux.combineReducers(). How am I correctly supposed to have A & B participate, but not C? In C, so far the only way I've gotten it to opt-out is to do something like:
```
const initialState:X = { mykey: [] };
const reducer = (state:X = initialState, action):X => {
  switch (action.type) {
    case REHYDRATE:
      return { mykey: state.mykey }; // i guess forcing a shallow diff?
  }
}
```

I also tried:
* omit the case, but when REHYDRATE happens and I end up with my initialState.
* just "return state;" in the case, but ditto same thing of ending up with my initialState.

(Is it maybe because of my initialState default value? I think that shouldn't be wrong/disallowed based on http://redux.js.org/docs/recipes/reducers/InitializingState.html)

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.

@raould I'm not sure if it solves your exact issue but you might want to take a look at the blacklist features documented in the project's README. Keys in the blacklist (i.e. reducer names) will not be persisted.
