### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by bradennapier** [rt2zz/redux-persist#366]
Not really sure why or what happened - woke up this morning and updated webpack and redux-persist now no longer works.  Says illegal invocation when trying to call setImmediate()

```
persistStore.js:25 Uncaught TypeError: Illegal invocation
    at persistStore (persistStore.js:25)
```

![image](https://user-images.githubusercontent.com/15365418/26886041-36c33926-4b59-11e7-971b-2dbda8238c9a.png)

**Comment by bradennapier** [comment]
You added a "module" key to the package.json which breaks it in the browser as it does not have all the es6 functionality.

**Comment by bradennapier** [comment]
Ugh - please remove the module key from package.json - it breaks everythign with illegal invocation... every time i install something it breaks again.

**Comment by bradennapier** [comment]
```json
  "typings": "lib/index.d.ts",
  "module": "es/index.js",
```

the es/index.js breaks the entire process

**Comment by Andarist** [comment]
`module` key alone is not at fault. You would have to share the repository with reproduced issue - with ur webpack config and redux-persist versions locked in there, so we could investigate the matter.

**Comment by rt2zz** [comment]
@bradennapier we took great care to update things to keep bundle sizes small and prevent unnecessary polyfills. In this case I am unaware why setImmediate is an illegal invocation.

I see your comment on the webpack issue, it is not clear to me however is the issue that webpack is not processing files with module field? Also what was the change in webpack 3 that caused this breakage?

**Comment by THernandez03** [comment]
Same here... after Webpack3 release,

**Comment by THernandez03** [comment]
Digging into the problem i see the following code using `eval` as `webpack.devtool`

![image](https://user-images.githubusercontent.com/1939521/27300863-2deee3c2-54ff-11e7-91d1-5220c79c318d.png)

I ran the following code and get the same error.

```javascript
foo = { bar: setTimeout }
foo.bar(function(){ console.log('baz'); })
// Throws: Uncaught TypeError: Illegal invocation at <anonymous>:3:5
```
So if you give it a context like `window` or `null` even `undefined` it works.  But if you give it a context like `{}`  or `[]` it fails.

**Comment by THernandez03** [comment]
Also can be related to this

https://github.com/webpack/webpack/issues/5074

**Comment by rt2zz** [comment]
@THernandez03 what do you recommend as resolution? do you believe this to be a webpack bug?

I would suggest if it is the es build causing issue you could import from lib `import { persistStore } from 'redux-persist/lib'`

**Comment by THernandez03** [comment]
I think is a webpack but, because following the TC39 spec, the top level context should be 'undefined'

**Comment by THernandez03** [comment]
check this out... its a new issue with a little bit information

https://github.com/webpack/webpack/issues/5111

**Comment by THernandez03** [comment]
To make it work and stick to the spec, you should put `module.strictThisContextOnImports: true` on your webpack config.

I think could be a great idea, adjust the code to this repo to make it compatible without this option

**Comment by THernandez03** [comment]
thanks a lot

**Comment by rt2zz** [comment]
🙌 @Andarist
