### ISSUE TITLE
Browser hangs during Redux-Persist startup

### ISSUE THREAD

**Issue by smattt** [rt2zz/redux-persist#375]
After I create my one and only persistor, Chrome hangs for multiple seconds before recovering but other browsers usually crash. After Chrome recovers, it works great - I'm successfully hydrating state and persisting new state changes. I love the library and would like to continue using it, but I need to resolve this performance issue before we go to production.

![image](https://user-images.githubusercontent.com/23129667/27246982-0b6a55ea-52aa-11e7-95d8-3c4b409ab237.png)

I have about a dozen reducers and I'm using some verbose libraries, such as Redux-Form - but I've blacklisted their reducers so that doesn't seem like it should be a problem. My Redux store is largely just key-value pairs of strings, no deep data structures or anything too heavy. I have about 100 Redux store fields spread across a dozen reducers. Could my issue be caused by the number of reducers I have?

Has anyone else encountered this? Any suggestions on how to mitigate the hanging/freezing issue?

Thanks!

**Comment by smattt** [comment]
It's interesting that if I just pass in a whitelist with every reducer specified - the hang goes not occur! If I omit the whitelist and let every reducer get automatically included, then I see a 15-20 second hang. I'm unblocked for now but a fix would still be very appreciated, I'd imagine other folks must be hitting this as well.

**Comment by rt2zz** [comment]
odd, I have never seen the behavior. Its possible your state object has a ton of properties you are not aware of?

I would recommend a few things
1. check your state, sounds like there is something unexpected on it
2. use a whitelist, this is generally not a bad approach
3. use localForage as your storage engine

You can also check the size of your localStorage usage, if the number is 2+ mb this could definitely cause perf issues, depending on the data shape.

**Comment by smattt** [comment]
You are 100% correct, I root caused the issue to two instances where I was caching JSX.Elements in the Redux store. The working whitelist was misleading because the problematic reducer was accidentally omitted from the whitelist - it was not working if the whitelist included all reducers.

Do you accept bitcoin? I'd like to send you some beer money for the help.

Thank you for producing such a useful library!

**Comment by iamrosepierre** [comment]
Can you help me
currently working on Redux persist it works fine on desktop browser chrome but in mobile browser chrome it does persist once but its not updating.
![image](https://user-images.githubusercontent.com/51813646/93558575-50993680-f9b0-11ea-9dd4-25e0a43f49e8.png)
