### ISSUE TITLE
QUESTION: How frequently or on what triggers does the persist occur?

### ISSUE THREAD

**Issue by ccuilla** [rt2zz/redux-persist#376]
I've been trying to understand when, after:

```js
// begin periodically persisting the store
persistStore(store)
```

Persistence occurs? Is there an interval? Triggered based on some other conditions? Is it configurable?

**Comment by rt2zz** [comment]
it registers `store.subscribe`, then on every state change it does a shallow compare of the state, and updates any keys that have changed. Typically this is very performant, but it does depend on your exact implementation. You can always set `debounce` on persist config if it becomes an issue.

**Comment by ccuilla** [comment]
Perfect. Thanks for the details.

**Comment by pensierinmusica** [comment]
@rt2zz I think this info is very useful, can we add it to the docs? If you like I can create a PR for it. Thx, cheers!

**Comment by tybro0103** [comment]
I second @pensierinmusica.

In the readme it just "periodically", which is concerning in say iOS - if the user were to kill the app before something was persisted that could be a problem.

Glad to hear it works the way @rt2zz explained above as that seems ideal.
