### ISSUE TITLE
Configuring sessionStorage persist state

### ISSUE THREAD

**Issue by qborreda** [rt2zz/redux-persist#381]
I'm trying to figure out what I've been doing wrong for a while. 

So, I implemented react-persist by passing the createStore the `autoHydrate()` along with my middleware. And then tried to call it to persist into the sessionStorage like 
```
  persistStore(store, {
    whitelist: ['locale', 'auth'],
    storage: sessionStorage
  });
```
trying to make only the locale and auth nodes of my state to persist into it. All I can get is the full state persisted into the localStorage instead .. 

What am I doing wrong? 

On a side question .. if I finally only make it so those two nodes are stored, should I just include the reducer entry looking for the `REHYDRATE` action.type into the reducers actually using those nodes? Or is it even better to create a new reducer to be looking for this one and get all the payload in? 

Thank you in advance

**Comment by qborreda** [comment]
Shameless bump .. can you offer some advice, please?

**Comment by qborreda** [comment]
Furthermore, if I set it to `storage: localStorage` it's not working either. It's only working when I don't pass any `storage` value on the config when I can get those two whitelisted nodes to persist.

**Comment by rrivem** [comment]
@qborreda, you need to use `import { asyncLocalStorage, asyncSessionStorage } from "redux-persist/storages"`

**Comment by qborreda** [comment]
Thanks @rrivem - will try that, although I made it work finally, with just the whitelist config part.

**Comment by lory-lu** [comment]
Cannot find module "redux-persist/storages"

**Comment by rt2zz** [comment]
that was v4, use `import storage from 'redux-persist/lib/storage'`for v5

**Comment by PavanKumarHRao** [comment]
is redux-persist session storage possible??

**Comment by syedshahidashiqali** [comment]
what if i want to make my storage dynamic like the default for some reducers and session for some reducers like auth ?

**Comment by alamenai** [comment]
That's interesting @syedshahidashiqali !

**Comment by alamenai** [comment]
Hi @syedshahidashiqali , I guess in this case you have to create 2 different stores.
