### ISSUE TITLE
Does not save when reducer is set to null or false

### ISSUE THREAD

**Issue by esganzerla** [rt2zz/redux-persist#382]
I'm trying to restart some reducers through the `REHYDRATE` action and when I set it to be `null` or `false` it's just not saving the new data. I tried setting a string and it works just fine.

```javascript
import { REHYDRATE } from 'redux-persist/constants'
import t from '../types'

const initialState = null // I have tried switching this to false too

export default function (loadingMessage = initialState, action) {
  switch (action.type) {
    case t.IS_LOADING:
      return action.payload
    case REHYDRATE:
    case t.DONE_LOADING:
      return initialState
    default:
      return loadingMessage
  }
}
```

Is it a bug? Should I do it differently?

Thanks!

**Comment by jamesmfriedman** [comment]
Setting the initial state of a reducer to null should be perfectly valid. This is a bug located here:

![image](https://user-images.githubusercontent.com/975256/28591082-6cd05d04-7152-11e7-90a0-2044c085e2f9.png)
![image](https://user-images.githubusercontent.com/975256/28591109-7f7df61e-7152-11e7-8205-ae05ca67b3d5.png)

The if statement on line 23 needs to check if its an object, and if it's truthy.

**Comment by jamesmfriedman** [comment]
A little more exploration, setting undefined as the default throws an error as well, but false is acceptable. Null seems like the appropriate value I should use for my reducer, but i'm ok with the workaround for the time being.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.

I'm not sure, but I think for better or worse, redux-persist may have some built-in assumptions around state/defaultState being an empty object (not undefined or null). Potentially related: https://github.com/rt2zz/redux-persist/issues/817
