### ISSUE TITLE
Break IE from 4.7+

### ISSUE THREAD

**Issue by jalkoby** [rt2zz/redux-persist#386]
Hi. After update from 4.6 to 4.8.1 my app had broken in all IE browsers(10, 11, edge) with "". I've made a short investigation and found the place - src/utils/setImmediate.js . In that file the code tries to use a native `setImmediate` which only present in node & IE. Probably the best case is avoid native usage for ie. What do you think and should I create a PR?

**Comment by Andarist** [comment]
What's the exact issue with `setImmediate` in IE?

**Comment by jalkoby** [comment]
It raises "Invalid calling object"  in: 
```js
# src/persistStore.js

if (shouldRestore) {
    setImmediate(() => {
```

One of possible reasons is https://github.com/facebook/draft-js/issues/1230

**Comment by Andarist** [comment]
Could u change `src/utils/setImmediate.js` (in reality u need to change appropriate file which is in `lib/` or `es/` directory - depending on which bundler do you use) to:
```js
const setImmediate = typeof global !== 'undefined' && typeof global.setImmediate !== 'undefined'
  ? (fn, ms) => global.setImmediate(fn, ms)
  : (fn, ms) => setTimeout(fn, ms)
```

I believe it should fix your issue, would like to get a confirmation, as I cannot check it at the moment myself. If you confirm it's fixed - we are going to incorporate it into the library.

**Comment by jalkoby** [comment]
@Andarist yep, wrapping helped to fix it - here is the PR
