### ISSUE TITLE
Question about how the data persists

### ISSUE THREAD

**Issue by 9thwall** [rt2zz/redux-persist#391]
Hi, 
I'm trying to understand the basic logic of how this works. 
If I'm using AsyncStorage, does this plugin copy the data from AsyncStorage to Redux or from Redux to AsyncStorage?

Should I modify data in the AsyncStorage and then trigger a overwrite to Redux or the other way around?  
Any clarification would be great.

**Comment by Noitidart** [comment]
It copies the data from async storage to redux, where the key matches `reduxPersist:[store_key]`. Then everytime it changes, it updates `AsyncStorage` (you can debounce/delay this save but by default it tries immediately).

I personally never have the need to mess with AsyncStorage,if you are using redux-persist, redux-persist handles everything for us.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
