### ISSUE TITLE
sessionStorage IF "remember me" is not checked

### ISSUE THREAD

**Issue by daniloprates** [rt2zz/redux-persist#392]
I'm trying to implement the localStorage/sessionStorage depending on the "remember me" checkbox. 

Since Redux Persist is set before the login action, is there a way I could do that?

**Comment by itslittlejohn** [comment]
You could always use localStorage, but also store the rememberMe selection. If rememberMe is false when your app loads, just clear the stored user data.

**Comment by daniloprates** [comment]
@itslittlejohn sounds good. just don't know how to detect is it's a simple reload or a new session, without using any other resource, like saving a flag in the sessionStorage...

**Comment by daniloprates** [comment]
@itslittlejohn great, I'll give it a go.

thanks!

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
