### ISSUE TITLE
Question - Does autoRehydrate() store data auto 

### ISSUE THREAD

**Issue by AlmogRnD** [rt2zz/redux-persist#393]
I had a question regarding autoRehydrate() does this store data automatic i.e. each time I update my redux store/state? 

Or should I be triggering this each do I update my store?  

Also is there a way to see what data is being saved to the local storage to make sure it's working?

**Comment by mim-Armand** [comment]
Hey @AlmogRnD,
I believe you can choose the way you want to rehydrate your store (have a look at the root Readme.md and it's all explained clearly):

- If you import `autoRehydrate` from the package and pass it as an enhancer it will rehydrate the store automatically and you don't have to worry about it, you can also let it know which components you want to persist with `blacklist` and `whitelist` options (one or the other)
- if you opt to do it in per container basis you have to trigger it yourself and handle the logic (to when)

> Also is there a way to see what data is being saved to the local storage to make sure it's working?

Sure, There are different ways, to start with, depending on the storage engine you use, you can use the developer-tools to inspect them and even change them on the fly!
For the default engine ( LocalStorage ), [Go to the local-storage](https://developers.google.com/web/tools/chrome-devtools/manage-data/local-storage)

Hope it helps, :+1:

**Comment by farhanmannan** [comment]
@mim-Armand how frequently does `autoRehydrate` persist the store?

**Comment by mim-Armand** [comment]
@farhanmannan `autoRehydrate` I believe automatically rehydrate the store and doesn't affect the frequency in which the storage is updated, `persistStore` is what's taking care of that part and you can call it whenever you want or have it update the storage whenever there is a change in the tracking stores, you can also provide a callback function to it and get notified whenever it updates the storage to find out how frequent it does it in your code.
Look at the [docs](https://github.com/rt2zz/redux-persist) to find out more.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
