### ISSUE TITLE
File:// protocol

### ISSUE THREAD

**Issue by mim-Armand** [rt2zz/redux-persist#394]
**Local Storage**, understandably, does not work on `File://..` protocol, but even with a custom storage implementation which works in both protocols, **Redux-Persist** does not work when the page is loaded from the **file system** ( works when served from a domain! )

Everything looks like it should work on `file://` as well except that it doesn't.. and the fact that it works on `http://` does not help understanding the problem!

Is there anything in the project's code that would prevent it from working properly on the file protocol?

PS: I know that the custom storage -mentioned above- works, because I wrote it myself and to trim down the problem sources I ended up just returning a pre-defined json string on `getItem` to make sure that the problem is not async stuff, and it works all fine when served from a domain.. just the local file system.. and after two days trying everything I'm really out of ideas about what could be causing it!
ANY idea/clues are appreciated 👍

**Comment by mim-Armand** [comment]
When on `file://` protocol, I get the following error which makes me think the json payload is already parsed and it's attempting to parse it again, I'm for sure sending a serialized json string tho, and it doesn't happen when being served from a server:
```
Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at createStore.js:149
    at t (persistStore.js:46)
    at persistStore.js:39
    at l (getStoredState.js:62)
    at getStoredState.js:41
    at Object.getItem (createStore.js:121)
    at getStoredState.js:38
    at Array.forEach (<anonymous>)
    at getStoredState.js:37
```

**Comment by mim-Armand** [comment]
Actually, the localStorage does work in `file://` system in the recent versions of Chrome! So I really don't know what could be causing the problem!
I can easily set and get items in the local storage during different sessions manually and it behaves exactly the same as it would otherwise (Except perhaps it is not as secure) but Redux-Persist behaves differently depending on the `location.origin`!
Any idea why this is happening? :/

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
