### ISSUE TITLE
store.getState() calls cause  undefined is not an object (evaluating '_AppNavigator.AppNavigator.router')

### ISSUE THREAD

**Issue by bm-software** [rt2zz/redux-persist#400]
Hi, I'm trying to get a state value from a function. The function is:

    export const fetchApi = (endPoint, payload = {}, method = 'get', headers = {}): Promise<any> => {
    	const accessToken: string = store.getState().auth.access_token // authSelectors.getAccessToken(store.getState())
    	return fetch(`${apiConfig.url}${endPoint}`, {
    		headers: _.pickBy({
    			...(accessToken ? {
    				Authorization: `Bearer ${accessToken}`
    			} : {
    				'Client-ID': apiConfig.clientId
    			}),
    			...headers
    		}, item => !_.isEmpty(item))
    	})[method.toLowerCase()](payload)
    	.then((response: Response) => response.json())
    	.catch((e) => {
    		if (e.response && e.response.json) {
    			e.response.json().then((json) => {
    				if (json) throw json
    				throw e
    			})
    		} else {
    			throw e
    		}
    	})
    }

This code, in particular this line:

    const accessToken: string = store.getState().auth.access_token

cause this execption:

    undefined is not an object (evaluating '_AppNavigator.AppNavigator.router')

If I remove the `getState()` call everything works fine.
I've imported the state with:

    import store from '../state/store'

and the store is implemented in a separate file as follows:

    const store: Store<AppState> = configureStore()
    
    function configureStore(initialState?: any) {
        const enhancer = compose(
            applyMiddleware(
    		      thunk
            ),
            autoRehydrate({log: env.isDebug})
        )
        return createStore(AppReducer, initialState, enhancer)
    }
    
    const stateTransform = createTransform(
        // transform state coming from redux on its way to being serialized and stored
        // tslint:disable-next-line:no-empty
        (inboundState, key) => { return inboundState },
        // transform state coming from storage, on its way to be rehydrated into redux
        (outboundState, key) => {
            if (key === 'auth') {
                return mapAuth(outboundState)
            }
            return outboundState as any
        },
        // configuration options
        {}
    )
    
    export const persist = persistStore(store, {
        storage: AsyncStorage,
        transforms: [stateTransform],
        whitelist : ['auth'] // save only auth
    } as any, () => {
        store.dispatch(persistActionCreators.update({ isHydrated: true }))
    })
    
    export default store

Why I can't call `getState()` from my function? Any solution?

**EDIT**
The same issue happens if I call `store.dispatch(..)` method from any Component (excluding the root component)

**Comment by rochapablo** [comment]
No one?

**Comment by isabelleaubron** [comment]
Do you still have the issue ? 
I'm using store.getState() and it's ok for me (redux v3.7.2; redux-persist v5.9.1)
Maybe you have an error in the structure of your store ?

**Comment by bm-software** [comment]
@isabelleaubron I've just tried and now with redux v3.7.2 and redux-persist v4.10.1 (I've not tried v5 yet) it works without problems. Maybe updating redux solves the problem.
Thank you
