### ISSUE TITLE
createTransform  in v5?

### ISSUE THREAD

**Issue by dwelch2344** [rt2zz/redux-persist#401]
Digging through the docs trying to get a working v5 example. Have almost everything I need, except I need to support immutable. Looking through both the old and the new docs, as well as v5 code, I see there's a `createTransform.js` but it's not exported in the library. Should it be? 

Happy to submit a PR. Just need to know what will be accepted

**Comment by rt2zz** [comment]
yes this was an oversight on my part, it should be exported. The transform api has not changed at all so it should continue to work as before once exported.

As discussed on twitter I am still hesitant to implement top level immutable support until the api is finalized.

**Comment by dwelch2344** [comment]
Gotcha. Yeah, we got our implementation working with immutable, but it takes considerable babysitting so we've scrapped it. Thanks for feedback

**Comment by rt2zz** [comment]
can you clarify what babysitting was required? redux-persist-transform-immutable *should* be compatible with v5 now that I added the createTransform export.
