### ISSUE TITLE
persistStore's callback state is different than store.getState()

### ISSUE THREAD

**Issue by dharik** [rt2zz/redux-persist#404]
My init function runs each time my react native app is launched.  On first launch, this parameter is an empty object. However, I was expecting all of the default values as declared in my reducer.  What's the intended/recommended way to use that 'state' parameter? 

```
import init from '../init';
...
persistStore(AppStore, { storage: AsyncStorage }, init);
```

```
// init.js
export default (err, state) => {
  // state from function param is an empty object on first launch

  // But state from store.getState() has the default values from my reducer
  stateFromStore = AppStore.getState();
  ...
}
```

**Comment by kormang** [comment]
Seems that callback's state is plain state from storage, and on first run there is nothing in storage. Store's state is then initialized with initial state for each reducer. So if it works for you consider that it is first run if state is empty. If it does not work for your use case, then use Stare's state in callback or somewhere later if possible.

**Comment by kormang** [comment]
However, I think this should at least be mentioned in the docs if not fixed otherwise.

**Comment by rt2zz** [comment]
ya this is a bit confusing and should be documented. in v5 the callback does not receive any arguments so it will no longer be an issue. In v5 you will either call `store.getState()` if needed or if you need the intermediary state you can implement a migration.

**Comment by kormang** [comment]
Thanks for telling me, I'm on my way to change my code to make it future proof :D

**Comment by dharik** [comment]
Thanks!

**Comment by laihoit** [comment]
Pls help me, i get similar issue but i don't know fix way.
