### ISSUE TITLE
[QUESTION] ReactNative and rehydration

### ISSUE THREAD

**Issue by joshhornby** [rt2zz/redux-persist#407]
Hi,

The chances are this isn't a bug and most likely user error on my behalf, but redux persist doesn't seem to be saving the state to `AsyncStorage` on react native.

I have included a example repo highlighting this issue: https://github.com/joshhornby/redux-persist-example

If my understanding is correct then when I fire my [test action](https://github.com/joshhornby/redux-persist-example/blob/master/Test.js#L7) next time I load the app the [store should have this value](https://github.com/joshhornby/redux-persist-example/blob/master/App.js#L28). But in my case the store is empty.

Am I missing something? For completeness I have also included my code below:

```
const store = compose(autoRehydrate())(createStore)(reducer);

export default class App extends React.Component {
  constructor() {
    super();
    this.state = { rehydrated: false };
  }

  componentWillMount() {
    persistStore(store, { storage: AsyncStorage }, () => {
      this.setState({ rehydrated: true });
      console.log(store.getState());
    });
  }

  render() {
    return (
      <Provider store={store}>
        <Test />
      </Provider>
    );
  }
}
```

**Comment by abi** [comment]
Hey @joshhornby I spent a bit of time struggling with this today. What you probably need to do is add a `REHYRDATE` action to your reducer. Check this out: https://github.com/brentvatne/chain-react-conf/blob/6175110aa2c0a4e819f1ac2d05c066fba3a297ff/state/Store.js

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
