### ISSUE TITLE
Error restoring data for key:todoList [ReferenceError: localStorage is not defined]

### ISSUE THREAD

**Issue by jinaymehta25** [rt2zz/redux-persist#41]
I am seeing this error in console and most probably that's happening on the node server side (isomorphic app). Is there a way to handle this?

**Comment by rt2zz** [comment]
yes this is a relatively easy fix

question though: how do you expect redux-persist to work on the server? are you expecting a noop?

**Comment by zalmoxisus** [comment]
Unless you do not store states in something like Redis, you don't need  Redux Persist on the server side. A solution could be to move store persisting in a separate module and import it only on the client side or to have 2 different logic depending on the side. Like [here](https://github.com/zalmoxisus/browser-redux/blob/edda20127424b9bae503022bfe498ee5c9538bb9/src/app/store/configureStore.js#L8).

**Comment by jinaymehta25** [comment]
@rt2zz : Yes something like noop. @zalmoxisus: I saw your solution, exactly how do you decide where is the app running?

**Comment by zalmoxisus** [comment]
In that example, I just add the environment flag to the second parameter of `configureStore`, but in case of an universal ("isomorphic") app it's even easier, you may just use, for example, `process.env.isServer`. Using it as a noop wouldn't be a good solution as `redux-persist` tries to persist new state on every action.

**Comment by rt2zz** [comment]
just released 1.4.4

no localStorage now `console.error`s with a useful message. In production it is a noop.

@zalmoxisus I do not think `process.env.isServer` is defined in most node environments. AFAIK the tyipical albeit indirect way to check if in node is https://gist.github.com/rt2zz/ac9eb396793f95ff3c3b

**Comment by jinaymehta25** [comment]
thanks @rt2zz and @zalmoxisus !!
