### ISSUE TITLE
waiting for rehydration leads to error using react-snapshot

### ISSUE THREAD

**Issue by jasan-s** [rt2zz/redux-persist#411]
I'm trying to use redux-persist with[ react-snapshot ](https://github.com/geelen/react-snapshot) however, since i'm waiting for state value to rehydrate to render the App component.  However this leads to null from the react-snapshot . any suggestions.

**Comment by rt2zz** [comment]
I am not familiar with react-snapshot but it sounds like there are two options:
1. use react-snapshot snapshotDelay option, maybe 500ms would be more than sufficient.
2. use redux-persist [getStoredState](https://github.com/rt2zz/redux-persist#getstoredstate--createpersistor) api, and do not call render until store is created

**Comment by jasan-s** [comment]
I will have give getStoredState a try because currently I'm doing the following: 
```    
 render () {
       if (!this.state.rehydrated) {
         return <Loading />
       }
       return (
        <div>
       <App />
       </div>
      )
     }
```
And with a snapshotDelay of  1200 The html static markup contains only the Loading component not the main App component.

**Comment by jasan-s** [comment]
Tried using getStoredState getting error: `Cannot read property 'dispatch' of undefined`.  I'm passing the persistorState to the Redux Provider instead of original store state. like so:

```
export const persistedStore = getStoredState(persistConfig, (err, restoredState) => {
  // // Add the reducer to your store on the `router` key
  // // Also apply our middleware for navigating
  const store = createStore(
  rootReducer,
  restoredState,
  compose(migration, applyMiddleware(reduxThunk, historyMiddleware),
  window.devToolsExtension && process.env.NODE_ENV !== 'production' ? window.devToolsExtension() : f => f))

  const persistor = createPersistor(store, persistConfig)
  return persistor
})

```

**Comment by rt2zz** [comment]
the fact that a snapshot delay of 1200 does not resolve the issue leads me to believe something else is blocking the resolution. How did action buffer solve the problem?

**Comment by jasan-s** [comment]
I was initially conditionally rendering the App post rehydration, removing the conditional and rendering the App right away solved it.

**Comment by jasan-s** [comment]
I was mistaken , the issue was never solved. Action buffer just buffers the action , the app still renders before rehydration is complete.  I am not sure why snapshot delay is not working.

**Comment by jasan-s** [comment]
I now am using async store render like so:

```
async function init() {
  const store = await configureStore()
  snapshotRender( 
  <Provider store={store}>
    {/* ConnectedRouter will use the store from Provider automatically */}
    <ConnectedRouter history={history}>
      <App />
    </ConnectedRouter>
  </Provider>,
  document.getElementById('root')
)
}
init()
registerServiceWorker()
```
I dont think this isn't `redux-persist` related but I now keep getting the following error I posted this on [Stackoverflow ](https://stackoverflow.com/questions/46385860/)and react-snapshot [issue ](https://github.com/geelen/react-snapshot/issues/68)but been nearly a month yet no reply: 
`'render' from react-snapshot was never called. Did you replace the call to ReactDOM.render()?`

**Comment by rt2zz** [comment]
:/ im not familiar with react-snapshot, sorry not much help here. If anyone else has experience related to this please weigh in.

**Comment by jasan-s** [comment]
I switched to using [react-snap](https://github.com/stereobooster/react-snap) for prerendering and it works with it.

**Comment by piotr-cz** [comment]
@jasan-s 
I'm having exactly same issue with [react-snap](https://github.com/stereobooster/react-snap): The PersistGate is stuck at loading and never renders it's child
