### ISSUE TITLE
2 strange issues on Android SDK 23 with RN 0.47

### ISSUE THREAD

**Issue by pongponglau** [rt2zz/redux-persist#420]
I use Android SDK 23 and RN 0.47 in my project. I use redux, redux saga and redux perist. In iOS, this combination works perfectly. However, in Android, there are 2 strange problems found.

1) fetch does not return any promise
2) componentDidMount of a component is called repeatedly.

The above issues 1 and 2 do not occur when the app is run just after the installation. They happen after i reload the app, or force kill the app and start it again.

However, after i disable redux-persist (in other words, just run redux with redux-saga), these 2 issues are gone even i reload the app. Do you have any ideas why these strange issues happen?

Thank you very much

**Comment by rt2zz** [comment]
do you have a global error handler set up or any other special configuration? its possible an error is throwing and causing the app to reload. 

On way to debug is to put a breakpoint in redux-persist/lib/persistStore.js at https://github.com/rt2zz/redux-persist/blob/master/src/persistStore.js#L32 and step through to see if the rehydration completes without error.

FWIW I have never heard of this behavior before, definitely strange.

**Comment by pongponglau** [comment]
@rt2zz, thank you for your advice.

I have tried to debug your said function and the chrome debugger does not catch any exception (i.e. pause on caught exceptions). Does it mean that there is no error?

I have copied the following stack trace for your reference which happens repeatedly and repeatedly, ended up in the repeated call of componentDidMount of my home component. May i ask if you have any idea for that? Or what else i can check?

One more info, i am using Android 6 with SDK 23 with React Native 0.47.1. Due to permission issue of Android 6?

Thank you very much.

componentDidMount (Home.js:280)
(anonymous) (ReactNativeStack-dev.js:1658)
measureLifeCyclePerf (ReactNativeStack-dev.js:1610)
(anonymous) (ReactNativeStack-dev.js:1657)
CallbackQueue.notifyAll (ReactNativeStack-dev.js:2121)
close (ReactNativeStack-dev.js:2138)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
perform (ReactNativeStack-dev.js:1382)
perform (ReactNativeStack-dev.js:1451)
flushBatchedUpdates (ReactNativeStack-dev.js:1476)
close (ReactNativeStack-dev.js:1434)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
perform (ReactNativeStack-dev.js:1451)
flushBatchedUpdates (ReactNativeStack-dev.js:1476)
close (ReactNativeStack-dev.js:1434)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
perform (ReactNativeStack-dev.js:1451)
flushBatchedUpdates (ReactNativeStack-dev.js:1476)
close (ReactNativeStack-dev.js:1434)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
perform (ReactNativeStack-dev.js:1451)
flushBatchedUpdates (ReactNativeStack-dev.js:1476)
close (ReactNativeStack-dev.js:1434)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
perform (ReactNativeStack-dev.js:1451)
flushBatchedUpdates (ReactNativeStack-dev.js:1476)
close (ReactNativeStack-dev.js:1434)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
perform (ReactNativeStack-dev.js:1451)
flushBatchedUpdates (ReactNativeStack-dev.js:1476)
close (ReactNativeStack-dev.js:1434)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
perform (ReactNativeStack-dev.js:1451)
flushBatchedUpdates (ReactNativeStack-dev.js:1476)
close (ReactNativeStack-dev.js:1434)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
perform (ReactNativeStack-dev.js:1451)
flushBatchedUpdates (ReactNativeStack-dev.js:1476)
close (ReactNativeStack-dev.js:1434)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
perform (ReactNativeStack-dev.js:1451)
flushBatchedUpdates (ReactNativeStack-dev.js:1476)
close (ReactNativeStack-dev.js:1434)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
perform (ReactNativeStack-dev.js:1451)
flushBatchedUpdates (ReactNativeStack-dev.js:1476)
close (ReactNativeStack-dev.js:1434)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
perform (ReactNativeStack-dev.js:1451)
flushBatchedUpdates (ReactNativeStack-dev.js:1476)
close (ReactNativeStack-dev.js:1434)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
perform (ReactNativeStack-dev.js:1451)
flushBatchedUpdates (ReactNativeStack-dev.js:1476)
close (ReactNativeStack-dev.js:1434)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
perform (ReactNativeStack-dev.js:1451)
flushBatchedUpdates (ReactNativeStack-dev.js:1476)
closeAll (ReactNativeStack-dev.js:1412)
perform (ReactNativeStack-dev.js:1388)
batchedUpdates (ReactNativeStack-dev.js:2077)
enqueueUpdate$1 (ReactNativeStack-dev.js:1481)
enqueueUpdate (ReactNativeStack-dev.js:1510)
enqueueSetState (ReactNativeStack-dev.js:1556)
ReactComponent.setState (react.development.js:167)
onStateChange (connectAdvanced.js:222)
dispatch (createStore.js:186)
(anonymous) (middleware.js:72)
(anonymous) (persistStore.js:55)
complete (getStoredState.js:73)
(anonymous) (getStoredState.js:52)
(anonymous) (AsyncStorage.js:86)
__invokeCallback (MessageQueue.js:307)
(anonymous) (MessageQueue.js:120)
__guard (MessageQueue.js:231)
invokeCallbackAndReturnFlushedQueue (MessageQueue.js:119)
(anonymous) (debuggerWorker.js:72)

**Comment by rt2zz** [comment]
sounds like a bug in `componentDidMount (Home.js:280)`, can you paste the code in Home.js here?

Perhaps try commenting out componentDidMount and see if the issues goes away? If so we know its definitely a bad interaction there and hopefully that will help narrow it down.

**Comment by pongponglau** [comment]
I have the same problem even with the following componentDidMount in Home.js.

componentDidMount() {
console.log('home componentdidmount called')
 }

Thank you for your advice

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
