### ISSUE TITLE
Async transforms

### ISSUE THREAD

**Issue by Noitidart** [rt2zz/redux-persist#426]
Was it thought of to support async transforms in v5? Was there reasons against it?

**Comment by rt2zz** [comment]
right the closest thing we have right now is `config.migrate` which allows for async transformation of state as it is being restored. No way to do async on the way to serialization atm.

Mainly concerned with performance and code size. We may reconsider its inclusion again in the future but I think it would be too risky at the moment.

**Comment by aguynamedben** [comment]
Tracking in this issue: https://github.com/rt2zz/redux-persist/issues/303
and this PR: https://github.com/rt2zz/redux-persist/pull/360

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
