### ISSUE TITLE
[v5] Flow doesn't support number as key for MigrationManifest

### ISSUE THREAD

**Issue by leethree** [rt2zz/redux-persist#433]
MigrationManifest has number as object keys, but Flow doesn't support it.
```js
export type MigrationManifest = {
  [number]: (PersistedState) => PersistedState,
}

const migrations = {
  0: (state) => ({}),
};

(migrations: MigrationManifest);
```

Flow error:
```
18:  0: (state) => ({}),
     ^ non-string literal property keys not supported
```

See:
https://flow.org/try/#0PTAEAEDMBsHsHcBQyCmAPADrATgF1LgJ4YqgAKK2AzgJZW4DKuAhrqQLygDeiooAbpVqwAdgC5QIgK4BbAEaUANL1DYUAC0IATbKxRaJc2LGgpmI5QF9UmHPiIlyQumy1M9oTjz4B9EtRcJCgD6dzYrUAAfAVgaLRssPAJiUgBZGgBzXVwaUVTzGkgUek9uFQBtaXlKAF0JAApg2np9MJQASk8APicQ1zarZABjURKZTOzckSpSngBIAAYG+j1O9h76rkt2qwBuZHrxrNYpqgl045y8gqL6dv2gA

**Comment by rt2zz** [comment]
@leethree ya this is unfortunate, we should really be using Map here, which we could perhaps do with object to map conversion as a fallback:
```js
const migrations = new Map([
  [1, () => {}]
])
```

What I would recommend in the meantime is to make your keys strings like so:
```js
const migrations = {
  '0': (state) => ({}),
};
```

Let me know if you have opinions about the api / using Map instead.

**Comment by leethree** [comment]
Using string keys would still cause Flow error. The only workaround I found without using `Map` is to use computed keys like:
```js
const migrations = {
  [0]: (state) => ({}),
};
```

But it will trigger ESlint error [`no-useless-computed-key`](https://eslint.org/docs/rules/no-useless-computed-key).

I guess I'll go with Map if it makes both ESlint and Flow happy.

**Comment by rt2zz** [comment]
@leethree Map is not yet supported, I was suggesting that as a possible api change that redux-persist could make. 

I think we at a minimum need to update the type on MigrationManifest to accept string keys: https://github.com/rt2zz/redux-persist/blob/v5/src/types.js#L37

**Comment by rt2zz** [comment]
@leethree updated to accept string keys in #436 and cut new beta.11 release

lmk if that works

**Comment by leethree** [comment]
Should be working now. Thanks a lot!
