### ISSUE TITLE
Can I upgrade to v5 on an existing app using v4 and keep my data?

### ISSUE THREAD

**Issue by williamoliveira** [rt2zz/redux-persist#434]
I tried it but rehydration comes `undefined`

**Comment by williamoliveira** [comment]
Just checked the storage now, I see the keys are different, everything is under the root key, so is there a easy way to migrate data from v4? or should I just keep on v4?

**Comment by rt2zz** [comment]
there is not currently a way to migrate state from v4 to v5.

I think the way to solve this would be for redux-persist to ship with a pluggable "getStoredState":
```js
import { getStoredState } from 'redux-persist'
import { getStoredStateV4 } from 'redux-persist/lib/integration'

const v4Config = { /* whatever the old config was */ }

const config = {
  key,
  storage,
  getStoredState: async (persistConfig) => {
    let storedState = getStoredState(persistConfig)
    if (!storedState) storedState = getStoredStateV4(v4Config)
    return storedState
  }
}

persistReducer(config, baseReducer)
```

Its not the prettiest api, but the pattern would be generally useful, could be used to move from one storage engine to another for example.

**NOTE** this is not currently possible, we would need to add `getStoredState` option to config for this to work.

**Comment by williamoliveira** [comment]
I dont know how the internals work, is it easy to do? do you plan to implement it?

**Comment by rt2zz** [comment]
the implementation would be trivial, I just would want to take some time first to make sure this is the right api. In abstract I would like to call the config option: "migrate" or something, but unfortunately "migrate" is a loaded word, we already use that for migrating state between app state versions.

**Comment by rt2zz** [comment]
I just took a first stab at it: https://github.com/rt2zz/redux-persist/tree/v5#experimental-v4-to-v5-state-migration

I have not run this code at all so it likely requires some tweaking, but it should be generally a good approach.

**Comment by kelset** [comment]
Hi folks, can I revive this issue by asking if there is any update on how to migrate?

Because it looks like the migration guide that was present in the README and linked by @rt2zz earlier is now 404 😅

**Comment by levsero** [comment]
@kelset https://github.com/rt2zz/redux-persist/blob/master/docs/MigrationGuide-v5.md

**Comment by levsero** [comment]
@aguynamedben yep all worked as expected once the fix was in.

**Comment by JennieJi** [comment]
A one time dirty hack here for using persistStore with whitelist only config:

```javascript
const v5StorageKey = `persist:${PERSIST_CONFIG.key}`;
if (!localStorage.getItem(v5StorageKey)) {
  const v4StoredState = {};
  PERSIST_CONFIG.whitelist.forEach(key => {
    v4StoredState[key] = localStorage.getItem(`reduxPersist:${key}`);
  });
  localStorage.setItem(v5StorageKey, JSON.stringify(v4StoredState));
}
``` 

Blacklist can hack with similar stuff. 
After few weeks, should be able to remove this piece of code.
Doing this is because the official migration guide is setting `getStoredState` in `persistReducer`, but my project does not have reducer level configurations and I don't want to touch that one by one.
