### ISSUE TITLE
[v5] Store no longer persists after purge

### ISSUE THREAD

**Issue by leethree** [rt2zz/redux-persist#435]
Steps:
- store something and persists
- `persistor.purge()`
- modify reducers.

Expected:
New changes are persisted. Restart the app the store should rehydrate normally.

Actual:
Store no longer persists to storage. Restart the app and the stored data is gone.

**Comment by rt2zz** [comment]
I just tested it and it works as expected (new changes after the purge are persisted). Are you on web or native?

**Comment by leethree** [comment]
I'm using it on native. I think I found the problem. I'm using `persistReducer` on sub reducers, and I need to clear the entire store when the user logged out. 

When the root reducer is cleared, the `_persist` keys in the sub reducers are cleared too. And the persistReducer function will refuse to persist store when `_persist` is missing. ([persistReducer.js line 121](https://github.com/rt2zz/redux-persist/blob/v5/src/persistReducer.js#L121))

Should the reducer reconstruct the `_persist` key when it's reset? Or is there any suggested way to handle this use case? Thanks!

**Comment by leethree** [comment]
I solved the issue by calling `persistStore()` again after the entire store is cleared (`_persist` is missing). Here's my code:
```js
async () => {
  // this action will clear everything in the store
  store.dispatch(storeReset());
  // purge persisted data
  persistor.purge();
  // re-persist store
  await new Promise(resolve => persistStore(store, {}, resolve));
};
```
But the `purge` function is no longer async, which might cause issue in `persistStore` because the purge might still in progress. I'll open another issue for that.

**Comment by laksh1010** [comment]
hi can i know how u defined `storeReset ` at `    store.dispatch(storeReset()); `

**Comment by leethree** [comment]
@laksh1010 you can use something like [redux-reset](https://github.com/wwayne/redux-reset) or implement your own.

**Comment by skoob13** [comment]
One more solution is to call `persistor.persist()` after purging.

**Comment by lolz42** [comment]
> One more solution is to call `persistor.persist()` after purging.

Also for people who are using redux-reset don't forget that .persist() is async action and that you need to wait for a response before you reset your redux.
