### ISSUE TITLE
Consider using less ambiguous terms when describing transforms

### ISSUE THREAD

**Issue by abonander** [rt2zz/redux-persist#437]
I got caught out yesterday by assuming the "inbound" transform was for going from storage -> redux state, and the "outbound" transform was for going from redux -> storage. The terminology is rather ambiguous, because it could mean going out from the Redux store to disk, or out from storage into the Redux store, and vice versa.

Maybe consider using "serialize" and "deserialize" instead, since transforms will usually be used to flatten complex datastructures to simpler ones or reinflate said datastructures from the serialized layout.

Or to be completely unambiguous, how about "toStorage" and "fromStorage"?

**Comment by rt2zz** [comment]
agreed it is ambiguous. Serialize I dont like because transforms may do other things.

What if we just make it clearly ambiguous and rely on the comment to guide people?
```js
let myTransform = createTransform(
  // transform state coming from redux on its way to being serialized and stored
  (state, key) => specialSerialize(inboundState, key),
  // transform state coming from storage, on its way to be rehydrated into redux
  (state, key) => specialDeserialize(storedState, key),
  // configuration options
  {whitelist: ['specialKey']}
)
```

Open to other suggestions

**Comment by abonander** [comment]
Sure, that's already in the README (which I'm sure you're alluding to), but if someone hits goto-definition or quick-documentation in their IDE, there's no documentation or comments to speak of. So if you're happy with the terminology, maybe just document it in the source.

**Comment by rrichardson** [comment]
My preferred bikeshed paint: 
 I think that the variables should indicate that they're state, but in different forms.. one is the live, and in mem state, and the other is persisted. 

```javascript
  (liveState, key) => specialSerialize(liveState, key),
  (persistedState, key) => specialDeserialize(persistedState, key),
```

the source vars should be something like : 
```
function createTransform (serializeFn, deserializeFn, config = {})
```

or if you don't like serialize/deserialize .. 

```
function createTransform (toStorageFn, fromStorageFn, config = {})
```

If we all like a set of words for the readme and source docs and params I am happy to put in a PR.

**Comment by rt2zz** [comment]
gotcha, ya good idea. Right from the docs all I swapped was inboundState -> state

Couple other options might be `preTransformState / postTransformState` or changed createTransform to take an object of the shape `{ applyTransform, unapplyTransform, config }`

For now I will simply add comments to source 👍

**Comment by aguynamedben** [comment]
Looks like this was done here: https://github.com/rt2zz/redux-persist/commit/867317cf0a4a19cd8a51b8048589c893d18a9fa2
