### ISSUE TITLE
Working with react-native 0.16

### ISSUE THREAD

**Issue by af** [rt2zz/redux-persist#44]
React Native 0.16 upgraded to Babel 6, which chokes on `redux-persist`'s `.babelrc` file (I think because it uses the `stage` field). You can see how `react-redux` [dealt with that change](https://github.com/rackt/react-redux/commit/975a9030a880a2e59f7843ed54134ee840f87ce9), basically it looks like you just don't want to ship a `.babelrc` as part of the published package. I think that's the only change needed, let me know if you want any more diagnostic info.

**Comment by rt2zz** [comment]
thanks, just release 1.4.10 with analogous changes

**Comment by af** [comment]
Super fast, thanks!
