### ISSUE TITLE
Clear AsyncStorage cache upon uninstall the application

### ISSUE THREAD

**Issue by luqmanrom** [rt2zz/redux-persist#441]
I am persisting my redux data using this package, and I realised upon uninstall, it won't clear the data. After I uninstall it, and install it again, it will still have the old data. 

How can I clear the data upon uninstall?

**Comment by rt2zz** [comment]
are you referring to uninstalling your app or uninstalling redux-persist?

The former I believe will reset state.

**Comment by luqmanrom** [comment]
Oh sorry. I mean uninstalling the application. Updated to avoid confusion

**Comment by rt2zz** [comment]
this might be relevant: https://stackoverflow.com/a/44065166

I am not certain under what scenarios it will be cleared vs kept, please post back if you figure out the conditions.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.

**Comment by afizboltz** [comment]
i believe this  https://stackoverflow.com/a/44065166 only works on android..  how about iOS ? can we clear the data upon uninstall?

> this might be relevant: https://stackoverflow.com/a/44065166
> 
> I am not certain under what scenarios it will be cleared vs kept, please post back if you figure out the conditions.

**Comment by Biplovkumar** [comment]
Please suggest the solution!

**Comment by Biplovkumar** [comment]
Please reopen this case.

**Comment by sLurPPPeRsTaR** [comment]
hey i have problem with IOS but not in Android, open this case
this only relevant for android : https://stackoverflow.com/a/44065166
not IOS
