### ISSUE TITLE
processSpecial is not defined

### ISSUE THREAD

**Issue by zacharybrady** [rt2zz/redux-persist#442]
I've gotten this error in two different projects related to using the REHYDRATE action type in my reducers. I've used redux-persist in previous projects without this issue.

`redux-logger.js:1 Uncaught ReferenceError: processSpecial is not defined`

Error is related to code like this:

`case REHYDRATE:
      var incoming = action.payload.user
      if (incoming) return {...state, ...incoming, userData: processSpecial(incoming.userData)}
      return state`

Inside a reducer.

While this code is identical to the documentation I cannot:

1. Find any documentation on when processSpecial is or should be
2. Find processSpecial anywhere in the code of the library
3. Find any documentation on how to create processSpecial which seems to be crucial in extracting parts of a reducer
4. Find anyone else having this issue on the web

Again, seeing this in 2 projects using the most recent version of redux-persist

**Comment by rt2zz** [comment]
the code
```js
case REHYDRATE: var incoming = action.payload.user if (incoming) return {...state, ...incoming, userData: processSpecial(incoming.userData)} return state
```
is sample code from the docs. You should not need to copy it verbatim into your code base. In fact in most cases you should not need to add `case REHYDRATE` to your reducer at all. I would recommend removing that code.

**Comment by zacharybrady** [comment]
I don't particularly want to use authRehydrate() ( which does work of course ). So if I do want to rehydrate specific reducers how would I do that?

**Comment by rt2zz** [comment]
got it, then ya you will want something custom. e.g. to get *all* state for the given reducer:
```
// yourReducer.js
case REHYDRATE: 
  return { ...state, ...action.payload.yourReducer }
```

you can implement whatever custom code you want in here to conditionally restore bits and pieces of your state

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.
