### ISSUE TITLE
Problem with PersistStore whitelist

### ISSUE THREAD

**Issue by ArthurBugan** [rt2zz/redux-persist#444]
Hi, I was trying to make only one reducer persist like in my code below:

`  persistStore(store, {whitelist: ['login']});`

But all my reducers keep persisting,how I am suppose to make the whitelist to work? Thank you in advance!

**Comment by rt2zz** [comment]
Are you using v4 of v5?

**Comment by ArthurBugan** [comment]
^4.8.3

**Comment by nolan-m** [comment]
Also having this problem on 4.9.1

**Comment by ArthurBugan** [comment]
+1

**Comment by burrack** [comment]
+1 basically, right now it seems like only top level redux store keys can be treated by whitelist

**Comment by rt2zz** [comment]
@burrack that is correct, whitelist will only work on top level keys. so e.g. of the state has shape:
```js
{
  login: loginState,
  otherThing: otherThingState,
}
```
adding whitelist: ['login'] will cause only login to be persisted, not otherThing

**Comment by Elena2016** [comment]
+1 the same issue is in 5.4.3

**Comment by rt2zz** [comment]
@Elena2016 what issue are you having? whitelist should work, make sure you have it applied to the persistConfig, **not** passed to persist store

**Comment by Elena2016** [comment]
Zack, thank you very much for your help!
Would you mind to take a look at this code and suggest what I'm doing wrong?

persistStore(store, { storage: AsyncStorage, whitelist: ['something'] });

Errors:
1. redux-persist: invalid option passed to persistStore: "whitelist". You may be incorrectly passing persistConfig into persistStore, whereas it should be passed into persistReducer.

2. redux-persist: invalid option passed to persistStore: "storage". You may be incorrectly passing persistConfig into persistStore, whereas it should be passed into persistReducer.
- node_modules/redux-persist/lib/persistStore.js:50:38 in <unknown>
- node_modules/redux-persist/lib/persistStore.js:49:23 in persistStore

**Comment by dchersey** [comment]
I am also having this issue: 
```javascript
const channelPersistConfig = {
  key: 'channel',
  storage,
  stateReconciler: autoMergeLevel1,
  blacklist: ['messages']
}

const metaPersistConfig = {
  key: 'meta',
  storage,
  stateReconciler: autoMergeLevel1,
  whitelist: ['channel']
}

const channelReducer = persistCombineReducers(channelPersistConfig, {
  messages: messagesReducer,
  meta: persistReducer(metaPersistConfig, metaReducer)})

export default channelReducer;
```
is my reducer, combined into my rootReducer using 
```javascript
const rootPersistConfig = {
  key: 'root',
  storage,
  stateReconciler: autoMergeLevel1
};

const reducers = {
  auth,
  nav: navReducer,
  channel: channelReducer
};
const rootReducer = persistCombineReducers(rootPersistConfig, reducers);
```
Despite the white/black list nested configs, the entire state is persisted from all reducers, as I can see by inspecting action.payload in my 'persist/REHYDRATE' state listener.

Am I using this correctly?

**Comment by burrack** [comment]
@dchersey - where is 'persistCombineReducers' function coming from ?

**Comment by dchersey** [comment]
I'm following the docs in the [Migration guide](https://github.com/rt2zz/redux-persist/blob/master/docs/MigrationGuide-v5.md) that say to 
```
replace combineReducers with persistCombineReducers
e.g. let reducer = persistCombineReducers(config, reducers)
```
This is inconsistent with the info in the README under nested persists ... but it seemed pretty clear and I thought it would supercede it. But that is confusing ... maybe it should go back to `combineReducers`?

**Comment by assyme** [comment]
@dchersey , I am trying to do something similar with having a combination of whitelist and blacklist to cherry pick what I want to persist in redux. Have you managed to solve this? Any leads for me (and anyone who land up here).

**Comment by luongs3** [comment]
2019, and still got this issue....
any solutions here?

**Comment by v2lrf** [comment]
2019, and still got this issue.... too

**Comment by ladifire** [comment]
2020, and still got this issue.... too

**Comment by ladifire** [comment]
maybe 2021 still got this issue.... too

**Comment by zlanich** [comment]
Still an issue. Why is there no motion on this?

**Comment by gfaraj** [comment]
I seem to be having this same issue. Anyone figure it out yet?

**Comment by JRyuzaki** [comment]
Please any insight on this issue? Has anyone resolved this?

**Comment by imanolpg** [comment]
2022, and still got this issue.... too

**Comment by seliverstovv** [comment]
I've made an addition for nested reducers but still getting state saved to localstorage. I will be glad for any help.
Tried using persistCombineReducers but the result is the same

Code example in sandbox:
https://codesandbox.io/s/dazzling-river-ni6fe5?file=/src/store.js

**Comment by karanbht007** [comment]
This issue still persists. Why was it closed without a fix?

**Comment by jcdk** [comment]
For anyone running into this issue, I found the whitelist to work once I passed a combinedReducer array to the persistReducer function.

```
const persistConfig = {
  key: 'root',
  storage,
  whitelist: ['cart'], // only cart will be persisted
};

const rootReducer = combineReducers({
  cart: cartReducer,
});

const persistedReducer = persistReducer(persistConfig, rootReducer);

export const store = configureStore({
  reducer: persistedReducer,
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware({
      serializableCheck: false,
    }),
});
```
