### ISSUE TITLE
[v5] Purge asynchonously?

### ISSUE THREAD

**Issue by leethree** [rt2zz/redux-persist#447]
In redux-persist v4, the `purge` function is async, so we could do something after purge is finished:
```js
  await persistor.purge();
  // dispatch "store ready" action
  store.dispatch(storeReady());
```

But it's different in v5 because `persistor.purge()` no longer returns a promise. The persisted file is in an indeterministic state if we want to read from it (e.g. to restart persisting such as in #435).

**Comment by rt2zz** [comment]
I am leaning towards registering purge when the reducer first sets up so that we can await the promises. Should be a relatively small and safe refactor

**Comment by rt2zz** [comment]
ok this just landed in `5.0.0-beta.13`

persistor.purge() now returns a promise that will resolve once all persisted reducers declare purge complete. 

Thanks for discussion 👍

**Comment by rt2zz** [comment]
also please test and LMK if it works as expected.

**Comment by leethree** [comment]
Awesome! thanks a lot!

**Comment by leethree** [comment]
Hi @rt2zz , I just upgraded to `5.0.0-beta.13` but I'm not seeing the async purge changes in the package. Are the new changes published to NPM?

**Comment by rt2zz** [comment]
The code is there: https://github.com/rt2zz/redux-persist/blob/v5/src/persistStore.js#L74 that said, I wrote a test for flush but not purge (https://github.com/rt2zz/redux-persist/blob/v5/tests/flush.spec.js). I think the next step is to write a test for this.

**Comment by leethree** [comment]
@rt2zz just tested out 5.0.0-rc.2 in out project. Async `purge` works great! 

Besides, `flush` is very useful for making sure data is cleared when user logs out. Thanks a lot!
