### ISSUE TITLE
Question on v5 performance - serialize/deserialize whole store on each change

### ISSUE THREAD

**Issue by Noitidart** [rt2zz/redux-persist#449]
Hi there is v5 really more performant then v4? It seems to serialize and deserialize the whole store on every change. v4 would only serialize/deserialize the key that got changed. I am sure from the learning you have found this is more performant, but may you please explain how it is so? This question just keeps looming in my head and I can't answer for it weeks so finally asked. :(

**Comment by rt2zz** [comment]
v5 is a bit more complicated, roughly the flow looks like this:
  

1. serialize each piece of substate so the working state looks like this:
```js
{
  foo: serializedFoo,
  bar: serailizedBar,
}
```  

2. once all substates are serialized, serialize the entire thing and write to disk. in pseudo code:
```js
let final = serialize(workingState)
storage.set(key, final)
```
In this case we have already serialized all substates so workingState is simply an object of strings for which serialization is super fast.  

3. foo changes, redux-persist detects this and re-serializes *only* foo, and then again proceeds to step 2.


So All in all it is pretty performant for most use cases. The one additional cost as compared to v4 is that we set the entire serialized state into storage all at once. In my observation serialization is much more costly than storage sets. Additionally this choice was made for two reasons:
1. now we can guarantee consistent state.
2. its easier to coordinate the single state write to happen in idle time than it was to coordinate lots of little writes.

**Comment by Noitidart** [comment]
Ah very interesting! So if the key didn't change, that thing is not re-serialized. Thanks sir very much for putting up with me and my questions in your issues topic! And leaving this open for me to close, much respect!

**Comment by rt2zz** [comment]
Also I should note::
1. you can add `throttle` to the persistReducer config to force a delay between the serialization of each sub state
2. in v5 one can apply persistReducer to each sub-reducer rather than the root. This allows for more control over state (e.g. a large throttle on one and not antoher). 

Redux persist strives to be both performant and consistent out of the box. Of course this still needs to be tuned per the specific needs of each app and there may be special cases where the defaults are not ideal. FWIW in most of my production apps the default set up has been great.

**Comment by Altiano** [comment]
I'm still using v4,
You said, 

> The one additional cost as compared to v4 is that we set the entire serialized state into storage all at once

And from the docs
> Performant out of the box (uses a time iterator and operates on state partials)

First, just want to ask for confirmation that another term of the state partial is substate, right? And in v4, when changes occur in a substate, only that one will be evaluated (persisted) to the storage?

If I have a really big substate, let say one that has array of 50 items, with each item has about 6 KB of characters (JSON.stringified), that state is changing frequently, how can the persistence process still be performant when I have all still data?
Or do you think It is not really a problem if I have that 50 * 6 = 300KB write to disk so frequent?
Is there any recommended limit you would give?

**Comment by Noitidart** [comment]
@Altiano - I had the same situation, where there was many entries of many kb. I had to modify redux-persist v5, I used async transforms.

Whenever it tries to save it, it turns it into an id, and if that id has not yet been written, it writes to disk using `AsyncStroage.set`. Opposite is followed for reading.

**Comment by Altiano** [comment]
@Noitidart Oh I see.. It's a good solution to manually save (edited) individual item in its own key rather than to bundle it all together in a single key of subState.

It is more to programming/engineering concept than the API of this library to make performant persistence process.

**Comment by dancancro** [comment]
If the point of this library is to enable persistence only when a specific value changes and React Effects give you a a place to put code that should run only when a specific value changes, does the introduction of React Effects make this library unnecessary?
