### ISSUE TITLE
ts error v4.10

### ISSUE THREAD

**Issue by nomoreboredom** [rt2zz/redux-persist#458]
Hi, 

I am trying to use redux-persist with react-native-sensitive-info so I want to use SharedPreferences as the storage.

However I am getting the error: 

node_modules/redux-persist/lib/index.d.ts(55,50): error TS2304: Cannot find name 'T'.
node_modules/redux-persist/lib/index.d.ts(108,12): error TS2305: Module '"redux-persist"' has no exported member 'Storage'.

Any idea what may be causing this?

**Comment by pheromonez** [comment]
It looks like the type `Storage` was deleted and replaced with `AsyncStorage`, `WebStorage`, and `LocalForageStorage`. However, a small chunk of code at the bottom of the type definitions still referes to the deleted `Storage` type.

**Comment by actra-gschuster** [comment]
Any idea when the fixed master will be released to NPM?

**Comment by peterdev6** [comment]
+ 1

**Comment by peterdev6** [comment]
+1

**Comment by rt2zz** [comment]
just released 4.10.1 with TS fix
