### ISSUE TITLE
Use case questions

### ISSUE THREAD

**Issue by RichardForrester** [rt2zz/redux-persist#46]
I've been looking into different options for a persistence layer to work with a server-side redux app based on this [full-stack-redux-tutorial](http://teropa.info/blog/2015/09/10/full-stack-redux-tutorial.html) by Tero Parviainen.

After looking into RethinkDB and Redis as options to back up the server side store, I started thinking that all I need to do is to write the current state or a log of the actions to disk so that when the server needs a restart I don't lose the store. Likewise, hydration functionally will be necessary after a restart. Other than that, my server side store can act as a full on substitute for a database. I don't really need anything except to protect against losing the store. So a few Google searches later and I'm here.

At least some of the readme docs suggests this package is for the client side. Would this package also be a substitute for a database on the back end? It sounds like the right idea.

**Comment by rt2zz** [comment]
This is an idea I have pondered, but not yet tried. The short answer is yes, redux-persist could be useful for this. The longer answer depends on how your application works:

**If your state is identical for all users:**
redux-persist should work out of the box, you just need to wrap your database in a [compatible](https://github.com/rt2zz/redux-persist/blob/master/src/defaults/asyncLocalStorage.js) api. Make sure you are not recreating your store on every request, either by making it a singleton or storing a reference to it in your server.

**If your state is different per user:**
You will need to do some extra work to make this work. Off the top of my head, lets assume you have a id for each user that you can parse out of a token or cookie. Using that id you can create a Storage engine per user. Something like:
```js
routeHandler = (request, reply)  => {
  let uid = getUidFromRequest(request)
  let UserStorage = createUserStorage(uid)
  let store = createReduxStore()
  persistState(store, {storage: UserStorage})
  // ...
}

function createUserStorage (uid) {
  return {
    setItem: (key, value, cb) => {
      dbClient.insert({uid: uid, key: key, value: value}, cb)
    },
    getItem: (key, cb) => {
      dbClient.find({uid: uid, key: key}, cb)
    }
  }
}
```
Obviously this leaves much to the imagination and will need to be changed depending on the workings of your database driver, but hopefully the general approach makes sense.

Let me know how that works out for you, I would be happy to support changes needed to make this use case more comfortable.

**Comment by RichardForrester** [comment]
I'm going to give it a shot over the next few weeks. Basically, persistence is the last piece of the puzzle for me and it's all very conceptual right now, but this is a basic overview of how I see it working:

The server-side redux store is the source of truth for all state that needs to be persisted and will be the database for the entire app. The client-side redux stores will contain a subset of what is contained in the server-side store as well as any state specific to that user that does not need to be persisted.

Example:
>The server-side store will contain usernames and hashed passwords for all users, however, an authenticated user's client-side store would not contain information on other users but would contain data specific to the browser state like current route, etc.

When a client makes changes to state that is shared with the server, it will emit a socket.io event which will be handled by server-side redux which will emit an event to all clients updating their state. 

Before The server emits the event to all clients, some persistence mechanism should guard against potential data loss. It could be as simple as a logging all actions into a MongoDB document so that when the server is restarted they could be reduced to pull the server-side store up to it's latest state. This approach would have the benefit of being able to roll back the server-side store to some previous state. The alternative approach would be to keep the server-side state as a MongoDB document which would simply be reloaded in the case of a server crash or restart.

It all seems possible but with many potential hurtles. That tutorial I linked to earlier gets me 90% there so we'll see.

**Comment by rt2zz** [comment]
interesting concept,

You should also give some serious thought to how you would handle deploying updates that require state shape changes. In typical client side redux you just blow out the old state and build it fresh, but if using redux as your source of truth database, you will likely need a well thought out mechanism to migrate state between versions.

redux-persist essentially solves the problem of "after updates how do I store my state as quickly and efficiently as reasonable?". It may or may not be useful for your endeavor. 

A naive data migration strategy could be: version your data, and use [getStoredState](https://github.com/rt2zz/redux-persist#initialstate-rehydration) to get the state and run upgrade scripts prior to rehydration.

**Comment by rt2zz** [comment]
@RichardForrester did you ever figure out a solution? Curious to hear your thoughts and if any modifications were required.

**Comment by rt2zz** [comment]
closing for now, feel free to reopen if still relevant!

**Comment by RichardForrester** [comment]
@rt2zz Ya, I struggled with it for a bit but eventually scratched redux on the server and went RethinkDB + socket.io with Redux on the client. I still think the idea of using redux on the server is interesting, but getting away from a database entirely just turned out to be more change than I can handle.

**Comment by rt2zz** [comment]
Interesting. I love the idea of server side redux in lieu of a db, but you are probably right the tooling will need to develop a lot before that can be a reality.
