### ISSUE TITLE
redux-persist asyncLocalStorage requires a global localStorage object

### ISSUE THREAD

**Issue by harshsrivastavaglobussoft** [rt2zz/redux-persist#463]
import React, { Component } from 'react';
      import {
       AppRegistry,
       StyleSheet,
        Text,
        View,
        AsyncStorage,
        } from 'react-native';
      import {createStore,compose} from 'redux';
      import {Provider} from 'react-redux';
      import AllReducer from './reducers/reducer-index';
      import StackNavigation from './components/navigation';
      import {persistStore, autoRehydrate} from 'redux-persist';

       const store = compose(autoRehydrate())(createStore)(AllReducer)

       if (typeof self === 'object') persistStore(store, {storage: AsyncStorage})
       export default class Index extends Component {

       constructor(props) {
         super(props);
          this.state = { rehydrated: false };
        }

         componentWillMount(){
           persistStore(store, {}, () => {
           this.setState({ rehydrated: true })
          })
         }

        render() {
         if(!this.state.rehydrated){
          return (<Text>Loading...</Text>);
          }
           return (
           <Provider store={store}>
                <StackNavigation />
           </Provider>
         );
        }
     }

      AppRegistry.registerComponent('LocalDBProject', () => Index);
`

![simulator screen shot 26-sep-2017 1 26 08 pm](https://user-images.githubusercontent.com/24026483/30848940-5453f0c2-a2be-11e7-90f4-22540169bf54.png)

**Comment by ccoeder** [comment]
just change this line

```
persistStore(store, {}, () => {
       this.setState({ rehydrated: true })
      })
```
with this

```
persistStore(store, { storage: AsyncStorage }, () => {
       this.setState({ rehydrated: true })
      })
```

and top of your file add this line: 

`import { AsyncStorage } from 'react-native';`

**Comment by harshsrivastavaglobussoft** [comment]
yeah it worked 
thanks
