### ISSUE TITLE
[v5] createPersistoid.js:(20, 46) leaving behind console logs

### ISSUE THREAD

**Issue by clodal** [rt2zz/redux-persist#464]
Hi there, i'm using v5 `"redux-persist": "^5.0.0-beta.14"` and importing code as stated in the README:
```
import { persistStore, persistReducer } from 'redux-persist';
import storage from 'redux-persist/es/storage'; // default: localStorage if web, AsyncStorage if react-native
```

However, in Chrome 60 browser, these console.logs are being called due to a console.log in the code, is this an accidental debug info left behind or I'm doing the wrong imports?
```
// my chrome browser console output at each page load
pn admin              createPersistoid.js:46
pn counter            createPersistoid.js:46
pn user               createPersistoid.js:46
pn _persist           createPersistoid.js:46
```
```
// redux-persist/es/createPersistoid.js:46
console.log('pn', key);
```

**Update: Also note createPersistoid.js:20 also leaves another console.log(...)**

**Comment by Hauuguu** [comment]
I'm also getting the "update" console.log in 5.0.0-beta.15 on line 25 in createPersistoid.js

`console.log('update', state);`

**Comment by rt2zz** [comment]
sorry about that, @5.0.0-beta.16 removes the remaining errant logs
