### ISSUE TITLE
Changelog is outdated

### ISSUE THREAD

**Issue by christianrank** [rt2zz/redux-persist#468]
The latest entry in `CHANGELOG.md` is `4.9.1`.

If you have a `CHANGELOG.md`, please remember to keep it up to date with every new release.

**Comment by piotr-cz** [comment]
Seems that _CHANGELOG.md_ file has been left behind with the v4 branch and isn't available in v5 releases anymore.

This very inconvenient when upgrading package, I have to compare changes before very upgrade.

**Comment by rt2zz** [comment]
adding release notes for v5.4 - will begin doing regular release notes with releases
