### ISSUE TITLE
Typescript issue

### ISSUE THREAD

**Issue by oferRounds** [rt2zz/redux-persist#470]
Hi!

So I have my `User` object which gets persisted with the store. The problem is that when the user data is loaded from cache, it does not get initialized as `User` object, but as plain `Object`. Therefore, when trying to call a function of the object I get: `<function_name> is not a function`.

Any idea how to workaround this issue?

**Comment by oferRounds** [comment]
This is my `User` class definition:
```
import { Type, Expose } from 'class-transformer'
import 'reflect-metadata'

export class User {
  readonly id: string
  readonly firstName: string

  @Expose({ name: 'surname' })
  readonly lastName: string

  @Type(() => Date)
  readonly creationDate: Date

  readonly about: any
  readonly personal: any

  // Is there a way to create an Extension for a class in TS? Such as in C# or Obj-C. Couldn’t find how to.
  key(): string {
    return this.id
  }

  shortBirthdate(): string {
    return this.personal.shortBirthDate
  }

  photoURL(): string {
    return this.about.avatar || ''
  }

  fullName(): string {
    return this.firstName + ' ' + this.lastName
  }
}```

**Comment by rt2zz** [comment]
redux-persist relies on serializing the state, i.e. really only works with plain objects / primitives. If you want to persist a User class, you will need some serialization and / or rehydration handler. The simplest way to do this would be to customize your REHYDRATE case in your reducer, something like

```js
case REHYDRATE
  if (!action.payload) return state
  let user = new User(action.payload.auth.user)
  return {
    ...state,
    ...action.payload.auth,
    user,
   }
```

**Comment by oferRounds** [comment]
@rt2zz got you, thanks!
