### ISSUE TITLE
Please add doc for "PersistGate" component

### ISSUE THREAD

**Issue by wellyshen** [rt2zz/redux-persist#474]
Thank you for this great library :)
Current I upgrade it from v4 to v5. And I found there's no document for the `PersistGate` component. Could you please add it (e.g. example, docs).

**Comment by rt2zz** [comment]
added some notes the the usage section: https://github.com/rt2zz/redux-persist/tree/v5#usage

feel free to propose further improvements 👍

**Comment by wellyshen** [comment]
@rt2zz Nice Man ;)
