### ISSUE TITLE
persistReducer is undefined Error

### ISSUE THREAD

**Issue by jonasgrunert** [rt2zz/redux-persist#480]
Hey there
I am currently building a react-native app using Redux. I want to persist my store using v5 but currently I get an error using persistReducer. voteApp is a valid reducer using combineReducer.
`undefined is not a function (evaluating '(0, _reduxPersist.persistReducer)(config, _reducers.voteApp)')`

```
import React from 'react';
import { AsyncStorage } from 'react-native';
import { createStore } from 'redux'
import { Provider } from 'react-redux'
import { persistStore, persistReducer } from 'redux-persist'
import { voteApp } from './reducers/reducers'
const config = {
  key: 'root',
  storage: AsyncStorage,
}
const reducer = persistReducer(config, voteApp)
function configureStore () {
  let store = createStore(reducer)
  let persistor = persistStore(store, {storage: AsyncStorage})
  return { persistor, store }
}
```
As this is my first use of redux-persist and react-native I think the error is on my side. Maybe someone could help me out.

**Comment by rt2zz** [comment]
Are you certain you have installed v5, i.e. `npm i redux-persist@next`? It seems persistReducer is undefined.  Also below where you call `  let persistor = persistStore(store, {storage: AsyncStorage})` you do not need to pass config to persistStore.

**Comment by jonasgrunert** [comment]
Thanks a lot. I did not install v5 properly. But I did now and another error came instead. I did not change any code except for your advised changes, but got an error, which looks the following:
`undefined is not a function (evaluating 'baseReducer(undefined, {type: 'redux-persist/default-state-probe'})')` and the error log points towards node_modules\redux-persist\lib\persistReducer.js:55:35.
Thanks for your help. Do you have any further advise?

**Comment by jonasgrunert** [comment]
Ok that was an error in my code. Thank you very much.

**Comment by jawadulhassan** [comment]
What exactly was the error you fixed? Because I am facing the some sort of same error?

**Comment by jonasgrunert** [comment]
I am unfortunately unable to tell you what I did, because it was so trivial I forgot it. But it is something in the code. So maybe you can provide your code and error and I try to help out?
