### ISSUE TITLE
Trouble getting v5 to install / run

### ISSUE THREAD

**Issue by claykohut** [rt2zz/redux-persist#486]
The install seems to work when I try to install the v5 branch via npm / the files are in the node_modules file, but I'm getting an 'unable to resolve module `redux-persist`' error in react native.

Any idea why this might be? It works fine when I install the master branch.

Would it be possible to make the a tag / release for v5? I'm wondering if that might help.

**Comment by claykohut** [comment]
Also everything works when I download the library and use it directly / without npm.

**Comment by reblws** [comment]
I think I'm running into the same thing. The problem with installing from v5 is the source still needs to be compiled so the modules can be accessed from the `es/` folder.  You can check if we're having the same issue I'm having if you don't see an `es/` or `lib/` folder in `node_modules/redux-persist` when you install the v5 branch.

I've set up a [a fork here](https://github.com/reblws/redux-persist/tree/v5) with the files built so you can install from npm. Just set `"redux-persist": "reblws/redux-persist#v5"` in package.json.

**Comment by rt2zz** [comment]
how are you installing v5? the recommended way is via the next tag which is a compiled release `npm i redux-persist@next`

**Comment by colinramsay** [comment]
@rt2zz can I ask what the rationale is for having to use the `next` tag for a compiled release? It's currently pointing at `5.3.0-rc.2`.

**Comment by rt2zz** [comment]
this was old, pre-v5. now you can just install per normal `npm i redux-persist`
