### ISSUE TITLE
Weird issue with rehydrate on rn49

### ISSUE THREAD

**Issue by jimji1005** [rt2zz/redux-persist#487]
Hi guys very weird issue here.

Running ios simulator ios 9, latest rn49, latest version of redux, redux-persist

My rehydrate works when remote js debug is activated.

But when i turn it off, my rehydrate does not work. Redux works, the app functions normally, just couldn't reload the data.

Persist uses asyncstorage.

here is my code

`const store = createStore(reducers,
			undefined,
			compose(
				applyMiddleware(ReduxThunk),
				autoRehydrate()
			));

if (typeof self === 'object') persistStore(store, {blacklist: ['customer'], storage: AsyncStorage}, () => { console.log('hydrate complete'); });`

**Comment by rt2zz** [comment]
not sure what is going on,
1. I recall a while back, AsyncStorage was broken on android with debug enabled. Obviously not the same issue, but it is possible this is an upstream bug.
2. perhaps more likely something is erroring out. Can you add `debug: true` to your persist config and see if any errors are logged.
3. is `if (typeof self === 'object')` before persisting the store to make sure it does not persist in SSR? that check may have broken in more recent versions of react-native which could explain why it works in the browser (with remote debug) but not on device.

**Comment by jimji1005** [comment]
Hi


I don't think its an asyncstorage issue, i have a different function that haven't been migrated to redux yet which still uses asyncstorage to store a string. that is working and the data persists from remote debut to remote debug off.


I am going to test with debug true to see if it works as well as removing the object check

**Comment by jimji1005** [comment]
remove typeof self check fixed the issue. self seems to be undefined when remote debug is OFF.
