### ISSUE TITLE
skipDispatch option

### ISSUE THREAD

**Issue by af** [rt2zz/redux-persist#49]
`skipDispatch` is listed as an option in the Readme, but it's not in the code anywhere. Not sure if this was removed? 

Also I'm wondering if the plan is still to not dispatch the REHYDRATE actions when v2.0 lands? Alternately, is there any recommended pattern for delaying the loading/rendering of the rest of an app until `persist/COMPLETE` is fired?

**Comment by rt2zz** [comment]
good catch. it was renamed to `skipRestore`. There are multiple options for delaying the rendering, and this is in fact the reason skipRestore was added.

Option 1: [getStoredState w/ callback](https://github.com/rt2zz/redux-persist#initialstate-rehydration)
Option 2: [App.js lifecycle hooks](https://gist.github.com/rt2zz/1e9e0216b8b44b400df8)
Option 3: Set a piece of state `rehydrated: true` in response to REHYDRATE_COMPLETE action.

Not sure the best option for your use case. I typically like option 3 but it does require wiring up your reducer appropriately

**Comment by rt2zz** [comment]
btw just updated the readme with `skipRestore`

**Comment by af** [comment]
Thanks! Not sure how I missed getStoredState()

**Comment by rt2zz** [comment]
@af its a new api that honestly I am uncertain about right now. Let me know how it feels for you - it could potentially become the recommended usage.

**Comment by af** [comment]
One potential issue with it for me is that I export my persister (the output of `persistStore()`) so I can purge the store elsewhere. AFAIK having `persistStore()` in a callback means I can't export it anymore using ES6 modules. I haven't tried any workarounds for this yet, but one of your other two approaches may work for me anyways.

**Comment by rt2zz** [comment]
hm yes no super elegant way to export persistor in this scenario. I will think about it. I would say option 3 will always give you the most optionality albeit at a certain effort to implement.

**Comment by af** [comment]
Yeah I've gone with option 3, was very easy and seems to do what I need. Thanks again for your suggestions!
