### ISSUE TITLE
Cannot use purge() and PersistGate at the same time

### ISSUE THREAD

**Issue by mazing** [rt2zz/redux-persist#494]
Purging store with `const persistor = persistStore(store).purge()` while using `PersistGate` results in critical error.

**Comment by rt2zz** [comment]
Right, purge returns a promise, not the persistor. I think you want
```js
const persistor = persistStore(store)
persistor.purge()
```

**Comment by mazing** [comment]
Yes! Thanks for the quick reply! :-D
