### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by jirikolarik** [rt2zz/redux-persist#497]
Hi, could you please release latest version to NPM?

It falls on flow type, thanks!

**Comment by rt2zz** [comment]
@jirikolarik can you clarify, the latest version for v5 or v4? what is the flowtype error?

**Comment by jirikolarik** [comment]
I didn't even noticed, that there is a v5 version. I'll upgrade to that one..

I don't know the error right now, I can get it later this day, but this (commit)[https://github.com/rt2zz/redux-persist/commit/f512ef0de5e0e3d58221283b830f7f9c0c6eb3f4] fixed it

**Comment by rt2zz** [comment]
👍  ill publish a new v4 release as well

**Comment by rt2zz** [comment]
released v4.10.2

**Comment by jirikolarik** [comment]
Great! Thanks :)
