### ISSUE TITLE
[V5] persisted state (which is correct) not overwrtiting intial state with 'persist/REHYDRATE' action

### ISSUE THREAD

**Issue by NathHorrigan** [rt2zz/redux-persist#502]
Love this lib but having trouble with initial being replaced. Title explains all really, Here's some code snippets:

```
// Reducers.js:
export default combineReducers({
  firebase: firebaseStateReducer,
  navbarReducer: navbar,
  auth,
  util
})

```

```
// store.js
const config = {
  key: 'root', // key is required
  storage: AsyncStorage, // storage is now required
  debug: true
}
const reducer = persistReducer(config, reducers)

export default (initialState = { firebase: {} }) => {
  // initialize firebase;
  const firebase = RNFirebase.initializeApp(reactNativeFirebaseConfig)
  const store = createStore(
    reducer,
    initialState,
    compose(
      applyMiddleware(createEpicMiddleware(epics)),
      reactReduxFirebase(firebase, reduxFirebaseConfig),
      applyMiddleware(logger)
    )
  )
  const persistor = persistStore(store);
  return store
}
```

Screenshot of action in devtools (notice state.util.showOnboarding):

![screen shot 2017-10-24 at 17 53 03](https://user-images.githubusercontent.com/13197111/31956729-408e2d0a-b8e4-11e7-8f14-5be4986b6282.png)

**Comment by rt2zz** [comment]
is it possible util reducer is modifying its state? If any piece of sub state is modified, then state reconciler will skip rehydration for the sub state.

If that is not the case then I am not positive what is happening. I am thinking about adding a new stateReconciler that can be plugged in which does not do the state mutation check, so would *always* cause incoming state to be rehydrated. If mutation is indeed the source of the problem then I think this new state reconciler is the best option to fix the issue.

**Comment by NathHorrigan** [comment]
Hi @rt2zz 

Thanks for the quick response. Your first statement tipped me off to the problem; 

### I'll expand on my problem/solution for anyone passing by:
I had a 'rehydrated' value in my util reducer state that would allow me to know when state had been hydrated. What was happening was that when state was rehydrated it would return initial state with 'rehydrated' value as true (hence the problem, also see code example). My solution was to remove 'rehydrated' value/action case and use the one supplied by V5 of redux-persist under `state._persist.rehydrated`.

Thanks again!!

```
// Reducer Code
const initial = {
  showOnboarding: true,
  rehydrated: false
}

export default (state = initial, action) => {
  switch (action.type) {
    case SHOW_ONBOARDING:
      return Object.assign({}, state, {
        showOnboarding: action.payload
      })
    case REHYDRATE:
      return Object.assign({}, state, {
        rehydrated: true
      })
    default:
      return state
  }
}
```

**Comment by rt2zz** [comment]
nice! ya I have long considered removing that "skip if modified" logic, but it has stuck around for legacy reasons (don't want to break everyones code needlessly!). Glad you got it working 👍

**Comment by rt2zz** [comment]
also fyi in v5 you can know everything is done rehydrating by checking `persistor.getState().bootstrapped`, which is how the provided react integration component `PersistGate` works.
