### ISSUE TITLE
Store doesn't have a valid reducer while using persistCombineReducers

### ISSUE THREAD

**Issue by therise3107** [rt2zz/redux-persist#516]
This is related to v5.
Error file
![image](https://user-images.githubusercontent.com/2356810/32145187-4f0c36e2-bcea-11e7-8e64-999acbcb7a51.png)

Store.js
```
import { persistStore, persistCombineReducers } from 'redux-persist'
import { createStore } from 'redux'
import storage from 'redux-persist/es/storage'
import reducers from './reducers'

const config = {
  key: 'root',
  storage,
}

const reducer = persistCombineReducers(config, reducers)

const configureStore = () => {
  const store = createStore(reducer)
  const persistor = persistStore(store)

  return { store, persistor }
}


export default configureStore

```
redcuers/index.js
```
import { combineReducers } from 'redux'

const initialReducer = (state = [], action) => return state

const reducers = combineReducers({
  initialReducer 
})

export default reducers

```

**Comment by rt2zz** [comment]
perhaps the docs did not make this clear, but you should not need combineReducers that is handled by persistCombineReducers, so simply change reducers/index.js to be 
```js
import { combineReducers } from 'redux'

const initialReducer = (state = [], action) => return state

export default {
  initialReducer 
}
```

Open to suggestions for how to improve the docs around this.

**Comment by therise3107** [comment]
Thank you @rt2zz. I'm closing this. Docs are fine just needs some more clarification on usage. I am just starting with redux-persist so I will gladly create PR's in coming days.

**Comment by Coder108** [comment]
@rt2zz What if I want to clear all the stored data?
