### ISSUE TITLE
IE11/Edge Requires Manual Browser Reload

### ISSUE THREAD

**Issue by ZeroMcMuffin** [rt2zz/redux-persist#522]
I've been toying with an IE11/Edge issue for a few days certain it was an implementation issue on my end, but I'm at a dead end now.  I have the issue with both 4.x and 5.x (up to the very new 5.2.0) versions of redux-persist.  I've tried several combinations of action buffers (including the current changes in redux-action-buffer master that allows passthrough for PERSIST), PersistGates, and manually delaying rendering until after REHYDRATE.  

The behavior I'm seeing is that initially starting an application with empty storage (using LocalForage or just plain local storage) works just fine.  However, if I click the link to launch the application with a populated storage, the application never starts.  The rehydrate event is firing.  I can see it in my reducers.  My components never really initializes/receive props.  If, however, I manually reload the page...voila the app springs to life.  

Any help is greatly appreciated.

Here is my implementation:

```javascript
import React, {PureComponent} from 'react';
import ReactDOM from 'react-dom';
import {applyMiddleware, compose, createStore} from 'redux';
import {Provider} from 'react-redux';
import {syncHistoryWithStore, routerMiddleware} from 'react-router-redux';
import {hashHistory} from 'react-router';
import thunk from 'redux-thunk';
import { PersistGate } from 'redux-persist/lib/integration/react';
import { persistStore, persistCombineReducers } from 'redux-persist';
import createMiddleware from 'redux/middleware/clientMiddleware';
import localForage from 'localforage';
import { composeWithDevTools } from 'redux-devtools-extension';

import Routes from './routes';
import ApiClient from './helpers/ApiClient';

const client = new ApiClient();

const config = {
  key: 'exogen',
  storage: localForage
};

const rootReducer = require('redux/modules/reducer');
const reducer = persistCombineReducers(config, rootReducer);

const reduxRouterMiddleware = routerMiddleware(hashHistory);
const middleware = [thunk, createMiddleware(client), reduxRouterMiddleware];

let enhancer;

enhancer = (__DEVTOOLS__)
  ? composeWithDevTools(
    applyMiddleware(...middleware)
  )
  : compose(
    applyMiddleware(...middleware)
  );

const store = createStore(reducer, enhancer);
const history = syncHistoryWithStore(hashHistory, store);
const persistor = persistStore(store, enhancer);

if (__DEVELOPMENT__ && module.hot) {
  module.hot.accept('redux/modules/reducer', () => {
    store.replaceReducer(reducer);
  });
}

const spinner = <div className="spinner-wrapper"><i className="spinner fa fa-circle-o-notch fa-spin fa-3x"/></div>;

ReactDOM.render(
  <PersistGate
    persistor={persistor}
    loading={spinner}
  >
    <Provider store={store} key="provider">
      <Routes history={history}/>
    </Provider>
  </PersistGate>,
  document.getElementById('content')
);

if (__DEVTOOLS__) {
  window.React = React;
}

```

**Comment by rt2zz** [comment]
what do you mean by "click the link to launch the application with a populated storage, the application never starts" which link are you referring to?

I know many instances of redux-persist working in ie11 / edge, so my thought is this is a nuance with your set up although it is not clear what (the code pated looks good).

Can you check two things
1. the state of the store, does the _persist state show rehydrated: true?
2. the state of the persistor (call `persistor.getState()`) does it have an empty registry *and* bootstrapped should be true.

**Comment by rt2zz** [comment]
also I have not personall used HMR w/ reducers, but I think after calling store.replaceReducer you need to then call `persistor.persist()` in order to get the replaced reducer kicked into action.

**Comment by ZeroMcMuffin** [comment]
The 'link' comment was a little vague.  This SPA lives inside of another multi-page site.  Navigating to it from the link that launches the app vs hitting refresh on the browser produces different behavior.  

I've removed the HMR code.  That isn't necessary for this.  I created a component to wrap the provider/router so I can tie into the life cycle methods and read the persistor/store state as you requested.   This was illuminating.  The persist gate is not rendering its child component after the REHYDRATE action unless we have empty storage or we hit refresh on the browser.  I see exactly what you describe:  empty registry and bootstrapped == true in those situations.  In the other scenario (link navigation), the loading component is perpetually displayed.

**Comment by ZeroMcMuffin** [comment]
Strangely, if I have the developer console open in Edge...it also loads.

**Comment by rt2zz** [comment]
hmm that is odd. so the code in PersistGate is pretty straight forward: https://github.com/rt2zz/redux-persist/blob/master/src/integration/react.js

Is it possible that the PERSIST action is not being fired at all (in the link navigation case)? This should be observable using redux-devools (I recommend https://github.com/zalmoxisus/remote-redux-devtools)

**Comment by ZeroMcMuffin** [comment]
The default-state-probe, PERSIST, and REHYDRATE actions are firing in all scenarios.  

In a normal scenario, it looks PersistGate gets two events in handlePersistorState.  One with a bootstrapped of false, next a bootstrapped of true.    In the scenarios where this is failing, the second event never arrives which is causing the perpetual loading component.

**Comment by rt2zz** [comment]
I dont think this is the issue, but looks like to do need to switch the order of these calls: https://github.com/rt2zz/redux-persist/blob/master/src/integration/react.js#L28-L29

**Comment by rt2zz** [comment]
just updated in 5.2.2, again I dont think this is the issue but worth updating regardles :/

**Comment by ZeroMcMuffin** [comment]
That didn't fix it, but I'm thankful either way.

**Comment by ZeroMcMuffin** [comment]
I've chipped away at this a little more.  The store dispatches the REHYDRATE action, but execution hangs around this point in redux-persist, preventing the PersistGate from giving the 'all clear' signal. 

https://github.com/rt2zz/redux-persist/blob/master/src/persistStore.js#L109-#L109

At some point the REHYDRATE dispatch is freezing.  I created a vanilla middleware to try and get some insight, but next(action) just freezes.  Hitting refresh fails....hitting refresh with Edge dev tools...success.  Bizarre... If I can't get people to not use edge...maybe they will just use it with developer tools enabled.  😄

**Comment by ZeroMcMuffin** [comment]
@rt2zz  If I just reverse the order of lines 109 and 110...I get a happy outcome.  It appears that my data is rehydrated as well.  Any concerns about a PR doing this reversal?

**Comment by ZeroMcMuffin** [comment]
This was unrelated to redux-persist, just as I'm guessing @rt2zz suspected.  It looks like another library was choking silently.  Sorry for the trouble!

**Comment by rt2zz** [comment]
😓  👍 

Did the fact that the REHYDRATE action was being somehow swallowed complicate the debugging?

**Comment by ZeroMcMuffin** [comment]
Yeah.  We have a singleton wrapper around json-rules-engine that we populate with REHYDRATE'd data.  Passing it an empty array was blocking.  That dispatch would stall.  It looked like REHYDRATE was completing until I started debugging redux persist.  Thanks again!
