### ISSUE TITLE
Uncaught ReferenceError: setImmediate is not defined ?

### ISSUE THREAD

**Issue by goodhyun** [rt2zz/redux-persist#53]
I'm getting this error while building nw.js chromium app with this index.js

> 
webpack:///./~/redux-persist/lib/persistStore.js?:49 Uncaught ReferenceError: setImmediate is not defined

I thought setImmediate was not supported natively in most of browsers. 

```
import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import { Router } from 'react-router';
import routes from './routes';
import configureStore from './store/configureStore';
import './app.css';

import {persistStore, autoRehydrate} from 'redux-persist'


const store = configureStore();

persistStore(store);

render(
  <Provider store={store}>
    <Router>
      {routes}
    </Router>
  </Provider>,
  document.getElementById('root')
);

**Comment by goodhyun** [comment]
Well, l didn't know that within a certain framework setImmediate is [not automatically provided by](https://github.com/nwjs/nw.js/issues/897) global.setImmediate(). 
I sent a PR.

**Comment by rt2zz** [comment]
accepted (with some modification) can you test on master to see if it is working as anticipated: `npm install rt2zz/redux-persist`

**Comment by noma4i** [comment]
Doesn't work. Solution was to 
`npm install setimmediate ` 
and use 
`import setimmediate from 'setimmediate';`

**Comment by goodhyun** [comment]
Works like a charm. 
Had to do `npm run build `at the folder though.

@noma4i the setImmediate shim was [only effective when you don't have global.setImmediate already.](https://github.com/nwjs/nw.js/issues/897) ?

**Comment by neurosnap** [comment]
On a fresh install I ran into this issue, it might be a good idea to mention this in the docs.

The fix:
```bash
npm install setimmediate
```

```js
import 'setimmediate';
import { persistStore } from 'redux-persist';
```

**Comment by latchy** [comment]
> On a fresh install I ran into this issue, it might be a good idea to mention this in the docs.
> 
> The fix:
> 
> ```shell
> npm install setimmediate
> ```
> 
> ```js
> import 'setimmediate';
> import { persistStore } from 'redux-persist';
> ```

.. and 6 years later, this fixes my issue with nodemailer.
Though I didn't need to npm install it, I could just import it.
Thank you!
