### ISSUE TITLE
[v5] _persist key not stored when whitelist config option is used

### ISSUE THREAD

**Issue by uiii** [rt2zz/redux-persist#533]
If the `whitelist` options in config for `persistReducer` is used, the `_persist` reducer key is not stored in a storage. I'm not sure if this is intended behavior. Should I explicitly specify it if using `whitelist`?

**Comment by uiii** [comment]
To get my point, the version is stored under that key, so it looks it's needed for a migrations to work. As I see in the code, `createMigrate` depends on it: https://github.com/rt2zz/redux-persist/blob/master/src/createMigrate.js#L22

**Comment by rt2zz** [comment]
ah excellent point, this is in fact a bug - or at least not intended. I suppose we should *always* persist _persist since the whole versioning design does not work without it. This can probably be an easy 1 line change to `createPersistoid`
