### ISSUE TITLE
How to persist initial state

### ISSUE THREAD

**Issue by fabiosussetto** [rt2zz/redux-persist#55]
Hi, I'm using the latest version and I can't figure out how to persist to local storage the initial state I pass to createStore. It looks like redux-persist starts to sync state with the local storage as soon as I fire up an actions. 
I'm after a way to store some initial data that my server provides on the window object (I'm doing server side rendering).

Thanks!

**Comment by rt2zz** [comment]
This is currently not possible (in any elegant way). We could expose another option: `storeInitialState` but I am wary of adding any more options. 

Storing initial state is actually the safe & logical thing to do, but I am concerned about adding any cpu load during the already impacted bootstrap process of a web app. Thoughts?

**Comment by fabiosussetto** [comment]
I ended up extending your delayed rendering recipe [here](https://github.com/rt2zz/redux-persist/blob/master/docs/recipes.md#delay-render-until-rehydration-complete)

On rehydration completed, I dispatch a normal action (say 'INITIAL_DATA_RESTORED') with the window.__INITIAL_STATE__ data that I get from the server. That triggers the normal redux-persist functionality so after I update the state with the server side data everything is persisted.

**Comment by rt2zz** [comment]
@fabiosussetto this seems like the correct approach.

In the meantime I am working on 2.0 which has some semi-significant api changes. https://github.com/rt2zz/redux-persist/issues/35#issuecomment-182596103

In 2.0 I am leaning toward making storing initial state the default behavior since this is more intuitive.

**Comment by RajnishDashora** [comment]
Hey @rt2zz, I am using 3.2.2, not able to figure out the way to store the initial state passed to createStore incase there is nothing in the local storage to rehydrate ?? 
Tried the above recipe mentioned by @fabiosussetto but that make REHYDRATE getting called twice?

**Comment by rt2zz** [comment]
redux-persist now stores the initial state, relevant lines: https://github.com/rt2zz/redux-persist/blob/master/src/createPersistor.js#L21-L40

Are you experiencing some issues?
