### ISSUE TITLE
[ V5] How persistStore work to get persisted state on rehydration

### ISSUE THREAD

**Issue by Shhzdmrz** [rt2zz/redux-persist#550]
Hello,

I am wondering when I create store without the persisted config then I need to make reducer to listen to the action `persist/REHYDRATE` then I can return new state with the payload return from the rehydration.
But when I add persisted config even empty config but specifying the param as given below then I don't need to listen to that action `persist/REHYDRATE` and state automatically restore on rehydration.

## Code without persisted config:
**store.js**
```Javascript
const config = { key: 'root', storage };
const middleware = [];
const reducers = persistCombineReducers(config, rootReducers);
const enhancers = [applyMiddleware(...middleware)];
const initialState = {};
const store = createStore(reducers, undefined, compose(...enhancers));
const persistor = persistStore(store); //persistStore with only store parameter
const configureStore = () => {
    return { persistor, store };
}
```
**reducer.js**
```Javascript
const reducer = (state = {}, action) => {
    switch(action.type){        
        case "persist/REHYDRATE": {
            const data = action.payload;
                if (data) return {...state, ...data.auth}
        }
    }
}
```
## Code with persisted config:
**store.js**
```Javascript
const config = { key: 'root', storage };
const middleware = [];
const reducers = persistCombineReducers(config, rootReducers);
const enhancers = [applyMiddleware(...middleware)];
const initialState = {};
const persistConfig = { enhancers };
const store = createStore(reducers, undefined, compose(...enhancers));
const persistor = persistStore(store, persistConfig, () => { //persistStore with all parameters
    //console.log(store.getState());
});
const configureStore = () => {
    return { persistor, store };
}
```
Now I don't need to listen to any action. Because the state automatically restored after rehydration. Could you please explain how it's working without listening to action? 

Incase if you need more information please checkout [**this example repo**](https://github.com/Shhzdmrz/reduxpersist) that I have created to test v5.

Thanks

**Comment by rt2zz** [comment]
you should not need to listen for the action, and you should also not need to pass persistConfig to persistStore. What happens is persistCombineReducers is a higher order reducer that will handle rehydration for you.

I am not sure why it was not working for you originally but I would try again (without handling the action and without persistConfig), it should work.

**Comment by Shhzdmrz** [comment]
@rt2zz thank you.
I'll wait for your response once you try again and the repo that I linked in my issue please consider it for testing.

**Comment by rahkumar2** [comment]
Hi rt2zz,

I am trying to use PersistGate (using V5 redux-persist) to delay rendering, but it's not working as expected.
I even tried without PersistGate, I am able to see state available after rehydration, but component is getting rendered before state gets available.

I am waiting for you reply. Thank you.

**Comment by rahkumar2** [comment]
Hi Shhzdmrz,
    Actually I am working from last 4 days on redux state persistence, but still not done. I think you have already been working on this. Can you please share the sample working code for reducer (for multiple reducer), store, routes, and connected component (just rehydration part of code) ?

Thank you.

**Comment by Shhzdmrz** [comment]
@rahkumar2 have a look on [this example repo](https://github.com/Shhzdmrz/reduxpersist)

**Comment by rahkumar2** [comment]
Thanks Shhzdmrz.
I already have taken a look into that. I have similar logic, but it's not working.
Do you know any custom logic to delay the render until rehydration ?

**Comment by Shhzdmrz** [comment]
@rahkumar2 did you tried **onBeforeLift**? as mentioned in [this example](https://github.com/rt2zz/redux-persist/blob/master/docs/PersistGate.md)

**Comment by rahkumar2** [comment]
No, I did not use that as I don't the meaning of it. But it's working now, actually there was problem with our customized form .js file itself.
