### ISSUE TITLE
[V5] Persist loads string like Object

### ISSUE THREAD

**Issue by tvorogme** [rt2zz/redux-persist#552]
After my actions token in store looks like:
```{token: "1c62bdaccd3f2a9ba1a29ad79c9cbc773c8ceca1", user: {…}, _persist: {…}}```

![latest-screenshot](https://user-images.githubusercontent.com/19264196/32553092-f1bc7794-c4a6-11e7-88fd-19b0b37a8432.png)

I reload page, and ```"persist/REHYDRATE"``` action loads token like string:

![latest-screenshot](https://user-images.githubusercontent.com/19264196/32551943-4ec9b2ca-c4a3-11e7-9bfb-e2d36146e844.png)

But in the next state of store token is an Object:

```
token:{0: "1", 1: "c", 2: "6", 3: "2", 4: "b", 5: "d", 6: "a", 7: "c", 8: "c", 9: "d", 10: "3", 11: "f", 12: "2", 13: "a", 14: "9", 15: "b", 16: "a", 17: "1", 18: "a", 19: "2", 20: "9", 21: "a", 22: "d", 23: "7", 24: "9", 25: "c", 26: "9", 27: "c", 28: "b", 29: "c", 30: "7", 31: "7", 32: "3", 33: "c", 34: "8", 35: "c", 36: "e", 37: "c", 38: "a", 39: "1"}
```

![latest-screenshot](https://user-images.githubusercontent.com/19264196/32551963-65c06c4e-c4a3-11e7-825d-ded332ed05f0.png)

My code:

```
const config = {
    key: 'root',
    storage,
};

export const reducers = persistCombineReducers(config, {
    token: tokenReducer,
    user: userReducer,
    loginError:
        loginFailed()
});


export const store = createStore(
    reducers,
    applyMiddleware(logger),
);

export const persistor = persistStore(store);
```
And ```App.js```:

```
....
import {store, persistor} from './Redux'
....

ReactDOM.render(
    <Provider store={store}>
        <ApolloProvider client={client}>
            <PersistGate persistor={persistor}>
                <BrowserRouter>
                    <App/>
                </BrowserRouter>
            </PersistGate>
        </ApolloProvider>
    </Provider>,
    document.getElementById('container')
);
```

Maybe I made something wrong? 
Thanks.

**Comment by rt2zz** [comment]
5.3 is out now, and should now support your use case out of the box

**Comment by tvorogme** [comment]
Let me check, and then I'll close the issue.

**Comment by tvorogme** [comment]
All works fine. 
Thanks!

![latest-screenshot](https://user-images.githubusercontent.com/19264196/32587424-576e8ce0-c519-11e7-849a-e840b1ada893.png)
