### ISSUE TITLE
Skip PersistGate while doing server side rendering?

### ISSUE THREAD

**Issue by rsbh** [rt2zz/redux-persist#576]
react is giving html mismatch error, because server is not rendering loading component of persist gate

**Comment by rt2zz** [comment]
I expect other have more experience with SSR than I, but generally I would recommend not using PersistGate if you are using SSR. redux-persist-cookie-storage might help here, since it allows you have identical state server side and client side during rehydration.

**Comment by mark-slepkov** [comment]
Hey, guys. I solved this problem using code like this.
`
import {PersistGate as PersistGateClient} from 'redux-persist/integration/react';
class PersistGateServer extends React.Component {
    render() {
        return this.props.children
    }
}

class App extends React.Component {
    render() {
        let runtime = process.env.RUNTIME;
        let PersistGate = PersistGateServer;
        if (runtime === 'browser') {
             PersistGate = PersistGateClient
        }
        return (
            <Provider store={store}>
                <PersistGate loading={null} persistor={persistor}>
                       <WhateverYouWant />
                </PersistGate>
            </Provider>
        )
    }
`

I hope it is helpful for you.

**Comment by DBosley** [comment]
@mark-slepkov: How did you mock out or load the `persistor` server side? I'm using the localstorage option for redux-persist, so you can't really load the persistor when server side rendering.

**Comment by awwong1** [comment]
I came across this issue when running my own SSR React application.
I'm currently seeing no issues just stubbing in PersistGate with no props defined:

```ts
// client.ts
const appLayout = createElement(ApplicationLayout);
const withRouter = createElement(BrowserRouter, undefined, appLayout);
const withRedux = createElement(ReduxProvider, {store}, withRouter);
const withPersist = createElement(PersistGate, {loading: null, persistor}, withRedux);
const withHelmet = createElement(HelmetProvider, undefined, withPersist);

// server.ts
const appLayout = createElement(ApplicationLayout);
const withRouter = createElement(StaticRouter, { context: {}, location: req.url }, appLayout);
const withRedux = createElement(Provider, { store }, withRouter);
const withPlaceholderPersistor = createElement(PersistGate, null, withRedux); // no persistor! just for structure
const withHelmet = createElement(HelmetProvider, { context: helmetContext }, withPlaceholderPersistor);
```

**Comment by orkunmert98** [comment]
this ismy solutıon ıt works for me but i am not sure correct solutıon 
`
 let runtime = process.env.RUNTIME;
        
        if (runtime === 'browser') {
             


             return(
<ApolloProvider client={apollo}>

<Provider store={store}>
<PersistGate loading={null} persistor={store.__persistor}>
<Header></Header>

<Component {...pageProps} ></Component>

</PersistGate>
</Provider>
</ApolloProvider>

             )
        }else{

          return(

<ApolloProvider client={apollo}>

<Provider store={store}>

<Header></Header>

<Component {...pageProps} ></Component>


</Provider>
</ApolloProvider>



            )

        }


`

**Comment by orkunmert98** [comment]
this is my solutıon. ıt works for me but i am not sure ıt ıs correct

**Comment by nuriun** [comment]
Here, this is my solution either:

This is able to work on the server and client-side. Also, since it works the same way on both sides, so we don't annoy the hydrate function for HTML mismatch error.

```js
<PersistGate loading={null} persistor={persistor}>
    {() => (
        <ThemeProvider theme={{}}>
            <Everything />
        </ThemeProvider>
    )}
</PersistGate>
```

So, how?

Because, as you can see below, `PersistGate` defines `this.state.bootstrapped`'s  value while `componentDidMount` work. But `componentDidMount`  doesn't work on the server-side. Also, it means you can not persist on the server-side.

```js
  componentDidMount() {
    this._unsubscribe = this.props.persistor.subscribe(
      this.handlePersistorState
    )
    this.handlePersistorState()
  }

  handlePersistorState = () => {
    const { persistor } = this.props
    let { bootstrapped } = persistor.getState()
    if (bootstrapped) {
      if (this.props.onBeforeLift) {
        Promise.resolve(this.props.onBeforeLift())
          .finally(() => this.setState({ bootstrapped: true }))
      } else {
        this.setState({ bootstrapped: true })
      }
      this._unsubscribe && this._unsubscribe()
    }
  }
```

And if we passed a function as a child, we can return our component directly according to code below. In this scenario, the status of `this.state.bootstrapped` is not important.
```js
render() {
    if (process.env.NODE_ENV !== 'production') {
      if (typeof this.props.children === 'function' && this.props.loading)
        console.error(
          'redux-persist: PersistGate expects either a function child or loading prop, but not both. The loading prop will be ignored.'
        )
    }
    if (typeof this.props.children === 'function') {
      return this.props.children(this.state.bootstrapped)
    }

    return this.state.bootstrapped ? this.props.children : this.props.loading
  }
```

I hope it helps.

**Comment by chrisLoPresti** [comment]
> Hey, guys. I solved this problem using code like this.
> 
> ```
> import {PersistGate as PersistGateClient} from 'redux-persist/integration/react';
> class PersistGateServer extends React.Component {
>     render() {
>         return this.props.children
>     }
> }
> 
> class App extends React.Component {
>     render() {
>         let runtime = process.env.RUNTIME;
>         let PersistGate = PersistGateServer;
>         if (runtime === 'browser') {
>              PersistGate = PersistGateClient
>         }
>         return (
>                 <PersistGate loading={null} persistor={persistor}>
>                        <WhateverYouWant />
>                 </PersistGate>
>         )
>     }
> ```
> 
> I hope it is helpful for you.

This solved the problem for me, left me with a 100% performance score on lighthouse, and persist working clientside

**Comment by stevenKirill** [comment]
I'm getting the following error
<img width="700" alt="Screenshot 2023-05-14 at 13 17 51" src="https://github.com/rt2zz/redux-persist/assets/47239173/7102e905-d8e4-4a39-95f5-776a96401649">
How can i get rid of it ? Could you help me please ?

> this is my solutıon. ıt works for me but i am not sure ıt ıs correct ![çözüm](https://user-images.githubusercontent.com/58224943/79032935-d53a8a00-7bb2-11ea-9c2b-23ffd876f97a.png)
