### ISSUE TITLE
All object class name is reset to Object

### ISSUE THREAD

**Issue by vshy108** [rt2zz/redux-persist#577]
_Before_ **rehydrate**,
![image](https://user-images.githubusercontent.com/808926/32981245-d7c71938-ccae-11e7-92d3-9c60c6eebe6b.png)

currentCognitoUser.constructor.name = "**CognitoUser**"

_After_ rehydrate,
![image](https://user-images.githubusercontent.com/808926/32981422-a8ca5706-ccb0-11e7-9c83-380c39810a6c.png)

currentCognitoUser.constructor.name = "**Object**"

It is kind of trouble when I needs to call the rehydrated object's class functions.  Error of "those functions are not defined" is popped up because the rehydrated object is general Object now. thanks.

The spread operator will not remain the object class name if spread operator is used in rehydrate operation

**Comment by rt2zz** [comment]
persist relies on serialization, which will not work on functions and classes out of the box. If you need class rehydration, you will need to right a custom serializer transform. This is for example how redux-persist-transform-immutable works

**Comment by vshy108** [comment]
okay, will read how redux-persist-transform-immutable works. thanks

**Comment by rt2zz** [comment]
one strategy if you just have one or two classes you want rehydrated, you can implement a custom REHYDRATE handler in your reducer that does the "class instantiation". e.g.
```js
// yourReducer
case REHYDRATE:
  if (action.payload && action.payload.yourReducer) return { 
    ...state, 
    ...action.payload.yourReducer,
    someClassInstance: new SomeClass(action.payload.yourReducer.someClassInstance),
  }
```

hopefully that helps! there is no simple answer but usually depending on your use case there is a way to make it work.

**Comment by vshy108** [comment]
Unfortunately, the object class I tried to rehydrate is CognitoUser class that has many different classes as its object value. So the suggested method is somehow very complex to implemented in my case. But no worry, the package has a helper to restore the class from AsyncStorage in React Native somehow. Redux persist is not restrict to React-Native hence maybe harder to solve this problem?

The helper code from
`https://github.com/AirLabsTeam/react-native-aws-cognito-js/blob/77a5956a1f4b9d288ad667e720080bf13e9c58f3/src/StorageHelper.js`

**Comment by rt2zz** [comment]
Nice, in that case you can probably use that StorageHelper as your storage engine for this reducer. For that usage you probably want to use `persistReducer` on just the cognito reducer, so something like
```js
let reducer = combinReducer({
  cognito: persistReducer({ key: 'cognito', storage: CongnitoStorageHelper }, cognitoReducer)
```
