### ISSUE TITLE
Question: Is it possible to divide reducer persistence by id

### ISSUE THREAD

**Issue by adeelshahid** [rt2zz/redux-persist#594]
for example,

*documents* reducer with a Map of documents (each key represents a document id)

```
documents: {
    [document id]: {
        meta information about the document
    }
}
```

Is it possible to make the configuration so that each *document id* is stored in a separate key inside the localStorage

**Comment by rt2zz** [comment]
no this is not possible, unless you model each document as a separate reducer (but that has its own set of challenges). You might be able to toy with redux-persist's internals to get this functionality, but tbh I think this is a pretty specific use case and probably a custom solution. 

One big question: during rehydration, how do you know which documents you want to restore?

**Comment by adeelshahid** [comment]
@rt2zz we can have a reserved reducer with a prefix _, like *_persist*.


e.g.
_docs: [documents ids]
_docs:doc_id (contains the meta)

later on rehydrate we merge all _docs:parts into *docs*

**Comment by rt2zz** [comment]
that is possible and something we might be open to, but we need to consider a couple thing:
1. will the extra read per persistoid add meaningfully to startup time?
2. will the extra code to store this state outside of the reducer state add to code size?
3. will the risk of out of sync issues (where state is written but _persist fails or vice versa) going to be problematic?

**Comment by ethanroday** [comment]
@rt2zz Curious about this as well. To expand on @adeelshahid's example, let's say I have an application where users can create and edit documents. Some slice of my state looks like this:

```javascript
{
  docIds: ['a', 'b', 'c', ...],
  docs: {
    a: { title: 'Document A', text: 'Lorem ipsum ...' },
    b: { title: 'Document B', text: 'Lorem ipsum ...' },
    c: { title: 'Document C', text: 'Lorem ipsum ...' },
    ...
  }
}
```

Let's say documents can get fairly large, and that there can be a lot of them. I wouldn't want the entire document state to be stored under one key. Rather, I'd likely want something like this:

Key | Value
------------ | -------------
`doc_ids`|`"['a', 'b', 'c', ...]"`
`doc_a`|`"{ title: 'Document A', text: 'Lorem ipsum ...' }"`
`doc_a`|`"{ title: 'Document A', text: 'Lorem ipsum ...' }"`
`doc_a`|`"{ title: 'Document A', text: 'Lorem ipsum ...' }"`

**Comment by adeelshahid** [comment]
@ethanroday no I had a server based solution to remove the complexity from the reducer.
