### ISSUE TITLE
Hot module replacement using _persisst

### ISSUE THREAD

**Issue by ScreamZ** [rt2zz/redux-persist#601]
Hey,

I'm implementing HMR in my app using the following code 

```js
import { combineReducers } from 'redux'
import configureStore from './configureStore'

/* ------------- Assemble The reducers ------------- */
export const reducers = combineReducers({
  nav: require('./reducers/navigation').reducer,
  user: require('./reducers/user').reducer
})

export default () => {
  const storeTools = configureStore(reducers)

  if (module.hot) {
    module.hot.accept(() => {
      const nextRootReducer = require('./').reducers
      storeTools.store.replaceReducer(nextRootReducer)
    })
  }

  return storeTools
}
```

It is supposed to work well, but the app display the following message, that is annoying for on a HMR purpose with message the following message:

`Unexpected key "_persist" found in preloadedState argument passed to createStore. Expected to find one of the kwown reducer keys instead "nav", "user". Unexpected keys will be ignored.`

Any idea how can I deal with that ?

Best regards

**Comment by rt2zz** [comment]
Does it still warn if you use persistCombineReducers instead of combineReducers?

**Comment by ScreamZ** [comment]
@rt2zz Seems to work boss ! 

I have to adapt my code, I can give you an example with a PR for the documentation, I can see this part is "Coming soon" are you interested in ?

**Comment by ScreamZ** [comment]
I'm encountering new issues, can we talk about it in the above PR ? Thanks

**Comment by blackLearning** [comment]
For me, persist reducer in replaceReducer solves the problem.

```
export const store = createStore(
  persistReducer(config, rootReducer),
  compose(applyMiddleware(...middlewares), ...enhancers)
);

if (module.hot) {
  module.hot.accept(() => {
    const nextRootReducer = require('../reducer/index').default; // eslint-disable-line
    store.replaceReducer(persistReducer(config, nextRootReducer))
  })
}
```

**Comment by ScreamZ** [comment]
It should works, true :) Bug it could be nice to use the built-in method (see my PR #607)

**Comment by rt2zz** [comment]
@ScreamZ thanks, I modified your PR to be a little more inline with standard setup / simplify.

I apologize I lost the attribution on the squashed commit.
