### ISSUE TITLE
PERSIST is being called before REHYDRATE when using <PersistGate/>

### ISSUE THREAD

**Issue by mim-Armand** [rt2zz/redux-persist#609]
The PERSIST is being called before REHYDRATE causing stale state rehydrated over the fresh one.
TO my understanding PersistGate component was supposed to prevent this in React applications, or am I doing something wrong?

Thank you,
```javascript
ReactDOM.render(
    <Provider store={store}>
        <PersistGate
            loading={<Spinner/>}
            onBeforeLift={onBeforeLift}
            persistor={persistor}>
        <App></App>
        </PersistGate>
    </Provider>
    , document.getElementById('root'));
```

**Comment by mim-Armand** [comment]
I think the problem was that `getState()` returns the actual state and not the immutable state clone that can be used to update the actual state in an action, ( in contrary to what I was expecting or maybe it has been changed recently.. ? ), or maybe always returns the same instance of the state that Redux-Persist is using too, but anyway, I was mutating the object returned from `getState` and passing back to reducer to update at which point the state was already mutated ( or atleast the instance that was usied by Redux-Persist ) hence the reason behind the confusion..

Anyway, I think it issue is not related to Redux-Persist, so I'll close it,
Thanks, :)

**Comment by kg912** [comment]
Hi I'm facing the same problem with the same setup (Using immutable maps for different state records and having stale state persisted on refresh). Can you tell me how exactly you solved it? I have tried everything at this point. Thanks in advance.

**Comment by mim-Armand** [comment]
Don't remember really which project I was working on when I had this issue! But I think I ended up implementing the functionality myself and decided to not use the library ( as I didn't even need to persist the whole state, just a portion of it ).

**Comment by hrishabh-tykhe** [comment]
https://github.com/rt2zz/redux-persist/issues/1114#issuecomment-549107922
 This helped in resolving my issue.
