### ISSUE TITLE
PersistConfig.throttle definition

### ISSUE THREAD

**Issue by oninojudo** [rt2zz/redux-persist#617]
It would be helpful if PersistConfig.throttle was documented, at least insofar as indicating units.

**Comment by debrice** [comment]
according to 
https://github.com/rt2zz/redux-persist/blob/e92def2bfd819218cce4e0e03c0dbd149c56afc8/src/createPersistoid.js#L38

throttle should be in milliseconds

**Comment by rt2zz** [comment]
updated: https://github.com/rt2zz/redux-persist/commit/8a6c6924f5d09739f96e571199bf57f384f0d791

thanks
