### ISSUE TITLE
persistReducer creates a reducer that will create a new state on each action

### ISSUE THREAD

**Issue by stropitek** [rt2zz/redux-persist#622]
First, thank you for the library!

I noticed that on every action, the new state returned by a persisted reducer changes. Even if state has not changed and the object returned by the base reducer is the same. This is quiet unexpected. Is it intended?

https://github.com/rt2zz/redux-persist/blob/8c01ac8703d8c9665b088f6ce3e2fd357df5afc0/src/persistReducer.js#L145

**Comment by Keethanjan** [comment]
Currently we are also having the same issues. Due to this reselect is not memorizing the values.
Could you guys answer if this is intended?

Thanks in advance!

**Comment by rt2zz** [comment]
sorry this took a while, definitely an important fix. 

proposed solution here: https://github.com/rt2zz/redux-persist/pull/689

feedback appreciated, I will get this into a beta release shortly

**Comment by hockeylagu** [comment]
#747
