### ISSUE TITLE
v4 Rehydrate/persistStore only working sometimes

### ISSUE THREAD

**Issue by zacholas** [rt2zz/redux-persist#626]
I wish I could be more specific on this one, but I've tried a lot of tweaks in my code and can't establish any patterns.... Basically what's happening to me is that rehydration is happening only intermittently in my android emulator. I think it may in fact be a problem with persistStore not running, as I've turned on logging for the rehydration function, and when the problem happens, that callback never gets hit, so there are no logs to look at.

I've used this sort of base code template for a few projects now and have never had this problem before, and am wondering if I accidentally have a few spaghetti-esque remnants around from past projects, or what the deal is. Even if there's no solution around, I'm curious if anyone else has ever had this issue.

I might try just upgrading to v5 to see if that happens to fix it, but wanted to ask first. Thanks in advance.

Specs of the project:
React native 23.0.0
expo 23.0.0
redux 3.7.2
redux persist 4.8.2

**Comment by bintoll** [comment]
+ Have the same, firstly it did not work, i tried to fix it and it was not success, than i started to do other things, a day later it starts working, i removed it because had no time to figure out why, today i turned it again, and it again does not work.

**Comment by zacholas** [comment]
I think this is a problem with either expo or genymotion. Seems to get fixed when I close the android emulator window and re-launch from genymotion.

**Comment by kaym0** [comment]
I have the same problem occasionally. Sometimes when I restart the emulator it still doesn't work, or I get stuff that was edited/deleted by me a while ago reappearing while newer stuff doesn't. I think it just cuts out at a certain point. It would be nice to find out exactly when that is so someone could pinpoint the exact cause.

**Comment by clems36** [comment]
I had a similar problem and I think I found a solution (can't be 100% sure). I had about 30 actions being handled by the same reducer which somehow caused to reducer to use the default values. My solution was to split the action types in multiple reducers.
