### ISSUE TITLE
README is missing about section

### ISSUE THREAD

**Issue by JanKaifer** [rt2zz/redux-persist#647]
Hi,
when I found this repo I had to google what redux-persist should do, why I might want to learn it, etc. Your README don't care about newcomers :smile:.

I'm just suggesting this to you guys since I don't have enough knowledge about redux-persist to make this about section myself.

**Comment by rooque** [comment]
See https://medium.com/@thenewt15/the-definitive-guide-to-redux-persist-84738167975

I think it's a WIP

https://github.com/rt2zz/redux-persist/pull/588
