### ISSUE TITLE
rehydrateAction is gone

### ISSUE THREAD

**Issue by totallymike** [rt2zz/redux-persist#65]
It seems that the provision for a custom actionCreator has been removed at some point since v1.5.3 and v2.0.1.  Is there an alternative recommendation for handing the data to be rehydrated to an action creator upon rehydration?

**Comment by rt2zz** [comment]
What do you currently use rehydrateAction for? The recommendation is currently to do any custom rehydration processing in your reducer, or if you need to do async validation in a saga. 

It was removed because in an attempt to keep the overall api and complexity limited. If you have a use case that cannot be satisfactorily handled elsewise, I would be happy to readd support.

**Comment by rt2zz** [comment]
also fwiw in the short term you should probably stick to 1.5.3 until we have time to think over how this fits into 2.0

**Comment by totallymike** [comment]
The use case that came to mind was triggering a refresh of an authentication token if the prior had expired.

**Comment by totallymike** [comment]
I did end up just keeping our dependency at 1.5.3.  The addition of the `rehydrateAction` to handle this scenario has the odd effect of `persist/COMPLETE` firing before the `persist/REHYDRATE` events, though :)

I'm rather unfamiliar with how sagas work (or what they are, in this context), but I'll do some digging.  It's clear that some rearranging needs to be done.

**Comment by rt2zz** [comment]
Ah, ok refreshing/expiring auth tokens is exactly why I added rehydrateAction in the first place! Since then however we changed how we handle auth tokens. 

My recommendation is you do auth token validation in the persistStore callback:
```js
persistStore(store, config, (err, state) => {
  if(state.auth.token) processToken(state.auth.token)
})
```

Thoughts?

**Comment by totallymike** [comment]
That makes sense to me.  I'm thinking I'm going to pull the whole auth flow out into a middleware, actually.  There I can schedule the next token refresh and so on in a reasonable manner.

Thanks for all your help!
