### ISSUE TITLE
import storage from 'redux-persist/lib/storage' does not work for me

### ISSUE THREAD

**Issue by dhanala89** [rt2zz/redux-persist#658]
Hi there, 

I tried to use the above import but I keep getting error saying import could not be found. I am using redux-persist for my reactjs web app.

**Comment by bmueller-sykes** [comment]
I get the same issue. Something seems amiss here. Some details:

If I try any of the following:

```
import storageLocal from 'redux-persist/es/storage/session';
import storageLocal from 'redux-persist/es/storage/'
import storageLocal from 'redux-persist/lib/storage/'
import storageLocal from 'redux-persist/lib/storage/index'
```

...then I get a React error that says `Error: redux-persist: config.storage is required. Try using import storageLocal from 'redux-persist/es/storages/local'`

Then, in the following cases:

```
import storageLocal from 'redux-persist/es/storages/local'
import storageLocal from 'redux-persist/es/storages/session'
import storageLocal from 'redux-persist/lib/storages/local'
import storageLocal from 'redux-persist/lib/storages/session'
```

...I get a JS import error saying the module cannot be found:
`Module not found: Can't resolve 'redux-persist/specific/path/from/above'`

Digging through the redux-persist library, I see both an `es/storage` folder and a `lib/storage` folder. Nowhere do I see a `storages` folder or sub-folder. I don't know if that means the error message is wrong (it says `storages` in the error message) or I'm importing the wrong way.

**Comment by rt2zz** [comment]
right `storages` was a typo, I just updated it

`import storageSession from 'redux-persist/es/storage/session'` should work. I suspect you are passing it into the wrong config or as the wrong key.

your code should look roughly like:
```
import storageSession from 'redux-persist/es/storage/session'
// ...
let persistConfig = {
  storage: storageSession,
  // ...
}

let reducer = persistReducer(persistConfig, rootReducer)
```

**Comment by bmueller-sykes** [comment]
Thanks for the reply!

Typo makes sense. Here's what I was doing for config:

```
const config = {
  key: 'myKey',
  sessionStorage
}
```

...because that's what the example shows. The fact that the example just shows `storage` and not `storage: [some storage object]` threw me off, but I thought maybe you were doing something clever with JS that I just didn't understand. If the proper format is:

```
const config = {
  key: 'root',
  storage: sessionStorage
}
```

...then that makes way more sense. I'll try again and report back (though it may not be until tomorrow). Meantime, I might suggest updating the docs to be more explicit there for dopes like me who need our hands held. (-;

**Comment by rt2zz** [comment]
good call, will update readme now

**Comment by rt2zz** [comment]
also yes this was certainly the issue, naming things is hard!

**Comment by bmueller-sykes** [comment]
Thanks! One more small note: the v4 to v5 migration section of the docs should be updated as well (that's where I was looking, as I'm an upgrader).

**Comment by dhanala89** [comment]
still an issue for me. when i try to use storage in my reactjs app I get the following error 

> ./src/Config/ReduxPersist.js
> Module not found: Can't resolve 'redux-persist/lib/storage'

Using redux-persist 4.1.0

**Comment by bmueller-sykes** [comment]
This particular thread is just about v5 of redux-persist. There was a big API change from 4 to 5, so if you try to invoke redux persist in the manner detailed above using a version of the library prior to 5.x.x, it will break.

**Comment by rt2zz** [comment]
👍 

Docs have been improved a bit in the last couple weeks

**Comment by drydenwilliams** [comment]
I just did an instal of `redux-persist` and I'm still getting: `Can't resolve 'redux-persist/lib/storage'`

**Comment by bmueller-sykes** [comment]
In case it's helpful, here's a somewhat stripped-down version of how I'm invoking `redux-persist`:

```
import { persistCombineReducers, persistStore } from 'redux-persist';
import sessionStorage from 'redux-persist/es/storage/session';

const persistConfig = {
	key: 'myPersistKeyword',
	storage: sessionStorage
}

const reducers = persistCombineReducers(persistConfig, allMyReducersWhichAreDefinedOutsideThisExample);

export default function configureStore() {

	const store = createStore (
	 reducers,
         ...whatever else you pass to createStore()
	)

	const persistor = persistStore (store)
	return { persistor, store }
}

```

**Comment by Mysterious786** [comment]
Thank you I was facing this error and you resolved it...
