### ISSUE TITLE
Clear stored state from browser console

### ISSUE THREAD

**Issue by icaroponce** [rt2zz/redux-persist#667]
Hello there, 

I've being using this awesome module for some days, and I'm facing a problem while developing a project which I couldn't find an answer in the docs or stackoverflow. 

I'd like to know if it's possible to someway clear the stored state from the browser console. Since I'm still developing the app, we're doing changes to the state structure very often, and seeing that there's already a stored state, when the app loads again we only get the outdated state which was stored. Then would be very convenient for us to find a way to clear the whole stored state some times to order to check the new changes to the redux state.

I tried the basic `localStorage.clear` but once the `persist/REHYDRATE` is dispatched, the old stored state strikes again.

I'm sorry if I missed a very basic point about it.

Thanks,

**Comment by ChrisLahaye** [comment]
You can use the functions `persistor.flush()` to enforce writing the latest redux data to local storage, or `persistor.purge()` to clear the local storage (note that it leaves the redux data intact).

In order to get access to the persistor we the persistor to the appropriate component from the router.

**Comment by ChrisLahaye** [comment]
https://github.com/rt2zz/redux-persist/issues/612  @giacomocerquone

**Comment by icaroponce** [comment]
@ChrisLahaye thank you for your reply. 

I'll try to export the persistor object someway to get access to it into the browser console and be able to call both methods.

**Comment by rt2zz** [comment]
you can access it from the browser console by exposing it as a window variable

i.e.
```js
window.persistor = persistor
```

**Comment by JimLynchCodes** [comment]
I'm getting `window.persistor is undefined`... 🤔

**Comment by ewurufortune** [comment]
I encountered this same problem, to expand on what the highest liked comment here said. in your index.js where persist store is imported, define persistor as a const and set its value as persistStore. then call .purge() on it like so... 
const persistor = persistStore(store);
persistor.purge().then(() => {
  console.log('Persisted state has been cleared.');
});
