### ISSUE TITLE
React Native app crashing immediately after adding redux-persist

### ISSUE THREAD

**Issue by axelkennedal** [rt2zz/redux-persist#669]
I had redux and react-redux working perfectly with my app and wanted to add persistence, so I followed the guide in the readme of this repo, but when I attempt to launch my app it just crashes without any helpful feedback.

I've described the problem in detail [here](https://stackoverflow.com/questions/48344836/redux-persist-crashing-immediately).

**Comment by rt2zz** [comment]
I just updated the docs to be `loading={null}` with a note below about usage
