### ISSUE TITLE
rehydrate fires after first dispatch

### ISSUE THREAD

**Issue by justrag** [rt2zz/redux-persist#673]
If I put a manual dispatch just after `createStore`:
```
const store = createStore(
  persistedReducer,
  composeEnhancers(applyMiddleware(...))
);
const persistor = persistStore(store);
store.dispatch(myActionCreator());
```

the `persist/REHYDRATE` action fires *after* myAction. Is there a way to assure that `REHYDRATE` dispatches first?

**Comment by rt2zz** [comment]
you have a few options.

1. move your dispatch into the persistStore callback:
```js
const persistor = persistStore(store, null, () => {
  store.dispatch(myActionCreator())
})
```
2. move your dispatch to be triggered somewhere inside of your component tree, inside of PersistGate
3. use something like redux-action-buffer to capture the actions and delay their application

I would recommend them in that order, but of course it depends on your specific needs

**Comment by justrag** [comment]
Option 1 worked great, big thanks!
