### ISSUE TITLE
package.json doesn't refer to types

### ISSUE THREAD

**Issue by openscript** [rt2zz/redux-persist#674]
The `package.json` should reference the types.

```
[...]
  },
  "types": "src/index.d.ts",
  "devDependencies": {
[...]
```

I'll create a pull-request for this.

**Comment by BeaveArony** [comment]
I think it should be "typings" instead of "types". At least that's what is working for me.

**Comment by openscript** [comment]
According to https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html it should be `types`.
