### ISSUE TITLE
states are undefined when persistor.pruge  is deleted

### ISSUE THREAD

**Issue by MortezaAghili** [rt2zz/redux-persist#680]
I have an app which load data from the server and saves them in the state. I need to store a few of these states to decrease the load from the server. But when i commented my persistor.purge() in my configureStore app does not startups anymore!

**configureStore.js**

    import { createStore, applyMiddleware } from 'redux';
    import { persistStore, persistReducer } from 'redux-persist';
    import storage from 'redux-persist/lib/storage';
    import hardSet from 'redux-persist/lib/stateReconciler/hardSet';
    import logger from 'redux-logger';
    import createSagaMiddleware from 'redux-saga';

    import reducers from '../reducers';
    import rootSaga from './sagas';

    const sagaMiddleware = createSagaMiddleware();
    const middleware = [sagaMiddleware];

    if (process.env.NODE_ENV === 'development') {
      middleware.push(logger);
    }

    const persistConfig = {
      key: 'rootApp',
      storage,
      stateReconciler: hardSet,
    };

    const persistedReducer = persistReducer(persistConfig, reducers);

    export default () => {
      const store = createStore(persistedReducer, applyMiddleware(...middleware));
      sagaMiddleware.run(rootSaga);
      const persistor = persistStore(store);
      // persistor.purge();
      return { store, persistor };
    };

**index.js**

    import { Provider } from 'react-redux';
    import { PersistGate } from 'redux-persist/es/integration/react';
    import configureStore from './config/configureStore';

    const { store, persistor } = configureStore();
    const onBeforeLift = () => {
      // take some action before the gate lifts
    };

    const App = () => (
      <Provider store={store}>
        <PersistGate loading={null} onBeforeLift={onBeforeLift} persistor={persistor}>
          <MainStack />
        </PersistGate>
      </Provider>
    );

    export default App;

**The error:**

![screenshot from 2018-01-24 16-36-36](https://user-images.githubusercontent.com/6826680/35333662-cb600e84-0124-11e8-87f3-3564ccc0e31c.png)

**Comment by rt2zz** [comment]
I think this is a "bug" in hardSet reconciler. Basically it is hard setting the state to undefined, but in redux persist undefined is supposed to mean "there was no state found" and no reconciliation should occur. PR forthcoming
