### ISSUE TITLE
Need an Example

### ISSUE THREAD

**Issue by grebenyuksv-preply** [rt2zz/redux-persist#696]
Dear maintainers, your library looks great but *v5* just doesn't work for me, I did read the readme and the only [guide](https://blog.reactnativecoach.com/the-definitive-guide-to-redux-persist-84738167975) I've found. It just doesn't write to my localStorage, here's how I setup the store:

```
import { applyMiddleware, createStore } from 'redux';
import { persistStore, persistReducer } from 'redux-persist';
import storage from 'redux-persist/lib/storage';
import thunk from 'redux-thunk';
import rootReducer from '../reducers';

const persistConfig = {
	key: 'root',
	storage: storage,
};
const persistedReducer = persistReducer(persistConfig, rootReducer);

const middlewares = [thunk];
let ehnancer = applyMiddleware(...middlewares);

const isDevMode = process.env.NODE_ENV === 'development';

if (isDevMode) {
	const { composeWithDevTools } = require('redux-devtools-extension'); // eslint-disable-line global-require
	ehnancer = composeWithDevTools(ehnancer);
}

const store = createStore(persistedReducer, undefined, ehnancer);
export default store;
export const persistor = persistStore(store);
```

Is it supposed to automatically persist when my store updates? I actually assumed that.

Please correct me if I'm missing something obvious, but I believe a working demo would solve anyone else's problem of that kind. Does this make sense?

**Comment by Baransu** [comment]
It would work if your reducers are not nested. Here is official documentation about this.
https://github.com/rt2zz/redux-persist#state-reconciler
What I'm doing in my application is persisting store only for one branch of reducer (auth in my case). If you want to persist whole state you have to change merging strategy.

**Comment by grebenyuksv-preply** [comment]
Thanks for your kind answer @Baransu , I did make it write smth into localStorage by wrapping both my root reducer and a nested reducer into `persistReducer`, but now it only saves the root state to `localStorage`, and rehydrates in a weird way. I've already spent several hours on trying too make it work, and I honestly think I won't try anymore until someone helps me with an example. This lib was my first choice because of 4k+ stars. 

Am I having an unlucky day? Could you somehow share exactly what you did to make it work?

**Comment by Baransu** [comment]
```js
const reducers = combineReducers({
  /* auth is just a simple (state, action) => state function reducer */
  auth: persistReducer({ key: 'my-key', storage }, auth), 
  router: routerReducer
});
```
I don't care about other parts of the state to be persisted so I'm applying `persistReducer` only to this one key.
```js
/* I want ReduxDevTools connected to I'm adding this here. */
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const store = createStore(
  reducer,
  composeEnhancers(applyMiddleware(thunkMiddleware, routerMiddleware(history)))
);
export const persistor = persistStore(store);
export default store;
```
I'm passing `store` to my `<Provider/>` and then `persistor` to `<PersistGate/>`. It's exactly the same as in this part of documentation: https://github.com/rt2zz/redux-persist#quickstart.

I hope this will somehow help you.

**Comment by grebenyuksv-preply** [comment]
Thank you so much @Baransu , I did do this all before, but you inspired me for one more try. My setup didn't seem to work for a combination of reasons:

- my reducer was returning a Number, not an Object;
- I still find it a bit weird that `const double = (state, { type }) => ({ value: Math.random() })` does not get persisted even if there are actions before the series of `persist/REHYDRATE`;
- When it does persist, no more actions are dispatched;
- I was misunderstanding the action names `persist/PERSIST` and `persist/REHYDRATE`.

Apparently, everything actually works, I think I'll close this — but still, an example could save me a day. Maybe I'll think of creating one.

**Comment by rt2zz** [comment]
@grebenyuksv-preply sorry this has not been a straight forward integration for you! we are constantly working to improve the docs but it is a tough challenge.

I am glad you got it working. persistReducer should work as expected whether you apply it to the rootReducer or a nested reducer. There are a couple of things to look out for:
1. any state changes dispatched before REHYDRATE will most likely be overwritten by the REHYDRATE action. Usually people use PersistGate or redux-action-buffer or custom strategies to delay firing actions.
2. if you reducer updates state during REHYDRATE, then the state reconciler will skip rehydration for that reducer. This is done so that reducers can opt-in to custom rehydration handling as needed. Unfortunately it does cause confusion as in your case.
3. it is true that you can only persist reducers which have object like state. This may change in the future but it is the case for now.

If you have suggestions for how to further improve the docs please share. I think (2) is the biggest gotcha that we are looking for ways to better communicate.

**Comment by aaesis** [comment]
Hi, I have also the same problem with @grebenyuksv-preply. "When does persist no more actions are dispatched". I also inspired with this [guide](https://blog.reactnativecoach.com/the-definitive-guide-to-redux-persist-84738167975). I search all the possibilities and tried several times, but still I does not work for me. 

Overview of my code (ConfigureStore):

`const persistConfig = {
  key: "root",
  storage: storage
};

function configureStore(): Store {
  const sagaMiddleware = createSagaMiddleware();
  const middlewares = [sagaMiddleware];
  const enhancer =
    process.env.NODE_ENV === "development"
      ? composeWithDevTools(applyMiddleware(...middlewares))
      : applyMiddleware(...middlewares);
  const persistedReducer = persistReducer(persistConfig, createGlobalReducer());

  // create store
  const store = createStore(persistedReducer, enhancer)
  // running saga
  sagaMiddleware.run(rootSaga);
  return store;
}

export const persistor = persistStore(configureStore());

export default configureStore;`

I already put my persistor in my index. What also I want is to have good example and will help me.
