### ISSUE TITLE
No `action.key` on `REHYDRATE` 

### ISSUE THREAD

**Issue by authentik8** [rt2zz/redux-persist#71]
As per the "Custom Rehydration" section in [recipies.md](https://github.com/rt2zz/redux-persist/blob/master/docs/recipes.md), I implemented a `case REHYDRATE` statement in my reducer.

```javascript
case REHYDRATE:
    const { key } = action  // key = undefined !!!
    if (key === 'newAppointmentForm') { // key === 'forms.newAppointmentForm' ?
      const startedMoment = moment(action.payload.startedMoment)
      return Object.assign({}, state, { startedMoment })
    }
```

However, when the action fires during the rehydration process, the action has no `key` attribute attached.

My alternate method (which seems to work) is to simply pull out the relevant part of the state tree from `action.payload`, and implement my custom rehydration logic there:

```javascript
case REHYDRATE:
  const startedMoment = moment(action.payload.forms.newAppointmentForm.startedMoment)
  return Object.assign({}, state, { startedMoment })
```

Could you confirm that this is the "new" way of doing things, and that the docs are just out-of-sync with the API?

Thanks!

**Comment by rt2zz** [comment]
Ah those recipes were out of date, I just updated them. 

Your alternate method is perfect, but one note is you might want to be careful to make sure the keys are defined i.e.
```js
if (action.payload.forms && action.payload.forms.newAppointmentForm) {
  const startedMoment = moment(action.payload.forms.newAppointmentForm.startedMoment)
}
```

**Comment by authentik8** [comment]
Very true, well spotted! 

Thanks for getting back to me, docs look fine now. Love the library!
