### ISSUE TITLE
How do I access .purge() for an onClick event?

### ISSUE THREAD

**Issue by heymaddieh** [rt2zz/redux-persist#710]
I'm trying to clear redux-persist when the user logs out of the app, and I'm having trouble accessing the persistor method .purge().  Do I need to pass down the method through props, or is it imported? I've tried passing the persistor down into the component through react-router v.4 but its replaces all other props being passed down into that component. 

Ideally I'm trying to do this: 
`
if(logout === true){
          this.props.persistor.purge()
          this.props.history.push('/');
 }
`

Any ideas?

**Comment by rt2zz** [comment]
are you already resetting state on logout?

if so the reset state will be written over the old state and you should be good, no purge required.

if you are not then I recommend you look into it. that is out of scope for this project, but fwiw I usually do state resets via a custom action.

**Comment by heymaddieh** [comment]
So what is the purpose of purge? Where would it be used?

**Comment by rt2zz** [comment]
purge is mostly used for clearing storage during dev. There could be some valid use in prod but it would be something specific like purge old state after a migration.

**Comment by hpelitebook745G2** [comment]
@heymaddieh have you figured out how to do this?
