### ISSUE TITLE
Testing create-react-app fails due to createWebStorage

### ISSUE THREAD

**Issue by j33n** [rt2zz/redux-persist#722]
I know this should be posted on Stackoverflow, but also It might be a redux-persist issue.
I'm using create-react-app and I want to test a component using jest
My _App.test.js_ looks like this:
```
import expect from "expect";
import React from "react";
import { shallow } from "enzyme";
import App from "./App";

describe("Test App.js", () => {
	function setup() {
		return shallow(<App />);
	}
	it("renders a div of class container", () => {
		const wrapper = setup();
		expect(wrapper.find("div").props().className).toBe("container");
	});
});

```
My App.js looks like this except for imports I removed, the whole file is [here](https://gist.github.com/JeanAbayo/bdc95bcbfdd61afe3787b19213e73d02)

```
class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <PersistGate loading={<div />} persistor={persistor}>
          <Router history={history}>
            <div className="wrapper">
              <section className="sl_hero">
                <Navbar />
              </section>
              <section className="sl_footer">
                <Footer />
              </section>
            </div>
          </Router>
        </PersistGate>
      </Provider>
    );
  }
}

export default App;

```
My error looks like this, Any idea what is required to test with redux-persist while using CRA

<img width="801" alt="screen shot 2018-02-15 at 16 12 43" src="https://user-images.githubusercontent.com/19430799/36258825-38209c6a-126d-11e8-9737-6fc7746036a9.png">

**Comment by rt2zz** [comment]
so I am guessing you are importing storage from `redux-persist/es/storage`, but your testing environment does not support es modules. In that case the quickest fix is going to be to import from lib `redux-persist/lib/storage`.

**Comment by JeanAbayo** [comment]
I actually switched to using `redux-persist/lib/storage` after seeing issue #488 but the output was the same.
