### ISSUE TITLE
What is the `key` config property exactly?

### ISSUE THREAD

**Issue by corysimmons** [rt2zz/redux-persist#726]
Grepped README for it and just saw it being used.

Is it just there to uniquely identify the `PersistGate`?

**Comment by rt2zz** [comment]
key is used to set the storage key and keep track of which persists have completed (the the case of multiple persistoids)

We could give it a default, but making it explicit seemed like it would avoid confusion in the future.

**Comment by corysimmons** [comment]
Thanks for clearing that up. =)
