### ISSUE TITLE
FEATURE REQUEST: Nested config

### ISSUE THREAD

**Issue by serhiipalash** [rt2zz/redux-persist#727]
Hi!
Is it possible to use one complex config for whole state, not multiple configs each for one reducer, but one config for rootReducer?

```
const rootConfig = {
  key: 'root',
  storage: storage,
  blacklist: ['navigation'],
  children: {
     auth: {
         whitelist: ['email'],
     },
     user: {
        blacklist: ['tokens']
     }
  }
}
```

**Comment by rt2zz** [comment]
that is not possible, we have explored things to expose deep filtering, but settled on nested persists as being the best generic approach that preserves performance. 

https://github.com/edy/redux-persist-transform-filter allows for deep filtering however

**Comment by serhiipalash** [comment]
> that is not possible

Ok, I understand. 

In my case I have a very big reducer imported from `react-redux-firebase` package and it has `data` child with local copy of database collections. I just don't want to persist all `data` as it is very big.

Thanks anyway.

**Comment by PiotrKujawa** [comment]
Here is what you can do using my package **[redux-deep-persist](https://github.com/PiotrKujawa/redux-deep-persist)**
which can be helpful in creating a config for redux-persist.
```js
import { getPersistConfig } from 'redux-deep-persist';

const config = getPersistConfig({
    key: 'root',
    storage: LocalStorage, // whatever storage you use
    whitelist: [
        'a1.b1.c1',  
        'a2.b2.c2',  
        'a3',
        'a4.b4.c4.no.matter.how.deep.you.go'
    ],
    rootReducer, // your root reducer must be also passed here
    ... // any other props from original redux-persist config, omitting the stateReconciler
});
```
