### ISSUE TITLE
React-native 0.53.2 upgrade error

### ISSUE THREAD

**Issue by gusgard** [rt2zz/redux-persist#728]
After I upgrade to `0.53.2` I'm having this error in `Release mode` `TypeError: undefined is not an object (evaluating 'Object.keys(inboundState)')`. Is anyone having the same issue?

**Comment by pdoggi** [comment]
@gusgard I am getting this error with `redux-persist: ^5.9.1` and `react-native: 0.55.4`. Were you able to fix the error?

**Comment by gusgard** [comment]
We switch to version 4, is more a workaround than a fix.

**Comment by pdoggi** [comment]
Thanks @gusgard! Turns out for me, I am using `redux-offline` and it rolls with a copy of `redux-persist ^4.5.0`, and I still had the error. I had to patched [this line](https://github.com/rt2zz/redux-persist/blob/v4.5.0/src/autoRehydrate.js#L51) with a `try/catch` wrapper in `autoRehydrate.js`

**Comment by DianaKoenraadt** [comment]
Does anyone know if there's a neater solution?
