### ISSUE TITLE
Compression?

### ISSUE THREAD

**Issue by tcjustin** [rt2zz/redux-persist#73]
Has there been any thoughts on using compression before storing to local storage?  Was playing around with this library, http://pieroxy.net/blog/pages/lz-string/index.html, and it looks like you can get a significant storage savings.

**Comment by rt2zz** [comment]
Great idea. Probably would want the ability to toggle compression on a per reducer basis. I have not thought about this much but an open to suggestion

**Comment by rt2zz** [comment]
👍   https://github.com/rt2zz/redux-persist-transform-compress

requires redux-persist@3

**Comment by tcjustin** [comment]
Awesome, I hadn't got around to implementing it myself, thanks for knocking this out.
