### ISSUE TITLE
More robust loading component

### ISSUE THREAD

**Issue by heygrady** [rt2zz/redux-persist#733]
I've been using react-loadable for code splitting their docs specify a loading component that takes a few different props to help manage the loading experience more fully.

Most interesting is the use of a "delay" to prevent the loading screen from flashing. Right now redux-persist would force a user to provide their own smart loading function that implements these timeouts. It would be awesome if the `<PersistGate />` implemented a few timers, like what Loadable does, to track the progress of loading.

https://github.com/jamiebuilds/react-loadable#avoiding-flash-of-loading-component

In a nutshell, a redux-persist `<Loading />` component should adhere to the react-loadable loading API (because it's simple and useful).

Here is a complete component that works with react-loadable but not with redux-persist.

```js
import React from 'react'
import PropTypes from 'prop-types'

const Loading = ({ error, pastDelay, timedOut }) => {
  if (error) {
    return <div>Error!</div>
  } else if (timedOut) {
    return <div>Taking a long time...</div>
  } else if (pastDelay) {
    return <div>Loading...</div>
  } else {
    return null
  }
}

Loading.propTypes = {
  error: PropTypes.bool,
  pastDelay: PropTypes.bool,
  timedOut: PropTypes.bool
}

export default Loading
```

**Comment by rt2zz** [comment]
There is a decent amount of code that goes into timeout and delay: https://github.com/jamiebuilds/react-loadable/blob/master/src/index.js

I wonder if this could be abstracted into another module that is generally applicable, so the composition with PersistGate might look something like

```js
<PersistGate
  persistor={persistor}
  loading={<DelayedRender dealy={200}><Loading /></DelayedRender>}
  >
```

**Comment by heygrady** [comment]
That's fair enough. Adding delay like that will work and will avoid you having to add extra code into this library. I was seeing if there was a way to adopt a common loading interface that I've encountered with other libraries.

FWIW, the code for actually managing the two timeouts isn't very much to add. I notice that a major difference between redux-persist and react-loadable is that you ask for a `<Loading />` (a rendered component) while react-loadable asks for `Loading` (a component reference). With your model I could create a simple `withTimers` HOC and pass a wrapped loading component into redux-persist to accomplish the same thing.
