### ISSUE TITLE
peerDependencies on react-native@^0.18 

### ISSUE THREAD

**Issue by willks** [rt2zz/redux-persist#75]
Hi,
  Any chance on support react-native 0.23.x? I'd love to use this as I have not found a clean way to restore long-life app state.

**Comment by rt2zz** [comment]
Ya redux persist is react agnostic. Specifically for react native it works with all versions, just make sure to pass in AsyncStorage as the storage engine

**Comment by willks** [comment]
Thanks for that - I had an issue with deps which I fixed. Integrated redux-persist and now happily restoring state to my reducers.

Thanks!!

**Comment by rt2zz** [comment]
:+1:
