### ISSUE TITLE
How to convert string to object when restore the store?

### ISSUE THREAD

**Issue by deju** [rt2zz/redux-persist#77]
Hi, my store is 
    {userStore: {name: '', duty: '', userObj: {"first":xxx, "second": xxx}}}

When restore from the AsyncStorage, i found the the value of  key userObj is String, not Object, how to fix it?

**Comment by deju** [comment]
And i do not want to change the data struct.

**Comment by rt2zz** [comment]
AsyncStorage keeps everything as strings. However Redux persist handles deserialization for you so you should never need to touch the raw string output. 

Can you paste the code where you are observing a string value and maybe I can better understand the context.

**Comment by deju** [comment]
@rt2zz 
reducers:
import userReducer from './user';
module.exports = combineReducers({
	userStore: userReducer,
})

in './user.js' file:
const initialState = {
	duty: null,
	isLoggedIn: false,
	user: {'name': 'guest'},
	loginStatus: null,
	loginError: null,
};
That is the initialState.

I run the app, close it, and restart the app. I got the value of `user` is "{"name":"guest"}" in console. It is just a string, not a object.

**Comment by deju** [comment]
I write the:
      case REHYDRATE:
			// restore from localstorage
			let userStore = action.payload.userStore;
			let user = action.payload.userStore.user;
			
			if(_.isString(user)){
				user = JSON.parse(action.payload.userStore.user);
			}
			//console.log(action);
			return {
				...state,
				duty: userStore.duty,
				isLoggedIn: userStore.isLoggedIn,
				user: user,
			}
			break;
It is ok now. Thx. @rt2zz

**Comment by rt2zz** [comment]
are you using redux-persist-crosstab?

I am glad you got it working but this is unexpected behavior and hopefully we can figure out what is going on.

**Comment by deju** [comment]
@rt2zz No, i was not used redux-persist-crosstab. I think that is a plugin for browser. But my app is a react-native app. I used the code above and everything is fine. Thank you.  :)

**Comment by deju** [comment]
Close the issue. I will let you know if i got any problems.
