### ISSUE TITLE
Persistor.purge() doesn't clean all data

### ISSUE THREAD

**Issue by williamliangwl** [rt2zz/redux-persist#770]
## What I want to achieve
When my app crashes, I want to clear the data persisted in storage, thus when user re-open the application, which will trigger the Rehydrate, will update the redux store to be default values and the user can continue to use the app ( avoiding the error component, of course )

## Problem
So I put persistor.purge() in the ErrorUtils.globalHandler of React Native, but when the Rehydrate happens, the data passed along the redux action still has the old data before crashing

## Workaround tested
I tried to use redux-reset right after the persistor.purge() and now the Rehydrates only passes the default values.

## Question
The question is that: **What does the persistor.purge() then ?**

**Comment by williamliangwl** [comment]
After doing some tests and check, I found the following:

> the purge() seems really not clearing any data, even at the storage itself.

I am using AsyncStorage and the way I check the data is following the guide [here](https://github.com/jhen0409/react-native-debugger/blob/master/docs/debugger-integration.md#use-requireprovidesmodule-in-the-console) 

Is it a problem of using the AsyncStorage ? I haven't test with other storage type and only tested in Android device

**Comment by williamliangwl** [comment]
I finally found out the problem!

To make things simple, let's make some assumptions:

- The redux state has several keys: auth and nav
- There exists a component with its componentWillUnmount is to dispatch change on the nav state
- There also exists a global error handler which will purge all keys in the AsyncStorage

When an error happens, the order of call is:

1. componentWillUnmount
2. global error handler

Since both calls above will trigger promise / async actions, we cannot make sure who will finish first. However, most of the time, the **purge** will finish **first**, while the nav state change second.

This scenario will lead to:

1. Before error -> The redux state is { auth: "something", nav: "something" }. Same value exists in the Async storage
2. On error -> the purge finishes first -> The redux state remains the same as no 1, but Async storage is empty
3. On error -> the nav state change finishes -> The redux state becomes { auth: "something", nav: "" }. Then this change will write to the AsyncStorage again.

That's why it creates "illusion" that the purge is not working ( for auth key ). Sorry for the confusion in this issue, this can be closed now :)

**Comment by ronnierios** [comment]
I have the same problem. I try to reset my state from a custom action, but only works for some reducers.

const appReducer = combineReducers({
  plans,
  contracts,
  user,
  appState
})

const rootReducer = (state, action) => {
  console.log("STATE", state)
  if (action.type === 'RESET') {
    state = undefined
  }

  return appReducer(state, action)
}

export default rootReducer

I also tried to reset the state passing the default values, without exit

//Action
export const clearPlans = function () {
        return {
            type: CLEAR_PLANS,
            payload: []
        }
}

//Reducer
const initialState = {
  plans: [],
  persistExpiresAt: DATA_EXPIRES_AT,
};

const plans = (state = initialState, action) => {
    switch(action.type) {
        case FETCH_PLANS:
            console.log(action.payload)
            return {...state,
              plans: action.payload
            }
        case CLEAR_PLANS:
            console.log(action.payload)
            return {...state,
              plans: action.payload
            }
        default:
            return state
    }
}

export { plans }

How did you handle the redux state? Thank you in advance

**Comment by Vall3y** [comment]
Ran into the same issue. The solution suggested here is to wipe your own state and have redux-persist persist the wiped state, which means this is a workaround as it doesnt require you to call `persistor.purge` at all.

**Comment by vinhphamthanh** [comment]
Hi @williamliangwl ,

Using redux-reset just make your store clean in the current browser tab.
If you open another tab, all state persisted there.

Do you have any solution to purge the persistor so far.

Regards,

**Comment by williamliangwl** [comment]
Hi @vinhphamthanh, to be honest I have never implemented redux in web, so I might not have good answer to your problem

But after skimming this [link](https://spectrum.chat/react/general/sharing-redux-state-across-multiple-browser-tabs-windows~954300ae-736a-4a35-bc49-e60897d9b49b), it looks like you can store the redux to the `localStorage` which can be synced across tabs

**Comment by mrakhgari** [comment]
According to the [doc of redux](https://redux-toolkit.js.org/usage/usage-guide). If you want to clear states with `persistor.purge()` you have to add `extraReducers` to each slice that you want to get cleaned. 
The syntax is like:
```
import { PURGE } from "redux-persist";

....
extraReducers: (builder) => {
        builder.addCase(PURGE, () => {
            return initialState
        });
    }
```

**Comment by rangerisrael** [comment]
@mrakhgari  thanks bro
