### ISSUE TITLE
error：'store.dispatch({  type: _constants.PERSIST})     ,undefined is not a function;please help me

### ISSUE THREAD

**Issue by chenyinlong** [rt2zz/redux-persist#771]
undefined is not a function (evaluating 'store.dispatch({
          type: _constants.PERSIST,
          register: register,
          rehydrate: rehydrate
        })')
persist
    F:\cyl\work\YUNTONG\node_modules\redux-persist\lib\persistStore.js:104:21
persistStore
    F:\cyl\work\YUNTONG\node_modules\redux-persist\lib\persistStore.js:108:2
<unknown>
    F:\cyl\work\YUNTONG\src\redux\index.js:16:31

**Comment by lalitkumar50678** [comment]
I got same issue.
