### ISSUE TITLE
React Native - Android dev mode - rehydrated called after timeout

### ISSUE THREAD

**Issue by Noitidart** [rt2zz/redux-persist#784]
This question is for other react-native devs on Android that come across this question.

Android dev mode is horrible with timeouts and event callbacks on proper time. Here is a quote:

https://github.com/archriss/react-native-snap-carousel#important-note-regarding-android

> Android's debug mode is a mess: timeouts regularly desynchronize and scroll events are fired with some lag, .... On Android, you will experience issues with timeouts triggering when expected when JS Dev Mode is enabled, and you might have trouble with unreliable callbacks and loop mode when it isn't.

Due to this, while in dev mode only, I get:

> redux-persist: rehydrate for "primary" called after timeout. Object { ... } undefined

And my whole store gets wiped out.

Do you react-native on android dev have any experience with a work around for this?

**Comment by jamsch** [comment]
Type `adb shell date && date` to figure out time discrepancies between the device and the computer. If the device is an emulator, reboot the emulator by holding the power button and re-opening the emulator. 

`AsyncStorage.get()` often never resolves, especially after the first time you reload. This issue specifically has been ongoing for React Native -- https://github.com/facebook/react-native/issues/14101 https://github.com/facebook/react-native/issues/18372 https://github.com/facebook/react-native/issues/12830

One thing you may want to try is changing the storage engine to `redux-persist-filesystem-storage` which may fix this issue.

**Comment by Noitidart** [comment]
Oh wow thanks very much for that awesome reply!! Those linked issues are super helpful. It's ok I don't want to move to a seperate storage engine just for dev mode. This only happens in dev mode correct? (from my experience it seems so). If its not "just in dev mode" then for sure ill switch engine.

**Comment by jamsch** [comment]
In my experience it only occurs in dev mode. I have quite a large production app running with the latest version of redux-persist using AsyncStorage on Android and there's been no problems so far besides not being able to effectively debug it while using the remote debugger.

**Comment by Noitidart** [comment]
Sincerest thanks @jamsch for your replies!! Should I close this topic out do you think? I thought it would be helpful for people searching in redux-persist repo first as thats where the error is happening. But after seeing those issues it makes total sense to be in react-native repo's

**Comment by jamsch** [comment]
We can just leave the package maintainer to decide ;)

**Comment by kopax** [comment]
@Noitidart Does it work well on react-native ? (iOS/Android) I can see many open issues regarding native, I am just not sure if it is that superb.
Thanks

**Comment by Noitidart** [comment]
@kopax  yeah it works perfectly on react-native. Just ignore the dev issue. Any issue that is easy to bear with can be overlooked. Simple restart of the app when it hangs is all it takes to fix dev. And its perfect in production.
