### ISSUE TITLE
Rehydrate action is triggered after the Persist action and erase the redux state

### ISSUE THREAD

**Issue by karimone** [rt2zz/redux-persist#788]
I installed redux-persist and seems to work because I can see the actions triggered in the logs.

I have a flow where the app is loaded with a query param. The param is used to call an api endpoint and the result is saved in the store. What I see in the logs is the reversed order of the actions!

Load the page with the query param

 1. action persist/PERSIST
 2. my actions
 3. router5 load another page (another action)
 4. action persist/HYDRATE
 5. my action fails here because some values were erased by the hydrate.

I'm not an expert, but I guess it should be reversed? first the hydrate and then the persist. Right?

Here the configuration:

    import { createStore, applyMiddleware } from 'redux'
    
    import { persistStore, persistReducer} from 'redux-persist'
    import storage from 'redux-persist/lib/storage' // defaults to localStorage for web and AsyncStorage for react-native
    import autoMergeLevel2 from 'redux-persist/lib/stateReconciler/autoMergeLevel2';
    
    import {router5Middleware, } from 'redux-router5';
    import { reduxPlugin } from 'redux-router5';
    import reduxThunkMiddleware from 'redux-thunk';
    import promiseMiddleware from 'redux-promise-middleware'
    
    
    import reducers from 'reducers';  // the result of a combineReducers
    import ic_settings from 'settings';
    import {createLogger} from 'redux-logger'
    
    
    const loggerMiddleware = createLogger({
       level: ic_settings.REDUX_LOG_LEVEL,
    });
    
    
    export default function configureStore(router) {
    
        // create the middleware for the store
        const createStoreWithMiddleware = applyMiddleware(
            router5Middleware(router),
            promiseMiddleware(),
            reduxThunkMiddleware,
            loggerMiddleware,  // redux-logger
        )(createStore);
    
        const persistConfig = {
            key: 'root',
            storage,
            stateReconciler: autoMergeLevel2,
            whitelist: ['tab', 'business']
        };
    
        const persistedReducer = persistReducer(persistConfig, reducers);
    
        const store = createStoreWithMiddleware(persistedReducer);
    
        router.usePlugin(reduxPlugin(store.dispatch));
    
        const persistor = persistStore(store);
        return { store, persistor };

Any idea?

**Comment by karimone** [comment]
Here a screenshot of the logger. I'm sure something is wrong in the configuration, what can make the `hydrate` running after the `persist? Do I miss something in the config?

<img width="590" alt="screen shot 2018-04-05 at 21 46 14" src="https://user-images.githubusercontent.com/564180/38364211-033d44ba-391b-11e8-8e7e-39946ec6cea5.png">

**Comment by karimone** [comment]
Was my fault. I had some calls running outside the PersistGate. Bad design. Mea culpa.

**Comment by kevinho** [comment]
removing calls outsite persisitgate will make it work? rehydrte before persist?

**Comment by jacobedawson** [comment]
For fellow Googlers, I managed to resolve this issue by adding a 'stateReconciler' property to the persistConfig object:

```
// store/index.js 
// other imports...
import autoMergeLevel2 from "redux-persist/lib/stateReconciler/autoMergeLevel2"; // ADDED

export default initialState => {
    // usual setup
    const persistConfig = {
        key: "root",
        storage,
        stateReconciler: autoMergeLevel2 // ADDED
    }
}
```
The relevant info in redux-persist is here: [https://github.com/rt2zz/redux-persist#state-reconciler](https://github.com/rt2zz/redux-persist#state-reconciler)

**Comment by kodunmi** [comment]
for anyone having this issue, 

clear your localStorage

**Comment by tamangsuresh** [comment]
Any one have found solution on it. I'm using it in react native. I'm using persist v6.

**Comment by jai-k-gohil** [comment]
For anyone having this issue, if it's not stateReconciler issue then, sometimes when the application page is refreshed or reloaded, so the pending actions might not be completed. So for newer versions, we can do this -
```
import { persistStore } from "redux-persist";
import { useEffect } from "react";

const store = configureStore({...});
const persistor = persistStore(store);

//call on before leaving the page
useEffect(() => {
    const flushStoreUpdates = async () => {
      await persistor.flush(); // this worked for me
    };
    window.addEventListener("beforeunload", flushStoreUpdates);
    return () => {
      window.removeEventListener("beforeunload", flushStoreUpdates);
    };
  }, []);
```

Hope this helps!
