### ISSUE TITLE
Not compatible with taobaofed/react-web

### ISSUE THREAD

**Issue by Tiagojdferreira** [rt2zz/redux-persist#79]
Hey! First of all, great work on the lib, I am currently using it for a personal project https://github.com/Tiagojdferreira/ryuutama and I am loving it.

Recently I have added [taobaofed/react-web](https://github.com/taobaofed/react-web) and realised that both libraries don't seem to work together. You can find the original issue here https://github.com/taobaofed/react-web/issues/94

I will try to find more details about the problem, but you can see that commenting out redux-persist makes the app work again
https://github.com/Tiagojdferreira/ryuutama/commit/891ab33f9b2654f93df8044f286e89372e3c89c0

**Comment by rt2zz** [comment]
Ah, i have a pretty good idea what is going on here. Tldr; try redux-persist v3 `npm i redux-persist@next`

It removes the action buffer

**Comment by Tiagojdferreira** [comment]
That seems to partially solve the problem, but now I don't seem to persist the data in between sessions. I

**Comment by rt2zz** [comment]
Hm, sounds like there may be some issue/conflict with the `AsyncStorage` implementation in react-web.

To debug further the relevant code is in `src/getStoredState.js`. Possibly `getAllKeys` or `getItem` is failing...

**Comment by rt2zz** [comment]
fix: https://github.com/taobaofed/react-web/pull/96

**Comment by Tiagojdferreira** [comment]
Thanks for your quick reaction. I will try this out this weekend.
