### ISSUE TITLE
Cross-tab syncing

### ISSUE THREAD

**Issue by jeremejevs** [rt2zz/redux-persist#8]
Since this lib is backend-agnostic, it probably shouldn't implement any localStorage event listening, but a recipe would be nice (e.g. the usual authentication scenario, where a user logs in/out in one tab, and the other tab gets updated accordingly). How would you go about syncing the state across tabs, when using redux-persist?

**Comment by rt2zz** [comment]
This is something I have been wanting to do. The underlying mechanism should be fairly trivial using the [window storage event](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API) but I am not sure about best practices for merging conflict such as when seperate changes occur on both tabs simultaneously.

Maybe instead of syncing state we should sync/replay actions?

Also I am wondering if we can generalize this to work cross device using webrtc.

Let me know if you have any thoughts, or make a pull request if you have a working implementation.

**Comment by jeremejevs** [comment]
Unfortunately, I'm on a very tight schedule with my project, and I can't let myself sink extra time into this right now (it's not a game-breaking problem, since everybody is used to getting "your token has expired" from regular websites, and I'm not persisting any cached data yet). However, I'll gladly revisit this once I'm done with the first phase.

Otherwise, maybe not caring about conflicts and overwriting, like it's done right now, is sufficient? Unless somebody is trying to persist user-modifiable data (but in that case they probably shouldn't be using a convenience lib in the first place, and roll their own). If the app persists a lot of frequently changing stuff (which it shouldn't), something like `reselect` could probably alleviate most of the extra overhead?

Syncing/replaying actions is actually a good idea, but I can see it conflicting with routing (e.g. two tabs with different pages open sending redundant or even potentially harmful actions to each other; unless I'm missing something, and this can't actually make any harm) and other redux-incompatible things. However, maybe some kind of an action filter could help with that? E.g. "I want to sync only auth- and sidebar-related actions, but not the rest".

**Comment by rt2zz** [comment]
https://github.com/rt2zz/redux-persist-crosstab

took about 20 lines :D 

It is not well tested, so please let me know how it goes.

**Comment by rt2zz** [comment]
closing for now. I think there is work to do to further abstract this, but I imagine https://github.com/rt2zz/redux-persist-crosstab will cover a larger portion of the use cases.

**Comment by jeremejevs** [comment]
Sorry for not getting back to you earlier, thanks for implementing this! Works like a charm. Certainly sufficient for something like auth token synchronization (which doesn't update very often nor isn't likely to be overwritten from multiple tabs simultaneously).
