### ISSUE TITLE
Supply key to transforms

### ISSUE THREAD

**Issue by Kim-Andersen** [rt2zz/redux-persist#80]
It would be helpful if the transforms' "in" and "out" handlers receive the current key as an argument. That would enable per-key transform logic.

**Comment by rt2zz** [comment]
👍  https://github.com/rt2zz/redux-persist/commit/5dbe16d1aff7d7d62827b68d55616a7e2c8919ea

great idea. To go along with it I created a new [`createTransform`](https://github.com/rt2zz/redux-persist/blob/master/src/createTransform.js) method and also published [redux-persist-transform-compress](https://github.com/rt2zz/redux-persist-transform-compress)

Let me know how that goes

**Comment by rt2zz** [comment]
one thing that is not entirely solved by this api though is the ability to run certain transforms before serialization and others after...

**Comment by Kim-Andersen** [comment]
@rt2zz Thanks for adding this. Finally got to apply your solution, and it works like a charm.
