### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by JonathanLehner** [rt2zz/redux-persist#804]
This seems like a good project but the documentation is very confusing. Especially the differences between version 4 and 5 are not clear. Some complete example for use with Immutable and with HMR would be good. 
For immutable for instance there are also redux-persist-immutable and
redux-persist-transform-immutable and it is completely unconceivable which one to use with redux persist and how.
If someone has a good explanation it would be nice to add it to github, after I understand it I can make a PR as well.

**Comment by SteveMellross** [comment]
Yeah, I also found the migration documentation a bit confusing. I've got it mostly sorted now, but clearing it up could help if other people are still migrating.

`persistCombineReducers` is used in the migration document but is nowhere to be found in the normal documentation. Pretty straight forward but slightly confusing.

Migration now seems to store the version in `state._persist.version` when before (in `redux-migrate-persist`) it was stored in a user-defined location via a custom reducer and selector. I was hoping this might work while upgrading from version 4 using `getStoredStateMigrateV4` if I got everything in the right order, but `redux-migrate-persist` no linger seems to work with `redux-migrate` v5, so... 🤷‍♂️ 

I'd like to avoid having to reset users state in the future...

**Comment by aguynamedben** [comment]
@SteveMellross Thanks for the info on persistCombineReducers.

Also, if it's not too late, take a look at https://github.com/rt2zz/redux-persist/issues/434, I'm about to try that method for v4->v5. Someone verified they got it working.

**Comment by ckalika** [comment]
Closing this as it relates to v4/v5. Documentation definitely needs to be updated, but it's separate from this issue.
