### ISSUE TITLE
How to use PersistGate with react-router-dom?

### ISSUE THREAD

**Issue by someden** [rt2zz/redux-persist#814]
PersistGate is a PureComponent, so children doesn't rerender, when location changed with react-router-dom

Example: https://stackblitz.com/edit/redux-persist

**Comment by someden** [comment]
I have found some solution:
```
const PersistGateWithRouter = withRouter(PersistGate);
```
But maybe PersistGate doesn't need to be a pure?

**Comment by knpwrs** [comment]
`PersistGate` and `Provider` need to go outside of `ReactRouter`:

```jsx
export default () => (
  <Provider store={store}>
    <PersistGate loading={null} persistor={persistor}>
      <Router history={history}>
        <App />
      </Router>
    </PersistGate>
  </Provider>
);
```
