### ISSUE TITLE
Persisting Javascript Date objects

### ISSUE THREAD

**Issue by MichaelDanielTom** [rt2zz/redux-persist#82]
Hey guys, I'm trying to persist a Javascript Date object in the redux store, but it seems to be serializing into a string automatically, without being deserialized upon rehydration. Right now I can handle it with a transform (although it's a little messy), I feel like this should be default behavior, what do you guys think? 

At the very least we could put a warning when persisting and then rehydrating gives you back a different object.

**Comment by marvinhagemeister** [comment]
I'm not sure if this is a great thing to add to our core. Date objects will be converted to string by  `JSON.stringify()` which is used in the default serializer.

One great advantage of redux is that everything only has to deal with plain objects, not with functions. Here is a great answer by redux's creator to a similar question [on Stackoverflow](http://stackoverflow.com/questions/32352982/how-to-put-methods-onto-the-objects-in-redux-state)

**Comment by rt2zz** [comment]
ya, for the reasons outline above, I usually store my dates as ms integers, and convert to Date/moment as needed in the application (but outside of redux).

In so far as redux-persist goes, I think a transform is the right way to handle this, probably something like https://github.com/cognitect/transit-js which is performant and will handle dates as well as maps and symbols.

**Comment by rt2zz** [comment]
for reference creating a transit transform would look almost exactly like: https://github.com/rt2zz/redux-persist-transform-immutable/blob/master/index.js except instead of transit-immutable-js use plain transit and instead of toJSON and fromJSON use read/write.

**Comment by rt2zz** [comment]
Having x many more months of redux experience, I think the best practice is to store your dates as integers (or other serializable format). 👍

**Comment by JonesN7** [comment]
Don't know if this is best practice but: converting a date to string with built in methods, and then creating a new Date with that string, will give you the correct date object. So one could just store the date as a string, and create a new date object when used. Was useful in my case, since I had a lot of date object operations.

```
const dateString = new Date(Date.now()).toString())
Date now = new Date(dateString)
```

**Comment by chrylis** [comment]
At a minimum, the persistor needs to log a warning when saving a date object. This is a really nasty gotcha that violates the general API promise of getting back what you put in, and even if it's unquestionably better to store the integer, the user shouldn't have to spend an hour tracking down  `undefined is not a function` errors because the object that was a Date is now a string with no warning.

**Comment by marvinhagemeister** [comment]
@chrylis That's a great ux suggestion. We could print a warning in dev mode for the default persistor. I'll have to check how that would work with immutablejs (haven't touched it in a while), but I'm all for helpful warning messages.

**Comment by rt2zz** [comment]
I definitely like the idea of checking for Date objects (in dev) and logging if found. 👍 

Additionally I think a good solution for people who want to store date objects in redux state would be to have a transform that implements https://github.com/cognitect/transit-js. It would be almost identical to https://github.com/rt2zz/redux-persist-transform-immutable except using plain transit-js.

**Comment by digitalmaster** [comment]
I think in principle i agree that what goes in should be what comes back out... Cases where this is not true should be clearly highlighted (i like the idea of a dev warning here).

I'm new to redux persist 🙈 .. is there some example code you could point me to that shows how to transform strings back to dates on rehydrate?

**Comment by you-fail-me** [comment]
Hey, @rt2zz , I would like to ask you a bit more about creating a transform for dates. Won't transit-js cause troubles if my code expects plain js objects? AFAIK it returns maps instead

**Comment by rt2zz** [comment]
@you-fail-me plain transit-js deals with plain js objects, transit-js-immutable adds the Map etc.

`json-literal` is just as well (maybe better?). I do not want to increase the lib size by making that default, but I am open to suggestions for how to work this into the api / core lib in a way that is opt-in and does not affect bunlde size.

**Comment by aguynamedben** [comment]
This hasn't been responded to in a long while, so I'm going to mark it as stale. Please feel free to continue the conversation and I'll reopen.

@chrylis you mentioned
> At a minimum, the persistor needs to log a warning when saving a date object. This is a really nasty gotcha that violates the general API promise of getting back what you put in
That suggestion has 31 upvotes. Would you help the redux-persist project by contributing a PR that does that? I'd be happy to review it and merge it.

**Comment by vcarel** [comment]
@digitalmaster got the point. However instead of traversing object tree, one may just json-serialize and deserialize objects using _replacer_ and _reviver_ to handle dates.

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Parameters
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Syntax

Here the "codec":
```
const replacer = (key, value) => date instanceof Date ? value.toISOString() : value

const reviver = (key, value) =>
  (typeof value === 'string' && value.match(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/))
    ? new Date(value)
    : value

export const encode = toDeshydrate => JSON.stringify(toDeshydrate, replacer)

export const decode = toRehydrate => JSON.parse(toRehydrate, reviver)
```

And how to use it:
```
const persistConfig = {
  key: 'myKey',
  transforms: [createTransform(encode, decode)]
}```

**Comment by dsernst** [comment]
@vcarels

> @digitalmaster got the point. However instead of traversing object tree, one may just json-serialize and deserialize objects using _replacer_ and _reviver_ to handle dates.
> 
> * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Parameters
> * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Syntax
> 
> Here the "codec":
> 
> ```
> const replacer = (key, value) => date instanceof Date ? value.toISOString() : value
> 
> const reviver = (key, value) =>
>   (typeof value === 'string' && value.match(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/))
>     ? new Date(value)
>     : value
> 
> export const encode = toDeshydrate => JSON.stringify(toDeshydrate, replacer)
> 
> export const decode = toRehydrate => JSON.parse(toRehydrate, reviver)
> ```
> 
> And how to use it:
> 
> ```
> const persistConfig = {
>   key: 'myKey',
>   transforms: [createTransform(encode, decode)]
> }```
> ```

This works great, after fixing a typo causing a fatal error:

In the first line, `date` should be `value`.

```diff
- const replacer = (key, value) => date instanceof Date ? value.toISOString() : value
+ const replacer = (key, value) => value instanceof Date ? value.toISOString() : value
```

Also `toDeshydrate` looks like a typo of `toDehydrate` (without the extra `s`).

----

The `encode` and `replacer` functions aren't actually needed though, because `JSON.stringify()` already transforms Dates to ISO strings. 

So I was able to reduce this snippet down to just this addition to my config:

```js
const persistConfig = {
  key: 'myKey',

  // Transform dates back into JS Dates on rehydrate
  // (see: https://github.com/rt2zz/redux-persist/issues/82)
  transforms: [
    createTransform(JSON.stringify, toRehydrate =>
      JSON.parse(toRehydrate, (key, value) =>
        typeof value === 'string' && value.match(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/)
          ? new Date(value)
          : value,
      ),
    ),
  ],
}
```




----

Thanks again for this, @vcarel. It fixed this issue for me.

And agree with other commenters, there could still be better warnings about this to avoid subtle bugs that take a while to track down.

**Comment by pkyeck** [comment]
@dsernst  @vcarel but your solution would also convert ISO-strings that were strings to start with to Date objects when rehydrating the store. so we'd need a solution that "marks" the Dates going in to be recognized and transformed when coming out.

json-literal does exactly that but uses esprima under the hood - which bloats my project up by 132KB :( 

I'll take a look at transit ...

**Comment by aditya1711** [comment]
> @vcarels
> 
> > @digitalmaster got the point. However instead of traversing object tree, one may just json-serialize and deserialize objects using _replacer_ and _reviver_ to handle dates.
> > 
> > * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Parameters
> > * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Syntax
> > 
> > Here the "codec":
> > ```
> > const replacer = (key, value) => date instanceof Date ? value.toISOString() : value
> > 
> > const reviver = (key, value) =>
> >   (typeof value === 'string' && value.match(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/))
> >     ? new Date(value)
> >     : value
> > 
> > export const encode = toDeshydrate => JSON.stringify(toDeshydrate, replacer)
> > 
> > export const decode = toRehydrate => JSON.parse(toRehydrate, reviver)
> > ```
> > 
> > 
> > And how to use it:
> > ```
> > const persistConfig = {
> >   key: 'myKey',
> >   transforms: [createTransform(encode, decode)]
> > }```
> > ```
> 
> This works great, after fixing a typo causing a fatal error:
> 
> In the first line, `date` should be `value`.
> 
> ```diff
> - const replacer = (key, value) => date instanceof Date ? value.toISOString() : value
> + const replacer = (key, value) => value instanceof Date ? value.toISOString() : value
> ```
> 
> Also `toDeshydrate` looks like a typo of `toDehydrate` (without the extra `s`).
> 
> The `encode` and `replacer` functions aren't actually needed though, because `JSON.stringify()` already transforms Dates to ISO strings.
> 
> So I was able to reduce this snippet down to just this `transform` addition to my config:
> 
> ```js
> const persistConfig = {
>   key: 'myKey',
> 
>   // Transform dates back into JS Dates on rehydrate
>   // (see: https://github.com/rt2zz/redux-persist/issues/82)
>   transforms: [
>     createTransform(JSON.stringify, toRehydrate =>
>       JSON.parse(toRehydrate, (key, value) =>
>         typeof value === 'string' && value.match(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/)
>           ? new Date(value)
>           : value,
>       ),
>     ),
>   ],
> }
> ```
> 
> Thanks again for this, @vcarel. It fixed this issue for me.
> 
> And agree with other commenters, there could still be better warnings about this to avoid subtle bugs that take a while to track down.

Does this solution results stringify and parse running twice, since the library itself runs it once?

**Comment by fanxueqin** [comment]
> > @vcarels
> > > @digitalmaster got the point. However instead of traversing object tree, one may just json-serialize and deserialize objects using _replacer_ and _reviver_ to handle dates.
> > > 
> > > * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#Parameters
> > > * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#Syntax
> > > 
> > > Here the "codec":
> > > ```
> > > const replacer = (key, value) => date instanceof Date ? value.toISOString() : value
> > > 
> > > const reviver = (key, value) =>
> > >   (typeof value === 'string' && value.match(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/))
> > >     ? new Date(value)
> > >     : value
> > > 
> > > export const encode = toDeshydrate => JSON.stringify(toDeshydrate, replacer)
> > > 
> > > export const decode = toRehydrate => JSON.parse(toRehydrate, reviver)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And how to use it:
> > > ```
> > > const persistConfig = {
> > >   key: 'myKey',
> > >   transforms: [createTransform(encode, decode)]
> > > }```
> > > ```
> > 
> > 
> > This works great, after fixing a typo causing a fatal error:
> > In the first line, `date` should be `value`.
> > ```diff
> > - const replacer = (key, value) => date instanceof Date ? value.toISOString() : value
> > + const replacer = (key, value) => value instanceof Date ? value.toISOString() : value
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also `toDeshydrate` looks like a typo of `toDehydrate` (without the extra `s`).
> > The `encode` and `replacer` functions aren't actually needed though, because `JSON.stringify()` already transforms Dates to ISO strings.
> > So I was able to reduce this snippet down to just this `transform` addition to my config:
> > ```js
> > const persistConfig = {
> >   key: 'myKey',
> > 
> >   // Transform dates back into JS Dates on rehydrate
> >   // (see: https://github.com/rt2zz/redux-persist/issues/82)
> >   transforms: [
> >     createTransform(JSON.stringify, toRehydrate =>
> >       JSON.parse(toRehydrate, (key, value) =>
> >         typeof value === 'string' && value.match(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/)
> >           ? new Date(value)
> >           : value,
> >       ),
> >     ),
> >   ],
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks again for this, @vcarel. It fixed this issue for me.
> > And agree with other commenters, there could still be better warnings about this to avoid subtle bugs that take a while to track down.
> 
> Does this solution results stringify and parse running twice, since the library itself runs it once?

yes  stringify and parse running twice!!cry

**Comment by sherriff93** [comment]
I think this is a way to preserve all Date objects with redux persist without converting any other values accidentally. The check for `!!Object.entries(x).length` seems to prevent un-needed object searches (e.g. Functions and Date objects don't need to be searched) but I'm not 100% it prevents all those cases (maybe someone can verify).

Also if you had any strings which ended with the random key anyway that'd cause issues so maybe come up with something else there, however the chances of that are tiny.

It also could end up being slow if you have deeply nested state.

```js
const randomKeyToIdentifyAnyTimestampsWhichShouldBeConvertedBackToDates = "-dl29fXphyr403uGstd6G7fhJdHSydg3055h"

const convertDatesToTimestampsWithKeysRecursively = (x) => {
  if (x instanceof Date) {
    return `${x.getTime()}${randomKeyToIdentifyAnyTimestampsWhichShouldBeConvertedBackToDates}`
  }

  if (Array.isArray(x)) {
    return x.map(convertDatesToTimestampsWithKeysRecursively);
  }

  if (typeof x === 'object' && x !== null && !!Object.entries(x).length) {
    return Object.entries(x).reduce((acc, [key, value]) => {
      acc[key] = convertDatesToTimestampsWithKeysRecursively(value);
      return acc;
    }, {});
  }

  return x;
};

const convertTimestampsWithKeysToDatesRecursively = (x) => {
  if (
    typeof x === 'string'
    && x.endsWith(randomKeyToIdentifyAnyTimestampsWhichShouldBeConvertedBackToDates)
  ) {
    return new Date(
      parseInt(
        x.replace(
          randomKeyToIdentifyAnyTimestampsWhichShouldBeConvertedBackToDates,
          ""
        )
      )
    )
  }

  if (Array.isArray(x)) {
    return x.map(convertTimestampsWithKeysToDatesRecursively);
  }

  if (typeof x === 'object' && x !== null && !!Object.entries(x).length) {
    return Object.entries(x).reduce((acc, [key, value]) => {
      acc[key] = convertTimestampsWithKeysToDatesRecursively(value);
      return acc;
    }, {});
  }

  return x;
};

const preventDatesFromBeingTurnedIntoTZStrings = createTransform(
  convertDatesToTimestampsWithKeysRecursively,
  convertTimestampsWithKeysToDatesRecursively,
)

const persistConfig = {
  ...,
  transforms: [preventDatesFromBeingTurnedIntoTZStrings]
};
```
