### ISSUE TITLE
redux-persist is not working

### ISSUE THREAD

**Issue by vicky-blr** [rt2zz/redux-persist#826]
I followed doc here for setup --> https://github.com/rt2zz/redux-persist

Basically I've simple basic setup as per the document

```
import { createStore } from 'redux'
import { persistStore, persistReducer } from 'redux-persist'
import storage from 'redux-persist/lib/storage'
import user from './reducers/user';

const persistConfig = {
  key: 'root',
  storage,
}

const rootReducer = combineReducers({user: user});

const persistedReducer = persistReducer(persistConfig, rootReducer);

const store = createStore(persistedReducer, applyMiddleware(thunk));

const persistor = persistStore(store);

export { store, persistor } ;
```
And then, I add PersistGate in my render.
```
ReactDOM.render(
  <Provider store={store}>
    <PersistGate loading={null} persistor={persistor} >
      <RootRouter />
    </PersistGate>
  </Provider> ,
  document.getElementById('root')
);
```

But still when I refresh my page, it doesn't keep those states active. The only difference I can see in my code (than document) is that I'm using thunk. Can someone please help me?

**Comment by Dmitrylolo** [comment]
`const store = createStore(
persistedReducer,`
`{},`
`applyMiddleware(thunk));`

**Comment by vicky-blr** [comment]
Thanks @Dmitrylolo , I will try this later. In the meantime, I went ahead with another library redux-storage which is working perfectly for me. Closing it for now

**Comment by Dmitrylolo** [comment]
sometimes it calls error with key in persistConfig. try key: 'primary'

**Comment by basudz365** [comment]
@Dmitrylolo I had the same issue as the OP and after changing the key from 'root' to 'primary', it seems to be working properly now. Not sure why this is or if it's only an issue when inside the Expo environment but either way, thanks for the suggestion!

**Comment by rodrigo-fonseca** [comment]
I'm having the same issue, here is my code:

```
import { createStore, applyMiddleware } from 'redux'
import promiseMiddleware from 'redux-promise-middleware'
import reducer from 'redux/reducers'
import createReduxListen from 'redux-listen'
import { persistStore, persistReducer } from 'redux-persist'
import storage from 'redux-persist/lib/storage'

const persistConfig = {
  key: 'primary',
  storage,
}

const persistedReducer = persistReducer(persistConfig, reducer)
const listenStore = createReduxListen()
const middleware = applyMiddleware(promiseMiddleware(), listenStore.middleware)
const store = createStore(
  persistedReducer,
  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__(),
  middleware,
)
const persistor = persistStore(store)

export { store, listenStore, persistor }
```

**Comment by rodrigo-fonseca** [comment]
it simply doesn't work like it should

**Comment by gabrielhpugliese** [comment]
Hey guys, did you manage to find out what was wrong? I am struggling right now too...

**Comment by hackrit** [comment]
Hi guys,
I found a solution to this problem. (might not apply to all the cases, but worked for me).
The problem was caused by my `default` return in my `reducer`, which I returned `{...state}`.
Once I changed the default return to just return `state`, everything work as expected.

**Comment by programmer-RN** [comment]
Hi, I am new in redux persist, I am facing the error of **redux-persist failed to create sync storage, falling back to memory storage**, may I know which part am I missing?

**Comment by MartinJHItInstituttet** [comment]
@hackrit I hardly can't believe this was the solution... I could see my outbound state being correct, but somehow it wasn't being reflected in my state. And sure enough, I returned a clone of my state in the default, instead of the original state.

Thanks so much for the help!

**Comment by andrewmartin** [comment]
Really wish the docs were a bit more clear in naming `primary` as the required option for `key` instead of `root`...very confusing. works well now though. 👍

**Comment by jerryzlau** [comment]
How would I be able to deal with nested reducers then? 

I have a nested reducer: 
default:
      return {
        ...state,
        business: businessReducer(state.business, action)
      }

**Comment by klis87** [comment]
@jerryzlau you can wrap any nested reducer in `persistReducer` independently, because `persistReducer` is higher order reducer:
```js
return {
  ...state,
  business: persistReducer(
    { storage, key: 'business' },
    businessReducer(state.business, action),
  ),
}
```

**Comment by dvaldivia** [comment]
How can you even debug this problem?

**Comment by ckOfor** [comment]
use version `"redux-persist": "^5.10.0"`

**Comment by ckOfor** [comment]
use version `"redux-persist": "^5.10.0"`

**Comment by bharatgupta99** [comment]
> a solution to this problem. (might not apply to all the cases, but worked for me).
> The problem was caused by my `default` retur

worked for me. but why does this happen?

**Comment by KBiswas98** [comment]
> Hi guys,
> I found a solution to this problem. (might not apply to all the cases, but worked for me).
> The problem was caused by my `default` return in my `reducer`, which I returned `{...state}`.
> Once I changed the default return to just return `state`, everything work as expected.

Man u just save my day....

**Comment by AbrahamMayowa** [comment]
@hackrit thanks.

**Comment by heyphord** [comment]
> expected

Thanks Man, you are lifesaver

**Comment by amaben2020** [comment]
...state : Spreading the state crashed my app.

**Comment by fredzerpa** [comment]
> Hi guys,
> I found a solution to this problem. (might not apply to all the cases, but worked for me).
> The problem was caused by my `default` return in my `reducer`, which I returned `{...state}`.
> Once I changed the default return to just return `state`, everything work as expected.

GIVE THIS MAN A RAISE!

**Comment by dragano316** [comment]
@hackrit thanks bro..your solution worked but i was wondering what is the reason behind the solution, if you have any leads than please let me know.

**Comment by rahuls24** [comment]
> primary

Thanks man. You just really save lots of my time

**Comment by jaydeep911** [comment]
In My case this same issue happen after updating expo version. 

Solution: 
// import FSStorage from "redux-persist-expo-fs-storage";
import FSStorage from "redux-persist-fs-storage";
/* 
Import change 
*/
const primary = {
  key: "root",
  timeout: 0,
  version: 1,
  keyPrefix: "",
  storage: FSStorage(),
  stateReconciler: autoMergeLevel2, // see "Merge Process" section for details.
};

ADD keyPrefix: "", in config. 
Hope this solutions work for others.

**Comment by kunalprakash1309** [comment]
> Hi guys, I found a solution to this problem. (might not apply to all the cases, but worked for me). The problem was caused by my `default` return in my `reducer`, which I returned `{...state}`. Once I changed the default return to just return `state`, everything work as expected.

It worked for me....

**Comment by shashankw3** [comment]
> Hi guys, I found a solution to this problem. (might not apply to all the cases, but worked for me). The problem was caused by my `default` return in my `reducer`, which I returned `{...state}`. Once I changed the default return to just return `state`, everything work as expected.

still not working for me

**Comment by RossVertizan** [comment]
> Hi guys, I found a solution to this problem. (might not apply to all the cases, but worked for me). The problem was caused by my `default` return in my `reducer`, which I returned `{...state}`. Once I changed the default return to just return `state`, everything work as expected.

@hackrit - just wanted to say a quick thanks - this solved my problem before I ripped out the last of my hair !!

**Comment by Mnabawy** [comment]
thanks @hackrit  that worked for me

**Comment by dvrock** [comment]
You can check my code it is working fine with redux-toolkit
import AuthReducer from '../redux/reducer/AuthReducer';
import {configureStore,combineReducers } from '@reduxjs/toolkit';
import thunk from "redux-thunk"
import AsyncStorage from '@react-native-async-storage/async-storage';
import {persistStore, persistReducer} from 'redux-persist';

const persistConfig = {
  key: 'root',
  storage: AsyncStorage,  
  version:1
};
const rootReducer = combineReducers({
  AuthReducer: persistReducer(persistConfig, AuthReducer),
});
const store = configureStore({
  reducer: rootReducer,    
  middleware:[thunk]
});
  const persistor = persistStore(store)

 export {store, persistor};

**Comment by sathishkumarm1701** [comment]
instalation error installed after the error was not found in the project redux-persist
