### ISSUE TITLE
Realm.js as backend storage?

### ISSUE THREAD

**Issue by fungilation** [rt2zz/redux-persist#83]
On React Native, what about integration with https://github.com/realm/realm-js, using it as a backend storage? Redux Persist currently uses AsyncStorage as storage, is Realm a natural fit here instead?

Reference: https://github.com/realm/realm-js/issues/141#issuecomment-215973753

**Comment by rt2zz** [comment]
That would be great. I have not used realm but the project looks exciting.

Does realm require schemas are defined up front?

**Comment by fungilation** [comment]
Afaik it's an object store. Like mongo but with a nicer querying interface.
And obviously go beyond just key value store. So I'm thinking this
integration would be useful as a drop in for getting the data in initially,
while allowing for a powerful querying interface via Realm for alternate
views not directly backed by redux.

**Comment by liubiggun** [comment]
Are there any new developments about integration with realm?

**Comment by JulianKingman** [comment]
FYI - Realm requires a schema, so you'd have to know the data structures that you want to persist.

**Comment by kenma9123** [comment]
any progress?

**Comment by Selman555** [comment]
Just passing by from google, I really hope there will be a way to ditch AsyncStorage.
As far as my understanding goes, a "universal" scheme would have to exist. Otherwise there will have to be a lot of cleaning going on to keep things tidy and small in size.
[This accepted answer](http://stackoverflow.com/questions/40167038/using-realm-in-react-native-app-with-redux) convinced me to keep using redux-persist

**Comment by rt2zz** [comment]
note redux-persist v5 now has a simpler / more flexible storage model. It also no longer requires `getAllKeys`, so I think a realm storage engine would be trivial aside from the need to write a well defined schema.

Just three methods required: `setItem, getItem, removeItem`

**Comment by fungilation** [comment]
Interesting. If no one tackle this in a month or 3 I will, when I think my app will need a secondary local offline storage other than Firebase I'm using currently (which does offline but it's a blackbox regarding the persistence, and I want redux fulltext search capability at some point)

**Comment by fungilation** [comment]
Sorry no, my priorities have changed. For those interested in similar use case, I'll likely go with Apollo with https://github.com/apollographql/apollo-cache-persist instead.
