### ISSUE TITLE
persistStore after action.

### ISSUE THREAD

**Issue by jeroenbourgois** [rt2zz/redux-persist#84]
This is probably a stupid question, but is the store persisted constantly? Or should I call `persistStore` explicit after a certain action is done? For instance, I load my store on a fresh application so the `user` will be empty. After logging in I would like to persist the store which now contains user data such as a session token. 

How could I achieve that? In my `redux` action or reducer I always have access to a part of the state, never the complete store? My goal is that after logging in and reloading the app, the store is rehydrated with the previous session token, thus the user is logged in. Right now I achieved that with `AsyncStorage` but the `redux-persist` API is much more transparent in a way that I don't need special callbacks throughout my actions, I can just inspect the store.

**Comment by jeroenbourgois** [comment]
Nevermind, I was being stupid, the package does everything 👯

**Comment by rt2zz** [comment]
👍 I assume that means it is working? to be clear: yes you only need to call persistStore once, and under the hood it will monitor changes via store.subscribe.

**Comment by jeroenbourgois** [comment]
Yes it is working! Thank you so much for this package :D
