### ISSUE TITLE
Not re-hydrating a map field

### ISSUE THREAD

**Issue by EgidioCaprino** [rt2zz/redux-persist#879]
Hi all 👋

This is how I'm creating the reducer:

``` javascript
import { createPersistedReducer } from '../common/storage';

const initalState = {
  map: {},
  loaded: false,
  loading: false,
};

const reducer = (state = initalState, action) => {
  switch (action.type) {
    case 'SET_MESSAGES':
      return {
        ...state,
        map: {
          ...state.map,
          [action.conversationId]: action.messages,
        },
      };
    case 'LOADING_MESSAGES':
      return {
        ...state,
        loading: action.inProgress,
      };
    case 'MESSAGES_LOADED':
      return {
        ...state,
        loaded: true,
      };
    default:
      return state;
  }
};

export default createPersistedReducer({
  blacklist: ['loading'],
  key: 'messages',
  reducer,
});
```

This is the `createPersistedReducer` function

``` javascript
export const createPersistedReducer = ({ blacklist, key, reducer }) => {
  const persistConfig = {
    blacklist,
    debug: !isProduction(),
    key,
    stateReconciler: autoMergeLevel2,
    storage,
  };
  return persistReducer(persistConfig, reducer);
};
```

The `map` field is not persisted though.

When the field is populated:
![image](https://user-images.githubusercontent.com/5156120/43687122-5b7f207a-98d0-11e8-8376-184ce4987d7c.png)

When the field is re-hydrated:
![image](https://user-images.githubusercontent.com/5156120/43687128-6dc490b2-98d0-11e8-9e09-41845eb05302.png)

**Comment by maysam** [comment]
I have similar problem with 

`
let initialState = Immutable.Map({
  a: 1
})
`

not getting persisted, after page reload, the state is an object and not an Immutable anymore

**Comment by EgidioCaprino** [comment]
@maysam that's a different issue. Look at the [Transforms](https://github.com/rt2zz/redux-persist#transforms) section.

**Comment by tommyalvarez** [comment]
@EgidioCaprino Maybe by chance you're mutating state somehow?

**Comment by EgidioCaprino** [comment]
@tommyalvarez what do you mean exactly? Yes, I'm mutating state through the reducer I've posted above.

**Comment by tommyalvarez** [comment]
By principle in redux you should never mutate reducers state. You should
always return new objects with the contents also being new objects. That’s
why the immutable lib is so popular in react-redux app but well, you can do
it manually.
Redux-persist fails to persist state if its mutated because it doesn’t
recognize it as a change if the new state is not a new object

**Comment by EgidioCaprino** [comment]
@tommyalvarez I see what you mean. I'd like to introduce Observable in a next release of our app.
Anyway, I can't say where we're mutating the state. We always do `return { ...state, something: value }`.
