### ISSUE TITLE
Allow defining only one of "in" and "out" handlers in transforms.

### ISSUE THREAD

**Issue by Kim-Andersen** [rt2zz/redux-persist#88]
I dont necessarily need to handle both in and out. So having to add a dummy pass-through handler now, feels a bit wrong.

**Comment by rt2zz** [comment]
I would be open to this. Something like what react-redux does:
```js
createTransform(null, outbound)
```

I would definitely accept a PR to that affect

**Comment by rt2zz** [comment]
included in latest release
