### ISSUE TITLE
Setting debounce discards state

### ISSUE THREAD

**Issue by egeriis** [rt2zz/redux-persist#89]
It seems like setting `debounce` for `persistStore` will discard state updates that falls outside the interval. 

I will see to get a minimal working example asap, but for now I've registered this issue.

**Comment by rt2zz** [comment]
I believe although am not entirely sure, that this is an artifact of the way babel transpiles the code. Either way I just cut a new release that solves said issue. Thanks!

**Comment by egeriis** [comment]
@rt2zz Sounds great. Thank you for being so swift :)

**Comment by egeriis** [comment]
Btw., there's no 3.0.3 tag :)
