### ISSUE TITLE
Multidimensional Object/Array is not persisted right.

### ISSUE THREAD

**Issue by mafiusu** [rt2zz/redux-persist#898]
Hello folks,

I've never got any problems till now with this library but in the new project my data is not persisted right. See the provided screenshots below:

After a request my Redux Store looks like this. The data is filled with content.
<img width="671" alt="bildschirmfoto 2018-08-29 um 14 27 47" src="https://user-images.githubusercontent.com/33623047/44787689-145fc700-ab98-11e8-8d55-3d95d24c266b.png">

But if I restart the application I start with this kind of data:
<img width="463" alt="bildschirmfoto 2018-08-29 um 14 27 59" src="https://user-images.githubusercontent.com/33623047/44787734-36f1e000-ab98-11e8-84c8-231205e9cb6a.png">

It seems that the structure of the data object remains the same but it doesn't have any content. Redux Persist works because other attributes(vars) are getting persisted but the data object not so well.

What can I do?

**Comment by ghhamza** [comment]
any ubpdate ?

**Comment by mafiusu** [comment]
Hey @ghhamza it's been a long time but I think I solved the bug using the library the correct way. It was not a bug by the library itself.

**Comment by bockc** [comment]
@mafiusu I'm glad to hear that, but I think I am currently having a similar issue right now and have no idea what I am doing wrong. What did you do to solve this ?
