### ISSUE TITLE
Cannot read property 'type' of undefined on Chrome Android

### ISSUE THREAD

**Issue by pavliha** [rt2zz/redux-persist#899]
![image](https://user-images.githubusercontent.com/10353006/44900968-c7eac780-ad0e-11e8-8b21-0c44ba8af7c8.png)

**Comment by pavliha** [comment]
I used     if(!action){ return baseReducer(state, action); }

to fix the problem but I get 

Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers.

**Comment by zry754331875** [comment]
l have same issue

**Comment by aguynamedben** [comment]
Does this fix it? https://github.com/rt2zz/redux-persist/pull/961/files

**Comment by sRect** [comment]
how to solve problems
