### ISSUE TITLE
Whitelist support

### ISSUE THREAD

**Issue by grabbou** [rt2zz/redux-persist#9]
Because sometimes it's easier to write whitelist: ['user'] instead of blacklist: [`..list 10 reducers and remember to list new ones as well`]... Is this something you've been considering already in the past?

**Comment by rt2zz** [comment]
yes, and the code for this would be trivial. My hesitation is that I have yet to see an app that would whitelist more than it would blacklist.

Have you run into this situation? can you explain more about your use case?

**Comment by grabbou** [comment]
Well, in my case, the React app data depends on the user location meaning that even a small change of location requires full data reload (location change loads `places`, there are `pubs` in places etc.) hence there's no point in persisting the whole tree since in 99% it will need to reload anyway. The only thing that needs to be serialised at this point is the user profile and its token. 

Anyway, it might be just a matter of personal preference, but usually I prefer whitelisting than blacklisting to be explicit about the serialisation.

**Comment by rt2zz** [comment]
Makes sense. I just added whitelist to to 0.5.8

Let me know how that goes
