### ISSUE TITLE
Some state changes are not registered

### ISSUE THREAD

**Issue by egeriis** [rt2zz/redux-persist#90]
I am having an issue where a couple of actions does not seems to be caught by this lib, so they are not being persisted. This is a gist of what I'm doing, where it doesn't work for me:

```js
dispatch(uploadBegun(item.id));
fileReader(file).then(reader => {
  dispatch(createEntity( ... )).then(res => {
    dispatch(setItemDetail( item.id, ... ));
    dispatch(uploadDone( item.id ));
  });
});
```

I've tried to add a transformer which logs what comes in to redux-persist, and it shows the wrong data coming after the `setItemDetail` and `uploadDone` actions have been dispatched. Neither are registered.

Could this be a bug triggered by dispatching two actions "simultaneously"?

**Comment by rt2zz** [comment]
Two actions simultaneously should be no problem. Could this be related to the debounce issue you reported earlier?

The only other thing I can think of is that redux-persist only stores state which changes, i.e. does not have reference eqaulity. So make sure you are not mutating your state for uploadDone, and are rather copying it, typically with a `return {...newState}` in your reducer.

**Comment by jburich** [comment]
@egeriis Are you on version 3.0.3? I was having the same problem with very very similiar code and the problem was in createPresistor endState was pulling from a local state variable instead of store.getState() which causes the data to be stale. I just upgraded to 3.0.3 and that fixed the problem.

**Comment by rt2zz** [comment]
@jburich fantastic, I just released 3.0.3 to solve the [debounce issue](https://github.com/rt2zz/redux-persist/issues/89), and I guess this solved collaterally 🎉 (or I guess more accurately this simply the same issue)

**Comment by egeriis** [comment]
@jburich I am not. 3.0.2. Will try to pull 3.0.3 tomorrow and see if it has fixed my issue :)

**Comment by egeriis** [comment]
@rt2zz Btw., definitely not state mutation, as I am using ImmutableJS to handle state changes—to ensure that there are no mutations.

I've experienced that `{ ... state }` does not do a deep clone.

**Comment by egeriis** [comment]
Works with 3.1.1. Great!
