### ISSUE TITLE
CRA Cannot find module 'redux-persist/integration/react'

### ISSUE THREAD

**Issue by Infonautica** [rt2zz/redux-persist#900]
**Create React App TypeScript** start throwing this error, since i've tried to update it to TypeScript 3.0.3

It builds successfully only on each even(2, 4, 6 and etc.) build, no matter what changed in the code.

I fix this with relative imports.
From:
`import { persistReducer } from 'redux-persist';`
To:
`// @ts-ignore
import persistReducer from '../../../node_modules/redux-persist/lib/persistReducer';`

**Comment by InfiniteCode** [comment]
@Infonautica Have you figured out the cause for it?

**Comment by Infonautica** [comment]
> @Infonautica Have you figured out the cause for it?

No i didn't. But for now i assume better option is migrate to Create-React-App v2 if any problems occur
