### ISSUE TITLE
WhiteList doesn't work

### ISSUE THREAD

**Issue by perevezencev** [rt2zz/redux-persist#905]
I have a `entities` reducer with structure like this:
```
entities: {
  users: {}
  sessions: {}
}
```
persist config and reducer code look like this
```
import { merge } from "lodash";
import { persistReducer } from "redux-persist";
import storage from "redux-persist/es/storage";

const persistConfig = {
  key: "entities",
  storage,
  whiteList: ["users"]
};

const initialState = {
  sessions: {
    a: "a",
    b: "b"
  },
  users: {}
};

export default persistReducer(persistConfig, (state = initialState, action) => {
  if (action.payload && action.payload.entities) {
    return merge({}, state, action.payload.entities);
  }
  return state;
});
```
I expect that in localStorage persists only `entities.users` but now persist all state in `entities` reducers.

`{"sessions":"{\"a\":\"a\",\"b\":\"b\"}","users":"{}","_persist":"{\"version\":-1,\"rehydrated\":true}"} `

Demo here:

[![Edit j3j5mml53y](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j3j5mml53y)

**Comment by perevezencev** [comment]
@lautaro-osacar This does not work.

 [![Edit pml2r5y5lq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pml2r5y5lq)

**Comment by lautaro-osacar** [comment]
@perevezencev 
Don't you get `{"users":"{}","_persist":"{\"version\":-1,\"rehydrated\":true}"}` as response with the last sandbox?

**Comment by perevezencev** [comment]
@lautaro-osacar, not at first, but then I cleared localStorage =) Thanks
