### ISSUE TITLE
Can I still read from my store without mapStateToProps using redux-persist?

### ISSUE THREAD

**Issue by telmotrooper** [rt2zz/redux-persist#916]
There's a specific situation in my application where I don't have a component but I need to read from the Redux store. Usually I'd use `store.getState()`, but in this case (I'm assuming it's because of `redux-persist`) it returns a lot of information and not (at least that I can see) the value of the state.

I've got a `rootReducer` created with `persistReducer`, then I have:
```
const store = createStore(rootReducer)
const persistor = persistStore(store)
```
But when I try to access the state with `store.getState()` my state returns the objects `_persist` and `<prototype>` and I can't find the actual data in the state. If I try to access the value directly I get `Property 'example' does not exist on type 'PersistPartial'.`. Is there a way for me to access my state directly without relying on mapStateToProps since I don't want to have a component in this very specific scenario?

My **workaround for now** is to read straight from my storage engine, but that's no good since I plan on encrypting the state in the near future and having to decrypt it straight from there would just make my code needlessly more complicated...

**Comment by erksch** [comment]
Since you call `createStore` with `rootReducer` I assume you did not wrap your `rootReducer` in a `persistedReducer`. 

Try this:
```
const rootReducer = combineReducers({ ... });
const persistedReducer = persistReducer(persistConfig, rootReducer);

const store = createStore(persistedReducer);

const persistor = persistStore(store);
```

**Comment by rajk1121** [comment]
Hi, I am also facing same issue, Is it resolved and if yes, how did you do it?
