### ISSUE TITLE
Cannot use sessionStorage instead of localStorage

### ISSUE THREAD

**Issue by mguijarr** [rt2zz/redux-persist#92]
First of all thanks a lot for this very handy library ! I just started to use it, it's really great.

It seems it is not possible to use `sessionStorage` instead of `localStorage`, I thought I could simply switch to `sessionStorage` by assign `sessionStorage` to the `storage` key of the configuration, however here is the error message I get:

> TypeError: storage.getAllKeys is not a function

*EDIT*: found a solution, very easy in fact when reading the code:

    import {persistStore, autoRehydrate, storages} from 'redux-persist'

Then I passed `storages.asyncSessionStorage` to the `storage` config key.

Would be great to have this documented ;)

**Comment by rt2zz** [comment]
👍 and agreed about the readme

**Comment by rt2zz** [comment]
closing, feel free to PR with readme update :D

**Comment by lory-lu** [comment]
Cannot read property 'asyncSessionStorage' of undefined
