### ISSUE TITLE
is there any method to get a specific index stored by persist?

### ISSUE THREAD

**Issue by henriqueweiand** [rt2zz/redux-persist#922]
I'm trying to get an indece of the saga / redux that was previously stored by the persist in AsyncStorage. Is there any method to get the value right? I say something like:

reduxPersist.getItem ('xxxx')

**Comment by aguynamedben** [comment]
I don't think there is a low-level API for doing this in a special way with redux-persist. You should load your store. Once it's rehydrated, you can use normal Redux methods (i.e. [store.getState()](https://redux.js.org/api/store#getState)) to access a specific key.

```js
// using redux-persist when generating your Redux store...
export default () => {
  let store = createStore(persistedReducer)
  let persistor = persistStore(store)
  return { store, persistor }
}

// getting a value from the store...
console.log(store.getState().xxxx);
```

Does that make sense?
