### ISSUE TITLE
Is redux-persist dead?

### ISSUE THREAD

**Issue by DBosley** [rt2zz/redux-persist#929]
It's been a while since @rt2zz has accepted any PRs, commented on issues, or committed any code. Is this project dead? Is there a fork of it that someone is maintaining?

**Comment by carlomazzaferro** [comment]
Probably this is the current best bet: https://github.com/redux-offline/redux-offline

**Comment by ssorallen** [comment]
@carlomazzaferro redux-offline is dependent on redux-persist though: https://github.com/redux-offline/redux-offline/blob/c11e27940a935a891197e5c86a43e036b4569d74/package.json#L61

**Comment by dillonreyna** [comment]
I've sent an email out to @rt2zz. Will report back if I get a response.

**Comment by Slapbox** [comment]
Seems safe to say yes given it's been completely broken for this long without any update. I hope otherwise, but I doubt it.

**Comment by Slapbox** [comment]
Seems like yes unfortunately. There's plenty of forks though. Hopefully one takes over where @rt2zz left off.

**Comment by rt2zz** [comment]
Hi all, sorry about the neglect, I have not been keeping up on the issues. Please reach out if you are interested in maintaining, and additionally ill take a look at open PRs next week.

**Comment by mefjuu** [comment]
Glad to hear it, rt2zz. Can't wait for repository revival :)

**Comment by rt2zz** [comment]
New pre-release: redux-persist@5.11.0-alpha available via `npm i --save redux-persist@next`

- improve deleted key handling https://github.com/rt2zz/redux-persist/pull/928
- improve typescript types https://github.com/rt2zz/redux-persist/pull/919

Will take some time before I work through the entire backlog of PRs but if something is urgent please ping me directly.

**Comment by Slapbox** [comment]
@rt2zz thanks so much for the updates and the great work on this library!

**Comment by Marvedog** [comment]
Bump?

**Comment by aguynamedben** [comment]
@Marvedog I think there has been some updates to this library since this issue was created.

I found a simple alternative in rolling my own using this approach: https://medium.com/@jrcreencia/persisting-redux-state-to-local-storage-f81eb0b90e7e

If you want to roll your own simple persist w/ support for async migrations, here's some code that might be helpful: https://gist.github.com/aguynamedben/3bef9af36c2a257aa2f0c77e3f046d01

**Comment by bobbui** [comment]
Does anyone know any other alternative lib?

**Comment by Subham-Maity** [comment]
https://dev.to/codexam/is-redux-dead-why-i-kicked-redux-out-of-our-saas-app-5d1g

**Comment by Nantris** [comment]
Redux isn't dead and that's not relevant to this discussion. Don't spam.
