### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by suhaotian** [rt2zz/redux-persist#93]
Maybe provide a little example to learn it ? thank you !

**Comment by ggharry** [comment]
Check these out first https://github.com/rt2zz/redux-persist/blob/master/docs/recipes.md :)

**Comment by rt2zz** [comment]
👍  Feel free to contribute more examples as well.    

Here is one really simple example: https://github.com/philipshurpik/react-native-starter-kit/blob/master/app/store.js
