### ISSUE TITLE
Documentation: How to apply createTransform?

### ISSUE THREAD

**Issue by kreba** [rt2zz/redux-persist#933]
Hi redux-persist team

The README explains how to create transforms but not how to make redux-persist actually use them. 

I found the answer in a blog post here:
https://blog.reactnativecoach.com/the-definitive-guide-to-redux-persist-84738167975

Future users might be delighted to find the last bit of the instructions in the README, too :)

Keep up the good work! :kudos:

**Comment by aguynamedben** [comment]
@kreba Would you be willing to help out and submit a PR with the appropriate changes to the README so we can improve the docs for the project?

**Comment by kreba** [comment]
@thenewt15 I realize that you added the relevant bits in the README with a PR that you reference from said blog post. Is it ok for you if I continue the work on this topic or would you prefer to do it yourself? I'll gladly do it but I don't want to steal the show.

**Comment by aguynamedben** [comment]
Ah good catch @kreba. Looks like that PR was merged. Either of you should feel free to submit a PR for any improvements to these docs and I will review and merge.

**Comment by aguynamedben** [comment]
Closing this for now. @kreba feel free to submit a PR to update the README.

I added a Community section to the README that links to tutorials including the one you mentioned. https://github.com/rt2zz/redux-persist#blog-articles-from-the-community
