### ISSUE TITLE
"store" is read-only 

### ISSUE THREAD

**Issue by vishalTechnoFreek** [rt2zz/redux-persist#936]
While integrating redux-persist I am getting bellow error 
![store](https://user-images.githubusercontent.com/18363600/49429309-3340ab80-f7ce-11e8-98e8-8290f4082c4f.png)

**Comment by aguynamedben** [comment]
What storage engine are you using? Can you please provide a test repo that demonstrates the issue and I'll take a look?

**Comment by aguynamedben** [comment]
@vishalTechnoFreek I haven't heard back from you. Let me know if you're still having issues with this and I'll re-open and help you look at an example project.
