### ISSUE TITLE
State not saved to storage

### ISSUE THREAD

**Issue by ducanh2110** [rt2zz/redux-persist#938]
Hi @rt2zz, 
I have a confusing problem like I have an action that store an Image everytime I upload, when I see in devtool it work perfectly with store. When I checked in storage, there's no image thumbURL there, but the others properties still save to storage. Help me with this problem please. Thanks so much

**Comment by aguynamedben** [comment]
Can you please provide an example repo demonstrating the issue and I will help inspect it?

**Comment by ducanh2110** [comment]
It's a private repo. But I have figure the problem I had. First, I think's the data I save to storage is too big that make the browser lag. Second, I dispatched so many actions every time 1 image uploaded temporarily. At this time I need to do something like persistore.flush(() =>> {...}) but it still can save some small thumbUrl with base64 to storage. With some big image (> 2MB) can't save.

**Comment by aguynamedben** [comment]
Cool, glad you figured it out.
