### ISSUE TITLE
confused about persistStore

### ISSUE THREAD

**Issue by wiiiim** [rt2zz/redux-persist#94]
Hello,
Going from the documentation I was left a bit confused. persistStore actually restores (rehydrates) state from your database and not the reverse? Or it does both a restore and then persist?
Thanks

**Comment by rt2zz** [comment]
Yes `persistStore` does both persist and restore. It retrieves the stored state, rehydrates said state, and dispatches a REHYDRATE action. It also sets up a listener that will continuously saves newly changed state to storage.

The only thing it does not do is merge the rehydrated state into your reducer. For that you will want to use `autoRehydrate`.

**Comment by wiiiim** [comment]
Thanks for clarifying. Does it dispatch a REHYDRATE only once (after the persistStore call)? The listener that continuously saves, does it dispatch actions too?

**Comment by rt2zz** [comment]
right REHYDRATE is only called once, as soon as all state is retrieved from the storage. After that there will be no more actions, unless you call `persistor.rehydrate()` yourself.
