### ISSUE TITLE
Difference between persistStore's whitelist config and createTransform's whitelist config

### ISSUE THREAD

**Issue by customcommander** [rt2zz/redux-persist#947]
Hi,

I’m a bit confused about the difference between `config.whitelist` in `persistStore` and `config.whitelist` in `createTransform`? What purposes do they each serve? Are they complementary or separate things?

Relevant parts of the docs:

1. https://github.com/rt2zz/redux-persist/tree/v4#persiststorestore-config-callback
2. https://github.com/rt2zz/redux-persist/tree/v4#transforms

**Comment by aguynamedben** [comment]
I have not use custom transforms in a project, but it seems:
* `whitelist` as an option for `persistReducer` (i.e. [`PersistConfig`](https://github.com/rt2zz/redux-persist/blob/master/docs/api.md#type-persistconfig)): "only persist these keys" (documented with comment [here](https://github.com/rt2zz/redux-persist/blob/master/docs/api.md#type-persistconfig))
* `whitelist` as an option for `createTransform` (i.e. [`TransformConfig`](https://github.com/rt2zz/redux-persist/blob/208c6b112ead87b3701dfacaae2cdbe78377775a/src/createTransform.js#L3)): "define which reducers this transform gets called for" (documented with comment [here](https://github.com/rt2zz/redux-persist#transforms))

It seems like we should document `TransformConfig` in the [Full API](https://github.com/rt2zz/redux-persist/blob/master/docs/api.md) doc. Would you be willing to take a stab at that if the differentiation above make sense? Maybe you could include a comment like "not to be confused with PersistConfig.whitelist" as well.

**Comment by aguynamedben** [comment]
@customcommander I haven't heard back from you. Let me know if you still have questions around this and I'll re-open.
