### ISSUE TITLE
Redux persist

### ISSUE THREAD

**Issue by atifaziz2** [rt2zz/redux-persist#967]
npm: 6.4.1
node: 10.15.0
"redux-persist": "^5.10.0",

I am gettig this error while persisting redux.Please let me know what i am doing wrong

TypeError: state.filterNot is not a function

**Comment by erksch** [comment]
As far as I know, there is no such call in the entire code base of redux-persist.
So please recheck your code.

**Comment by aguynamedben** [comment]
I also don't see this anywhere in redux-persist... are you sure you don't have a line that is checking your own Redux state for something? (i.e. `state.filterNot`, is that state you manage?)
