### ISSUE TITLE
Doesn't purgeAll when using "localforage": "^1.4.1"

### ISSUE THREAD

**Issue by rahmanusta** [rt2zz/redux-persist#98]
Doesn't purgeAll when using "localforage": "^1.4.1"

**Comment by rt2zz** [comment]
what version of redux-persist are you using? Can you debug that the `removeItem` calls are being made properly?

**Comment by rahmanusta** [comment]
I'm not working on that project right now, sorry.

**Comment by rt2zz** [comment]
👍 all good, hopefully things worked out. A lot of the lib has been updated since last year so I am pretty sure we are 👌
