### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by erksch** [rt2zz/redux-persist#980]
Recently my PR was merged fixing flow errors with newer flow-bin versions.
But without a new release of redux-persist I still can't use an upgraded flow version.

If someone knows how I can build the npm package myself from the current master and use it in my project somehow, please let me know! 

@rt2zz

**Comment by km-tr** [comment]
[redux\-persist \- npm](https://www.npmjs.com/package/redux-persist)

@Andarist You are a collaborator, can you publish?

**Comment by erksch** [comment]
A few days ago (31.01.), I published an npm package of the (at that time) current master build.
I'm using this version in my projects which fixes my problems.

https://www.npmjs.com/package/redux-persist-erksch

If you need stuff from the current master I can update the package.

**Comment by Christopotamus** [comment]
Thanks @erksch's your version works for me as well.
 @rt2zz 
Hope we can get a new release soon.

**Comment by erksch** [comment]
Related issue #982 we wouldn't have to rely on fork packages if getting the package from GitHub directly would work.

**Comment by erksch** [comment]
OMG he is back!

**Comment by rt2zz** [comment]
👋 

I published v6.0.0-pre1 with the latest. `npm i redux-persist@next`. Its a major release because rn apps will now need to import AsyncStorage directly instead of relying on redux-persist to do it for them. 

Also install from github should work again!

**Comment by oltodo** [comment]
Hi, I did this update but I still have a Flow error:

`Cannot assign `rest` to `restState` because  `rest` [1] is incompatible with  `State` [2].`

**Comment by oltodo** [comment]
Using `$FlowIgnore` seems to have no effect here:

https://github.com/rt2zz/redux-persist/blob/3ee7bf8980c713bf42e09197283ac23effa9297b/src/persistReducer.js#L67

But `$FlowFixMe` works well.

**Comment by ChazZeromus** [comment]
> Using `$FlowIgnore` seems to have no effect here:
> 
> https://github.com/rt2zz/redux-persist/blob/3ee7bf8980c713bf42e09197283ac23effa9297b/src/persistReducer.js#L67-L68
> 
> But `$FlowFixMe` works well.

Adding `suppress_comment=\\(.\\|\n\\)*\\$FlowIgnore` to my `.flowconfig` works too.

**Comment by mighty-titan** [comment]
@oltodo is there any other way to solve this than adding `$FlowFixMe` in redux-persist in node_modules?

**Comment by ChazZeromus** [comment]
> @oltodo is there any other way to solve this than adding `$FlowFixMe` in redux-persist in node_modules?
I fixed it by adding that line I stated about in my project's flowconfig and using a "next" version instead of latest stable.
