### ISSUE TITLE
can't install repo from github

### ISSUE THREAD

**Issue by Morriz** [rt2zz/redux-persist#982]
Hi, I think your repo needs some pre/post/install scripts to make the repo installable directly from github. It now errors on the missing `lib/` folder that should be built.

**Comment by Morriz** [comment]
I see that `npm install redux-persist@next` works, but will keep this open as it is still a valid request.

**Comment by erksch** [comment]
@Morriz do you have some sort of article how to do this properly? I would like to do this.

**Comment by erksch** [comment]
Okay I did some investigation about this. 
I guess the npm script `prepare` is what we are looking for since it runs before publishing the package and before installing it with `npm install`.
So adding `prepare: npm run build` should do the trick, am I right?

**Comment by jacquesdev** [comment]
@erksch - have you been able to add a PR?

**Comment by jacquesdev** [comment]
@erksch - I created one in the meantime https://github.com/rt2zz/redux-persist/pull/1020
