### ISSUE TITLE
[ENHANCE] support customize storage

### ISSUE THREAD

**Issue by Genuifx** [rt2zz/redux-persist#987]
I am using redux to develop my [wechat-miniprogram](https://mp.weixin.qq.com/?lang=en_US&token=)( a mini-program run upon wechat app), which js environment is different from the web. eighter `sessionStorage` or `localStorage` is exist there. mini-program has it's own [storage](https://developers.weixin.qq.com/miniprogram/en/dev/api/data.html).

So, why not provide an API to allow user custom their storage~:sunny:

**Comment by erksch** [comment]
Great idea and I think you can already do this (don't take me for granted here).
When you take a look at the storages supported by redux-persist they only need the following things:

- getItem: (key: string): Promise<string>
- setItem: (key: string, item: string): Promise<void>
- removeItem: (key: string): Promise<void>

You can check the [webstorage implementation](https://github.com/rt2zz/redux-persist/blob/master/src/storage/createWebStorage.js) for reference.

So why not write your own storage by implementing these functions in an object or as static methods in a class. Then you should be able to import it and set it as the storage.

```
import storage from './myStorage';

const persistConfig = { 
  ...
  storage, 
};
```

**Comment by erksch** [comment]
Ups I just rechecked the readme and it's already in there! Please take a look.
https://github.com/rt2zz/redux-persist#storage-engines

There seems to exist a storage for your use case already [here](https://github.com/cuijiemmx/redux-casa/tree/master/packages/redux-persist-weapp-storage).

**Comment by Genuifx** [comment]
thank you very much:smile:
