### ISSUE TITLE
what was the default key for v4?

### ISSUE THREAD

**Issue by sibelius** [rt2zz/redux-persist#999]
in v4, the key was implicit, then in v5 the key is explicit 

we need to use the same key to keep our users logged in 

what was the default key name?

**Comment by sibelius** [comment]
nevermind

it was multiple keys, now it is just one

**Comment by johnlim5847** [comment]
@sibelius Hi, may I know how you migrate users from v4 to v5? I noticed that the key used in v4 is `reduxPersist:{reducer name}` whereas in v5 is `reduxPersist:{key name}`. Do you mind share me how you do it?  thanks!
